
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Aug 29 2026 17:57:01 PDT (Aug 30 2026 00:57:01 UTC)

// Verification Directory fv/tp_lvl_d16 

module tp_lvl_d16(clk, rst_n, s_awvalid, \s_aw[prot] , \s_aw[addr] ,
     s_wvalid, \s_w[strb] , \s_w[data] , s_arvalid, \s_ar[prot] ,
     \s_ar[addr] , s_bready, s_rready, s_awready, s_wready, s_arready,
     s_bvalid, \s_b[resp] , s_rvalid, \s_r[resp] , \s_r[data] ,
     m_awvalid, \m_aw[prot] , \m_aw[addr] , m_wvalid, \m_w[strb] ,
     \m_w[data] , m_arvalid, \m_ar[prot] , \m_ar[addr] , m_bready,
     m_rready, m_awready, m_wready, m_arready, m_bvalid, \m_b[resp] ,
     m_rvalid, \m_r[resp] , \m_r[data] , enable_reg, clear_reg, irq,
     status_reg, guard_busy);
  input clk, rst_n, s_awvalid, s_wvalid, s_arvalid, s_bready, s_rready,
       m_awready, m_wready, m_arready, m_bvalid, m_rvalid;
  input [2:0] \s_aw[prot] , \s_ar[prot] , enable_reg, clear_reg;
  input [31:0] \s_aw[addr] , \s_w[data] , \s_ar[addr] , \m_r[data] ;
  input [3:0] \s_w[strb] ;
  input [1:0] \m_b[resp] , \m_r[resp] ;
  output s_awready, s_wready, s_arready, s_bvalid, s_rvalid, m_awvalid,
       m_wvalid, m_arvalid, m_bready, m_rready, irq, guard_busy;
  output [1:0] \s_b[resp] , \s_r[resp] ;
  output [31:0] \s_r[data] , \m_aw[addr] , \m_w[data] , \m_ar[addr] ;
  output [2:0] \m_aw[prot] , \m_ar[prot] , status_reg;
  output [3:0] \m_w[strb] ;
  wire clk, rst_n, s_awvalid, s_wvalid, s_arvalid, s_bready, s_rready,
       m_awready, m_wready, m_arready, m_bvalid, m_rvalid;
  wire [2:0] \s_aw[prot] , \s_ar[prot] , enable_reg, clear_reg;
  wire [31:0] \s_aw[addr] , \s_w[data] , \s_ar[addr] , \m_r[data] ;
  wire [3:0] \s_w[strb] ;
  wire [1:0] \m_b[resp] , \m_r[resp] ;
  wire s_awready, s_wready, s_arready, s_bvalid, s_rvalid, m_awvalid,
       m_wvalid, m_arvalid, m_bready, m_rready, irq, guard_busy;
  wire [1:0] \s_b[resp] , \s_r[resp] ;
  wire [31:0] \s_r[data] , \m_aw[addr] , \m_w[data] , \m_ar[addr] ;
  wire [2:0] \m_aw[prot] , \m_ar[prot] , status_reg;
  wire [3:0] \m_w[strb] ;
  wire [1:0] dut_mode;
  wire [2:0] dut_rcvy_ack;
  wire [1:0] dut_u_wr_wpair_state;
  wire [4:0] dut_u_wr_outst_cnt;
  wire [15:0] dut_u_wr_w_timer;
  wire [4:0] dut_u_wr_drain_cnt;
  wire [15:0] dut_u_wr_b_timer;
  wire [1:0] dut_u_wr_wr_state;
  wire [4:0] dut_u_rd_outst_cnt;
  wire [4:0] dut_u_rd_drain_cnt;
  wire [15:0] dut_u_rd_timer;
  wire [1:0] dut_u_rd_rd_state;
  wire dut_all_upstream_empty, dut_epoch_clr, dut_flush, dut_n_418,
       dut_n_419, dut_rd_busy, dut_rd_timeout_pulse,
       dut_rd_upstream_empty;
  wire dut_u_rd_n_292, dut_u_rd_n_297, dut_u_rd_n_299, dut_u_rd_n_300,
       dut_u_rd_n_312, dut_u_rd_n_535, dut_u_rd_n_1356, dut_u_rd_n_1357;
  wire dut_u_rd_n_1795, dut_u_rd_n_1796, dut_u_rd_n_1838,
       dut_u_rd_n_1841, dut_u_rd_n_1842, dut_u_rd_n_1843,
       dut_u_rd_n_1848, dut_u_rd_n_1849;
  wire dut_u_rd_n_1855, dut_u_rd_n_2230, dut_u_rd_n_2233,
       dut_u_rd_n_2235, dut_u_rd_n_2237, dut_u_rd_n_2238,
       dut_u_rd_n_2243, dut_u_rd_n_2244;
  wire dut_u_rd_n_2245, dut_u_rd_n_2248, dut_u_rd_n_2250,
       dut_u_rd_n_2251, dut_u_rd_n_2252, dut_u_rd_n_2255,
       dut_u_rd_n_2257, dut_u_rd_n_2258;
  wire dut_u_rd_n_2259, dut_u_rd_n_2262, dut_u_rd_n_2264,
       dut_u_rd_n_2265, dut_u_rd_n_2266, dut_u_rd_n_2269,
       dut_u_rd_n_2271, dut_u_rd_n_2272;
  wire dut_u_rd_n_2273, dut_u_rd_n_2276, dut_u_rd_n_2278,
       dut_u_rd_n_2279, dut_u_rd_n_2280, dut_u_rd_n_2283,
       dut_u_rd_n_2285, dut_u_rd_n_2286;
  wire dut_u_rd_n_2287, dut_u_rd_n_2290, dut_u_rd_n_2292,
       dut_u_rd_n_2293, dut_u_rd_n_2294, dut_u_rd_n_2297,
       dut_u_rd_n_2299, dut_u_rd_n_2300;
  wire dut_u_rd_n_2301, dut_u_rd_n_2304, dut_u_rd_n_2306,
       dut_u_rd_n_2307, dut_u_rd_n_2308, dut_u_rd_n_2310,
       dut_u_rd_n_2311, dut_u_rd_n_2314;
  wire dut_u_rd_n_2317, dut_u_rd_n_2318, dut_u_rd_n_2319,
       dut_u_rd_n_2320, dut_u_rd_n_2322, dut_u_rd_n_2323,
       dut_u_rd_n_2324, dut_u_rd_n_2326;
  wire dut_u_rd_n_2329, dut_u_rd_n_2333, dut_u_rd_n_2335,
       dut_u_rd_n_2337, dut_u_rd_n_2339, dut_u_rd_n_2340,
       dut_u_rd_n_2341, dut_u_rd_n_2344;
  wire dut_u_rd_n_2346, dut_u_rd_n_2347, dut_u_rd_n_2349,
       dut_u_rd_n_2353, dut_u_rd_n_2354, dut_u_rd_n_2355,
       dut_u_rd_n_2359, dut_u_rd_n_2362;
  wire dut_u_rd_n_2364, dut_u_rd_n_2365, dut_u_rd_n_2367,
       dut_u_rd_n_2371, dut_u_rd_n_2372, dut_u_rd_n_2373,
       dut_u_rd_n_2374, dut_u_rd_n_2376;
  wire dut_u_rd_n_2380, dut_u_rd_n_2382, dut_u_rd_n_2384,
       dut_u_rd_n_2385, dut_u_rd_n_2386, dut_u_rd_n_2389,
       dut_u_rd_n_2390, dut_u_rd_n_2391;
  wire dut_u_rd_n_2392, dut_u_rd_n_2393, dut_u_rd_n_2394,
       dut_u_rd_n_2395, dut_u_rd_n_2402, dut_u_rd_n_2403,
       dut_u_rd_n_2404, dut_u_rd_n_2405;
  wire dut_u_rd_n_2406, dut_u_rd_n_2407, dut_u_rd_n_2408,
       dut_u_rd_n_2409, dut_u_rd_n_2412, dut_u_rd_n_2413,
       dut_u_rd_n_2414, dut_u_rd_n_2415;
  wire dut_u_rd_n_2418, dut_u_rd_n_2419, dut_u_rd_n_2420,
       dut_u_rd_n_2421, dut_u_rd_n_2428, dut_u_rd_n_2434,
       dut_u_rd_n_2439, dut_u_rd_n_2441;
  wire dut_u_rd_n_2442, dut_u_rd_n_2446, dut_u_rd_n_2447,
       dut_u_rd_n_2449, dut_u_rd_n_2452, dut_u_rd_n_2453,
       dut_u_rd_n_2455, dut_u_rd_n_2456;
  wire dut_u_rd_n_2457, dut_u_rd_n_2458, dut_u_rd_n_2460,
       dut_u_rd_n_2461, dut_u_rd_n_2462, dut_u_rd_n_2463,
       dut_u_rd_n_2464, dut_u_rd_n_2465;
  wire dut_u_rd_n_2466, dut_u_rd_n_2467, dut_u_rd_n_2468,
       dut_u_rd_n_2469, dut_u_rd_n_2470, dut_u_rd_n_2471,
       dut_u_rd_n_2472, dut_u_rd_n_2473;
  wire dut_u_rd_n_2474, dut_u_rd_n_2475, dut_u_rd_n_2476,
       dut_u_rd_n_2477, dut_u_rd_n_2490, dut_u_rd_n_2508,
       dut_u_rd_n_2520, dut_u_rd_n_2525;
  wire dut_u_rd_n_2530, dut_u_rd_n_2531, dut_u_rd_timer_run,
       dut_u_wr_b_timer_run, dut_u_wr_downstream_aw_done,
       dut_u_wr_downstream_aw_fire, dut_u_wr_downstream_w_done,
       dut_u_wr_downstream_w_fire;
  wire dut_u_wr_n_428, dut_u_wr_n_430, dut_u_wr_n_431, dut_u_wr_n_442,
       dut_u_wr_n_701, dut_u_wr_n_2282, dut_u_wr_n_2305,
       dut_u_wr_n_2739;
  wire dut_u_wr_n_2742, dut_u_wr_n_2752, dut_u_wr_n_2753,
       dut_u_wr_n_2755, dut_u_wr_n_2758, dut_u_wr_n_2761,
       dut_u_wr_n_2766, dut_u_wr_n_2770;
  wire dut_u_wr_n_2773, dut_u_wr_n_2774, dut_u_wr_n_2775,
       dut_u_wr_n_2776, dut_u_wr_n_2777, dut_u_wr_n_2778,
       dut_u_wr_n_2781, dut_u_wr_n_2785;
  wire dut_u_wr_n_2786, dut_u_wr_n_2787, dut_u_wr_n_2788,
       dut_u_wr_n_2796, dut_u_wr_n_3718, dut_u_wr_n_3719,
       dut_u_wr_n_3720, dut_u_wr_n_3722;
  wire dut_u_wr_n_3724, dut_u_wr_n_3726, dut_u_wr_n_3728,
       dut_u_wr_n_3729, dut_u_wr_n_3730, dut_u_wr_n_3734,
       dut_u_wr_n_3740, dut_u_wr_n_3741;
  wire dut_u_wr_n_3742, dut_u_wr_n_3744, dut_u_wr_n_3745,
       dut_u_wr_n_3747, dut_u_wr_n_3750, dut_u_wr_n_3752,
       dut_u_wr_n_3754, dut_u_wr_n_3755;
  wire dut_u_wr_n_3756, dut_u_wr_n_3758, dut_u_wr_n_3759,
       dut_u_wr_n_3761, dut_u_wr_n_3764, dut_u_wr_n_3766,
       dut_u_wr_n_3768, dut_u_wr_n_3769;
  wire dut_u_wr_n_3770, dut_u_wr_n_3772, dut_u_wr_n_3773,
       dut_u_wr_n_3775, dut_u_wr_n_3778, dut_u_wr_n_3780,
       dut_u_wr_n_3782, dut_u_wr_n_3783;
  wire dut_u_wr_n_3784, dut_u_wr_n_3786, dut_u_wr_n_3787,
       dut_u_wr_n_3789, dut_u_wr_n_3792, dut_u_wr_n_3794,
       dut_u_wr_n_3796, dut_u_wr_n_3797;
  wire dut_u_wr_n_3798, dut_u_wr_n_3800, dut_u_wr_n_3801,
       dut_u_wr_n_3803, dut_u_wr_n_3806, dut_u_wr_n_3808,
       dut_u_wr_n_3810, dut_u_wr_n_3811;
  wire dut_u_wr_n_3812, dut_u_wr_n_3814, dut_u_wr_n_3815,
       dut_u_wr_n_3817, dut_u_wr_n_3820, dut_u_wr_n_3822,
       dut_u_wr_n_3824, dut_u_wr_n_3825;
  wire dut_u_wr_n_3826, dut_u_wr_n_3828, dut_u_wr_n_3829,
       dut_u_wr_n_3831, dut_u_wr_n_3834, dut_u_wr_n_3836,
       dut_u_wr_n_3838, dut_u_wr_n_3839;
  wire dut_u_wr_n_3840, dut_u_wr_n_3842, dut_u_wr_n_3843,
       dut_u_wr_n_3845, dut_u_wr_n_3848, dut_u_wr_n_3850,
       dut_u_wr_n_3852, dut_u_wr_n_3853;
  wire dut_u_wr_n_3854, dut_u_wr_n_3855, dut_u_wr_n_3856,
       dut_u_wr_n_3858, dut_u_wr_n_3862, dut_u_wr_n_3864,
       dut_u_wr_n_3866, dut_u_wr_n_3867;
  wire dut_u_wr_n_3868, dut_u_wr_n_3869, dut_u_wr_n_3870,
       dut_u_wr_n_3873, dut_u_wr_n_3875, dut_u_wr_n_3878,
       dut_u_wr_n_3879, dut_u_wr_n_3881;
  wire dut_u_wr_n_3883, dut_u_wr_n_3885, dut_u_wr_n_3888,
       dut_u_wr_n_3889, dut_u_wr_n_3890, dut_u_wr_n_3892,
       dut_u_wr_n_3895, dut_u_wr_n_3896;
  wire dut_u_wr_n_3897, dut_u_wr_n_3899, dut_u_wr_n_3901,
       dut_u_wr_n_3902, dut_u_wr_n_3906, dut_u_wr_n_3908,
       dut_u_wr_n_3910, dut_u_wr_n_3912;
  wire dut_u_wr_n_3913, dut_u_wr_n_3914, dut_u_wr_n_3915,
       dut_u_wr_n_3916, dut_u_wr_n_3918, dut_u_wr_n_3920,
       dut_u_wr_n_3923, dut_u_wr_n_3924;
  wire dut_u_wr_n_3925, dut_u_wr_n_3926, dut_u_wr_n_3927,
       dut_u_wr_n_3935, dut_u_wr_n_3936, dut_u_wr_n_3937,
       dut_u_wr_n_3940, dut_u_wr_n_3941;
  wire dut_u_wr_n_3942, dut_u_wr_n_3943, dut_u_wr_n_3946,
       dut_u_wr_n_3948, dut_u_wr_n_3954, dut_u_wr_n_3956,
       dut_u_wr_n_3958, dut_u_wr_n_3959;
  wire dut_u_wr_n_3961, dut_u_wr_n_3964, dut_u_wr_n_3965,
       dut_u_wr_n_3966, dut_u_wr_n_3968, dut_u_wr_n_3970,
       dut_u_wr_n_3971, dut_u_wr_n_3972;
  wire dut_u_wr_n_3975, dut_u_wr_n_3977, dut_u_wr_n_3979,
       dut_u_wr_n_3980, dut_u_wr_n_3981, dut_u_wr_n_3982,
       dut_u_wr_n_3983, dut_u_wr_n_3984;
  wire dut_u_wr_n_3986, dut_u_wr_n_3988, dut_u_wr_n_4019,
       dut_u_wr_n_4020, dut_u_wr_n_4021, dut_u_wr_n_4022,
       dut_u_wr_n_4023, dut_u_wr_n_4024;
  wire dut_u_wr_n_4025, dut_u_wr_n_4026, dut_u_wr_n_4027,
       dut_u_wr_n_4028, dut_u_wr_n_4029, dut_u_wr_n_4036,
       dut_u_wr_n_4038, dut_u_wr_n_4041;
  wire dut_u_wr_n_4066, dut_u_wr_n_4068, dut_u_wr_n_4070,
       dut_u_wr_n_4071, dut_u_wr_n_4072, dut_u_wr_n_4075,
       dut_u_wr_n_4076, dut_u_wr_n_4078;
  wire dut_u_wr_n_4080, dut_u_wr_n_4081, dut_u_wr_n_4082,
       dut_u_wr_n_4084, dut_u_wr_n_4087, dut_u_wr_n_4088,
       dut_u_wr_n_4089, dut_u_wr_n_4096;
  wire dut_u_wr_n_4097, dut_u_wr_n_4098, dut_u_wr_n_4099,
       dut_u_wr_n_4100, dut_u_wr_n_4101, dut_u_wr_n_4102,
       dut_u_wr_n_4103, dut_u_wr_n_4120;
  wire dut_u_wr_n_4122, dut_u_wr_n_4124, dut_u_wr_n_4125,
       dut_u_wr_n_4126, dut_u_wr_n_4127, dut_u_wr_n_4128,
       dut_u_wr_n_4129, dut_u_wr_n_4130;
  wire dut_u_wr_n_4131, dut_u_wr_n_4134, dut_u_wr_n_4135,
       dut_u_wr_n_4136, dut_u_wr_n_4137, dut_u_wr_n_4138,
       dut_u_wr_n_4139, dut_u_wr_n_4141;
  wire dut_u_wr_n_4142, dut_u_wr_n_4143, dut_u_wr_n_4144,
       dut_u_wr_n_4145, dut_u_wr_n_4146, dut_u_wr_n_4147,
       dut_u_wr_n_4148, dut_u_wr_n_4149;
  wire dut_u_wr_n_4150, dut_u_wr_n_4151, dut_u_wr_n_4152,
       dut_u_wr_n_4153, dut_u_wr_n_4154, dut_u_wr_n_4155,
       dut_u_wr_n_4156, dut_u_wr_n_4157;
  wire dut_u_wr_n_4158, dut_u_wr_n_4182, dut_u_wr_n_4187,
       dut_u_wr_n_4192, dut_u_wr_n_4244, dut_u_wr_n_4264,
       dut_u_wr_n_4272, dut_u_wr_n_4274;
  wire dut_u_wr_n_4276, dut_u_wr_w_perm, dut_u_wr_w_timer_run,
       dut_wr_busy, dut_wr_timeout_pulse, dut_wr_upstream_empty,
       dut_wr_w_fault_pulse, logic_0_1_net;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_222;
  wire n_223, n_224, n_225;
  assign \m_ar[addr] [0] = \s_ar[addr] [0];
  assign \m_ar[addr] [1] = \s_ar[addr] [1];
  assign \m_ar[addr] [2] = \s_ar[addr] [2];
  assign \m_ar[addr] [3] = \s_ar[addr] [3];
  assign \m_ar[addr] [4] = \s_ar[addr] [4];
  assign \m_ar[addr] [5] = \s_ar[addr] [5];
  assign \m_ar[addr] [6] = \s_ar[addr] [6];
  assign \m_ar[addr] [7] = \s_ar[addr] [7];
  assign \m_ar[addr] [8] = \s_ar[addr] [8];
  assign \m_ar[addr] [9] = \s_ar[addr] [9];
  assign \m_ar[addr] [10] = \s_ar[addr] [10];
  assign \m_ar[addr] [11] = \s_ar[addr] [11];
  assign \m_ar[addr] [12] = \s_ar[addr] [12];
  assign \m_ar[addr] [13] = \s_ar[addr] [13];
  assign \m_ar[addr] [14] = \s_ar[addr] [14];
  assign \m_ar[addr] [15] = \s_ar[addr] [15];
  assign \m_ar[addr] [16] = \s_ar[addr] [16];
  assign \m_ar[addr] [17] = \s_ar[addr] [17];
  assign \m_ar[addr] [18] = \s_ar[addr] [18];
  assign \m_ar[addr] [19] = \s_ar[addr] [19];
  assign \m_ar[addr] [20] = \s_ar[addr] [20];
  assign \m_ar[addr] [21] = \s_ar[addr] [21];
  assign \m_ar[addr] [22] = \s_ar[addr] [22];
  assign \m_ar[addr] [23] = \s_ar[addr] [23];
  assign \m_ar[addr] [24] = \s_ar[addr] [24];
  assign \m_ar[addr] [25] = \s_ar[addr] [25];
  assign \m_ar[addr] [26] = \s_ar[addr] [26];
  assign \m_ar[addr] [27] = \s_ar[addr] [27];
  assign \m_ar[addr] [28] = \s_ar[addr] [28];
  assign \m_ar[addr] [29] = \s_ar[addr] [29];
  assign \m_ar[addr] [30] = \s_ar[addr] [30];
  assign \m_ar[addr] [31] = \s_ar[addr] [31];
  assign \m_ar[prot] [0] = \s_ar[prot] [0];
  assign \m_ar[prot] [1] = \s_ar[prot] [1];
  assign \m_ar[prot] [2] = \s_ar[prot] [2];
  assign \m_w[data] [0] = \s_w[data] [0];
  assign \m_w[data] [1] = \s_w[data] [1];
  assign \m_w[data] [2] = \s_w[data] [2];
  assign \m_w[data] [3] = \s_w[data] [3];
  assign \m_w[data] [4] = \s_w[data] [4];
  assign \m_w[data] [5] = \s_w[data] [5];
  assign \m_w[data] [6] = \s_w[data] [6];
  assign \m_w[data] [7] = \s_w[data] [7];
  assign \m_w[data] [8] = \s_w[data] [8];
  assign \m_w[data] [9] = \s_w[data] [9];
  assign \m_w[data] [10] = \s_w[data] [10];
  assign \m_w[data] [11] = \s_w[data] [11];
  assign \m_w[data] [12] = \s_w[data] [12];
  assign \m_w[data] [13] = \s_w[data] [13];
  assign \m_w[data] [14] = \s_w[data] [14];
  assign \m_w[data] [15] = \s_w[data] [15];
  assign \m_w[data] [16] = \s_w[data] [16];
  assign \m_w[data] [17] = \s_w[data] [17];
  assign \m_w[data] [18] = \s_w[data] [18];
  assign \m_w[data] [19] = \s_w[data] [19];
  assign \m_w[data] [20] = \s_w[data] [20];
  assign \m_w[data] [21] = \s_w[data] [21];
  assign \m_w[data] [22] = \s_w[data] [22];
  assign \m_w[data] [23] = \s_w[data] [23];
  assign \m_w[data] [24] = \s_w[data] [24];
  assign \m_w[data] [25] = \s_w[data] [25];
  assign \m_w[data] [26] = \s_w[data] [26];
  assign \m_w[data] [27] = \s_w[data] [27];
  assign \m_w[data] [28] = \s_w[data] [28];
  assign \m_w[data] [29] = \s_w[data] [29];
  assign \m_w[data] [30] = \s_w[data] [30];
  assign \m_w[data] [31] = \s_w[data] [31];
  assign \m_w[strb] [0] = \s_w[strb] [0];
  assign \m_w[strb] [1] = \s_w[strb] [1];
  assign \m_w[strb] [2] = \s_w[strb] [2];
  assign \m_w[strb] [3] = \s_w[strb] [3];
  AND4X1 g271(.A (dut_mode[1]), .B (n_14), .C (dut_rd_upstream_empty),
       .D (dut_wr_upstream_empty), .Y (dut_epoch_clr));
  NOR2XL g272(.A (n_13), .B (dut_mode[0]), .Y (n_14));
  NOR3X1 g273(.A (dut_rcvy_ack[0]), .B (dut_rcvy_ack[2]), .C
       (dut_rcvy_ack[1]), .Y (n_13));
  DFFRHQX1 \dut_u_irq_rcvy_ack_reg[2] (.RN (rst_n), .CK (clk), .D
       (clear_reg[2]), .Q (dut_rcvy_ack[2]));
  DFFRHQX1 \dut_u_irq_rcvy_ack_reg[1] (.RN (rst_n), .CK (clk), .D
       (clear_reg[1]), .Q (dut_rcvy_ack[1]));
  DFFRHQX1 \dut_u_irq_rcvy_ack_reg[0] (.RN (rst_n), .CK (clk), .D
       (clear_reg[0]), .Q (dut_rcvy_ack[0]));
  AND2XL g277(.A (dut_rd_upstream_empty), .B (dut_wr_upstream_empty),
       .Y (dut_all_upstream_empty));
  NAND2X1 g278(.A (dut_n_418), .B (dut_n_419), .Y (dut_flush));
  AND2X1 g222(.A (dut_all_upstream_empty), .B (n_12), .Y (irq));
  OAI2BB1X1 g223(.A0N (enable_reg[0]), .A1N (status_reg[0]), .B0
       (n_11), .Y (n_12));
  AOI22X1 g224(.A0 (enable_reg[1]), .A1 (status_reg[1]), .B0
       (enable_reg[2]), .B1 (status_reg[2]), .Y (n_11));
  OR2X1 g225(.A (dut_rd_busy), .B (dut_wr_busy), .Y (guard_busy));
  NOR2BX1 g366(.AN (n_9), .B (dut_mode[1]), .Y (n_10));
  OAI22X1 g368(.A0 (dut_mode[0]), .A1 (n_4), .B0 (dut_n_418), .B1
       (dut_all_upstream_empty), .Y (n_9));
  DFFRHQX1 \dut_u_irq_status_reg_reg[0] (.RN (rst_n), .CK (clk), .D
       (n_7), .Q (status_reg[0]));
  DFFRHQX1 \dut_u_irq_status_reg_reg[1] (.RN (rst_n), .CK (clk), .D
       (n_6), .Q (status_reg[1]));
  OAI33X1 g371(.A0 (dut_mode[0]), .A1 (dut_n_419), .A2 (dut_epoch_clr),
       .B0 (dut_n_418), .B1 (dut_mode[1]), .B2 (n_0), .Y (n_8));
  DFFRHQX1 \dut_u_irq_status_reg_reg[2] (.RN (rst_n), .CK (clk), .D
       (n_5), .Q (status_reg[2]));
  OR2XL g373(.A (n_3), .B (dut_rd_timeout_pulse), .Y (n_7));
  OR2XL g374(.A (n_2), .B (dut_wr_w_fault_pulse), .Y (n_6));
  OR2XL g375(.A (n_1), .B (dut_wr_timeout_pulse), .Y (n_5));
  NOR3XL g376(.A (dut_wr_timeout_pulse), .B (dut_wr_w_fault_pulse), .C
       (dut_rd_timeout_pulse), .Y (n_4));
  NOR2BX1 g377(.AN (status_reg[0]), .B (clear_reg[0]), .Y (n_3));
  NOR2BX1 g378(.AN (status_reg[1]), .B (clear_reg[1]), .Y (n_2));
  NOR2BX1 g379(.AN (status_reg[2]), .B (clear_reg[2]), .Y (n_1));
  INVX1 g380(.A (dut_all_upstream_empty), .Y (n_0));
  INVX1 dut_u_wr_g1995(.A (s_awvalid), .Y (dut_u_wr_n_2305));
  OA21X1 dut_u_wr_g2103(.A0 (dut_u_wr_downstream_aw_fire), .A1
       (dut_u_wr_downstream_aw_done), .B0 (n_225), .Y (s_wready));
  AND2X1 dut_u_wr_g2105(.A (m_awvalid), .B (m_awready), .Y
       (dut_u_wr_downstream_aw_fire));
  AND2X1 dut_u_wr_g2106(.A (m_wvalid), .B (m_wready), .Y
       (dut_u_wr_downstream_w_fire));
  NOR2X1 dut_u_wr_g2033(.A (dut_u_wr_wpair_state[0]), .B
       (dut_u_wr_n_442), .Y (dut_wr_upstream_empty));
  OR4X1 dut_u_wr_g2034(.A (dut_u_wr_outst_cnt[0]), .B
       (dut_u_wr_outst_cnt[1]), .C (dut_u_wr_outst_cnt[2]), .D
       (dut_u_wr_n_2282), .Y (dut_u_wr_n_442));
  OR2XL dut_u_wr_g2035(.A (dut_u_wr_outst_cnt[3]), .B
       (dut_u_wr_outst_cnt[4]), .Y (dut_u_wr_n_2282));
  NOR2X1 dut_u_wr_g2832(.A (dut_u_wr_n_2739), .B (dut_u_wr_n_2755), .Y
       (dut_wr_timeout_pulse));
  OR2X1 dut_u_wr_g2833(.A (dut_u_wr_n_2742), .B (n_224), .Y (s_bvalid));
  INVX1 dut_u_wr_g2834(.A (dut_u_wr_n_2739), .Y (dut_u_wr_b_timer_run));
  NAND2X1 dut_u_wr_g2836(.A (dut_u_wr_n_2752), .B (dut_u_wr_n_428), .Y
       (dut_u_wr_n_2739));
  NOR2XL dut_u_wr_g2837(.A (dut_u_wr_n_2752), .B (dut_u_wr_n_2781), .Y
       (dut_u_wr_n_2742));
  AND4XL dut_u_wr_g2838(.A (dut_u_wr_w_timer_run), .B
       (dut_u_wr_n_2775), .C (dut_u_wr_n_2774), .D (dut_u_wr_n_2758),
       .Y (dut_wr_w_fault_pulse));
  NOR2X2 dut_u_wr_g2839(.A (n_222), .B (dut_u_wr_downstream_aw_done),
       .Y (m_awvalid));
  NOR2X2 dut_u_wr_g2840(.A (n_222), .B (dut_u_wr_downstream_w_done), .Y
       (m_wvalid));
  OR2X1 dut_u_wr_g2841(.A (dut_u_wr_n_431), .B (dut_u_wr_n_430), .Y
       (m_bready));
  AOI211XL dut_u_wr_g2842(.A0 (dut_u_wr_outst_cnt[4]), .A1
       (dut_u_wr_n_2773), .B0 (dut_flush), .C0 (dut_u_wr_n_2785), .Y
       (dut_u_wr_n_2753));
  NAND3BXL dut_u_wr_g2843(.AN (dut_u_wr_n_442), .B (dut_u_wr_n_2786),
       .C (dut_u_wr_n_2761), .Y (dut_wr_busy));
  NAND4XL dut_u_wr_g2844(.A (dut_u_wr_n_2776), .B (dut_u_wr_n_2766), .C
       (dut_u_wr_n_2778), .D (dut_u_wr_n_2770), .Y (dut_u_wr_n_2755));
  NAND2BX1 dut_u_wr_g2845(.AN (dut_u_wr_n_430), .B (m_bvalid), .Y
       (dut_u_wr_n_2752));
  NOR4X1 dut_u_wr_g2847(.A (dut_u_wr_w_timer[2]), .B
       (dut_u_wr_w_timer[3]), .C (dut_u_wr_n_2787), .D
       (dut_u_wr_n_2777), .Y (dut_u_wr_n_2758));
  INVXL dut_u_wr_g2849(.A (dut_u_wr_n_430), .Y (dut_u_wr_n_2761));
  AO21X1 dut_u_wr_g2850(.A0 (\m_b[resp] [1]), .A1 (dut_u_wr_n_428), .B0
       (n_224), .Y (\s_b[resp] [1]));
  OR4X1 dut_u_wr_g2851(.A (dut_u_wr_drain_cnt[1]), .B
       (dut_u_wr_drain_cnt[0]), .C (dut_u_wr_drain_cnt[2]), .D
       (dut_u_wr_n_2788), .Y (dut_u_wr_n_430));
  NOR4BX1 dut_u_wr_g2852(.AN (dut_u_wr_b_timer[8]), .B
       (dut_u_wr_b_timer[3]), .C (dut_u_wr_b_timer[9]), .D
       (dut_u_wr_b_timer[2]), .Y (dut_u_wr_n_2766));
  AND2X1 dut_u_wr_g2854(.A (dut_u_wr_n_428), .B (\m_b[resp] [0]), .Y
       (\s_b[resp] [0]));
  NOR4X1 dut_u_wr_g2855(.A (dut_u_wr_b_timer[13]), .B
       (dut_u_wr_b_timer[12]), .C (dut_u_wr_b_timer[14]), .D
       (dut_u_wr_b_timer[15]), .Y (dut_u_wr_n_2770));
  NOR2BX1 dut_u_wr_g2856(.AN (s_bready), .B (dut_u_wr_n_2781), .Y
       (dut_u_wr_n_431));
  AND2X1 dut_u_wr_g2857(.A (dut_u_wr_w_perm), .B (dut_u_wr_n_2796), .Y
       (dut_u_wr_w_timer_run));
  INVX1 dut_u_wr_g2858(.A (dut_u_wr_n_2773), .Y (dut_u_wr_n_701));
  NOR4X1 dut_u_wr_g2859(.A (dut_u_wr_w_timer[13]), .B
       (dut_u_wr_w_timer[12]), .C (dut_u_wr_w_timer[14]), .D
       (dut_u_wr_w_timer[15]), .Y (dut_u_wr_n_2774));
  NOR4X1 dut_u_wr_g2860(.A (dut_u_wr_w_timer[4]), .B
       (dut_u_wr_w_timer[5]), .C (dut_u_wr_w_timer[10]), .D
       (dut_u_wr_w_timer[11]), .Y (dut_u_wr_n_2775));
  NOR4X1 dut_u_wr_g2861(.A (dut_u_wr_b_timer[4]), .B
       (dut_u_wr_b_timer[5]), .C (dut_u_wr_b_timer[10]), .D
       (dut_u_wr_b_timer[11]), .Y (dut_u_wr_n_2776));
  OR4X1 dut_u_wr_g2862(.A (dut_u_wr_w_timer[1]), .B
       (dut_u_wr_w_timer[0]), .C (dut_u_wr_w_timer[7]), .D
       (dut_u_wr_w_timer[6]), .Y (dut_u_wr_n_2777));
  NOR4X1 dut_u_wr_g2863(.A (dut_u_wr_b_timer[0]), .B
       (dut_u_wr_b_timer[1]), .C (dut_u_wr_b_timer[7]), .D
       (dut_u_wr_b_timer[6]), .Y (dut_u_wr_n_2778));
  NOR4X1 dut_u_wr_g2864(.A (dut_u_wr_outst_cnt[3]), .B
       (dut_u_wr_outst_cnt[2]), .C (dut_u_wr_outst_cnt[0]), .D
       (dut_u_wr_outst_cnt[1]), .Y (dut_u_wr_n_2773));
  INVX1 dut_u_wr_g2865(.A (dut_u_wr_n_2781), .Y (dut_u_wr_n_428));
  NOR2BX1 dut_u_wr_g2867(.AN (dut_u_wr_wpair_state[0]), .B
       (dut_u_wr_wpair_state[1]), .Y (dut_u_wr_w_perm));
  NAND2BX1 dut_u_wr_g2868(.AN (dut_u_wr_wr_state[1]), .B
       (dut_u_wr_wr_state[0]), .Y (dut_u_wr_n_2781));
  INVXL dut_u_wr_g2869(.A (dut_u_wr_n_2786), .Y (dut_u_wr_n_2785));
  NAND2BX1 dut_u_wr_g2870(.AN (dut_u_wr_w_timer[9]), .B
       (dut_u_wr_w_timer[8]), .Y (dut_u_wr_n_2787));
  OR2XL dut_u_wr_g2871(.A (dut_u_wr_drain_cnt[3]), .B
       (dut_u_wr_drain_cnt[4]), .Y (dut_u_wr_n_2788));
  NOR2X1 dut_u_wr_g2872(.A (dut_u_wr_wpair_state[0]), .B
       (dut_u_wr_wpair_state[1]), .Y (dut_u_wr_n_2786));
  INVXL dut_u_wr_g2874(.A (s_wvalid), .Y (dut_u_wr_n_2796));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][0] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [0]), .SI (\m_aw[addr] [0]), .SE (dut_u_wr_n_4103),
       .Q (\m_aw[addr] [0]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][1] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [1]), .SI (\m_aw[addr] [1]), .SE (dut_u_wr_n_4103),
       .Q (\m_aw[addr] [1]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][2] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [2]), .SI (\m_aw[addr] [2]), .SE (dut_u_wr_n_4103),
       .Q (\m_aw[addr] [2]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][3] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [3]), .SI (\m_aw[addr] [3]), .SE (dut_u_wr_n_4103),
       .Q (\m_aw[addr] [3]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][4] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [4]), .SI (\m_aw[addr] [4]), .SE (dut_u_wr_n_4103),
       .Q (\m_aw[addr] [4]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][5] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [5]), .SI (\m_aw[addr] [5]), .SE (dut_u_wr_n_4103),
       .Q (\m_aw[addr] [5]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][6] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [6]), .SI (\m_aw[addr] [6]), .SE (dut_u_wr_n_4103),
       .Q (\m_aw[addr] [6]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][7] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [7]), .SI (\m_aw[addr] [7]), .SE (dut_u_wr_n_4103),
       .Q (\m_aw[addr] [7]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][8] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [8]), .SI (\m_aw[addr] [8]), .SE (dut_u_wr_n_4103),
       .Q (\m_aw[addr] [8]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][9] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [9]), .SI (\m_aw[addr] [9]), .SE (dut_u_wr_n_4103),
       .Q (\m_aw[addr] [9]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][10] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [10]), .SI (\m_aw[addr] [10]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [10]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][11] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [11]), .SI (\m_aw[addr] [11]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [11]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][12] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [12]), .SI (\m_aw[addr] [12]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [12]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][13] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [13]), .SI (\m_aw[addr] [13]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [13]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][14] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [14]), .SI (\m_aw[addr] [14]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [14]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][15] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [15]), .SI (\m_aw[addr] [15]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [15]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][16] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [16]), .SI (\m_aw[addr] [16]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [16]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][17] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [17]), .SI (\m_aw[addr] [17]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [17]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][18] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [18]), .SI (\m_aw[addr] [18]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [18]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][19] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [19]), .SI (\m_aw[addr] [19]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [19]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][20] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [20]), .SI (\m_aw[addr] [20]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [20]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][21] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [21]), .SI (\m_aw[addr] [21]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [21]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][22] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [22]), .SI (\m_aw[addr] [22]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [22]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][23] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [23]), .SI (\m_aw[addr] [23]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [23]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][24] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [24]), .SI (\m_aw[addr] [24]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [24]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][25] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [25]), .SI (\m_aw[addr] [25]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [25]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][26] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [26]), .SI (\m_aw[addr] [26]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [26]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][27] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [27]), .SI (\m_aw[addr] [27]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [27]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][28] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [28]), .SI (\m_aw[addr] [28]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [28]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][29] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [29]), .SI (\m_aw[addr] [29]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [29]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][30] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [30]), .SI (\m_aw[addr] [30]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [30]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][31] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [31]), .SI (\m_aw[addr] [31]), .SE
       (dut_u_wr_n_4103), .Q (\m_aw[addr] [31]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[prot][0] (.RN (rst_n), .CK (clk), .D
       (\s_aw[prot] [0]), .SI (\m_aw[prot] [0]), .SE (dut_u_wr_n_4103),
       .Q (\m_aw[prot] [0]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[prot][1] (.RN (rst_n), .CK (clk), .D
       (\s_aw[prot] [1]), .SI (\m_aw[prot] [1]), .SE (dut_u_wr_n_4103),
       .Q (\m_aw[prot] [1]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[prot][2] (.RN (rst_n), .CK (clk), .D
       (\s_aw[prot] [2]), .SI (\m_aw[prot] [2]), .SE (dut_u_wr_n_4103),
       .Q (\m_aw[prot] [2]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3971), .Q (dut_u_wr_b_timer[0]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3965), .Q (dut_u_wr_b_timer[1]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3915), .Q (dut_u_wr_b_timer[2]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3888), .Q (dut_u_wr_b_timer[3]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3866), .Q (dut_u_wr_b_timer[4]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[5] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3852), .Q (dut_u_wr_b_timer[5]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[6] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3838), .Q (dut_u_wr_b_timer[6]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[7] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3824), .Q (dut_u_wr_b_timer[7]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[8] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3810), .Q (dut_u_wr_b_timer[8]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[9] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3796), .Q (dut_u_wr_b_timer[9]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[10] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3782), .Q (dut_u_wr_b_timer[10]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[11] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3768), .Q (dut_u_wr_b_timer[11]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[12] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3754), .Q (dut_u_wr_b_timer[12]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[13] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3740), .Q (dut_u_wr_b_timer[13]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[14] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3724), .Q (dut_u_wr_b_timer[14]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[15] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3719), .Q (dut_u_wr_b_timer[15]));
  DFFRHQX1 dut_u_wr_downstream_aw_done_reg(.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4076), .Q (dut_u_wr_downstream_aw_done));
  DFFRHQX1 dut_u_wr_downstream_w_done_reg(.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4078), .Q (dut_u_wr_downstream_w_done));
  SDFFRHQX1 \dut_u_wr_drain_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3977), .SI (dut_u_wr_n_3983), .SE
       (dut_u_wr_drain_cnt[0]), .Q (dut_u_wr_drain_cnt[0]));
  DFFRHQX1 \dut_u_wr_drain_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3927), .Q (dut_u_wr_drain_cnt[1]));
  SDFFRHQX1 \dut_u_wr_drain_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3966), .SI (dut_u_wr_n_3924), .SE
       (dut_u_wr_drain_cnt[3]), .Q (dut_u_wr_drain_cnt[3]));
  SDFFRHQX1 \dut_u_wr_drain_cnt_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3943), .SI (dut_u_wr_n_3916), .SE
       (dut_u_wr_drain_cnt[4]), .Q (dut_u_wr_drain_cnt[4]));
  DFFRHQX1 \dut_u_wr_outst_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3920), .Q (dut_u_wr_outst_cnt[0]));
  DFFRHQX1 \dut_u_wr_outst_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3918), .Q (dut_u_wr_outst_cnt[1]));
  DFFRHQX1 \dut_u_wr_outst_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3901), .Q (dut_u_wr_outst_cnt[2]));
  DFFRHQX1 \dut_u_wr_outst_cnt_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3892), .Q (dut_u_wr_outst_cnt[4]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4075), .Q (dut_u_wr_w_timer[0]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3964), .Q (dut_u_wr_w_timer[1]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3914), .Q (dut_u_wr_w_timer[2]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3889), .Q (dut_u_wr_w_timer[3]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3867), .Q (dut_u_wr_w_timer[4]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[5] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3853), .Q (dut_u_wr_w_timer[5]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[6] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3839), .Q (dut_u_wr_w_timer[6]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[7] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3825), .Q (dut_u_wr_w_timer[7]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[8] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3811), .Q (dut_u_wr_w_timer[8]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[9] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3797), .Q (dut_u_wr_w_timer[9]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[10] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3783), .Q (dut_u_wr_w_timer[10]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[11] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3769), .Q (dut_u_wr_w_timer[11]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[12] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3755), .Q (dut_u_wr_w_timer[12]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[13] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3741), .Q (dut_u_wr_w_timer[13]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[14] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3726), .Q (dut_u_wr_w_timer[14]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[15] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3718), .Q (dut_u_wr_w_timer[15]));
  DFFRHQX1 \dut_u_wr_wpair_state_reg[0] (.RN (rst_n), .CK (clk), .D
       (n_223), .Q (dut_u_wr_wpair_state[0]));
  DFFRHQX1 \dut_u_wr_wr_state_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3868), .Q (dut_u_wr_wr_state[0]));
  DFFRHQX1 \dut_u_wr_wr_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3958), .Q (dut_u_wr_wr_state[1]));
  NOR2XL dut_u_wr_g6042(.A (dut_u_wr_n_4089), .B (dut_u_wr_n_3720), .Y
       (dut_u_wr_n_3718));
  NOR2XL dut_u_wr_g6043(.A (dut_u_wr_n_4029), .B (dut_u_wr_n_3722), .Y
       (dut_u_wr_n_3719));
  AOI22X1 dut_u_wr_g6046(.A0 (dut_u_wr_w_timer_run), .A1
       (dut_u_wr_n_3728), .B0 (dut_u_wr_w_timer[15]), .B1
       (dut_u_wr_n_4192), .Y (dut_u_wr_n_3720));
  AOI22X1 dut_u_wr_g6047(.A0 (dut_u_wr_b_timer_run), .A1
       (dut_u_wr_n_3729), .B0 (dut_u_wr_b_timer[15]), .B1
       (dut_u_wr_n_4276), .Y (dut_u_wr_n_3722));
  AOI21XL dut_u_wr_g6048(.A0 (dut_u_wr_n_4155), .A1 (dut_u_wr_n_3734),
       .B0 (dut_u_wr_n_4029), .Y (dut_u_wr_n_3724));
  AOI21XL dut_u_wr_g6049(.A0 (dut_u_wr_n_4152), .A1 (dut_u_wr_n_3730),
       .B0 (dut_u_wr_n_4089), .Y (dut_u_wr_n_3726));
  XNOR2X1 dut_u_wr_g6050(.A (dut_u_wr_w_timer[15]), .B
       (dut_u_wr_n_3742), .Y (dut_u_wr_n_3728));
  XNOR2X1 dut_u_wr_g6051(.A (dut_u_wr_b_timer[15]), .B
       (dut_u_wr_n_3744), .Y (dut_u_wr_n_3729));
  OAI211X1 dut_u_wr_g6054(.A0 (dut_u_wr_w_timer[14]), .A1
       (dut_u_wr_n_3750), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3742), .Y (dut_u_wr_n_3730));
  OAI211X1 dut_u_wr_g6055(.A0 (dut_u_wr_b_timer[14]), .A1
       (dut_u_wr_n_3752), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_3744), .Y (dut_u_wr_n_3734));
  AOI21XL dut_u_wr_g6056(.A0 (dut_u_wr_n_4153), .A1 (dut_u_wr_n_3747),
       .B0 (dut_u_wr_n_4029), .Y (dut_u_wr_n_3740));
  AOI21XL dut_u_wr_g6057(.A0 (dut_u_wr_n_4126), .A1 (dut_u_wr_n_3745),
       .B0 (dut_u_wr_n_4089), .Y (dut_u_wr_n_3741));
  NAND2X1 dut_u_wr_g6058(.A (dut_u_wr_w_timer[14]), .B
       (dut_u_wr_n_3750), .Y (dut_u_wr_n_3742));
  OAI211X1 dut_u_wr_g6061(.A0 (dut_u_wr_w_timer[13]), .A1
       (dut_u_wr_n_3764), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3756), .Y (dut_u_wr_n_3745));
  OAI211X1 dut_u_wr_g6062(.A0 (dut_u_wr_b_timer[13]), .A1
       (dut_u_wr_n_3766), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_3758), .Y (dut_u_wr_n_3747));
  NAND2X1 dut_u_wr_g6063(.A (dut_u_wr_b_timer[14]), .B
       (dut_u_wr_n_3752), .Y (dut_u_wr_n_3744));
  INVX1 dut_u_wr_g6064(.A (dut_u_wr_n_3756), .Y (dut_u_wr_n_3750));
  INVX1 dut_u_wr_g6065(.A (dut_u_wr_n_3758), .Y (dut_u_wr_n_3752));
  AOI21XL dut_u_wr_g6066(.A0 (dut_u_wr_n_4144), .A1 (dut_u_wr_n_3761),
       .B0 (dut_u_wr_n_4029), .Y (dut_u_wr_n_3754));
  AOI21XL dut_u_wr_g6067(.A0 (dut_u_wr_n_4129), .A1 (dut_u_wr_n_3759),
       .B0 (dut_u_wr_n_4089), .Y (dut_u_wr_n_3755));
  NAND2X1 dut_u_wr_g6068(.A (dut_u_wr_w_timer[13]), .B
       (dut_u_wr_n_3764), .Y (dut_u_wr_n_3756));
  OAI211X1 dut_u_wr_g6071(.A0 (dut_u_wr_w_timer[12]), .A1
       (dut_u_wr_n_3778), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3770), .Y (dut_u_wr_n_3759));
  OAI211X1 dut_u_wr_g6072(.A0 (dut_u_wr_b_timer[12]), .A1
       (dut_u_wr_n_3780), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_3772), .Y (dut_u_wr_n_3761));
  NAND2X1 dut_u_wr_g6073(.A (dut_u_wr_b_timer[13]), .B
       (dut_u_wr_n_3766), .Y (dut_u_wr_n_3758));
  INVX1 dut_u_wr_g6074(.A (dut_u_wr_n_3770), .Y (dut_u_wr_n_3764));
  INVX1 dut_u_wr_g6075(.A (dut_u_wr_n_3772), .Y (dut_u_wr_n_3766));
  AOI21XL dut_u_wr_g6076(.A0 (dut_u_wr_n_4150), .A1 (dut_u_wr_n_3775),
       .B0 (dut_u_wr_n_4029), .Y (dut_u_wr_n_3768));
  AOI21XL dut_u_wr_g6077(.A0 (dut_u_wr_n_4136), .A1 (dut_u_wr_n_3773),
       .B0 (dut_u_wr_n_4089), .Y (dut_u_wr_n_3769));
  NAND2X1 dut_u_wr_g6078(.A (dut_u_wr_w_timer[12]), .B
       (dut_u_wr_n_3778), .Y (dut_u_wr_n_3770));
  OAI211X1 dut_u_wr_g6081(.A0 (dut_u_wr_w_timer[11]), .A1
       (dut_u_wr_n_3794), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3784), .Y (dut_u_wr_n_3773));
  OAI211X1 dut_u_wr_g6082(.A0 (dut_u_wr_b_timer[11]), .A1
       (dut_u_wr_n_3792), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_3786), .Y (dut_u_wr_n_3775));
  NAND2X1 dut_u_wr_g6083(.A (dut_u_wr_b_timer[12]), .B
       (dut_u_wr_n_3780), .Y (dut_u_wr_n_3772));
  INVX1 dut_u_wr_g6084(.A (dut_u_wr_n_3784), .Y (dut_u_wr_n_3778));
  INVX1 dut_u_wr_g6085(.A (dut_u_wr_n_3786), .Y (dut_u_wr_n_3780));
  AOI21XL dut_u_wr_g6086(.A0 (dut_u_wr_n_4149), .A1 (dut_u_wr_n_3789),
       .B0 (dut_u_wr_n_4029), .Y (dut_u_wr_n_3782));
  AOI21XL dut_u_wr_g6087(.A0 (dut_u_wr_n_4158), .A1 (dut_u_wr_n_3787),
       .B0 (dut_u_wr_n_4089), .Y (dut_u_wr_n_3783));
  NAND2X1 dut_u_wr_g6088(.A (dut_u_wr_w_timer[11]), .B
       (dut_u_wr_n_3794), .Y (dut_u_wr_n_3784));
  OAI211X1 dut_u_wr_g6091(.A0 (dut_u_wr_w_timer[10]), .A1
       (dut_u_wr_n_3808), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3798), .Y (dut_u_wr_n_3787));
  OAI211X1 dut_u_wr_g6092(.A0 (dut_u_wr_b_timer[10]), .A1
       (dut_u_wr_n_3806), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_3800), .Y (dut_u_wr_n_3789));
  NAND2X1 dut_u_wr_g6093(.A (dut_u_wr_b_timer[11]), .B
       (dut_u_wr_n_3792), .Y (dut_u_wr_n_3786));
  INVX1 dut_u_wr_g6094(.A (dut_u_wr_n_3800), .Y (dut_u_wr_n_3792));
  INVX1 dut_u_wr_g6095(.A (dut_u_wr_n_3798), .Y (dut_u_wr_n_3794));
  AOI21XL dut_u_wr_g6096(.A0 (dut_u_wr_n_4146), .A1 (dut_u_wr_n_3803),
       .B0 (dut_u_wr_n_4029), .Y (dut_u_wr_n_3796));
  AOI21XL dut_u_wr_g6097(.A0 (dut_u_wr_n_4148), .A1 (dut_u_wr_n_3801),
       .B0 (dut_u_wr_n_4089), .Y (dut_u_wr_n_3797));
  NAND2X1 dut_u_wr_g6098(.A (dut_u_wr_w_timer[10]), .B
       (dut_u_wr_n_3808), .Y (dut_u_wr_n_3798));
  OAI211X1 dut_u_wr_g6101(.A0 (dut_u_wr_w_timer[9]), .A1
       (dut_u_wr_n_3820), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3812), .Y (dut_u_wr_n_3801));
  OAI211X1 dut_u_wr_g6102(.A0 (dut_u_wr_b_timer[9]), .A1
       (dut_u_wr_n_3822), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_3814), .Y (dut_u_wr_n_3803));
  NAND2X1 dut_u_wr_g6103(.A (dut_u_wr_b_timer[10]), .B
       (dut_u_wr_n_3806), .Y (dut_u_wr_n_3800));
  INVX1 dut_u_wr_g6104(.A (dut_u_wr_n_3814), .Y (dut_u_wr_n_3806));
  INVX1 dut_u_wr_g6105(.A (dut_u_wr_n_3812), .Y (dut_u_wr_n_3808));
  AOI21XL dut_u_wr_g6106(.A0 (dut_u_wr_n_4151), .A1 (dut_u_wr_n_3817),
       .B0 (dut_u_wr_n_4029), .Y (dut_u_wr_n_3810));
  AOI21XL dut_u_wr_g6107(.A0 (dut_u_wr_n_4134), .A1 (dut_u_wr_n_3815),
       .B0 (dut_u_wr_n_4089), .Y (dut_u_wr_n_3811));
  NAND2X1 dut_u_wr_g6108(.A (dut_u_wr_w_timer[9]), .B
       (dut_u_wr_n_3820), .Y (dut_u_wr_n_3812));
  OAI211X1 dut_u_wr_g6111(.A0 (dut_u_wr_w_timer[8]), .A1
       (dut_u_wr_n_3836), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3826), .Y (dut_u_wr_n_3815));
  OAI211X1 dut_u_wr_g6112(.A0 (dut_u_wr_b_timer[8]), .A1
       (dut_u_wr_n_3834), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_3828), .Y (dut_u_wr_n_3817));
  NAND2X1 dut_u_wr_g6113(.A (dut_u_wr_b_timer[9]), .B
       (dut_u_wr_n_3822), .Y (dut_u_wr_n_3814));
  INVX1 dut_u_wr_g6114(.A (dut_u_wr_n_3826), .Y (dut_u_wr_n_3820));
  INVX1 dut_u_wr_g6115(.A (dut_u_wr_n_3828), .Y (dut_u_wr_n_3822));
  AOI21XL dut_u_wr_g6116(.A0 (dut_u_wr_n_4156), .A1 (dut_u_wr_n_3831),
       .B0 (dut_u_wr_n_4029), .Y (dut_u_wr_n_3824));
  AOI21XL dut_u_wr_g6117(.A0 (dut_u_wr_n_4131), .A1 (dut_u_wr_n_3829),
       .B0 (dut_u_wr_n_4089), .Y (dut_u_wr_n_3825));
  NAND2X1 dut_u_wr_g6118(.A (dut_u_wr_w_timer[8]), .B
       (dut_u_wr_n_3836), .Y (dut_u_wr_n_3826));
  OAI211X1 dut_u_wr_g6121(.A0 (dut_u_wr_w_timer[7]), .A1
       (dut_u_wr_n_3848), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3842), .Y (dut_u_wr_n_3829));
  OAI211X1 dut_u_wr_g6122(.A0 (dut_u_wr_b_timer[7]), .A1
       (dut_u_wr_n_3850), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_3840), .Y (dut_u_wr_n_3831));
  NAND2X1 dut_u_wr_g6123(.A (dut_u_wr_b_timer[8]), .B
       (dut_u_wr_n_3834), .Y (dut_u_wr_n_3828));
  INVX1 dut_u_wr_g6124(.A (dut_u_wr_n_3840), .Y (dut_u_wr_n_3834));
  INVX1 dut_u_wr_g6125(.A (dut_u_wr_n_3842), .Y (dut_u_wr_n_3836));
  AOI21X1 dut_u_wr_g6126(.A0 (dut_u_wr_n_4122), .A1 (dut_u_wr_n_3845),
       .B0 (dut_u_wr_n_4029), .Y (dut_u_wr_n_3838));
  AOI21XL dut_u_wr_g6127(.A0 (dut_u_wr_n_4145), .A1 (dut_u_wr_n_3843),
       .B0 (dut_u_wr_n_4089), .Y (dut_u_wr_n_3839));
  NAND2X1 dut_u_wr_g6128(.A (dut_u_wr_b_timer[7]), .B
       (dut_u_wr_n_3850), .Y (dut_u_wr_n_3840));
  OAI211X1 dut_u_wr_g6131(.A0 (dut_u_wr_w_timer[6]), .A1
       (dut_u_wr_n_3862), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3855), .Y (dut_u_wr_n_3843));
  OAI211X1 dut_u_wr_g6132(.A0 (dut_u_wr_b_timer[6]), .A1
       (dut_u_wr_n_3864), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_3854), .Y (dut_u_wr_n_3845));
  NAND2X1 dut_u_wr_g6133(.A (dut_u_wr_w_timer[7]), .B
       (dut_u_wr_n_3848), .Y (dut_u_wr_n_3842));
  INVX1 dut_u_wr_g6134(.A (dut_u_wr_n_3855), .Y (dut_u_wr_n_3848));
  INVX1 dut_u_wr_g6135(.A (dut_u_wr_n_3854), .Y (dut_u_wr_n_3850));
  AOI21X1 dut_u_wr_g6136(.A0 (dut_u_wr_n_4125), .A1 (dut_u_wr_n_3858),
       .B0 (dut_u_wr_n_4029), .Y (dut_u_wr_n_3852));
  AOI21XL dut_u_wr_g6137(.A0 (dut_u_wr_n_4120), .A1 (dut_u_wr_n_3856),
       .B0 (dut_u_wr_n_4089), .Y (dut_u_wr_n_3853));
  OAI211X1 dut_u_wr_g6141(.A0 (dut_u_wr_w_timer[5]), .A1
       (dut_u_wr_n_3881), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3869), .Y (dut_u_wr_n_3856));
  OAI211X1 dut_u_wr_g6142(.A0 (dut_u_wr_b_timer[5]), .A1
       (dut_u_wr_n_3883), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_3870), .Y (dut_u_wr_n_3858));
  NAND2X1 dut_u_wr_g6143(.A (dut_u_wr_b_timer[6]), .B
       (dut_u_wr_n_3864), .Y (dut_u_wr_n_3854));
  NAND2X1 dut_u_wr_g6144(.A (dut_u_wr_w_timer[6]), .B
       (dut_u_wr_n_3862), .Y (dut_u_wr_n_3855));
  INVX1 dut_u_wr_g6145(.A (dut_u_wr_n_3869), .Y (dut_u_wr_n_3862));
  INVX1 dut_u_wr_g6146(.A (dut_u_wr_n_3870), .Y (dut_u_wr_n_3864));
  AOI21X1 dut_u_wr_g6147(.A0 (dut_u_wr_n_3879), .A1 (dut_u_wr_n_4130),
       .B0 (dut_u_wr_n_4029), .Y (dut_u_wr_n_3866));
  AOI21XL dut_u_wr_g6148(.A0 (dut_u_wr_n_4128), .A1 (dut_u_wr_n_3873),
       .B0 (dut_u_wr_n_4089), .Y (dut_u_wr_n_3867));
  AOI2BB1XL dut_u_wr_g6149(.A0N (dut_u_wr_n_3878), .A1N
       (dut_u_wr_n_3875), .B0 (dut_epoch_clr), .Y (dut_u_wr_n_3868));
  NAND2X1 dut_u_wr_g6150(.A (dut_u_wr_w_timer[5]), .B
       (dut_u_wr_n_3881), .Y (dut_u_wr_n_3869));
  NAND2X1 dut_u_wr_g6151(.A (dut_u_wr_b_timer[5]), .B
       (dut_u_wr_n_3883), .Y (dut_u_wr_n_3870));
  OAI211X1 dut_u_wr_g6154(.A0 (dut_u_wr_w_timer[4]), .A1
       (dut_u_wr_n_3906), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3895), .Y (dut_u_wr_n_3873));
  OAI32X1 dut_u_wr_g6155(.A0 (dut_u_wr_wr_state[0]), .A1
       (dut_u_wr_wr_state[1]), .A2 (dut_u_wr_n_4143), .B0
       (dut_u_wr_n_4081), .B1 (dut_u_wr_n_3890), .Y (dut_u_wr_n_3875));
  NOR4BX1 dut_u_wr_g6156(.AN (dut_u_wr_n_428), .B (dut_flush), .C
       (dut_wr_timeout_pulse), .D (dut_u_wr_n_3885), .Y
       (dut_u_wr_n_3878));
  OAI211X1 dut_u_wr_g6157(.A0 (dut_u_wr_b_timer[4]), .A1
       (dut_u_wr_n_3908), .B0 (dut_u_wr_n_3896), .C0
       (dut_u_wr_b_timer_run), .Y (dut_u_wr_n_3879));
  INVX1 dut_u_wr_g6158(.A (dut_u_wr_n_3895), .Y (dut_u_wr_n_3881));
  INVX1 dut_u_wr_g6159(.A (dut_u_wr_n_3896), .Y (dut_u_wr_n_3883));
  NOR2BX1 dut_u_wr_g6160(.AN (dut_u_wr_n_3890), .B (dut_u_wr_n_4138),
       .Y (dut_u_wr_n_3885));
  AOI21X1 dut_u_wr_g6162(.A0 (dut_u_wr_n_3897), .A1 (dut_u_wr_n_4137),
       .B0 (dut_u_wr_n_4029), .Y (dut_u_wr_n_3888));
  AOI21XL dut_u_wr_g6163(.A0 (dut_u_wr_n_4127), .A1 (dut_u_wr_n_3899),
       .B0 (dut_u_wr_n_4089), .Y (dut_u_wr_n_3889));
  NOR2BX1 dut_u_wr_g6166(.AN (dut_u_wr_n_3912), .B (dut_u_wr_n_3902),
       .Y (dut_u_wr_n_3890));
  NOR2X1 dut_u_wr_g6168(.A (dut_epoch_clr), .B (dut_u_wr_n_3912), .Y
       (dut_u_wr_n_3892));
  OAI211X1 dut_u_wr_g6173(.A0 (dut_u_wr_b_timer[3]), .A1
       (dut_u_wr_n_3954), .B0 (dut_u_wr_n_3935), .C0
       (dut_u_wr_b_timer_run), .Y (dut_u_wr_n_3897));
  OAI211X1 dut_u_wr_g6174(.A0 (dut_u_wr_w_timer[3]), .A1
       (dut_u_wr_n_3956), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3936), .Y (dut_u_wr_n_3899));
  AOI31X1 dut_u_wr_g6175(.A0 (dut_u_wr_n_3984), .A1 (dut_u_wr_n_3979),
       .A2 (dut_u_wr_n_3925), .B0 (dut_epoch_clr), .Y
       (dut_u_wr_n_3901));
  NAND4XL dut_u_wr_g6176(.A (dut_u_wr_n_3940), .B (dut_u_wr_n_3941), .C
       (dut_u_wr_n_3925), .D (dut_u_wr_n_3926), .Y (dut_u_wr_n_3902));
  NAND2X1 dut_u_wr_g6177(.A (dut_u_wr_w_timer[4]), .B
       (dut_u_wr_n_3906), .Y (dut_u_wr_n_3895));
  NAND2X1 dut_u_wr_g6178(.A (dut_u_wr_b_timer[4]), .B
       (dut_u_wr_n_3908), .Y (dut_u_wr_n_3896));
  INVX1 dut_u_wr_g6179(.A (dut_u_wr_n_3936), .Y (dut_u_wr_n_3906));
  INVX1 dut_u_wr_g6180(.A (dut_u_wr_n_3935), .Y (dut_u_wr_n_3908));
  NOR2XL dut_u_wr_g6181(.A (dut_epoch_clr), .B (dut_u_wr_n_3926), .Y
       (dut_u_wr_n_3910));
  OAI211X1 dut_u_wr_g6185(.A0 (dut_u_wr_n_4272), .A1 (dut_u_wr_n_3942),
       .B0 (dut_u_wr_n_3982), .C0 (dut_u_wr_n_3986), .Y
       (dut_u_wr_n_3913));
  AOI21XL dut_u_wr_g6186(.A0 (dut_u_wr_n_4157), .A1 (dut_u_wr_n_3946),
       .B0 (dut_u_wr_n_4089), .Y (dut_u_wr_n_3914));
  AOI21X1 dut_u_wr_g6187(.A0 (dut_u_wr_n_3948), .A1 (dut_u_wr_n_4135),
       .B0 (dut_u_wr_n_4029), .Y (dut_u_wr_n_3915));
  OAI221X1 dut_u_wr_g6188(.A0 (dut_u_wr_drain_cnt[3]), .A1
       (dut_u_wr_n_4027), .B0 (dut_u_wr_n_4187), .B1 (dut_u_wr_n_4025),
       .C0 (dut_u_wr_n_3923), .Y (dut_u_wr_n_3916));
  XNOR2X1 dut_u_wr_g6189(.A (dut_u_wr_outst_cnt[4]), .B
       (dut_u_wr_n_3937), .Y (dut_u_wr_n_3912));
  NOR2X1 dut_u_wr_g6190(.A (dut_epoch_clr), .B (dut_u_wr_n_3940), .Y
       (dut_u_wr_n_3918));
  NOR2X1 dut_u_wr_g6191(.A (dut_epoch_clr), .B (dut_u_wr_n_3941), .Y
       (dut_u_wr_n_3920));
  INVX1 dut_u_wr_g6193(.A (dut_u_wr_n_3924), .Y (dut_u_wr_n_3923));
  OAI211X1 dut_u_wr_g6194(.A0 (dut_u_wr_n_4080), .A1 (dut_u_wr_n_4025),
       .B0 (dut_u_wr_n_3972), .C0 (dut_u_wr_n_3959), .Y
       (dut_u_wr_n_3927));
  OAI221X1 dut_u_wr_g6195(.A0 (dut_u_wr_drain_cnt[2]), .A1
       (dut_u_wr_n_4027), .B0 (dut_u_wr_n_4272), .B1 (dut_u_wr_n_4025),
       .C0 (dut_u_wr_n_3942), .Y (dut_u_wr_n_3924));
  OAI21XL dut_u_wr_g6196(.A0 (dut_u_wr_n_3970), .A1 (dut_u_wr_n_3968),
       .B0 (dut_u_wr_outst_cnt[2]), .Y (dut_u_wr_n_3925));
  XNOR2X1 dut_u_wr_g6197(.A (dut_u_wr_outst_cnt[3]), .B
       (dut_u_wr_n_3961), .Y (dut_u_wr_n_3926));
  OAI22X1 dut_u_wr_g6198(.A0 (dut_u_wr_n_4264), .A1 (dut_u_wr_n_3980),
       .B0 (dut_u_wr_n_701), .B1 (dut_u_wr_n_4023), .Y
       (dut_u_wr_n_3937));
  NAND2X1 dut_u_wr_g6199(.A (dut_u_wr_b_timer[3]), .B
       (dut_u_wr_n_3954), .Y (dut_u_wr_n_3935));
  NAND2X1 dut_u_wr_g6201(.A (dut_u_wr_w_timer[3]), .B
       (dut_u_wr_n_3956), .Y (dut_u_wr_n_3936));
  OAI22X1 dut_u_wr_g6204(.A0 (dut_u_wr_drain_cnt[3]), .A1
       (dut_u_wr_n_3982), .B0 (dut_u_wr_n_4187), .B1 (dut_u_wr_n_3981),
       .Y (dut_u_wr_n_3943));
  OAI211X1 dut_u_wr_g6205(.A0 (dut_u_wr_w_timer[2]), .A1
       (dut_u_wr_n_4068), .B0 (dut_u_wr_n_4020), .C0
       (dut_u_wr_w_timer_run), .Y (dut_u_wr_n_3946));
  OAI211X1 dut_u_wr_g6206(.A0 (dut_u_wr_b_timer[2]), .A1
       (dut_u_wr_n_4066), .B0 (dut_u_wr_n_4019), .C0
       (dut_u_wr_b_timer_run), .Y (dut_u_wr_n_3948));
  AOI221X1 dut_u_wr_g6207(.A0 (dut_u_wr_n_4087), .A1 (dut_u_wr_n_4021),
       .B0 (dut_u_wr_outst_cnt[1]), .B1 (dut_u_wr_n_3970), .C0
       (dut_u_wr_n_3975), .Y (dut_u_wr_n_3940));
  XOR2XL dut_u_wr_g6208(.A (dut_u_wr_outst_cnt[0]), .B
       (dut_u_wr_n_3970), .Y (dut_u_wr_n_3941));
  AOI221X1 dut_u_wr_g6209(.A0 (dut_u_wr_n_4142), .A1 (dut_u_wr_n_4028),
       .B0 (dut_u_wr_n_4099), .B1 (dut_u_wr_n_4026), .C0
       (dut_u_wr_n_3983), .Y (dut_u_wr_n_3942));
  INVX1 dut_u_wr_g6210(.A (dut_u_wr_n_4019), .Y (dut_u_wr_n_3954));
  INVX1 dut_u_wr_g6211(.A (dut_u_wr_n_4020), .Y (dut_u_wr_n_3956));
  NOR2X1 dut_u_wr_g6212(.A (dut_epoch_clr), .B (dut_u_wr_n_3988), .Y
       (dut_u_wr_n_3958));
  NAND2X1 dut_u_wr_g6213(.A (dut_u_wr_drain_cnt[1]), .B
       (dut_u_wr_n_3983), .Y (dut_u_wr_n_3959));
  NAND2X1 dut_u_wr_g6214(.A (dut_u_wr_n_3979), .B (dut_u_wr_n_3980), .Y
       (dut_u_wr_n_3961));
  AOI21XL dut_u_wr_g6216(.A0 (dut_u_wr_n_4154), .A1 (dut_u_wr_n_4038),
       .B0 (dut_u_wr_n_4089), .Y (dut_u_wr_n_3964));
  AOI21X1 dut_u_wr_g6217(.A0 (dut_u_wr_n_4041), .A1 (dut_u_wr_n_4147),
       .B0 (dut_u_wr_n_4029), .Y (dut_u_wr_n_3965));
  NAND2XL dut_u_wr_g6218(.A (dut_u_wr_n_3982), .B (dut_u_wr_n_3981), .Y
       (dut_u_wr_n_3966));
  AOI22X1 dut_u_wr_g6219(.A0 (dut_u_wr_n_4141), .A1 (dut_u_wr_n_4022),
       .B0 (dut_u_wr_n_4102), .B1 (dut_u_wr_n_4023), .Y
       (dut_u_wr_n_3968));
  NOR2XL dut_u_wr_g6220(.A (dut_u_wr_n_4096), .B (dut_u_wr_n_4029), .Y
       (dut_u_wr_n_3971));
  NAND2X1 dut_u_wr_g6221(.A (dut_u_wr_n_4080), .B (dut_u_wr_n_4028), .Y
       (dut_u_wr_n_3972));
  NOR2XL dut_u_wr_g6222(.A (dut_u_wr_n_4087), .B (dut_u_wr_n_4023), .Y
       (dut_u_wr_n_3975));
  NAND2XL dut_u_wr_g6223(.A (dut_u_wr_n_4025), .B (dut_u_wr_n_4027), .Y
       (dut_u_wr_n_3977));
  NOR2BX1 dut_u_wr_g6224(.AN (dut_u_wr_n_4023), .B (dut_u_wr_n_4021),
       .Y (dut_u_wr_n_3970));
  NAND3BXL dut_u_wr_g6227(.AN (dut_u_wr_outst_cnt[2]), .B
       (dut_u_wr_n_4102), .C (dut_u_wr_n_4021), .Y (dut_u_wr_n_3984));
  NAND3BXL dut_u_wr_g6228(.AN (dut_u_wr_n_4142), .B (dut_u_wr_n_4272),
       .C (dut_u_wr_n_4028), .Y (dut_u_wr_n_3986));
  AOI221X1 dut_u_wr_g6229(.A0 (n_224), .A1 (dut_u_wr_n_4081), .B0
       (dut_flush), .B1 (dut_u_wr_n_428), .C0 (dut_wr_timeout_pulse),
       .Y (dut_u_wr_n_3988));
  NAND3BXL dut_u_wr_g6230(.AN (dut_u_wr_outst_cnt[2]), .B
       (dut_u_wr_n_4141), .C (dut_u_wr_n_4024), .Y (dut_u_wr_n_3979));
  NAND3X1 dut_u_wr_g6231(.A (dut_u_wr_outst_cnt[2]), .B
       (dut_u_wr_n_4102), .C (dut_u_wr_n_4021), .Y (dut_u_wr_n_3980));
  NAND3BXL dut_u_wr_g6232(.AN (dut_u_wr_n_4142), .B
       (dut_u_wr_drain_cnt[2]), .C (dut_u_wr_n_4028), .Y
       (dut_u_wr_n_3981));
  NAND3BXL dut_u_wr_g6233(.AN (dut_u_wr_n_4099), .B (dut_u_wr_n_4272),
       .C (dut_u_wr_n_4026), .Y (dut_u_wr_n_3982));
  NOR3X1 dut_u_wr_g6234(.A (dut_epoch_clr), .B (dut_u_wr_n_4071), .C
       (dut_u_wr_n_4070), .Y (dut_u_wr_n_3983));
  INVX1 dut_u_wr_g6259(.A (dut_u_wr_n_4021), .Y (dut_u_wr_n_4022));
  INVXL dut_u_wr_g6260(.A (dut_u_wr_n_4023), .Y (dut_u_wr_n_4024));
  INVX1 dut_u_wr_g6261(.A (dut_u_wr_n_4025), .Y (dut_u_wr_n_4026));
  INVX1 dut_u_wr_g6262(.A (dut_u_wr_n_4027), .Y (dut_u_wr_n_4028));
  OAI32X1 dut_u_wr_g6263(.A0 (dut_u_wr_wpair_state[0]), .A1
       (dut_u_wr_n_4182), .A2 (dut_epoch_clr), .B0 (dut_u_wr_n_4082),
       .B1 (dut_u_wr_n_4088), .Y (dut_u_wr_n_4036));
  OAI211X1 dut_u_wr_g6264(.A0 (dut_u_wr_w_timer[0]), .A1
       (dut_u_wr_w_timer[1]), .B0 (dut_u_wr_n_4101), .C0
       (dut_u_wr_w_timer_run), .Y (dut_u_wr_n_4038));
  OAI211X1 dut_u_wr_g6265(.A0 (dut_u_wr_b_timer[0]), .A1
       (dut_u_wr_b_timer[1]), .B0 (dut_u_wr_n_4100), .C0
       (dut_u_wr_b_timer_run), .Y (dut_u_wr_n_4041));
  NAND2X1 dut_u_wr_g6280(.A (dut_u_wr_b_timer[2]), .B
       (dut_u_wr_n_4066), .Y (dut_u_wr_n_4019));
  NAND2X1 dut_u_wr_g6281(.A (dut_u_wr_w_timer[2]), .B
       (dut_u_wr_n_4068), .Y (dut_u_wr_n_4020));
  NOR2X1 dut_u_wr_g6282(.A (dut_u_wr_n_4072), .B (dut_u_wr_n_4143), .Y
       (dut_u_wr_n_4021));
  NAND2X1 dut_u_wr_g6283(.A (dut_u_wr_n_4072), .B (dut_u_wr_n_4143), .Y
       (dut_u_wr_n_4023));
  NAND2X1 dut_u_wr_g6285(.A (dut_u_wr_n_4071), .B (dut_u_wr_n_4274), .Y
       (dut_u_wr_n_4025));
  NAND2X1 dut_u_wr_g6286(.A (dut_u_wr_n_4274), .B (dut_u_wr_n_4070), .Y
       (dut_u_wr_n_4027));
  OR3X1 dut_u_wr_g6287(.A (dut_epoch_clr), .B (dut_wr_timeout_pulse),
       .C (dut_u_wr_n_4072), .Y (dut_u_wr_n_4029));
  INVX1 dut_u_wr_g6288(.A (dut_u_wr_n_4100), .Y (dut_u_wr_n_4066));
  INVX1 dut_u_wr_g6289(.A (dut_u_wr_n_4101), .Y (dut_u_wr_n_4068));
  NOR2BX1 dut_u_wr_g6290(.AN (dut_u_wr_n_4098), .B (dut_u_wr_n_4081),
       .Y (dut_u_wr_n_4070));
  NOR2BX1 dut_u_wr_g6291(.AN (dut_u_wr_n_4081), .B (dut_u_wr_n_4098),
       .Y (dut_u_wr_n_4071));
  NAND2X1 dut_u_wr_g6292(.A (dut_u_wr_n_4081), .B (dut_u_wr_n_4138), .Y
       (dut_u_wr_n_4072));
  NOR2XL dut_u_wr_g6293(.A (dut_u_wr_n_4097), .B (dut_u_wr_n_4089), .Y
       (dut_u_wr_n_4075));
  AOI2BB1XL dut_u_wr_g6294(.A0N (dut_u_wr_downstream_aw_done), .A1N
       (dut_u_wr_downstream_aw_fire), .B0 (dut_u_wr_n_4088), .Y
       (dut_u_wr_n_4076));
  AOI2BB1XL dut_u_wr_g6295(.A0N (dut_u_wr_downstream_w_done), .A1N
       (dut_u_wr_downstream_w_fire), .B0 (dut_u_wr_n_4088), .Y
       (dut_u_wr_n_4078));
  AND2X1 dut_u_wr_g6296(.A (dut_u_wr_n_4139), .B (dut_u_wr_n_4182), .Y
       (dut_u_wr_n_4082));
  AND2X1 dut_u_wr_g6298(.A (dut_u_wr_n_4099), .B (dut_u_wr_n_4142), .Y
       (dut_u_wr_n_4080));
  NAND2X1 dut_u_wr_g6299(.A (s_bready), .B (n_224), .Y
       (dut_u_wr_n_4081));
  XNOR2X1 dut_u_wr_g6300(.A (dut_u_wr_b_timer[0]), .B
       (dut_u_wr_b_timer_run), .Y (dut_u_wr_n_4096));
  XNOR2X1 dut_u_wr_g6301(.A (dut_u_wr_w_timer[0]), .B
       (dut_u_wr_w_timer_run), .Y (dut_u_wr_n_4097));
  NOR2X1 dut_u_wr_g6302(.A (dut_u_wr_n_4102), .B (dut_u_wr_n_4141), .Y
       (dut_u_wr_n_4087));
  NAND2X1 dut_u_wr_g6303(.A (dut_u_wr_w_perm), .B (dut_u_wr_n_4143), .Y
       (dut_u_wr_n_4088));
  NAND2X1 dut_u_wr_g6304(.A (dut_u_wr_n_4124), .B (dut_u_wr_n_4143), .Y
       (dut_u_wr_n_4089));
  NAND2XL dut_u_wr_g6305(.A (dut_u_wr_w_timer[5]), .B
       (dut_u_wr_n_4192), .Y (dut_u_wr_n_4120));
  NAND2X1 dut_u_wr_g6306(.A (dut_u_wr_b_timer[6]), .B
       (dut_u_wr_n_4276), .Y (dut_u_wr_n_4122));
  NOR2X1 dut_u_wr_g6307(.A (dut_wr_w_fault_pulse), .B (dut_epoch_clr),
       .Y (dut_u_wr_n_4124));
  NAND2X1 dut_u_wr_g6308(.A (dut_u_wr_b_timer[5]), .B
       (dut_u_wr_n_4276), .Y (dut_u_wr_n_4125));
  NAND2XL dut_u_wr_g6309(.A (dut_u_wr_w_timer[13]), .B
       (dut_u_wr_n_4192), .Y (dut_u_wr_n_4126));
  NAND2XL dut_u_wr_g6310(.A (dut_u_wr_w_timer[3]), .B
       (dut_u_wr_n_4192), .Y (dut_u_wr_n_4127));
  NAND2XL dut_u_wr_g6311(.A (dut_u_wr_w_timer[4]), .B
       (dut_u_wr_n_4192), .Y (dut_u_wr_n_4128));
  NAND2XL dut_u_wr_g6312(.A (dut_u_wr_w_timer[12]), .B
       (dut_u_wr_n_4192), .Y (dut_u_wr_n_4129));
  NAND2X1 dut_u_wr_g6313(.A (dut_u_wr_b_timer[4]), .B
       (dut_u_wr_n_4276), .Y (dut_u_wr_n_4130));
  NAND2XL dut_u_wr_g6314(.A (dut_u_wr_w_timer[7]), .B
       (dut_u_wr_n_4192), .Y (dut_u_wr_n_4131));
  NAND2XL dut_u_wr_g6316(.A (dut_u_wr_w_timer[8]), .B
       (dut_u_wr_n_4192), .Y (dut_u_wr_n_4134));
  NAND2X1 dut_u_wr_g6317(.A (dut_u_wr_b_timer[2]), .B
       (dut_u_wr_n_4276), .Y (dut_u_wr_n_4135));
  NAND2XL dut_u_wr_g6318(.A (dut_u_wr_w_timer[11]), .B
       (dut_u_wr_n_4192), .Y (dut_u_wr_n_4136));
  NAND2X1 dut_u_wr_g6319(.A (dut_u_wr_b_timer[3]), .B
       (dut_u_wr_n_4276), .Y (dut_u_wr_n_4137));
  NAND2X1 dut_u_wr_g6320(.A (m_bvalid), .B (dut_u_wr_n_430), .Y
       (dut_u_wr_n_4098));
  OR2X1 dut_u_wr_g6321(.A (dut_u_wr_drain_cnt[1]), .B
       (dut_u_wr_drain_cnt[0]), .Y (dut_u_wr_n_4099));
  NAND2X1 dut_u_wr_g6322(.A (dut_u_wr_b_timer[1]), .B
       (dut_u_wr_b_timer[0]), .Y (dut_u_wr_n_4100));
  NAND2X1 dut_u_wr_g6323(.A (dut_u_wr_w_timer[1]), .B
       (dut_u_wr_w_timer[0]), .Y (dut_u_wr_n_4101));
  AND2X1 dut_u_wr_g6324(.A (dut_u_wr_outst_cnt[1]), .B
       (dut_u_wr_outst_cnt[0]), .Y (dut_u_wr_n_4102));
  OR2X2 dut_u_wr_g6325(.A (dut_u_wr_n_2305), .B (dut_u_wr_n_4244), .Y
       (dut_u_wr_n_4103));
  NAND2X1 dut_u_wr_g6326(.A (dut_u_wr_b_timer[12]), .B
       (dut_u_wr_n_4276), .Y (dut_u_wr_n_4144));
  NAND2XL dut_u_wr_g6327(.A (dut_u_wr_w_timer[6]), .B
       (dut_u_wr_n_4192), .Y (dut_u_wr_n_4145));
  NAND2X1 dut_u_wr_g6328(.A (dut_u_wr_b_timer[9]), .B
       (dut_u_wr_n_4276), .Y (dut_u_wr_n_4146));
  NAND2X1 dut_u_wr_g6329(.A (dut_u_wr_b_timer[1]), .B
       (dut_u_wr_n_4276), .Y (dut_u_wr_n_4147));
  NAND2XL dut_u_wr_g6330(.A (dut_u_wr_w_timer[9]), .B
       (dut_u_wr_n_4192), .Y (dut_u_wr_n_4148));
  NAND2X1 dut_u_wr_g6331(.A (dut_u_wr_b_timer[10]), .B
       (dut_u_wr_n_4276), .Y (dut_u_wr_n_4149));
  NAND2X1 dut_u_wr_g6332(.A (dut_u_wr_b_timer[11]), .B
       (dut_u_wr_n_4276), .Y (dut_u_wr_n_4150));
  NAND2X1 dut_u_wr_g6333(.A (dut_u_wr_b_timer[8]), .B
       (dut_u_wr_n_4276), .Y (dut_u_wr_n_4151));
  NAND2XL dut_u_wr_g6334(.A (dut_u_wr_w_timer[14]), .B
       (dut_u_wr_n_4192), .Y (dut_u_wr_n_4152));
  NAND2X1 dut_u_wr_g6335(.A (dut_u_wr_b_timer[13]), .B
       (dut_u_wr_n_4276), .Y (dut_u_wr_n_4153));
  NAND2XL dut_u_wr_g6336(.A (dut_u_wr_w_timer[1]), .B
       (dut_u_wr_n_4192), .Y (dut_u_wr_n_4154));
  NAND2X1 dut_u_wr_g6337(.A (dut_u_wr_b_timer[14]), .B
       (dut_u_wr_n_4276), .Y (dut_u_wr_n_4155));
  NAND2X1 dut_u_wr_g6338(.A (dut_u_wr_b_timer[7]), .B
       (dut_u_wr_n_4276), .Y (dut_u_wr_n_4156));
  NAND2XL dut_u_wr_g6339(.A (dut_u_wr_w_timer[2]), .B
       (dut_u_wr_n_4192), .Y (dut_u_wr_n_4157));
  NAND2XL dut_u_wr_g6340(.A (dut_u_wr_w_timer[10]), .B
       (dut_u_wr_n_4192), .Y (dut_u_wr_n_4158));
  NAND2X1 dut_u_wr_g6341(.A (dut_u_wr_n_431), .B (s_bvalid), .Y
       (dut_u_wr_n_4138));
  NOR2XL dut_u_wr_g6342(.A (dut_flush), .B (dut_wr_w_fault_pulse), .Y
       (dut_u_wr_n_4139));
  NOR2X1 dut_u_wr_g6344(.A (dut_u_wr_outst_cnt[1]), .B
       (dut_u_wr_outst_cnt[0]), .Y (dut_u_wr_n_4141));
  NAND2X1 dut_u_wr_g6345(.A (dut_u_wr_drain_cnt[1]), .B
       (dut_u_wr_drain_cnt[0]), .Y (dut_u_wr_n_4142));
  INVX1 dut_u_wr_g6348(.A (dut_u_wr_drain_cnt[3]), .Y
       (dut_u_wr_n_4187));
  INVX1 dut_u_wr_g6349(.A (dut_u_wr_w_timer_run), .Y (dut_u_wr_n_4192));
  INVXL dut_u_wr_g6350(.A (s_awready), .Y (dut_u_wr_n_4244));
  INVX1 dut_u_wr_g6353(.A (dut_epoch_clr), .Y (dut_u_wr_n_4274));
  INVX1 dut_u_wr_g6354(.A (dut_u_wr_b_timer_run), .Y (dut_u_wr_n_4276));
  DFFRX1 \dut_u_wr_drain_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3913), .Q (dut_u_wr_drain_cnt[2]), .QN
       (dut_u_wr_n_4272));
  DFFRX1 \dut_u_wr_outst_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3910), .Q (dut_u_wr_outst_cnt[3]), .QN
       (dut_u_wr_n_4264));
  DFFRX1 \dut_u_wr_wpair_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4036), .Q (dut_u_wr_wpair_state[1]), .QN
       (dut_u_wr_n_4182));
  INVX1 dut_u_rd_g1182(.A (dut_u_rd_n_312), .Y (dut_rd_upstream_empty));
  OR4X1 dut_u_rd_g1208(.A (dut_u_rd_outst_cnt[4]), .B
       (dut_u_rd_outst_cnt[2]), .C (dut_u_rd_outst_cnt[3]), .D
       (dut_u_rd_n_1356), .Y (dut_u_rd_n_312));
  OR2XL dut_u_rd_g1209(.A (dut_u_rd_outst_cnt[0]), .B
       (dut_u_rd_outst_cnt[1]), .Y (dut_u_rd_n_1356));
  OR2XL dut_u_rd_g1210(.A (dut_u_rd_n_312), .B (dut_u_rd_n_299), .Y
       (dut_rd_busy));
  OR4X1 dut_u_rd_g1211(.A (dut_u_rd_drain_cnt[0]), .B
       (dut_u_rd_drain_cnt[1]), .C (dut_u_rd_drain_cnt[2]), .D
       (dut_u_rd_n_1357), .Y (dut_u_rd_n_299));
  OR2XL dut_u_rd_g1212(.A (dut_u_rd_drain_cnt[3]), .B
       (dut_u_rd_drain_cnt[4]), .Y (dut_u_rd_n_1357));
  NOR2BX1 dut_u_rd_g2009(.AN (dut_u_rd_timer_run), .B
       (dut_u_rd_n_1795), .Y (dut_rd_timeout_pulse));
  AND3X1 dut_u_rd_g2010(.A (s_arvalid), .B (dut_u_rd_n_1796), .C
       (dut_u_rd_n_292), .Y (m_arvalid));
  AND3X1 dut_u_rd_g2011(.A (m_arready), .B (dut_u_rd_n_1796), .C
       (dut_u_rd_n_292), .Y (s_arready));
  NAND4XL dut_u_rd_g2012(.A (dut_u_rd_n_1843), .B (dut_u_rd_n_1842), .C
       (dut_u_rd_n_1841), .D (dut_u_rd_n_1838), .Y (dut_u_rd_n_1795));
  OR2X1 dut_u_rd_g2013(.A (dut_u_rd_n_300), .B (dut_u_rd_n_299), .Y
       (m_rready));
  NAND2BXL dut_u_rd_g2014(.AN (dut_u_rd_n_535), .B
       (dut_u_rd_outst_cnt[4]), .Y (dut_u_rd_n_1796));
  AO21X1 dut_u_rd_g2015(.A0 (dut_u_rd_n_1848), .A1 (dut_u_rd_n_297),
       .B0 (dut_u_rd_n_1849), .Y (s_rvalid));
  AO21X1 dut_u_rd_g2016(.A0 (\m_r[resp] [1]), .A1 (dut_u_rd_n_297), .B0
       (dut_u_rd_n_1849), .Y (\s_r[resp] [1]));
  AND2X1 dut_u_rd_g2017(.A (dut_u_rd_n_297), .B (\m_r[data] [18]), .Y
       (\s_r[data] [18]));
  AND2X1 dut_u_rd_g2018(.A (dut_u_rd_n_297), .B (\m_r[data] [17]), .Y
       (\s_r[data] [17]));
  AND2X1 dut_u_rd_g2019(.A (dut_u_rd_n_297), .B (\m_r[resp] [0]), .Y
       (\s_r[resp] [0]));
  AND2X1 dut_u_rd_g2020(.A (dut_u_rd_n_297), .B (\m_r[data] [16]), .Y
       (\s_r[data] [16]));
  AND2X1 dut_u_rd_g2021(.A (dut_u_rd_n_297), .B (\m_r[data] [15]), .Y
       (\s_r[data] [15]));
  AND2X1 dut_u_rd_g2022(.A (dut_u_rd_n_297), .B (\m_r[data] [14]), .Y
       (\s_r[data] [14]));
  AND2X1 dut_u_rd_g2023(.A (dut_u_rd_n_297), .B (\m_r[data] [13]), .Y
       (\s_r[data] [13]));
  AND2X1 dut_u_rd_g2024(.A (dut_u_rd_n_297), .B (\m_r[data] [12]), .Y
       (\s_r[data] [12]));
  AND2X1 dut_u_rd_g2025(.A (dut_u_rd_n_297), .B (\m_r[data] [11]), .Y
       (\s_r[data] [11]));
  AND2X1 dut_u_rd_g2026(.A (dut_u_rd_n_297), .B (\m_r[data] [30]), .Y
       (\s_r[data] [30]));
  AND2X1 dut_u_rd_g2027(.A (dut_u_rd_n_297), .B (\m_r[data] [10]), .Y
       (\s_r[data] [10]));
  AND2X1 dut_u_rd_g2028(.A (dut_u_rd_n_297), .B (\m_r[data] [9]), .Y
       (\s_r[data] [9]));
  AND2X1 dut_u_rd_g2029(.A (dut_u_rd_n_297), .B (\m_r[data] [29]), .Y
       (\s_r[data] [29]));
  AND2X1 dut_u_rd_g2030(.A (dut_u_rd_n_297), .B (\m_r[data] [8]), .Y
       (\s_r[data] [8]));
  AND2X1 dut_u_rd_g2031(.A (dut_u_rd_n_297), .B (\m_r[data] [7]), .Y
       (\s_r[data] [7]));
  AND2X1 dut_u_rd_g2032(.A (dut_u_rd_n_297), .B (\m_r[data] [28]), .Y
       (\s_r[data] [28]));
  AND2X1 dut_u_rd_g2033(.A (dut_u_rd_n_297), .B (\m_r[data] [6]), .Y
       (\s_r[data] [6]));
  AND2X1 dut_u_rd_g2034(.A (dut_u_rd_n_297), .B (\m_r[data] [5]), .Y
       (\s_r[data] [5]));
  AND2X1 dut_u_rd_g2035(.A (dut_u_rd_n_297), .B (\m_r[data] [27]), .Y
       (\s_r[data] [27]));
  AND2X1 dut_u_rd_g2036(.A (dut_u_rd_n_297), .B (\m_r[data] [4]), .Y
       (\s_r[data] [4]));
  AND2X1 dut_u_rd_g2037(.A (dut_u_rd_n_297), .B (\m_r[data] [3]), .Y
       (\s_r[data] [3]));
  AND2X1 dut_u_rd_g2038(.A (dut_u_rd_n_297), .B (\m_r[data] [26]), .Y
       (\s_r[data] [26]));
  AND2X1 dut_u_rd_g2039(.A (dut_u_rd_n_297), .B (\m_r[data] [2]), .Y
       (\s_r[data] [2]));
  AND2X1 dut_u_rd_g2040(.A (dut_u_rd_n_297), .B (\m_r[data] [1]), .Y
       (\s_r[data] [1]));
  AND2X1 dut_u_rd_g2041(.A (dut_u_rd_n_297), .B (\m_r[data] [25]), .Y
       (\s_r[data] [25]));
  AND2X1 dut_u_rd_g2042(.A (dut_u_rd_n_297), .B (\m_r[data] [0]), .Y
       (\s_r[data] [0]));
  AND2X1 dut_u_rd_g2043(.A (dut_u_rd_n_297), .B (\m_r[data] [24]), .Y
       (\s_r[data] [24]));
  AND2X1 dut_u_rd_g2044(.A (dut_u_rd_n_297), .B (\m_r[data] [23]), .Y
       (\s_r[data] [23]));
  AND2X1 dut_u_rd_g2045(.A (dut_u_rd_n_297), .B (\m_r[data] [22]), .Y
       (\s_r[data] [22]));
  AND2X1 dut_u_rd_g2046(.A (dut_u_rd_n_297), .B (\m_r[data] [21]), .Y
       (\s_r[data] [21]));
  AND2X1 dut_u_rd_g2047(.A (dut_u_rd_n_297), .B (\m_r[data] [20]), .Y
       (\s_r[data] [20]));
  NOR4X1 dut_u_rd_g2048(.A (dut_u_rd_timer[13]), .B
       (dut_u_rd_timer[12]), .C (dut_u_rd_timer[14]), .D
       (dut_u_rd_timer[15]), .Y (dut_u_rd_n_1838));
  AND2X1 dut_u_rd_g2049(.A (dut_u_rd_n_297), .B (\m_r[data] [31]), .Y
       (\s_r[data] [31]));
  AND2X1 dut_u_rd_g2050(.A (dut_u_rd_n_297), .B (\m_r[data] [19]), .Y
       (\s_r[data] [19]));
  NOR4X1 dut_u_rd_g2051(.A (dut_u_rd_timer[0]), .B (dut_u_rd_timer[1]),
       .C (dut_u_rd_timer[7]), .D (dut_u_rd_timer[6]), .Y
       (dut_u_rd_n_1841));
  NOR4BX1 dut_u_rd_g2052(.AN (dut_u_rd_timer[8]), .B
       (dut_u_rd_timer[3]), .C (dut_u_rd_timer[9]), .D
       (dut_u_rd_timer[2]), .Y (dut_u_rd_n_1842));
  NOR4X1 dut_u_rd_g2053(.A (dut_u_rd_timer[4]), .B (dut_u_rd_timer[5]),
       .C (dut_u_rd_timer[10]), .D (dut_u_rd_timer[11]), .Y
       (dut_u_rd_n_1843));
  OR4X1 dut_u_rd_g2055(.A (dut_u_rd_outst_cnt[0]), .B
       (dut_u_rd_outst_cnt[1]), .C (dut_u_rd_outst_cnt[2]), .D
       (dut_u_rd_outst_cnt[3]), .Y (dut_u_rd_n_535));
  AND2XL dut_u_rd_g2056(.A (s_rready), .B (dut_u_rd_n_297), .Y
       (dut_u_rd_n_300));
  AND2X1 dut_u_rd_g2059(.A (dut_u_rd_rd_state[0]), .B
       (dut_u_rd_n_1855), .Y (dut_u_rd_n_297));
  NOR2BX1 dut_u_rd_g2060(.AN (m_rvalid), .B (dut_u_rd_n_299), .Y
       (dut_u_rd_n_1848));
  NOR2X1 dut_u_rd_g2061(.A (dut_u_rd_rd_state[0]), .B
       (dut_u_rd_n_1855), .Y (dut_u_rd_n_1849));
  NOR2BX2 dut_u_rd_g2(.AN (dut_u_rd_n_297), .B (dut_u_rd_n_1848), .Y
       (dut_u_rd_timer_run));
  SDFFRHQX1 \dut_u_rd_drain_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2407), .SI (dut_u_rd_n_2405), .SE
       (dut_u_rd_drain_cnt[0]), .Q (dut_u_rd_drain_cnt[0]));
  DFFRHQX1 \dut_u_rd_drain_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2355), .Q (dut_u_rd_drain_cnt[1]));
  SDFFRHQX1 \dut_u_rd_drain_cnt_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2359), .SI (dut_u_rd_n_2341), .SE
       (dut_u_rd_drain_cnt[4]), .Q (dut_u_rd_drain_cnt[4]));
  DFFRHQX1 \dut_u_rd_outst_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2347), .Q (dut_u_rd_outst_cnt[0]));
  DFFRHQX1 \dut_u_rd_outst_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2335), .Q (dut_u_rd_outst_cnt[1]));
  DFFRHQX1 \dut_u_rd_outst_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2337), .Q (dut_u_rd_outst_cnt[2]));
  DFFRHQX1 \dut_u_rd_outst_cnt_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2319), .Q (dut_u_rd_outst_cnt[4]));
  DFFRHQX1 \dut_u_rd_rd_state_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2307), .Q (dut_u_rd_rd_state[0]));
  DFFRHQX1 \dut_u_rd_timer_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2408), .Q (dut_u_rd_timer[0]));
  DFFRHQX1 \dut_u_rd_timer_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2386), .Q (dut_u_rd_timer[1]));
  DFFRHQX1 \dut_u_rd_timer_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2344), .Q (dut_u_rd_timer[2]));
  DFFRHQX1 \dut_u_rd_timer_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2318), .Q (dut_u_rd_timer[3]));
  DFFRHQX1 \dut_u_rd_timer_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2306), .Q (dut_u_rd_timer[4]));
  DFFRHQX1 \dut_u_rd_timer_reg[5] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2299), .Q (dut_u_rd_timer[5]));
  DFFRHQX1 \dut_u_rd_timer_reg[6] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2292), .Q (dut_u_rd_timer[6]));
  DFFRHQX1 \dut_u_rd_timer_reg[7] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2285), .Q (dut_u_rd_timer[7]));
  DFFRHQX1 \dut_u_rd_timer_reg[8] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2278), .Q (dut_u_rd_timer[8]));
  DFFRHQX1 \dut_u_rd_timer_reg[9] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2271), .Q (dut_u_rd_timer[9]));
  DFFRHQX1 \dut_u_rd_timer_reg[10] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2264), .Q (dut_u_rd_timer[10]));
  DFFRHQX1 \dut_u_rd_timer_reg[11] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2257), .Q (dut_u_rd_timer[11]));
  DFFRHQX1 \dut_u_rd_timer_reg[12] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2250), .Q (dut_u_rd_timer[12]));
  DFFRHQX1 \dut_u_rd_timer_reg[13] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2243), .Q (dut_u_rd_timer[13]));
  DFFRHQX1 \dut_u_rd_timer_reg[14] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2235), .Q (dut_u_rd_timer[14]));
  DFFRHQX1 \dut_u_rd_timer_reg[15] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2230), .Q (dut_u_rd_timer[15]));
  NOR2XL dut_u_rd_g3760(.A (dut_u_rd_n_2233), .B (dut_u_rd_n_2421), .Y
       (dut_u_rd_n_2230));
  AOI22X1 dut_u_rd_g3762(.A0 (dut_u_rd_timer_run), .A1
       (dut_u_rd_n_2237), .B0 (dut_u_rd_n_2508), .B1
       (dut_u_rd_timer[15]), .Y (dut_u_rd_n_2233));
  AOI21XL dut_u_rd_g3763(.A0 (dut_u_rd_n_2465), .A1 (dut_u_rd_n_2238),
       .B0 (dut_u_rd_n_2421), .Y (dut_u_rd_n_2235));
  XNOR2X1 dut_u_rd_g3764(.A (dut_u_rd_timer[15]), .B (dut_u_rd_n_2244),
       .Y (dut_u_rd_n_2237));
  OAI211X1 dut_u_rd_g3766(.A0 (dut_u_rd_timer[14]), .A1
       (dut_u_rd_n_2248), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2244), .Y (dut_u_rd_n_2238));
  AOI21XL dut_u_rd_g3767(.A0 (dut_u_rd_n_2461), .A1 (dut_u_rd_n_2245),
       .B0 (dut_u_rd_n_2421), .Y (dut_u_rd_n_2243));
  OAI211X1 dut_u_rd_g3769(.A0 (dut_u_rd_timer[13]), .A1
       (dut_u_rd_n_2255), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2251), .Y (dut_u_rd_n_2245));
  NAND2X1 dut_u_rd_g3770(.A (dut_u_rd_timer[14]), .B (dut_u_rd_n_2248),
       .Y (dut_u_rd_n_2244));
  INVX1 dut_u_rd_g3771(.A (dut_u_rd_n_2251), .Y (dut_u_rd_n_2248));
  AOI21XL dut_u_rd_g3772(.A0 (dut_u_rd_n_2462), .A1 (dut_u_rd_n_2252),
       .B0 (dut_u_rd_n_2421), .Y (dut_u_rd_n_2250));
  OAI211X1 dut_u_rd_g3774(.A0 (dut_u_rd_timer[12]), .A1
       (dut_u_rd_n_2262), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2258), .Y (dut_u_rd_n_2252));
  NAND2X1 dut_u_rd_g3775(.A (dut_u_rd_timer[13]), .B (dut_u_rd_n_2255),
       .Y (dut_u_rd_n_2251));
  INVX1 dut_u_rd_g3776(.A (dut_u_rd_n_2258), .Y (dut_u_rd_n_2255));
  AOI21XL dut_u_rd_g3777(.A0 (dut_u_rd_n_2460), .A1 (dut_u_rd_n_2259),
       .B0 (dut_u_rd_n_2421), .Y (dut_u_rd_n_2257));
  OAI211X1 dut_u_rd_g3779(.A0 (dut_u_rd_timer[11]), .A1
       (dut_u_rd_n_2269), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2265), .Y (dut_u_rd_n_2259));
  NAND2X1 dut_u_rd_g3780(.A (dut_u_rd_timer[12]), .B (dut_u_rd_n_2262),
       .Y (dut_u_rd_n_2258));
  INVX1 dut_u_rd_g3781(.A (dut_u_rd_n_2265), .Y (dut_u_rd_n_2262));
  AOI21XL dut_u_rd_g3782(.A0 (dut_u_rd_n_2458), .A1 (dut_u_rd_n_2266),
       .B0 (dut_u_rd_n_2421), .Y (dut_u_rd_n_2264));
  OAI211X1 dut_u_rd_g3784(.A0 (dut_u_rd_timer[10]), .A1
       (dut_u_rd_n_2276), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2272), .Y (dut_u_rd_n_2266));
  NAND2X1 dut_u_rd_g3785(.A (dut_u_rd_timer[11]), .B (dut_u_rd_n_2269),
       .Y (dut_u_rd_n_2265));
  INVX1 dut_u_rd_g3786(.A (dut_u_rd_n_2272), .Y (dut_u_rd_n_2269));
  AOI21XL dut_u_rd_g3787(.A0 (dut_u_rd_n_2473), .A1 (dut_u_rd_n_2273),
       .B0 (dut_u_rd_n_2421), .Y (dut_u_rd_n_2271));
  OAI211X1 dut_u_rd_g3789(.A0 (dut_u_rd_timer[9]), .A1
       (dut_u_rd_n_2283), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2279), .Y (dut_u_rd_n_2273));
  NAND2X1 dut_u_rd_g3790(.A (dut_u_rd_timer[10]), .B (dut_u_rd_n_2276),
       .Y (dut_u_rd_n_2272));
  INVX1 dut_u_rd_g3791(.A (dut_u_rd_n_2279), .Y (dut_u_rd_n_2276));
  AOI21XL dut_u_rd_g3792(.A0 (dut_u_rd_n_2475), .A1 (dut_u_rd_n_2280),
       .B0 (dut_u_rd_n_2421), .Y (dut_u_rd_n_2278));
  OAI211X1 dut_u_rd_g3794(.A0 (dut_u_rd_timer[8]), .A1
       (dut_u_rd_n_2290), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2286), .Y (dut_u_rd_n_2280));
  NAND2X1 dut_u_rd_g3795(.A (dut_u_rd_timer[9]), .B (dut_u_rd_n_2283),
       .Y (dut_u_rd_n_2279));
  INVX1 dut_u_rd_g3796(.A (dut_u_rd_n_2286), .Y (dut_u_rd_n_2283));
  AOI21XL dut_u_rd_g3797(.A0 (dut_u_rd_n_2477), .A1 (dut_u_rd_n_2287),
       .B0 (dut_u_rd_n_2421), .Y (dut_u_rd_n_2285));
  OAI211X1 dut_u_rd_g3799(.A0 (dut_u_rd_timer[7]), .A1
       (dut_u_rd_n_2297), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2293), .Y (dut_u_rd_n_2287));
  NAND2X1 dut_u_rd_g3800(.A (dut_u_rd_timer[8]), .B (dut_u_rd_n_2290),
       .Y (dut_u_rd_n_2286));
  INVX1 dut_u_rd_g3801(.A (dut_u_rd_n_2293), .Y (dut_u_rd_n_2290));
  AOI21XL dut_u_rd_g3802(.A0 (dut_u_rd_n_2466), .A1 (dut_u_rd_n_2294),
       .B0 (dut_u_rd_n_2421), .Y (dut_u_rd_n_2292));
  OAI211X1 dut_u_rd_g3804(.A0 (dut_u_rd_timer[6]), .A1
       (dut_u_rd_n_2304), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2300), .Y (dut_u_rd_n_2294));
  NAND2X1 dut_u_rd_g3805(.A (dut_u_rd_timer[7]), .B (dut_u_rd_n_2297),
       .Y (dut_u_rd_n_2293));
  INVX1 dut_u_rd_g3806(.A (dut_u_rd_n_2300), .Y (dut_u_rd_n_2297));
  AOI21XL dut_u_rd_g3807(.A0 (dut_u_rd_n_2463), .A1 (dut_u_rd_n_2301),
       .B0 (dut_u_rd_n_2421), .Y (dut_u_rd_n_2299));
  OAI211X1 dut_u_rd_g3810(.A0 (dut_u_rd_timer[5]), .A1
       (dut_u_rd_n_2314), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2310), .Y (dut_u_rd_n_2301));
  NAND2X1 dut_u_rd_g3811(.A (dut_u_rd_timer[6]), .B (dut_u_rd_n_2304),
       .Y (dut_u_rd_n_2300));
  INVX1 dut_u_rd_g3812(.A (dut_u_rd_n_2310), .Y (dut_u_rd_n_2304));
  AOI21XL dut_u_rd_g3813(.A0 (dut_u_rd_n_2476), .A1 (dut_u_rd_n_2311),
       .B0 (dut_u_rd_n_2421), .Y (dut_u_rd_n_2306));
  OAI221X1 dut_u_rd_g3814(.A0 (dut_u_rd_n_2449), .A1 (dut_u_rd_n_2308),
       .B0 (dut_u_rd_n_2439), .B1 (dut_u_rd_n_2317), .C0
       (dut_u_rd_n_2442), .Y (dut_u_rd_n_2307));
  NOR2BX1 dut_u_rd_g3815(.AN (dut_u_rd_n_2317), .B (dut_u_rd_n_2467),
       .Y (dut_u_rd_n_2308));
  OAI211X1 dut_u_rd_g3817(.A0 (dut_u_rd_timer[4]), .A1
       (dut_u_rd_n_2333), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2323), .Y (dut_u_rd_n_2311));
  NAND2X1 dut_u_rd_g3818(.A (dut_u_rd_timer[5]), .B (dut_u_rd_n_2314),
       .Y (dut_u_rd_n_2310));
  INVX1 dut_u_rd_g3819(.A (dut_u_rd_n_2323), .Y (dut_u_rd_n_2314));
  AOI21XL dut_u_rd_g3822(.A0 (dut_u_rd_n_2464), .A1 (dut_u_rd_n_2329),
       .B0 (dut_u_rd_n_2421), .Y (dut_u_rd_n_2318));
  NOR4X1 dut_u_rd_g3823(.A (dut_u_rd_n_2371), .B (dut_u_rd_n_2354), .C
       (dut_u_rd_n_2353), .D (dut_u_rd_n_2320), .Y (dut_u_rd_n_2317));
  NOR2X1 dut_u_rd_g3826(.A (dut_epoch_clr), .B (dut_u_rd_n_2322), .Y
       (dut_u_rd_n_2319));
  NAND2X1 dut_u_rd_g3827(.A (dut_u_rd_n_2339), .B (dut_u_rd_n_2322), .Y
       (dut_u_rd_n_2320));
  OAI22X1 dut_u_rd_g3832(.A0 (dut_u_rd_n_2525), .A1 (dut_u_rd_n_2346),
       .B0 (dut_u_rd_drain_cnt[3]), .B1 (dut_u_rd_n_2365), .Y
       (dut_u_rd_n_2324));
  NOR2X1 dut_u_rd_g3833(.A (dut_epoch_clr), .B (dut_u_rd_n_2339), .Y
       (dut_u_rd_n_2326));
  OAI211X1 dut_u_rd_g3834(.A0 (dut_u_rd_timer[3]), .A1
       (dut_u_rd_n_2380), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2364), .Y (dut_u_rd_n_2329));
  XNOR2X1 dut_u_rd_g3835(.A (dut_u_rd_outst_cnt[4]), .B
       (dut_u_rd_n_2362), .Y (dut_u_rd_n_2322));
  NAND2X1 dut_u_rd_g3836(.A (dut_u_rd_timer[4]), .B (dut_u_rd_n_2333),
       .Y (dut_u_rd_n_2323));
  INVX1 dut_u_rd_g3837(.A (dut_u_rd_n_2364), .Y (dut_u_rd_n_2333));
  NOR2BX1 dut_u_rd_g3838(.AN (dut_u_rd_n_2354), .B (dut_epoch_clr), .Y
       (dut_u_rd_n_2335));
  NOR2BX1 dut_u_rd_g3839(.AN (dut_u_rd_n_2353), .B (dut_epoch_clr), .Y
       (dut_u_rd_n_2337));
  OAI211X1 dut_u_rd_g3842(.A0 (dut_u_rd_n_2470), .A1 (dut_u_rd_n_2390),
       .B0 (dut_u_rd_n_2385), .C0 (dut_u_rd_n_2349), .Y
       (dut_u_rd_n_2340));
  OAI221X1 dut_u_rd_g3843(.A0 (dut_u_rd_drain_cnt[3]), .A1
       (dut_u_rd_n_2420), .B0 (dut_u_rd_n_2525), .B1 (dut_u_rd_n_2414),
       .C0 (dut_u_rd_n_2346), .Y (dut_u_rd_n_2341));
  AOI21XL dut_u_rd_g3844(.A0 (dut_u_rd_n_2472), .A1 (dut_u_rd_n_2374),
       .B0 (dut_u_rd_n_2421), .Y (dut_u_rd_n_2344));
  XNOR2X1 dut_u_rd_g3845(.A (dut_u_rd_outst_cnt[3]), .B
       (dut_u_rd_n_2376), .Y (dut_u_rd_n_2339));
  NOR2BX1 dut_u_rd_g3846(.AN (dut_u_rd_n_2371), .B (dut_epoch_clr), .Y
       (dut_u_rd_n_2347));
  NAND2X1 dut_u_rd_g3847(.A (dut_u_rd_drain_cnt[2]), .B
       (dut_u_rd_n_2372), .Y (dut_u_rd_n_2349));
  AOI211XL dut_u_rd_g3848(.A0 (dut_u_rd_n_2415), .A1
       (dut_u_rd_drain_cnt[2]), .B0 (dut_u_rd_n_2389), .C0
       (dut_u_rd_n_2372), .Y (dut_u_rd_n_2346));
  OAI221X1 dut_u_rd_g3850(.A0 (dut_u_rd_n_2420), .A1 (dut_u_rd_n_2453),
       .B0 (dut_u_rd_n_2414), .B1 (dut_u_rd_n_2470), .C0
       (dut_u_rd_n_2367), .Y (dut_u_rd_n_2355));
  OAI22XL dut_u_rd_g3851(.A0 (dut_u_rd_drain_cnt[3]), .A1
       (dut_u_rd_n_2385), .B0 (dut_u_rd_n_2525), .B1 (dut_u_rd_n_2402),
       .Y (dut_u_rd_n_2359));
  XNOR2X1 dut_u_rd_g3852(.A (dut_u_rd_outst_cnt[2]), .B
       (dut_u_rd_n_2382), .Y (dut_u_rd_n_2353));
  OAI22X1 dut_u_rd_g3853(.A0 (dut_u_rd_n_2520), .A1 (dut_u_rd_n_2384),
       .B0 (dut_u_rd_n_535), .B1 (dut_u_rd_n_2413), .Y
       (dut_u_rd_n_2362));
  OAI2BB1X1 dut_u_rd_g3854(.A0N (dut_u_rd_outst_cnt[1]), .A1N
       (dut_u_rd_n_2393), .B0 (dut_u_rd_n_2373), .Y (dut_u_rd_n_2354));
  AND2XL dut_u_rd_g3855(.A (dut_u_rd_n_2402), .B (dut_u_rd_n_2385), .Y
       (dut_u_rd_n_2365));
  AOI21X1 dut_u_rd_g3856(.A0 (dut_u_rd_drain_cnt[1]), .A1
       (dut_u_rd_n_2405), .B0 (dut_u_rd_n_2391), .Y (dut_u_rd_n_2367));
  NAND2X1 dut_u_rd_g3857(.A (dut_u_rd_timer[3]), .B (dut_u_rd_n_2380),
       .Y (dut_u_rd_n_2364));
  AOI211XL dut_u_rd_g3859(.A0 (dut_u_rd_n_2530), .A1 (dut_u_rd_n_2418),
       .B0 (dut_u_rd_n_2395), .C0 (dut_u_rd_n_2403), .Y
       (dut_u_rd_n_2373));
  OAI211X1 dut_u_rd_g3860(.A0 (dut_u_rd_timer[2]), .A1
       (dut_u_rd_n_2434), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2412), .Y (dut_u_rd_n_2374));
  OAI21X1 dut_u_rd_g3861(.A0 (dut_u_rd_outst_cnt[2]), .A1
       (dut_u_rd_n_2404), .B0 (dut_u_rd_n_2384), .Y (dut_u_rd_n_2376));
  XNOR2X1 dut_u_rd_g3862(.A (dut_u_rd_outst_cnt[0]), .B
       (dut_u_rd_n_2393), .Y (dut_u_rd_n_2371));
  OAI211X1 dut_u_rd_g3863(.A0 (dut_u_rd_n_2414), .A1 (dut_u_rd_n_2456),
       .B0 (dut_u_rd_n_2406), .C0 (dut_u_rd_n_2394), .Y
       (dut_u_rd_n_2372));
  INVX1 dut_u_rd_g3864(.A (dut_u_rd_n_2412), .Y (dut_u_rd_n_2380));
  NOR2XL dut_u_rd_g3865(.A (dut_u_rd_n_2403), .B (dut_u_rd_n_2392), .Y
       (dut_u_rd_n_2382));
  AOI21XL dut_u_rd_g3868(.A0 (dut_u_rd_n_2474), .A1 (dut_u_rd_n_2428),
       .B0 (dut_u_rd_n_2421), .Y (dut_u_rd_n_2386));
  NAND2X1 dut_u_rd_g3869(.A (dut_u_rd_outst_cnt[2]), .B
       (dut_u_rd_n_2392), .Y (dut_u_rd_n_2384));
  NAND2X1 dut_u_rd_g3870(.A (dut_u_rd_n_2490), .B (dut_u_rd_n_2391), .Y
       (dut_u_rd_n_2385));
  INVXL dut_u_rd_g3871(.A (dut_u_rd_n_2390), .Y (dut_u_rd_n_2389));
  NAND2XL dut_u_rd_g3872(.A (dut_u_rd_n_2419), .B (dut_u_rd_n_2470), .Y
       (dut_u_rd_n_2394));
  NOR2X1 dut_u_rd_g3873(.A (dut_u_rd_n_2468), .B (dut_u_rd_n_2413), .Y
       (dut_u_rd_n_2395));
  NAND2XL dut_u_rd_g3874(.A (dut_u_rd_n_2419), .B (dut_u_rd_n_2490), .Y
       (dut_u_rd_n_2390));
  NOR2BX1 dut_u_rd_g3875(.AN (dut_u_rd_n_2456), .B (dut_u_rd_n_2414),
       .Y (dut_u_rd_n_2391));
  NOR2BX1 dut_u_rd_g3876(.AN (dut_u_rd_n_2418), .B (dut_u_rd_n_2468),
       .Y (dut_u_rd_n_2392));
  NOR2BX1 dut_u_rd_g3877(.AN (dut_u_rd_n_2413), .B (dut_u_rd_n_2418),
       .Y (dut_u_rd_n_2393));
  INVX1 dut_u_rd_g3878(.A (dut_u_rd_n_2403), .Y (dut_u_rd_n_2404));
  INVX1 dut_u_rd_g3879(.A (dut_u_rd_n_2406), .Y (dut_u_rd_n_2405));
  NAND2XL dut_u_rd_g3880(.A (dut_u_rd_n_2420), .B (dut_u_rd_n_2414), .Y
       (dut_u_rd_n_2407));
  NOR2XL dut_u_rd_g3881(.A (dut_u_rd_n_2452), .B (dut_u_rd_n_2421), .Y
       (dut_u_rd_n_2408));
  OAI22X1 dut_u_rd_g3882(.A0 (dut_u_rd_n_2531), .A1 (dut_u_rd_n_2455),
       .B0 (dut_u_rd_n_2447), .B1 (dut_epoch_clr), .Y
       (dut_u_rd_n_2409));
  NAND3BXL dut_u_rd_g3883(.AN (dut_u_rd_n_2470), .B (dut_u_rd_n_2419),
       .C (dut_u_rd_drain_cnt[2]), .Y (dut_u_rd_n_2402));
  NOR3X1 dut_u_rd_g3884(.A (dut_u_rd_outst_cnt[1]), .B
       (dut_u_rd_outst_cnt[0]), .C (dut_u_rd_n_2413), .Y
       (dut_u_rd_n_2403));
  MX2XL dut_u_rd_g3885(.A (dut_u_rd_n_2439), .B (dut_u_rd_n_2531), .S0
       (dut_u_rd_n_2471), .Y (dut_u_rd_n_2406));
  INVXL dut_u_rd_g3886(.A (dut_u_rd_n_2414), .Y (dut_u_rd_n_2415));
  NAND2X1 dut_u_rd_g3887(.A (dut_u_rd_timer[2]), .B (dut_u_rd_n_2434),
       .Y (dut_u_rd_n_2412));
  NAND2X1 dut_u_rd_g3888(.A (dut_u_rd_n_2469), .B (dut_u_rd_n_2441), .Y
       (dut_u_rd_n_2413));
  OR2X1 dut_u_rd_g3889(.A (dut_u_rd_n_2471), .B (dut_u_rd_n_2531), .Y
       (dut_u_rd_n_2414));
  INVX1 dut_u_rd_g3890(.A (dut_u_rd_n_2419), .Y (dut_u_rd_n_2420));
  OAI211X1 dut_u_rd_g3891(.A0 (dut_u_rd_timer[0]), .A1
       (dut_u_rd_timer[1]), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2457), .Y (dut_u_rd_n_2428));
  NOR2X1 dut_u_rd_g3892(.A (dut_u_rd_n_2469), .B (dut_u_rd_n_2441), .Y
       (dut_u_rd_n_2418));
  NOR2BX1 dut_u_rd_g3893(.AN (dut_u_rd_n_2471), .B (dut_u_rd_n_2439),
       .Y (dut_u_rd_n_2419));
  OR3X1 dut_u_rd_g3894(.A (dut_rd_timeout_pulse), .B (dut_u_rd_n_2441),
       .C (dut_epoch_clr), .Y (dut_u_rd_n_2421));
  INVX1 dut_u_rd_g3895(.A (dut_u_rd_n_2457), .Y (dut_u_rd_n_2434));
  OR2X1 dut_u_rd_g3897(.A (dut_u_rd_n_2446), .B (dut_epoch_clr), .Y
       (dut_u_rd_n_2439));
  OR4X1 dut_u_rd_g3898(.A (dut_u_rd_n_2469), .B (dut_u_rd_rd_state[1]),
       .C (dut_u_rd_rd_state[0]), .D (logic_0_1_net), .Y
       (dut_u_rd_n_2442));
  NAND2X1 dut_u_rd_g3899(.A (dut_u_rd_n_2446), .B (dut_u_rd_n_2467), .Y
       (dut_u_rd_n_2441));
  AOI21XL dut_u_rd_g3900(.A0 (dut_flush), .A1 (dut_u_rd_n_297), .B0
       (dut_rd_timeout_pulse), .Y (dut_u_rd_n_2447));
  NAND3BXL dut_u_rd_g3901(.AN (dut_rd_timeout_pulse), .B
       (dut_u_rd_n_297), .C (dut_u_rd_n_292), .Y (dut_u_rd_n_2449));
  NAND2BX1 dut_u_rd_g3902(.AN (dut_u_rd_n_2455), .B (s_rready), .Y
       (dut_u_rd_n_2446));
  XNOR2X1 dut_u_rd_g3903(.A (dut_u_rd_timer_run), .B
       (dut_u_rd_timer[0]), .Y (dut_u_rd_n_2452));
  XNOR2X1 dut_u_rd_g3904(.A (dut_u_rd_drain_cnt[0]), .B
       (dut_u_rd_drain_cnt[1]), .Y (dut_u_rd_n_2453));
  NAND2X1 dut_u_rd_g3906(.A (dut_u_rd_n_2508), .B (dut_u_rd_timer[10]),
       .Y (dut_u_rd_n_2458));
  NAND2X1 dut_u_rd_g3907(.A (dut_u_rd_n_2508), .B (dut_u_rd_timer[11]),
       .Y (dut_u_rd_n_2460));
  NAND2X1 dut_u_rd_g3908(.A (dut_u_rd_n_2508), .B (dut_u_rd_timer[13]),
       .Y (dut_u_rd_n_2461));
  NAND2X1 dut_u_rd_g3909(.A (dut_u_rd_n_2508), .B (dut_u_rd_timer[12]),
       .Y (dut_u_rd_n_2462));
  NAND2X1 dut_u_rd_g3910(.A (dut_u_rd_n_2508), .B (dut_u_rd_timer[5]),
       .Y (dut_u_rd_n_2463));
  NAND2X1 dut_u_rd_g3911(.A (dut_u_rd_n_2508), .B (dut_u_rd_timer[3]),
       .Y (dut_u_rd_n_2464));
  NAND2X1 dut_u_rd_g3912(.A (dut_u_rd_n_2508), .B (dut_u_rd_timer[14]),
       .Y (dut_u_rd_n_2465));
  NAND2X1 dut_u_rd_g3913(.A (dut_u_rd_n_2508), .B (dut_u_rd_timer[6]),
       .Y (dut_u_rd_n_2466));
  NAND2BX1 dut_u_rd_g3914(.AN (dut_u_rd_rd_state[0]), .B
       (dut_u_rd_rd_state[1]), .Y (dut_u_rd_n_2455));
  NOR2X1 dut_u_rd_g3915(.A (dut_u_rd_drain_cnt[1]), .B
       (dut_u_rd_drain_cnt[0]), .Y (dut_u_rd_n_2456));
  NAND2X1 dut_u_rd_g3916(.A (dut_u_rd_timer[1]), .B
       (dut_u_rd_timer[0]), .Y (dut_u_rd_n_2457));
  NAND2X1 dut_u_rd_g3917(.A (dut_u_rd_n_2508), .B (dut_u_rd_timer[2]),
       .Y (dut_u_rd_n_2472));
  NAND2X1 dut_u_rd_g3918(.A (dut_u_rd_n_2508), .B (dut_u_rd_timer[9]),
       .Y (dut_u_rd_n_2473));
  NAND2X1 dut_u_rd_g3919(.A (dut_u_rd_n_2508), .B (dut_u_rd_timer[1]),
       .Y (dut_u_rd_n_2474));
  NAND2X1 dut_u_rd_g3920(.A (dut_u_rd_n_2508), .B (dut_u_rd_timer[8]),
       .Y (dut_u_rd_n_2475));
  NAND2X1 dut_u_rd_g3921(.A (dut_u_rd_n_2508), .B (dut_u_rd_timer[4]),
       .Y (dut_u_rd_n_2476));
  NAND2X1 dut_u_rd_g3922(.A (dut_u_rd_n_2508), .B (dut_u_rd_timer[7]),
       .Y (dut_u_rd_n_2477));
  NAND2X1 dut_u_rd_g3923(.A (dut_u_rd_n_300), .B (s_rvalid), .Y
       (dut_u_rd_n_2467));
  NAND2X1 dut_u_rd_g3924(.A (dut_u_rd_outst_cnt[1]), .B
       (dut_u_rd_outst_cnt[0]), .Y (dut_u_rd_n_2468));
  NAND2X1 dut_u_rd_g3925(.A (s_arvalid), .B (s_arready), .Y
       (dut_u_rd_n_2469));
  NAND2X1 dut_u_rd_g3926(.A (dut_u_rd_drain_cnt[1]), .B
       (dut_u_rd_drain_cnt[0]), .Y (dut_u_rd_n_2470));
  NAND2X1 dut_u_rd_g3927(.A (m_rvalid), .B (dut_u_rd_n_299), .Y
       (dut_u_rd_n_2471));
  INVX1 dut_u_rd_g3929(.A (dut_u_rd_timer_run), .Y (dut_u_rd_n_2508));
  XOR2XL dut_u_rd_g2063(.A (dut_u_rd_outst_cnt[0]), .B
       (dut_u_rd_outst_cnt[1]), .Y (dut_u_rd_n_2530));
  NAND2BX1 dut_u_rd_g3934(.AN (dut_epoch_clr), .B (dut_u_rd_n_2446), .Y
       (dut_u_rd_n_2531));
  INVXL g6362(.A (dut_flush), .Y (dut_u_rd_n_292));
  CLKBUFX2 g6363(.A (dut_u_wr_n_2753), .Y (s_awready));
  INVXL g6364(.A (dut_u_wr_n_4139), .Y (dut_u_wr_n_4084));
  INVXL g6365(.A (s_wready), .Y (dut_u_wr_n_4143));
  NAND2X1 g2(.A (s_wvalid), .B (dut_u_wr_w_perm), .Y (n_222));
  OAI21X1 g6366(.A0 (dut_u_wr_n_4084), .A1 (dut_u_wr_n_4088), .B0
       (dut_u_wr_n_4103), .Y (n_223));
  NOR2BX1 dut_u_wr_g6367(.AN (dut_u_wr_wr_state[1]), .B
       (dut_u_wr_wr_state[0]), .Y (n_224));
  DFFRX1 \dut_mode_reg[0] (.RN (rst_n), .CK (clk), .D (n_10), .Q
       (dut_mode[0]), .QN (dut_n_418));
  DFFRX1 \dut_mode_reg[1] (.RN (rst_n), .CK (clk), .D (n_8), .Q
       (dut_mode[1]), .QN (dut_n_419));
  DFFRX1 \dut_u_rd_rd_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2409), .Q (dut_u_rd_rd_state[1]), .QN
       (dut_u_rd_n_1855));
  DFFRX1 \dut_u_rd_drain_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2340), .Q (dut_u_rd_drain_cnt[2]), .QN
       (dut_u_rd_n_2490));
  DFFRX1 \dut_u_rd_outst_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2326), .Q (dut_u_rd_outst_cnt[3]), .QN
       (dut_u_rd_n_2520));
  DFFRX1 \dut_u_rd_drain_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2324), .Q (dut_u_rd_drain_cnt[3]), .QN
       (dut_u_rd_n_2525));
  AOI2BB1XL g6380(.A0N (dut_u_wr_downstream_w_done), .A1N
       (dut_u_wr_downstream_w_fire), .B0 (n_222), .Y (n_225));
  TIELO tie_0_cell(.Y (logic_0_1_net));
endmodule

