
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Aug 29 2026 17:57:19 PDT (Aug 30 2026 00:57:19 UTC)

// Verification Directory fv/tp_lvl_d64 

module tp_lvl_d64(clk, rst_n, s_awvalid, \s_aw[prot] , \s_aw[addr] ,
     s_wvalid, \s_w[strb] , \s_w[data] , s_arvalid, \s_ar[prot] ,
     \s_ar[addr] , s_bready, s_rready, s_awready, s_wready, s_arready,
     s_bvalid, \s_b[resp] , s_rvalid, \s_r[resp] , \s_r[data] ,
     m_awvalid, \m_aw[prot] , \m_aw[addr] , m_wvalid, \m_w[strb] ,
     \m_w[data] , m_arvalid, \m_ar[prot] , \m_ar[addr] , m_bready,
     m_rready, m_awready, m_wready, m_arready, m_bvalid, \m_b[resp] ,
     m_rvalid, \m_r[resp] , \m_r[data] , enable_reg, clear_reg, irq,
     status_reg, guard_busy);
  input clk, rst_n, s_awvalid, s_wvalid, s_arvalid, s_bready, s_rready,
       m_awready, m_wready, m_arready, m_bvalid, m_rvalid;
  input [2:0] \s_aw[prot] , \s_ar[prot] , enable_reg, clear_reg;
  input [31:0] \s_aw[addr] , \s_w[data] , \s_ar[addr] , \m_r[data] ;
  input [3:0] \s_w[strb] ;
  input [1:0] \m_b[resp] , \m_r[resp] ;
  output s_awready, s_wready, s_arready, s_bvalid, s_rvalid, m_awvalid,
       m_wvalid, m_arvalid, m_bready, m_rready, irq, guard_busy;
  output [1:0] \s_b[resp] , \s_r[resp] ;
  output [31:0] \s_r[data] , \m_aw[addr] , \m_w[data] , \m_ar[addr] ;
  output [2:0] \m_aw[prot] , \m_ar[prot] , status_reg;
  output [3:0] \m_w[strb] ;
  wire clk, rst_n, s_awvalid, s_wvalid, s_arvalid, s_bready, s_rready,
       m_awready, m_wready, m_arready, m_bvalid, m_rvalid;
  wire [2:0] \s_aw[prot] , \s_ar[prot] , enable_reg, clear_reg;
  wire [31:0] \s_aw[addr] , \s_w[data] , \s_ar[addr] , \m_r[data] ;
  wire [3:0] \s_w[strb] ;
  wire [1:0] \m_b[resp] , \m_r[resp] ;
  wire s_awready, s_wready, s_arready, s_bvalid, s_rvalid, m_awvalid,
       m_wvalid, m_arvalid, m_bready, m_rready, irq, guard_busy;
  wire [1:0] \s_b[resp] , \s_r[resp] ;
  wire [31:0] \s_r[data] , \m_aw[addr] , \m_w[data] , \m_ar[addr] ;
  wire [2:0] \m_aw[prot] , \m_ar[prot] , status_reg;
  wire [3:0] \m_w[strb] ;
  wire [1:0] dut_mode;
  wire [2:0] dut_rcvy_ack;
  wire [1:0] dut_u_wr_wpair_state;
  wire [6:0] dut_u_wr_outst_cnt;
  wire [15:0] dut_u_wr_w_timer;
  wire [6:0] dut_u_wr_drain_cnt;
  wire [15:0] dut_u_wr_b_timer;
  wire [1:0] dut_u_wr_wr_state;
  wire [6:0] dut_u_rd_outst_cnt;
  wire [6:0] dut_u_rd_drain_cnt;
  wire [15:0] dut_u_rd_timer;
  wire [1:0] dut_u_rd_rd_state;
  wire dut_all_upstream_empty, dut_epoch_clr, dut_flush, dut_n_418,
       dut_n_419, dut_rd_busy, dut_rd_timeout_pulse,
       dut_rd_upstream_empty;
  wire dut_u_rd_n_316, dut_u_rd_n_321, dut_u_rd_n_323, dut_u_rd_n_324,
       dut_u_rd_n_336, dut_u_rd_n_571, dut_u_rd_n_1538, dut_u_rd_n_1541;
  wire dut_u_rd_n_1945, dut_u_rd_n_1946, dut_u_rd_n_1949,
       dut_u_rd_n_1950, dut_u_rd_n_1994, dut_u_rd_n_1995,
       dut_u_rd_n_1996, dut_u_rd_n_1997;
  wire dut_u_rd_n_1999, dut_u_rd_n_2001, dut_u_rd_n_2006,
       dut_u_rd_n_2009, dut_u_rd_n_2935, dut_u_rd_n_2938,
       dut_u_rd_n_2940, dut_u_rd_n_2942;
  wire dut_u_rd_n_2943, dut_u_rd_n_2948, dut_u_rd_n_2949,
       dut_u_rd_n_2950, dut_u_rd_n_2953, dut_u_rd_n_2955,
       dut_u_rd_n_2956, dut_u_rd_n_2957;
  wire dut_u_rd_n_2960, dut_u_rd_n_2962, dut_u_rd_n_2963,
       dut_u_rd_n_2964, dut_u_rd_n_2967, dut_u_rd_n_2969,
       dut_u_rd_n_2970, dut_u_rd_n_2971;
  wire dut_u_rd_n_2974, dut_u_rd_n_2976, dut_u_rd_n_2977,
       dut_u_rd_n_2978, dut_u_rd_n_2981, dut_u_rd_n_2983,
       dut_u_rd_n_2984, dut_u_rd_n_2985;
  wire dut_u_rd_n_2988, dut_u_rd_n_2990, dut_u_rd_n_2991,
       dut_u_rd_n_2992, dut_u_rd_n_2995, dut_u_rd_n_2997,
       dut_u_rd_n_2998, dut_u_rd_n_2999;
  wire dut_u_rd_n_3002, dut_u_rd_n_3004, dut_u_rd_n_3005,
       dut_u_rd_n_3006, dut_u_rd_n_3009, dut_u_rd_n_3011,
       dut_u_rd_n_3013, dut_u_rd_n_3015;
  wire dut_u_rd_n_3016, dut_u_rd_n_3018, dut_u_rd_n_3020,
       dut_u_rd_n_3022, dut_u_rd_n_3023, dut_u_rd_n_3024,
       dut_u_rd_n_3026, dut_u_rd_n_3027;
  wire dut_u_rd_n_3029, dut_u_rd_n_3030, dut_u_rd_n_3034,
       dut_u_rd_n_3035, dut_u_rd_n_3036, dut_u_rd_n_3037,
       dut_u_rd_n_3039, dut_u_rd_n_3041;
  wire dut_u_rd_n_3043, dut_u_rd_n_3050, dut_u_rd_n_3052,
       dut_u_rd_n_3053, dut_u_rd_n_3054, dut_u_rd_n_3056,
       dut_u_rd_n_3057, dut_u_rd_n_3058;
  wire dut_u_rd_n_3059, dut_u_rd_n_3060, dut_u_rd_n_3066,
       dut_u_rd_n_3070, dut_u_rd_n_3071, dut_u_rd_n_3075,
       dut_u_rd_n_3081, dut_u_rd_n_3082;
  wire dut_u_rd_n_3084, dut_u_rd_n_3085, dut_u_rd_n_3087,
       dut_u_rd_n_3090, dut_u_rd_n_3091, dut_u_rd_n_3092,
       dut_u_rd_n_3094, dut_u_rd_n_3096;
  wire dut_u_rd_n_3097, dut_u_rd_n_3104, dut_u_rd_n_3106,
       dut_u_rd_n_3108, dut_u_rd_n_3110, dut_u_rd_n_3112,
       dut_u_rd_n_3113, dut_u_rd_n_3114;
  wire dut_u_rd_n_3115, dut_u_rd_n_3116, dut_u_rd_n_3118,
       dut_u_rd_n_3122, dut_u_rd_n_3123, dut_u_rd_n_3124,
       dut_u_rd_n_3125, dut_u_rd_n_3126;
  wire dut_u_rd_n_3128, dut_u_rd_n_3129, dut_u_rd_n_3130,
       dut_u_rd_n_3135, dut_u_rd_n_3136, dut_u_rd_n_3137,
       dut_u_rd_n_3138, dut_u_rd_n_3139;
  wire dut_u_rd_n_3140, dut_u_rd_n_3141, dut_u_rd_n_3146,
       dut_u_rd_n_3147, dut_u_rd_n_3148, dut_u_rd_n_3149,
       dut_u_rd_n_3150, dut_u_rd_n_3151;
  wire dut_u_rd_n_3152, dut_u_rd_n_3153, dut_u_rd_n_3158,
       dut_u_rd_n_3159, dut_u_rd_n_3160, dut_u_rd_n_3167,
       dut_u_rd_n_3173, dut_u_rd_n_3175;
  wire dut_u_rd_n_3177, dut_u_rd_n_3180, dut_u_rd_n_3181,
       dut_u_rd_n_3184, dut_u_rd_n_3185, dut_u_rd_n_3186,
       dut_u_rd_n_3188, dut_u_rd_n_3189;
  wire dut_u_rd_n_3190, dut_u_rd_n_3191, dut_u_rd_n_3193,
       dut_u_rd_n_3196, dut_u_rd_n_3197, dut_u_rd_n_3198,
       dut_u_rd_n_3200, dut_u_rd_n_3201;
  wire dut_u_rd_n_3202, dut_u_rd_n_3203, dut_u_rd_n_3204,
       dut_u_rd_n_3205, dut_u_rd_n_3206, dut_u_rd_n_3207,
       dut_u_rd_n_3208, dut_u_rd_n_3209;
  wire dut_u_rd_n_3210, dut_u_rd_n_3211, dut_u_rd_n_3212,
       dut_u_rd_n_3213, dut_u_rd_n_3215, dut_u_rd_n_3216,
       dut_u_rd_n_3217, dut_u_rd_n_3218;
  wire dut_u_rd_n_3219, dut_u_rd_n_3237, dut_u_rd_n_3239,
       dut_u_rd_n_3261, dut_u_rd_n_3263, dut_u_rd_n_3265,
       dut_u_rd_n_3282, dut_u_rd_n_3283;
  wire dut_u_rd_n_3284, dut_u_rd_n_3285, dut_u_rd_timer_run,
       dut_u_wr_b_timer_run, dut_u_wr_downstream_aw_done,
       dut_u_wr_downstream_aw_fire, dut_u_wr_downstream_w_done,
       dut_u_wr_downstream_w_fire;
  wire dut_u_wr_n_452, dut_u_wr_n_454, dut_u_wr_n_455, dut_u_wr_n_466,
       dut_u_wr_n_2458, dut_u_wr_n_2525, dut_u_wr_n_2536,
       dut_u_wr_n_3004;
  wire dut_u_wr_n_3010, dut_u_wr_n_3014, dut_u_wr_n_3017,
       dut_u_wr_n_3022, dut_u_wr_n_3027, dut_u_wr_n_3029,
       dut_u_wr_n_3033, dut_u_wr_n_3037;
  wire dut_u_wr_n_3038, dut_u_wr_n_3039, dut_u_wr_n_3040,
       dut_u_wr_n_3041, dut_u_wr_n_3042, dut_u_wr_n_3043,
       dut_u_wr_n_3044, dut_u_wr_n_3046;
  wire dut_u_wr_n_3048, dut_u_wr_n_3049, dut_u_wr_n_3051,
       dut_u_wr_n_3930, dut_u_wr_n_3931, dut_u_wr_n_3932,
       dut_u_wr_n_3934, dut_u_wr_n_3936;
  wire dut_u_wr_n_3938, dut_u_wr_n_3940, dut_u_wr_n_3941,
       dut_u_wr_n_3942, dut_u_wr_n_3946, dut_u_wr_n_3952,
       dut_u_wr_n_3953, dut_u_wr_n_3954;
  wire dut_u_wr_n_3956, dut_u_wr_n_3957, dut_u_wr_n_3959,
       dut_u_wr_n_3962, dut_u_wr_n_3964, dut_u_wr_n_3966,
       dut_u_wr_n_3967, dut_u_wr_n_3968;
  wire dut_u_wr_n_3970, dut_u_wr_n_3971, dut_u_wr_n_3973,
       dut_u_wr_n_3976, dut_u_wr_n_3978, dut_u_wr_n_3980,
       dut_u_wr_n_3981, dut_u_wr_n_3982;
  wire dut_u_wr_n_3984, dut_u_wr_n_3985, dut_u_wr_n_3987,
       dut_u_wr_n_3990, dut_u_wr_n_3992, dut_u_wr_n_3994,
       dut_u_wr_n_3995, dut_u_wr_n_3996;
  wire dut_u_wr_n_3998, dut_u_wr_n_3999, dut_u_wr_n_4001,
       dut_u_wr_n_4004, dut_u_wr_n_4006, dut_u_wr_n_4008,
       dut_u_wr_n_4009, dut_u_wr_n_4010;
  wire dut_u_wr_n_4012, dut_u_wr_n_4013, dut_u_wr_n_4015,
       dut_u_wr_n_4018, dut_u_wr_n_4020, dut_u_wr_n_4022,
       dut_u_wr_n_4023, dut_u_wr_n_4024;
  wire dut_u_wr_n_4026, dut_u_wr_n_4027, dut_u_wr_n_4029,
       dut_u_wr_n_4032, dut_u_wr_n_4034, dut_u_wr_n_4036,
       dut_u_wr_n_4037, dut_u_wr_n_4038;
  wire dut_u_wr_n_4040, dut_u_wr_n_4041, dut_u_wr_n_4043,
       dut_u_wr_n_4046, dut_u_wr_n_4048, dut_u_wr_n_4050,
       dut_u_wr_n_4051, dut_u_wr_n_4052;
  wire dut_u_wr_n_4054, dut_u_wr_n_4055, dut_u_wr_n_4057,
       dut_u_wr_n_4060, dut_u_wr_n_4062, dut_u_wr_n_4064,
       dut_u_wr_n_4065, dut_u_wr_n_4066;
  wire dut_u_wr_n_4068, dut_u_wr_n_4069, dut_u_wr_n_4071,
       dut_u_wr_n_4072, dut_u_wr_n_4075, dut_u_wr_n_4077,
       dut_u_wr_n_4079, dut_u_wr_n_4080;
  wire dut_u_wr_n_4081, dut_u_wr_n_4082, dut_u_wr_n_4085,
       dut_u_wr_n_4087, dut_u_wr_n_4088, dut_u_wr_n_4090,
       dut_u_wr_n_4092, dut_u_wr_n_4095;
  wire dut_u_wr_n_4097, dut_u_wr_n_4099, dut_u_wr_n_4101,
       dut_u_wr_n_4102, dut_u_wr_n_4103, dut_u_wr_n_4105,
       dut_u_wr_n_4107, dut_u_wr_n_4109;
  wire dut_u_wr_n_4110, dut_u_wr_n_4111, dut_u_wr_n_4113,
       dut_u_wr_n_4115, dut_u_wr_n_4117, dut_u_wr_n_4119,
       dut_u_wr_n_4121, dut_u_wr_n_4124;
  wire dut_u_wr_n_4126, dut_u_wr_n_4128, dut_u_wr_n_4129,
       dut_u_wr_n_4131, dut_u_wr_n_4133, dut_u_wr_n_4134,
       dut_u_wr_n_4135, dut_u_wr_n_4136;
  wire dut_u_wr_n_4139, dut_u_wr_n_4140, dut_u_wr_n_4148,
       dut_u_wr_n_4150, dut_u_wr_n_4152, dut_u_wr_n_4155,
       dut_u_wr_n_4156, dut_u_wr_n_4157;
  wire dut_u_wr_n_4158, dut_u_wr_n_4160, dut_u_wr_n_4167,
       dut_u_wr_n_4168, dut_u_wr_n_4169, dut_u_wr_n_4170,
       dut_u_wr_n_4172, dut_u_wr_n_4176;
  wire dut_u_wr_n_4177, dut_u_wr_n_4178, dut_u_wr_n_4179,
       dut_u_wr_n_4181, dut_u_wr_n_4183, dut_u_wr_n_4185,
       dut_u_wr_n_4187, dut_u_wr_n_4191;
  wire dut_u_wr_n_4193, dut_u_wr_n_4195, dut_u_wr_n_4196,
       dut_u_wr_n_4197, dut_u_wr_n_4200, dut_u_wr_n_4202,
       dut_u_wr_n_4203, dut_u_wr_n_4204;
  wire dut_u_wr_n_4205, dut_u_wr_n_4206, dut_u_wr_n_4207,
       dut_u_wr_n_4210, dut_u_wr_n_4211, dut_u_wr_n_4212,
       dut_u_wr_n_4214, dut_u_wr_n_4215;
  wire dut_u_wr_n_4216, dut_u_wr_n_4220, dut_u_wr_n_4221,
       dut_u_wr_n_4222, dut_u_wr_n_4223, dut_u_wr_n_4224,
       dut_u_wr_n_4225, dut_u_wr_n_4228;
  wire dut_u_wr_n_4229, dut_u_wr_n_4262, dut_u_wr_n_4263,
       dut_u_wr_n_4264, dut_u_wr_n_4265, dut_u_wr_n_4266,
       dut_u_wr_n_4267, dut_u_wr_n_4268;
  wire dut_u_wr_n_4269, dut_u_wr_n_4270, dut_u_wr_n_4271,
       dut_u_wr_n_4272, dut_u_wr_n_4280, dut_u_wr_n_4281,
       dut_u_wr_n_4284, dut_u_wr_n_4287;
  wire dut_u_wr_n_4289, dut_u_wr_n_4311, dut_u_wr_n_4313,
       dut_u_wr_n_4315, dut_u_wr_n_4316, dut_u_wr_n_4317,
       dut_u_wr_n_4318, dut_u_wr_n_4322;
  wire dut_u_wr_n_4323, dut_u_wr_n_4325, dut_u_wr_n_4326,
       dut_u_wr_n_4329, dut_u_wr_n_4330, dut_u_wr_n_4331,
       dut_u_wr_n_4332, dut_u_wr_n_4334;
  wire dut_u_wr_n_4335, dut_u_wr_n_4339, dut_u_wr_n_4340,
       dut_u_wr_n_4341, dut_u_wr_n_4342, dut_u_wr_n_4343,
       dut_u_wr_n_4350, dut_u_wr_n_4352;
  wire dut_u_wr_n_4355, dut_u_wr_n_4356, dut_u_wr_n_4357,
       dut_u_wr_n_4358, dut_u_wr_n_4359, dut_u_wr_n_4361,
       dut_u_wr_n_4362, dut_u_wr_n_4363;
  wire dut_u_wr_n_4364, dut_u_wr_n_4365, dut_u_wr_n_4366,
       dut_u_wr_n_4367, dut_u_wr_n_4368, dut_u_wr_n_4369,
       dut_u_wr_n_4370, dut_u_wr_n_4371;
  wire dut_u_wr_n_4372, dut_u_wr_n_4373, dut_u_wr_n_4374,
       dut_u_wr_n_4375, dut_u_wr_n_4376, dut_u_wr_n_4377,
       dut_u_wr_n_4379, dut_u_wr_n_4380;
  wire dut_u_wr_n_4381, dut_u_wr_n_4382, dut_u_wr_n_4383,
       dut_u_wr_n_4384, dut_u_wr_n_4385, dut_u_wr_n_4386,
       dut_u_wr_n_4387, dut_u_wr_n_4388;
  wire dut_u_wr_n_4389, dut_u_wr_n_4390, dut_u_wr_n_4391,
       dut_u_wr_n_4392, dut_u_wr_n_4393, dut_u_wr_n_4396,
       dut_u_wr_n_4397, dut_u_wr_n_4398;
  wire dut_u_wr_n_4400, dut_u_wr_n_4428, dut_u_wr_n_4430,
       dut_u_wr_n_4432, dut_u_wr_n_4461, dut_u_wr_n_4464,
       dut_u_wr_n_4467, dut_u_wr_w_perm;
  wire dut_u_wr_w_timer_run, dut_wr_busy, dut_wr_timeout_pulse,
       dut_wr_upstream_empty, dut_wr_w_fault_pulse, logic_0_1_net, n_0,
       n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_222, n_223, n_224;
  wire n_225;
  assign \m_ar[addr] [0] = \s_ar[addr] [0];
  assign \m_ar[addr] [1] = \s_ar[addr] [1];
  assign \m_ar[addr] [2] = \s_ar[addr] [2];
  assign \m_ar[addr] [3] = \s_ar[addr] [3];
  assign \m_ar[addr] [4] = \s_ar[addr] [4];
  assign \m_ar[addr] [5] = \s_ar[addr] [5];
  assign \m_ar[addr] [6] = \s_ar[addr] [6];
  assign \m_ar[addr] [7] = \s_ar[addr] [7];
  assign \m_ar[addr] [8] = \s_ar[addr] [8];
  assign \m_ar[addr] [9] = \s_ar[addr] [9];
  assign \m_ar[addr] [10] = \s_ar[addr] [10];
  assign \m_ar[addr] [11] = \s_ar[addr] [11];
  assign \m_ar[addr] [12] = \s_ar[addr] [12];
  assign \m_ar[addr] [13] = \s_ar[addr] [13];
  assign \m_ar[addr] [14] = \s_ar[addr] [14];
  assign \m_ar[addr] [15] = \s_ar[addr] [15];
  assign \m_ar[addr] [16] = \s_ar[addr] [16];
  assign \m_ar[addr] [17] = \s_ar[addr] [17];
  assign \m_ar[addr] [18] = \s_ar[addr] [18];
  assign \m_ar[addr] [19] = \s_ar[addr] [19];
  assign \m_ar[addr] [20] = \s_ar[addr] [20];
  assign \m_ar[addr] [21] = \s_ar[addr] [21];
  assign \m_ar[addr] [22] = \s_ar[addr] [22];
  assign \m_ar[addr] [23] = \s_ar[addr] [23];
  assign \m_ar[addr] [24] = \s_ar[addr] [24];
  assign \m_ar[addr] [25] = \s_ar[addr] [25];
  assign \m_ar[addr] [26] = \s_ar[addr] [26];
  assign \m_ar[addr] [27] = \s_ar[addr] [27];
  assign \m_ar[addr] [28] = \s_ar[addr] [28];
  assign \m_ar[addr] [29] = \s_ar[addr] [29];
  assign \m_ar[addr] [30] = \s_ar[addr] [30];
  assign \m_ar[addr] [31] = \s_ar[addr] [31];
  assign \m_ar[prot] [0] = \s_ar[prot] [0];
  assign \m_ar[prot] [1] = \s_ar[prot] [1];
  assign \m_ar[prot] [2] = \s_ar[prot] [2];
  assign \m_w[data] [0] = \s_w[data] [0];
  assign \m_w[data] [1] = \s_w[data] [1];
  assign \m_w[data] [2] = \s_w[data] [2];
  assign \m_w[data] [3] = \s_w[data] [3];
  assign \m_w[data] [4] = \s_w[data] [4];
  assign \m_w[data] [5] = \s_w[data] [5];
  assign \m_w[data] [6] = \s_w[data] [6];
  assign \m_w[data] [7] = \s_w[data] [7];
  assign \m_w[data] [8] = \s_w[data] [8];
  assign \m_w[data] [9] = \s_w[data] [9];
  assign \m_w[data] [10] = \s_w[data] [10];
  assign \m_w[data] [11] = \s_w[data] [11];
  assign \m_w[data] [12] = \s_w[data] [12];
  assign \m_w[data] [13] = \s_w[data] [13];
  assign \m_w[data] [14] = \s_w[data] [14];
  assign \m_w[data] [15] = \s_w[data] [15];
  assign \m_w[data] [16] = \s_w[data] [16];
  assign \m_w[data] [17] = \s_w[data] [17];
  assign \m_w[data] [18] = \s_w[data] [18];
  assign \m_w[data] [19] = \s_w[data] [19];
  assign \m_w[data] [20] = \s_w[data] [20];
  assign \m_w[data] [21] = \s_w[data] [21];
  assign \m_w[data] [22] = \s_w[data] [22];
  assign \m_w[data] [23] = \s_w[data] [23];
  assign \m_w[data] [24] = \s_w[data] [24];
  assign \m_w[data] [25] = \s_w[data] [25];
  assign \m_w[data] [26] = \s_w[data] [26];
  assign \m_w[data] [27] = \s_w[data] [27];
  assign \m_w[data] [28] = \s_w[data] [28];
  assign \m_w[data] [29] = \s_w[data] [29];
  assign \m_w[data] [30] = \s_w[data] [30];
  assign \m_w[data] [31] = \s_w[data] [31];
  assign \m_w[strb] [0] = \s_w[strb] [0];
  assign \m_w[strb] [1] = \s_w[strb] [1];
  assign \m_w[strb] [2] = \s_w[strb] [2];
  assign \m_w[strb] [3] = \s_w[strb] [3];
  AND3X1 g271(.A (n_14), .B (dut_rd_upstream_empty), .C
       (dut_wr_upstream_empty), .Y (dut_epoch_clr));
  NOR3X1 g272(.A (n_13), .B (dut_mode[0]), .C (dut_n_419), .Y (n_14));
  NOR3X1 g273(.A (dut_rcvy_ack[0]), .B (dut_rcvy_ack[2]), .C
       (dut_rcvy_ack[1]), .Y (n_13));
  DFFRHQX1 \dut_u_irq_rcvy_ack_reg[2] (.RN (rst_n), .CK (clk), .D
       (clear_reg[2]), .Q (dut_rcvy_ack[2]));
  DFFRHQX1 \dut_u_irq_rcvy_ack_reg[1] (.RN (rst_n), .CK (clk), .D
       (clear_reg[1]), .Q (dut_rcvy_ack[1]));
  DFFRHQX1 \dut_u_irq_rcvy_ack_reg[0] (.RN (rst_n), .CK (clk), .D
       (clear_reg[0]), .Q (dut_rcvy_ack[0]));
  AND2XL g277(.A (dut_rd_upstream_empty), .B (dut_wr_upstream_empty),
       .Y (dut_all_upstream_empty));
  NAND2X1 g278(.A (dut_n_418), .B (dut_n_419), .Y (dut_flush));
  AND2X1 g222(.A (dut_all_upstream_empty), .B (n_12), .Y (irq));
  OAI2BB1X1 g223(.A0N (enable_reg[0]), .A1N (status_reg[0]), .B0
       (n_11), .Y (n_12));
  AOI22X1 g224(.A0 (enable_reg[1]), .A1 (status_reg[1]), .B0
       (enable_reg[2]), .B1 (status_reg[2]), .Y (n_11));
  OR2X1 g225(.A (dut_rd_busy), .B (dut_wr_busy), .Y (guard_busy));
  NOR2BX1 g366(.AN (n_9), .B (dut_mode[1]), .Y (n_10));
  OAI22X1 g368(.A0 (dut_mode[0]), .A1 (n_4), .B0 (dut_n_418), .B1
       (dut_all_upstream_empty), .Y (n_9));
  DFFRHQX1 \dut_u_irq_status_reg_reg[0] (.RN (rst_n), .CK (clk), .D
       (n_7), .Q (status_reg[0]));
  DFFRHQX1 \dut_u_irq_status_reg_reg[1] (.RN (rst_n), .CK (clk), .D
       (n_6), .Q (status_reg[1]));
  OAI33X1 g371(.A0 (dut_mode[0]), .A1 (dut_n_419), .A2 (dut_epoch_clr),
       .B0 (dut_n_418), .B1 (dut_mode[1]), .B2 (n_0), .Y (n_8));
  DFFRHQX1 \dut_u_irq_status_reg_reg[2] (.RN (rst_n), .CK (clk), .D
       (n_5), .Q (status_reg[2]));
  OR2XL g373(.A (n_3), .B (dut_rd_timeout_pulse), .Y (n_7));
  OR2XL g374(.A (n_2), .B (dut_wr_w_fault_pulse), .Y (n_6));
  OR2XL g375(.A (n_1), .B (dut_wr_timeout_pulse), .Y (n_5));
  NOR3X1 g376(.A (dut_rd_timeout_pulse), .B (dut_wr_timeout_pulse), .C
       (dut_wr_w_fault_pulse), .Y (n_4));
  NOR2BX1 g377(.AN (status_reg[0]), .B (clear_reg[0]), .Y (n_3));
  NOR2BX1 g378(.AN (status_reg[1]), .B (clear_reg[1]), .Y (n_2));
  NOR2BX1 g379(.AN (status_reg[2]), .B (clear_reg[2]), .Y (n_1));
  INVX1 g380(.A (dut_all_upstream_empty), .Y (n_0));
  INVX1 dut_u_wr_g2107(.A (s_awvalid), .Y (dut_u_wr_n_2536));
  OA21X1 dut_u_wr_g2215(.A0 (dut_u_wr_downstream_aw_fire), .A1
       (dut_u_wr_downstream_aw_done), .B0 (n_225), .Y (s_wready));
  AND2XL dut_u_wr_g2217(.A (m_awready), .B (m_awvalid), .Y
       (dut_u_wr_downstream_aw_fire));
  AND2XL dut_u_wr_g2218(.A (m_wready), .B (m_wvalid), .Y
       (dut_u_wr_downstream_w_fire));
  NOR2X1 dut_u_wr_g2162(.A (dut_u_wr_wpair_state[0]), .B
       (dut_u_wr_n_466), .Y (dut_wr_upstream_empty));
  OR4X1 dut_u_wr_g2163(.A (dut_u_wr_outst_cnt[5]), .B
       (dut_u_wr_outst_cnt[6]), .C (dut_u_wr_outst_cnt[0]), .D
       (dut_u_wr_n_2525), .Y (dut_u_wr_n_466));
  OR4X1 dut_u_wr_g2164(.A (dut_u_wr_outst_cnt[2]), .B
       (dut_u_wr_outst_cnt[1]), .C (dut_u_wr_outst_cnt[3]), .D
       (dut_u_wr_outst_cnt[4]), .Y (dut_u_wr_n_2525));
  NOR2BX1 dut_u_wr_g2970(.AN (dut_u_wr_b_timer_run), .B
       (dut_u_wr_n_3017), .Y (dut_wr_timeout_pulse));
  OR2X1 dut_u_wr_g2971(.A (dut_u_wr_n_3004), .B (n_224), .Y (s_bvalid));
  NOR2XL dut_u_wr_g2972(.A (dut_u_wr_n_3010), .B (dut_u_wr_n_3049), .Y
       (dut_u_wr_n_3004));
  AND2X1 dut_u_wr_g2973(.A (dut_u_wr_n_452), .B (dut_u_wr_n_3010), .Y
       (dut_u_wr_b_timer_run));
  AND2X1 dut_u_wr_g2974(.A (dut_u_wr_n_3014), .B (dut_u_wr_n_3048), .Y
       (s_awready));
  AND4XL dut_u_wr_g2975(.A (dut_u_wr_w_timer_run), .B
       (dut_u_wr_n_3041), .C (dut_u_wr_n_3040), .D (dut_u_wr_n_3022),
       .Y (dut_wr_w_fault_pulse));
  OR2X1 dut_u_wr_g2976(.A (dut_u_wr_n_455), .B (dut_u_wr_n_454), .Y
       (m_bready));
  NAND2BX1 dut_u_wr_g2977(.AN (dut_u_wr_n_454), .B (m_bvalid), .Y
       (dut_u_wr_n_3010));
  AOI211XL dut_u_wr_g2978(.A0 (dut_u_wr_n_3033), .A1 (dut_u_wr_n_3037),
       .B0 (dut_u_wr_wpair_state[0]), .C0 (dut_flush), .Y
       (dut_u_wr_n_3014));
  OR4X1 dut_u_wr_g2979(.A (dut_u_wr_wpair_state[0]), .B
       (dut_u_wr_wpair_state[1]), .C (dut_u_wr_n_466), .D
       (dut_u_wr_n_454), .Y (dut_wr_busy));
  NAND4XL dut_u_wr_g2980(.A (dut_u_wr_n_3038), .B (dut_u_wr_n_3029), .C
       (dut_u_wr_n_3044), .D (dut_u_wr_n_3039), .Y (dut_u_wr_n_3017));
  NOR2X2 dut_u_wr_g2981(.A (dut_u_wr_n_3027), .B
       (dut_u_wr_downstream_aw_done), .Y (m_awvalid));
  NOR2X2 dut_u_wr_g2982(.A (dut_u_wr_n_3027), .B
       (dut_u_wr_downstream_w_done), .Y (m_wvalid));
  NOR4X1 dut_u_wr_g2983(.A (dut_u_wr_w_timer[2]), .B
       (dut_u_wr_w_timer[3]), .C (dut_u_wr_n_3051), .D
       (dut_u_wr_n_3042), .Y (dut_u_wr_n_3022));
  AO21X1 dut_u_wr_g2984(.A0 (\m_b[resp] [1]), .A1 (dut_u_wr_n_452), .B0
       (n_224), .Y (\s_b[resp] [1]));
  OR4X1 dut_u_wr_g2985(.A (dut_u_wr_drain_cnt[5]), .B
       (dut_u_wr_drain_cnt[6]), .C (dut_u_wr_drain_cnt[2]), .D
       (dut_u_wr_n_3043), .Y (dut_u_wr_n_454));
  NOR4BX1 dut_u_wr_g2987(.AN (dut_u_wr_b_timer[8]), .B
       (dut_u_wr_b_timer[3]), .C (dut_u_wr_b_timer[9]), .D
       (dut_u_wr_b_timer[2]), .Y (dut_u_wr_n_3029));
  AND2X1 dut_u_wr_g2988(.A (dut_u_wr_n_452), .B (\m_b[resp] [0]), .Y
       (\s_b[resp] [0]));
  AND2XL dut_u_wr_g2989(.A (dut_u_wr_wpair_state[0]), .B
       (dut_u_wr_n_3048), .Y (dut_u_wr_w_perm));
  NOR3BX1 dut_u_wr_g2990(.AN (dut_u_wr_outst_cnt[6]), .B
       (dut_u_wr_outst_cnt[5]), .C (dut_u_wr_outst_cnt[4]), .Y
       (dut_u_wr_n_3033));
  NOR2X2 dut_u_wr_g2991(.A (dut_u_wr_n_3046), .B
       (dut_u_wr_wpair_state[1]), .Y (dut_u_wr_w_timer_run));
  NOR2BX1 dut_u_wr_g2992(.AN (s_bready), .B (dut_u_wr_n_3049), .Y
       (dut_u_wr_n_455));
  NAND3X1 dut_u_wr_g2993(.A (s_wvalid), .B (dut_u_wr_wpair_state[0]),
       .C (dut_u_wr_n_3048), .Y (dut_u_wr_n_3027));
  INVX1 dut_u_wr_g2994(.A (dut_u_wr_n_3037), .Y (dut_u_wr_n_2458));
  NOR4X1 dut_u_wr_g2995(.A (dut_u_wr_b_timer[4]), .B
       (dut_u_wr_b_timer[5]), .C (dut_u_wr_b_timer[10]), .D
       (dut_u_wr_b_timer[11]), .Y (dut_u_wr_n_3038));
  NOR4X1 dut_u_wr_g2996(.A (dut_u_wr_b_timer[13]), .B
       (dut_u_wr_b_timer[12]), .C (dut_u_wr_b_timer[14]), .D
       (dut_u_wr_b_timer[15]), .Y (dut_u_wr_n_3039));
  NOR4X1 dut_u_wr_g2997(.A (dut_u_wr_w_timer[13]), .B
       (dut_u_wr_w_timer[12]), .C (dut_u_wr_w_timer[14]), .D
       (dut_u_wr_w_timer[15]), .Y (dut_u_wr_n_3040));
  NOR4X1 dut_u_wr_g2998(.A (dut_u_wr_w_timer[4]), .B
       (dut_u_wr_w_timer[5]), .C (dut_u_wr_w_timer[10]), .D
       (dut_u_wr_w_timer[11]), .Y (dut_u_wr_n_3041));
  OR4X1 dut_u_wr_g2999(.A (dut_u_wr_w_timer[1]), .B
       (dut_u_wr_w_timer[0]), .C (dut_u_wr_w_timer[7]), .D
       (dut_u_wr_w_timer[6]), .Y (dut_u_wr_n_3042));
  OR4X1 dut_u_wr_g3000(.A (dut_u_wr_drain_cnt[1]), .B
       (dut_u_wr_drain_cnt[0]), .C (dut_u_wr_drain_cnt[3]), .D
       (dut_u_wr_drain_cnt[4]), .Y (dut_u_wr_n_3043));
  NOR4X1 dut_u_wr_g3001(.A (dut_u_wr_b_timer[0]), .B
       (dut_u_wr_b_timer[1]), .C (dut_u_wr_b_timer[7]), .D
       (dut_u_wr_b_timer[6]), .Y (dut_u_wr_n_3044));
  NOR4X1 dut_u_wr_g3002(.A (dut_u_wr_outst_cnt[1]), .B
       (dut_u_wr_outst_cnt[2]), .C (dut_u_wr_outst_cnt[3]), .D
       (dut_u_wr_outst_cnt[0]), .Y (dut_u_wr_n_3037));
  NAND2BX1 dut_u_wr_g3003(.AN (s_wvalid), .B (dut_u_wr_wpair_state[0]),
       .Y (dut_u_wr_n_3046));
  INVX1 dut_u_wr_g3005(.A (dut_u_wr_n_3049), .Y (dut_u_wr_n_452));
  NAND2BX1 dut_u_wr_g3006(.AN (dut_u_wr_w_timer[9]), .B
       (dut_u_wr_w_timer[8]), .Y (dut_u_wr_n_3051));
  NAND2BX1 dut_u_wr_g3008(.AN (dut_u_wr_wr_state[1]), .B
       (dut_u_wr_wr_state[0]), .Y (dut_u_wr_n_3049));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][0] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [0]), .SI (\m_aw[addr] [0]), .SE (dut_u_wr_n_4357),
       .Q (\m_aw[addr] [0]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][1] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [1]), .SI (\m_aw[addr] [1]), .SE (dut_u_wr_n_4357),
       .Q (\m_aw[addr] [1]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][2] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [2]), .SI (\m_aw[addr] [2]), .SE (dut_u_wr_n_4357),
       .Q (\m_aw[addr] [2]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][3] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [3]), .SI (\m_aw[addr] [3]), .SE (dut_u_wr_n_4357),
       .Q (\m_aw[addr] [3]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][4] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [4]), .SI (\m_aw[addr] [4]), .SE (dut_u_wr_n_4357),
       .Q (\m_aw[addr] [4]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][5] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [5]), .SI (\m_aw[addr] [5]), .SE (dut_u_wr_n_4357),
       .Q (\m_aw[addr] [5]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][6] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [6]), .SI (\m_aw[addr] [6]), .SE (dut_u_wr_n_4357),
       .Q (\m_aw[addr] [6]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][7] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [7]), .SI (\m_aw[addr] [7]), .SE (dut_u_wr_n_4357),
       .Q (\m_aw[addr] [7]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][8] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [8]), .SI (\m_aw[addr] [8]), .SE (dut_u_wr_n_4357),
       .Q (\m_aw[addr] [8]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][9] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [9]), .SI (\m_aw[addr] [9]), .SE (dut_u_wr_n_4357),
       .Q (\m_aw[addr] [9]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][10] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [10]), .SI (\m_aw[addr] [10]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [10]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][11] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [11]), .SI (\m_aw[addr] [11]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [11]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][12] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [12]), .SI (\m_aw[addr] [12]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [12]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][13] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [13]), .SI (\m_aw[addr] [13]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [13]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][14] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [14]), .SI (\m_aw[addr] [14]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [14]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][15] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [15]), .SI (\m_aw[addr] [15]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [15]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][16] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [16]), .SI (\m_aw[addr] [16]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [16]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][17] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [17]), .SI (\m_aw[addr] [17]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [17]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][18] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [18]), .SI (\m_aw[addr] [18]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [18]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][19] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [19]), .SI (\m_aw[addr] [19]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [19]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][20] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [20]), .SI (\m_aw[addr] [20]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [20]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][21] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [21]), .SI (\m_aw[addr] [21]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [21]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][22] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [22]), .SI (\m_aw[addr] [22]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [22]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][23] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [23]), .SI (\m_aw[addr] [23]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [23]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][24] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [24]), .SI (\m_aw[addr] [24]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [24]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][25] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [25]), .SI (\m_aw[addr] [25]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [25]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][26] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [26]), .SI (\m_aw[addr] [26]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [26]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][27] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [27]), .SI (\m_aw[addr] [27]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [27]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][28] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [28]), .SI (\m_aw[addr] [28]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [28]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][29] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [29]), .SI (\m_aw[addr] [29]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [29]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][30] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [30]), .SI (\m_aw[addr] [30]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [30]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][31] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [31]), .SI (\m_aw[addr] [31]), .SE
       (dut_u_wr_n_4357), .Q (\m_aw[addr] [31]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[prot][0] (.RN (rst_n), .CK (clk), .D
       (\s_aw[prot] [0]), .SI (\m_aw[prot] [0]), .SE (dut_u_wr_n_4357),
       .Q (\m_aw[prot] [0]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[prot][1] (.RN (rst_n), .CK (clk), .D
       (\s_aw[prot] [1]), .SI (\m_aw[prot] [1]), .SE (dut_u_wr_n_4357),
       .Q (\m_aw[prot] [1]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[prot][2] (.RN (rst_n), .CK (clk), .D
       (\s_aw[prot] [2]), .SI (\m_aw[prot] [2]), .SE (dut_u_wr_n_4357),
       .Q (\m_aw[prot] [2]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4228), .Q (dut_u_wr_b_timer[0]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4205), .Q (dut_u_wr_b_timer[1]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4128), .Q (dut_u_wr_b_timer[2]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4099), .Q (dut_u_wr_b_timer[3]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4079), .Q (dut_u_wr_b_timer[4]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[5] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4064), .Q (dut_u_wr_b_timer[5]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[6] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4050), .Q (dut_u_wr_b_timer[6]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[7] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4036), .Q (dut_u_wr_b_timer[7]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[8] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4022), .Q (dut_u_wr_b_timer[8]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[9] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4008), .Q (dut_u_wr_b_timer[9]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[10] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3994), .Q (dut_u_wr_b_timer[10]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[11] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3980), .Q (dut_u_wr_b_timer[11]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[12] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3966), .Q (dut_u_wr_b_timer[12]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[13] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3952), .Q (dut_u_wr_b_timer[13]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[14] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3936), .Q (dut_u_wr_b_timer[14]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[15] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3931), .Q (dut_u_wr_b_timer[15]));
  DFFRHQX1 dut_u_wr_downstream_aw_done_reg(.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4323), .Q (dut_u_wr_downstream_aw_done));
  DFFRHQX1 dut_u_wr_downstream_w_done_reg(.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4326), .Q (dut_u_wr_downstream_w_done));
  SDFFRHQX1 \dut_u_wr_drain_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4214), .SI (dut_u_wr_n_4224), .SE
       (dut_u_wr_drain_cnt[0]), .Q (dut_u_wr_drain_cnt[0]));
  DFFRHQX1 \dut_u_wr_drain_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4158), .Q (dut_u_wr_drain_cnt[1]));
  SDFFRHQX1 \dut_u_wr_drain_cnt_reg[5] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4148), .SI (dut_u_wr_n_4136), .SE
       (dut_u_wr_drain_cnt[5]), .Q (dut_u_wr_drain_cnt[5]));
  DFFRHQX1 \dut_u_wr_drain_cnt_reg[6] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4103), .Q (dut_u_wr_drain_cnt[6]));
  DFFRHQX1 \dut_u_wr_outst_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4152), .Q (dut_u_wr_outst_cnt[0]));
  DFFRHQX1 \dut_u_wr_outst_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4150), .Q (dut_u_wr_outst_cnt[1]));
  DFFRHQX1 \dut_u_wr_outst_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4107), .Q (dut_u_wr_outst_cnt[2]));
  DFFRHQX1 \dut_u_wr_outst_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4131), .Q (dut_u_wr_outst_cnt[3]));
  DFFRHQX1 \dut_u_wr_outst_cnt_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4105), .Q (dut_u_wr_outst_cnt[4]));
  DFFRHQX1 \dut_u_wr_outst_cnt_reg[5] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4129), .Q (dut_u_wr_outst_cnt[5]));
  DFFRHQX1 \dut_u_wr_outst_cnt_reg[6] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4115), .Q (dut_u_wr_outst_cnt[6]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4325), .Q (dut_u_wr_w_timer[0]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4204), .Q (dut_u_wr_w_timer[1]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4139), .Q (dut_u_wr_w_timer[2]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4102), .Q (dut_u_wr_w_timer[3]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4080), .Q (dut_u_wr_w_timer[4]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[5] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4065), .Q (dut_u_wr_w_timer[5]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[6] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4051), .Q (dut_u_wr_w_timer[6]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[7] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4037), .Q (dut_u_wr_w_timer[7]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[8] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4023), .Q (dut_u_wr_w_timer[8]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[9] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4009), .Q (dut_u_wr_w_timer[9]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[10] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3995), .Q (dut_u_wr_w_timer[10]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[11] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3981), .Q (dut_u_wr_w_timer[11]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[12] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3967), .Q (dut_u_wr_w_timer[12]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[13] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3953), .Q (dut_u_wr_w_timer[13]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[14] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3938), .Q (dut_u_wr_w_timer[14]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[15] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3930), .Q (dut_u_wr_w_timer[15]));
  DFFRHQX1 \dut_u_wr_wpair_state_reg[0] (.RN (rst_n), .CK (clk), .D
       (n_223), .Q (dut_u_wr_wpair_state[0]));
  DFFRHQX1 \dut_u_wr_wr_state_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4071), .Q (dut_u_wr_wr_state[0]));
  DFFRHQX1 \dut_u_wr_wr_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4196), .Q (dut_u_wr_wr_state[1]));
  NOR2XL dut_u_wr_g6111(.A (dut_u_wr_n_3932), .B (dut_u_wr_n_4343), .Y
       (dut_u_wr_n_3930));
  NOR2XL dut_u_wr_g6112(.A (dut_u_wr_n_3934), .B (dut_u_wr_n_4272), .Y
       (dut_u_wr_n_3931));
  AOI22X1 dut_u_wr_g6115(.A0 (dut_u_wr_w_timer_run), .A1
       (dut_u_wr_n_3940), .B0 (dut_u_wr_n_4467), .B1
       (dut_u_wr_w_timer[15]), .Y (dut_u_wr_n_3932));
  AOI22X1 dut_u_wr_g6116(.A0 (dut_u_wr_b_timer_run), .A1
       (dut_u_wr_n_3941), .B0 (dut_u_wr_n_4432), .B1
       (dut_u_wr_b_timer[15]), .Y (dut_u_wr_n_3934));
  AOI21XL dut_u_wr_g6117(.A0 (dut_u_wr_n_4363), .A1 (dut_u_wr_n_3946),
       .B0 (dut_u_wr_n_4272), .Y (dut_u_wr_n_3936));
  AOI21XL dut_u_wr_g6118(.A0 (dut_u_wr_n_4386), .A1 (dut_u_wr_n_3942),
       .B0 (dut_u_wr_n_4343), .Y (dut_u_wr_n_3938));
  XNOR2X1 dut_u_wr_g6119(.A (dut_u_wr_w_timer[15]), .B
       (dut_u_wr_n_3954), .Y (dut_u_wr_n_3940));
  XNOR2X1 dut_u_wr_g6120(.A (dut_u_wr_b_timer[15]), .B
       (dut_u_wr_n_3956), .Y (dut_u_wr_n_3941));
  OAI211X1 dut_u_wr_g6123(.A0 (dut_u_wr_w_timer[14]), .A1
       (dut_u_wr_n_3964), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3954), .Y (dut_u_wr_n_3942));
  OAI211X1 dut_u_wr_g6124(.A0 (dut_u_wr_b_timer[14]), .A1
       (dut_u_wr_n_3962), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_3956), .Y (dut_u_wr_n_3946));
  AOI21XL dut_u_wr_g6125(.A0 (dut_u_wr_n_4361), .A1 (dut_u_wr_n_3959),
       .B0 (dut_u_wr_n_4272), .Y (dut_u_wr_n_3952));
  AOI21XL dut_u_wr_g6126(.A0 (dut_u_wr_n_4372), .A1 (dut_u_wr_n_3957),
       .B0 (dut_u_wr_n_4343), .Y (dut_u_wr_n_3953));
  NAND2X1 dut_u_wr_g6127(.A (dut_u_wr_w_timer[14]), .B
       (dut_u_wr_n_3964), .Y (dut_u_wr_n_3954));
  OAI211X1 dut_u_wr_g6130(.A0 (dut_u_wr_w_timer[13]), .A1
       (dut_u_wr_n_3976), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3968), .Y (dut_u_wr_n_3957));
  OAI211X1 dut_u_wr_g6131(.A0 (dut_u_wr_b_timer[13]), .A1
       (dut_u_wr_n_3978), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_3970), .Y (dut_u_wr_n_3959));
  NAND2X1 dut_u_wr_g6132(.A (dut_u_wr_b_timer[14]), .B
       (dut_u_wr_n_3962), .Y (dut_u_wr_n_3956));
  INVX1 dut_u_wr_g6133(.A (dut_u_wr_n_3970), .Y (dut_u_wr_n_3962));
  INVX1 dut_u_wr_g6134(.A (dut_u_wr_n_3968), .Y (dut_u_wr_n_3964));
  AOI21XL dut_u_wr_g6135(.A0 (dut_u_wr_n_4392), .A1 (dut_u_wr_n_3973),
       .B0 (dut_u_wr_n_4272), .Y (dut_u_wr_n_3966));
  AOI21XL dut_u_wr_g6136(.A0 (dut_u_wr_n_4391), .A1 (dut_u_wr_n_3971),
       .B0 (dut_u_wr_n_4343), .Y (dut_u_wr_n_3967));
  NAND2X1 dut_u_wr_g6137(.A (dut_u_wr_w_timer[13]), .B
       (dut_u_wr_n_3976), .Y (dut_u_wr_n_3968));
  OAI211X1 dut_u_wr_g6140(.A0 (dut_u_wr_w_timer[12]), .A1
       (dut_u_wr_n_3990), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3982), .Y (dut_u_wr_n_3971));
  OAI211X1 dut_u_wr_g6141(.A0 (dut_u_wr_b_timer[12]), .A1
       (dut_u_wr_n_3992), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_3984), .Y (dut_u_wr_n_3973));
  NAND2X1 dut_u_wr_g6142(.A (dut_u_wr_b_timer[13]), .B
       (dut_u_wr_n_3978), .Y (dut_u_wr_n_3970));
  INVX1 dut_u_wr_g6143(.A (dut_u_wr_n_3982), .Y (dut_u_wr_n_3976));
  INVX1 dut_u_wr_g6144(.A (dut_u_wr_n_3984), .Y (dut_u_wr_n_3978));
  AOI21XL dut_u_wr_g6145(.A0 (dut_u_wr_n_4398), .A1 (dut_u_wr_n_3987),
       .B0 (dut_u_wr_n_4272), .Y (dut_u_wr_n_3980));
  AOI21XL dut_u_wr_g6146(.A0 (dut_u_wr_n_4371), .A1 (dut_u_wr_n_3985),
       .B0 (dut_u_wr_n_4343), .Y (dut_u_wr_n_3981));
  NAND2X1 dut_u_wr_g6147(.A (dut_u_wr_w_timer[12]), .B
       (dut_u_wr_n_3990), .Y (dut_u_wr_n_3982));
  OAI211X1 dut_u_wr_g6150(.A0 (dut_u_wr_w_timer[11]), .A1
       (dut_u_wr_n_4006), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3996), .Y (dut_u_wr_n_3985));
  OAI211X1 dut_u_wr_g6151(.A0 (dut_u_wr_b_timer[11]), .A1
       (dut_u_wr_n_4004), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_3998), .Y (dut_u_wr_n_3987));
  NAND2X1 dut_u_wr_g6152(.A (dut_u_wr_b_timer[12]), .B
       (dut_u_wr_n_3992), .Y (dut_u_wr_n_3984));
  INVX1 dut_u_wr_g6153(.A (dut_u_wr_n_3996), .Y (dut_u_wr_n_3990));
  INVX1 dut_u_wr_g6154(.A (dut_u_wr_n_3998), .Y (dut_u_wr_n_3992));
  AOI21XL dut_u_wr_g6155(.A0 (dut_u_wr_n_4389), .A1 (dut_u_wr_n_4001),
       .B0 (dut_u_wr_n_4272), .Y (dut_u_wr_n_3994));
  AOI21XL dut_u_wr_g6156(.A0 (dut_u_wr_n_4388), .A1 (dut_u_wr_n_3999),
       .B0 (dut_u_wr_n_4343), .Y (dut_u_wr_n_3995));
  NAND2X1 dut_u_wr_g6157(.A (dut_u_wr_w_timer[11]), .B
       (dut_u_wr_n_4006), .Y (dut_u_wr_n_3996));
  OAI211X1 dut_u_wr_g6160(.A0 (dut_u_wr_w_timer[10]), .A1
       (dut_u_wr_n_4020), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_4010), .Y (dut_u_wr_n_3999));
  OAI211X1 dut_u_wr_g6161(.A0 (dut_u_wr_b_timer[10]), .A1
       (dut_u_wr_n_4018), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_4012), .Y (dut_u_wr_n_4001));
  NAND2X1 dut_u_wr_g6162(.A (dut_u_wr_b_timer[11]), .B
       (dut_u_wr_n_4004), .Y (dut_u_wr_n_3998));
  INVX1 dut_u_wr_g6163(.A (dut_u_wr_n_4012), .Y (dut_u_wr_n_4004));
  INVX1 dut_u_wr_g6164(.A (dut_u_wr_n_4010), .Y (dut_u_wr_n_4006));
  AOI21XL dut_u_wr_g6165(.A0 (dut_u_wr_n_4359), .A1 (dut_u_wr_n_4015),
       .B0 (dut_u_wr_n_4272), .Y (dut_u_wr_n_4008));
  AOI21XL dut_u_wr_g6166(.A0 (dut_u_wr_n_4387), .A1 (dut_u_wr_n_4013),
       .B0 (dut_u_wr_n_4343), .Y (dut_u_wr_n_4009));
  NAND2X1 dut_u_wr_g6167(.A (dut_u_wr_w_timer[10]), .B
       (dut_u_wr_n_4020), .Y (dut_u_wr_n_4010));
  OAI211X1 dut_u_wr_g6170(.A0 (dut_u_wr_w_timer[9]), .A1
       (dut_u_wr_n_4034), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_4024), .Y (dut_u_wr_n_4013));
  OAI211X1 dut_u_wr_g6171(.A0 (dut_u_wr_b_timer[9]), .A1
       (dut_u_wr_n_4032), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_4026), .Y (dut_u_wr_n_4015));
  NAND2X1 dut_u_wr_g6172(.A (dut_u_wr_b_timer[10]), .B
       (dut_u_wr_n_4018), .Y (dut_u_wr_n_4012));
  INVX1 dut_u_wr_g6173(.A (dut_u_wr_n_4026), .Y (dut_u_wr_n_4018));
  INVX1 dut_u_wr_g6174(.A (dut_u_wr_n_4024), .Y (dut_u_wr_n_4020));
  AOI21XL dut_u_wr_g6175(.A0 (dut_u_wr_n_4396), .A1 (dut_u_wr_n_4029),
       .B0 (dut_u_wr_n_4272), .Y (dut_u_wr_n_4022));
  AOI21XL dut_u_wr_g6176(.A0 (dut_u_wr_n_4358), .A1 (dut_u_wr_n_4027),
       .B0 (dut_u_wr_n_4343), .Y (dut_u_wr_n_4023));
  NAND2X1 dut_u_wr_g6177(.A (dut_u_wr_w_timer[9]), .B
       (dut_u_wr_n_4034), .Y (dut_u_wr_n_4024));
  OAI211X1 dut_u_wr_g6180(.A0 (dut_u_wr_w_timer[8]), .A1
       (dut_u_wr_n_4048), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_4038), .Y (dut_u_wr_n_4027));
  OAI211X1 dut_u_wr_g6181(.A0 (dut_u_wr_b_timer[8]), .A1
       (dut_u_wr_n_4046), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_4040), .Y (dut_u_wr_n_4029));
  NAND2X1 dut_u_wr_g6182(.A (dut_u_wr_b_timer[9]), .B
       (dut_u_wr_n_4032), .Y (dut_u_wr_n_4026));
  INVX1 dut_u_wr_g6183(.A (dut_u_wr_n_4040), .Y (dut_u_wr_n_4032));
  INVX1 dut_u_wr_g6184(.A (dut_u_wr_n_4038), .Y (dut_u_wr_n_4034));
  AOI21XL dut_u_wr_g6185(.A0 (dut_u_wr_n_4375), .A1 (dut_u_wr_n_4043),
       .B0 (dut_u_wr_n_4272), .Y (dut_u_wr_n_4036));
  AOI21XL dut_u_wr_g6186(.A0 (dut_u_wr_n_4373), .A1 (dut_u_wr_n_4041),
       .B0 (dut_u_wr_n_4343), .Y (dut_u_wr_n_4037));
  NAND2X1 dut_u_wr_g6187(.A (dut_u_wr_w_timer[8]), .B
       (dut_u_wr_n_4048), .Y (dut_u_wr_n_4038));
  OAI211X1 dut_u_wr_g6190(.A0 (dut_u_wr_w_timer[7]), .A1
       (dut_u_wr_n_4060), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_4054), .Y (dut_u_wr_n_4041));
  OAI211X1 dut_u_wr_g6191(.A0 (dut_u_wr_b_timer[7]), .A1
       (dut_u_wr_n_4062), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_4052), .Y (dut_u_wr_n_4043));
  NAND2X1 dut_u_wr_g6192(.A (dut_u_wr_b_timer[8]), .B
       (dut_u_wr_n_4046), .Y (dut_u_wr_n_4040));
  INVX1 dut_u_wr_g6193(.A (dut_u_wr_n_4052), .Y (dut_u_wr_n_4046));
  INVX1 dut_u_wr_g6194(.A (dut_u_wr_n_4054), .Y (dut_u_wr_n_4048));
  AOI21X1 dut_u_wr_g6195(.A0 (dut_u_wr_n_4390), .A1 (dut_u_wr_n_4057),
       .B0 (dut_u_wr_n_4272), .Y (dut_u_wr_n_4050));
  AOI21XL dut_u_wr_g6196(.A0 (dut_u_wr_n_4368), .A1 (dut_u_wr_n_4055),
       .B0 (dut_u_wr_n_4343), .Y (dut_u_wr_n_4051));
  NAND2X1 dut_u_wr_g6197(.A (dut_u_wr_b_timer[7]), .B
       (dut_u_wr_n_4062), .Y (dut_u_wr_n_4052));
  OAI211X1 dut_u_wr_g6200(.A0 (dut_u_wr_w_timer[6]), .A1
       (dut_u_wr_n_4075), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_4066), .Y (dut_u_wr_n_4055));
  OAI211X1 dut_u_wr_g6201(.A0 (dut_u_wr_b_timer[6]), .A1
       (dut_u_wr_n_4077), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_4068), .Y (dut_u_wr_n_4057));
  NAND2X1 dut_u_wr_g6202(.A (dut_u_wr_w_timer[7]), .B
       (dut_u_wr_n_4060), .Y (dut_u_wr_n_4054));
  INVX1 dut_u_wr_g6203(.A (dut_u_wr_n_4066), .Y (dut_u_wr_n_4060));
  INVX1 dut_u_wr_g6204(.A (dut_u_wr_n_4068), .Y (dut_u_wr_n_4062));
  AOI21X1 dut_u_wr_g6205(.A0 (dut_u_wr_n_4370), .A1 (dut_u_wr_n_4072),
       .B0 (dut_u_wr_n_4272), .Y (dut_u_wr_n_4064));
  AOI21XL dut_u_wr_g6206(.A0 (dut_u_wr_n_4365), .A1 (dut_u_wr_n_4069),
       .B0 (dut_u_wr_n_4343), .Y (dut_u_wr_n_4065));
  NAND2X1 dut_u_wr_g6208(.A (dut_u_wr_w_timer[6]), .B
       (dut_u_wr_n_4075), .Y (dut_u_wr_n_4066));
  OAI211X1 dut_u_wr_g6211(.A0 (dut_u_wr_w_timer[5]), .A1
       (dut_u_wr_n_4097), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_4085), .Y (dut_u_wr_n_4069));
  AOI2BB1XL dut_u_wr_g6212(.A0N (dut_u_wr_n_4081), .A1N
       (dut_u_wr_n_4082), .B0 (dut_epoch_clr), .Y (dut_u_wr_n_4071));
  OAI211X1 dut_u_wr_g6213(.A0 (dut_u_wr_b_timer[5]), .A1
       (dut_u_wr_n_4095), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_4087), .Y (dut_u_wr_n_4072));
  NAND2X1 dut_u_wr_g6214(.A (dut_u_wr_b_timer[6]), .B
       (dut_u_wr_n_4077), .Y (dut_u_wr_n_4068));
  INVX1 dut_u_wr_g6215(.A (dut_u_wr_n_4085), .Y (dut_u_wr_n_4075));
  INVX1 dut_u_wr_g6216(.A (dut_u_wr_n_4087), .Y (dut_u_wr_n_4077));
  AOI21X1 dut_u_wr_g6217(.A0 (dut_u_wr_n_4369), .A1 (dut_u_wr_n_4092),
       .B0 (dut_u_wr_n_4272), .Y (dut_u_wr_n_4079));
  AOI21XL dut_u_wr_g6218(.A0 (dut_u_wr_n_4364), .A1 (dut_u_wr_n_4088),
       .B0 (dut_u_wr_n_4343), .Y (dut_u_wr_n_4080));
  NOR4BX1 dut_u_wr_g6219(.AN (dut_u_wr_n_452), .B
       (dut_wr_timeout_pulse), .C (dut_flush), .D (dut_u_wr_n_4090), .Y
       (dut_u_wr_n_4081));
  OAI32X1 dut_u_wr_g6220(.A0 (dut_u_wr_wr_state[0]), .A1
       (dut_u_wr_wr_state[1]), .A2 (dut_u_wr_n_4385), .B0
       (dut_u_wr_n_4331), .B1 (dut_u_wr_n_4101), .Y (dut_u_wr_n_4082));
  NAND2X1 dut_u_wr_g6222(.A (dut_u_wr_w_timer[5]), .B
       (dut_u_wr_n_4097), .Y (dut_u_wr_n_4085));
  OAI211X1 dut_u_wr_g6225(.A0 (dut_u_wr_w_timer[4]), .A1
       (dut_u_wr_n_4124), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_4109), .Y (dut_u_wr_n_4088));
  NOR2BX1 dut_u_wr_g6226(.AN (dut_u_wr_n_4101), .B (dut_u_wr_n_4355),
       .Y (dut_u_wr_n_4090));
  OAI211X1 dut_u_wr_g6227(.A0 (dut_u_wr_b_timer[4]), .A1
       (dut_u_wr_n_4126), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_4110), .Y (dut_u_wr_n_4092));
  NAND2X1 dut_u_wr_g6228(.A (dut_u_wr_b_timer[5]), .B
       (dut_u_wr_n_4095), .Y (dut_u_wr_n_4087));
  INVX1 dut_u_wr_g6229(.A (dut_u_wr_n_4110), .Y (dut_u_wr_n_4095));
  INVX1 dut_u_wr_g6230(.A (dut_u_wr_n_4109), .Y (dut_u_wr_n_4097));
  AOI21X1 dut_u_wr_g6231(.A0 (dut_u_wr_n_4367), .A1 (dut_u_wr_n_4119),
       .B0 (dut_u_wr_n_4272), .Y (dut_u_wr_n_4099));
  AOI21XL dut_u_wr_g6233(.A0 (dut_u_wr_n_4397), .A1 (dut_u_wr_n_4113),
       .B0 (dut_u_wr_n_4343), .Y (dut_u_wr_n_4102));
  MXI2XL dut_u_wr_g6234(.A (n_222), .B (dut_u_wr_n_4117), .S0
       (dut_u_wr_drain_cnt[6]), .Y (dut_u_wr_n_4103));
  NOR4BX1 dut_u_wr_g6235(.AN (dut_u_wr_n_4133), .B (dut_u_wr_n_4156),
       .C (dut_u_wr_n_4134), .D (dut_u_wr_n_4111), .Y
       (dut_u_wr_n_4101));
  NOR2X1 dut_u_wr_g6240(.A (dut_epoch_clr), .B (dut_u_wr_n_4135), .Y
       (dut_u_wr_n_4105));
  NOR2X1 dut_u_wr_g6241(.A (dut_epoch_clr), .B (dut_u_wr_n_4133), .Y
       (dut_u_wr_n_4107));
  NAND4XL dut_u_wr_g6247(.A (dut_u_wr_n_4176), .B (dut_u_wr_n_4178), .C
       (dut_u_wr_n_4157), .D (dut_u_wr_n_4135), .Y (dut_u_wr_n_4111));
  OAI211X1 dut_u_wr_g6248(.A0 (dut_u_wr_w_timer[3]), .A1
       (dut_u_wr_n_4191), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_4168), .Y (dut_u_wr_n_4113));
  NOR2BX1 dut_u_wr_g6249(.AN (dut_u_wr_n_4134), .B (dut_epoch_clr), .Y
       (dut_u_wr_n_4115));
  AOI221X1 dut_u_wr_g6250(.A0 (dut_u_wr_n_4270), .A1 (dut_u_wr_n_4430),
       .B0 (dut_u_wr_n_4268), .B1 (dut_u_wr_drain_cnt[5]), .C0
       (dut_u_wr_n_4136), .Y (dut_u_wr_n_4117));
  OAI211X1 dut_u_wr_g6251(.A0 (dut_u_wr_b_timer[3]), .A1
       (dut_u_wr_n_4193), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_4167), .Y (dut_u_wr_n_4119));
  OAI211X1 dut_u_wr_g6252(.A0 (dut_u_wr_n_4464), .A1 (dut_u_wr_n_4155),
       .B0 (dut_u_wr_n_4170), .C0 (dut_u_wr_n_4169), .Y
       (dut_u_wr_n_4121));
  NAND2X1 dut_u_wr_g6253(.A (dut_u_wr_w_timer[4]), .B
       (dut_u_wr_n_4124), .Y (dut_u_wr_n_4109));
  NAND2X1 dut_u_wr_g6254(.A (dut_u_wr_b_timer[4]), .B
       (dut_u_wr_n_4126), .Y (dut_u_wr_n_4110));
  INVX1 dut_u_wr_g6255(.A (dut_u_wr_n_4168), .Y (dut_u_wr_n_4124));
  INVX1 dut_u_wr_g6256(.A (dut_u_wr_n_4167), .Y (dut_u_wr_n_4126));
  AOI21X1 dut_u_wr_g6257(.A0 (dut_u_wr_n_4362), .A1 (dut_u_wr_n_4185),
       .B0 (dut_u_wr_n_4272), .Y (dut_u_wr_n_4128));
  NOR2BX1 dut_u_wr_g6258(.AN (dut_u_wr_n_4156), .B (dut_epoch_clr), .Y
       (dut_u_wr_n_4129));
  NOR2X1 dut_u_wr_g6259(.A (dut_epoch_clr), .B (dut_u_wr_n_4157), .Y
       (dut_u_wr_n_4131));
  AOI21XL dut_u_wr_g6265(.A0 (dut_u_wr_n_4393), .A1 (dut_u_wr_n_4179),
       .B0 (dut_u_wr_n_4343), .Y (dut_u_wr_n_4139));
  OAI211X1 dut_u_wr_g6266(.A0 (dut_u_wr_n_4461), .A1 (dut_u_wr_n_4183),
       .B0 (dut_u_wr_n_4225), .C0 (dut_u_wr_n_4221), .Y
       (dut_u_wr_n_4140));
  AOI221X1 dut_u_wr_g6267(.A0 (dut_u_wr_n_4332), .A1 (dut_u_wr_n_4266),
       .B0 (dut_u_wr_outst_cnt[2]), .B1 (dut_u_wr_n_4181), .C0
       (dut_u_wr_n_4222), .Y (dut_u_wr_n_4133));
  XNOR2X1 dut_u_wr_g6268(.A (dut_u_wr_outst_cnt[6]), .B
       (dut_u_wr_n_4187), .Y (dut_u_wr_n_4134));
  AOI221X1 dut_u_wr_g6269(.A0 (dut_u_wr_n_4280), .A1 (dut_u_wr_n_4266),
       .B0 (dut_u_wr_outst_cnt[4]), .B1 (dut_u_wr_n_4172), .C0
       (dut_u_wr_n_4223), .Y (dut_u_wr_n_4135));
  OAI221X1 dut_u_wr_g6270(.A0 (dut_u_wr_n_4271), .A1
       (dut_u_wr_drain_cnt[4]), .B0 (dut_u_wr_n_4269), .B1
       (dut_u_wr_n_4464), .C0 (dut_u_wr_n_4155), .Y (dut_u_wr_n_4136));
  NAND2X1 dut_u_wr_g6271(.A (dut_u_wr_n_4177), .B (dut_u_wr_n_4169), .Y
       (dut_u_wr_n_4148));
  NOR2X1 dut_u_wr_g6272(.A (dut_epoch_clr), .B (dut_u_wr_n_4176), .Y
       (dut_u_wr_n_4150));
  NOR2X1 dut_u_wr_g6273(.A (dut_epoch_clr), .B (dut_u_wr_n_4178), .Y
       (dut_u_wr_n_4152));
  OAI211X1 dut_u_wr_g6275(.A0 (dut_u_wr_n_4269), .A1 (dut_u_wr_n_4339),
       .B0 (dut_u_wr_n_4212), .C0 (dut_u_wr_n_4197), .Y
       (dut_u_wr_n_4158));
  OAI221X1 dut_u_wr_g6276(.A0 (dut_u_wr_n_4428), .A1 (dut_u_wr_n_4203),
       .B0 (dut_u_wr_n_4271), .B1 (dut_u_wr_n_4287), .C0
       (dut_u_wr_n_4195), .Y (dut_u_wr_n_4160));
  AOI221X1 dut_u_wr_g6277(.A0 (dut_u_wr_n_4270), .A1 (dut_u_wr_n_4322),
       .B0 (dut_u_wr_n_4268), .B1 (dut_u_wr_drain_cnt[3]), .C0
       (dut_u_wr_n_4202), .Y (dut_u_wr_n_4155));
  XNOR2X1 dut_u_wr_g6278(.A (dut_u_wr_outst_cnt[5]), .B
       (dut_u_wr_n_4200), .Y (dut_u_wr_n_4156));
  XNOR2X1 dut_u_wr_g6279(.A (dut_u_wr_outst_cnt[3]), .B
       (dut_u_wr_n_4207), .Y (dut_u_wr_n_4157));
  NAND3BXL dut_u_wr_g6280(.AN (dut_u_wr_n_4322), .B (dut_u_wr_n_4270),
       .C (dut_u_wr_n_4464), .Y (dut_u_wr_n_4170));
  NAND2X1 dut_u_wr_g6281(.A (dut_u_wr_n_4206), .B (dut_u_wr_n_4210), .Y
       (dut_u_wr_n_4172));
  NAND2X1 dut_u_wr_g6283(.A (dut_u_wr_b_timer[3]), .B
       (dut_u_wr_n_4193), .Y (dut_u_wr_n_4167));
  NAND2X1 dut_u_wr_g6284(.A (dut_u_wr_w_timer[3]), .B
       (dut_u_wr_n_4191), .Y (dut_u_wr_n_4168));
  OR2XL dut_u_wr_g6285(.A (dut_u_wr_drain_cnt[4]), .B
       (dut_u_wr_n_4195), .Y (dut_u_wr_n_4169));
  OAI211X1 dut_u_wr_g6288(.A0 (dut_u_wr_w_timer[2]), .A1
       (dut_u_wr_n_4311), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_4263), .Y (dut_u_wr_n_4179));
  OAI211X1 dut_u_wr_g6289(.A0 (dut_u_wr_n_4380), .A1 (dut_u_wr_n_4264),
       .B0 (dut_u_wr_n_4215), .C0 (dut_u_wr_n_4210), .Y
       (dut_u_wr_n_4181));
  AOI221X1 dut_u_wr_g6290(.A0 (dut_u_wr_n_4268), .A1 (dut_u_wr_n_4382),
       .B0 (dut_u_wr_n_4270), .B1 (dut_u_wr_n_4384), .C0
       (dut_u_wr_n_4224), .Y (dut_u_wr_n_4183));
  OAI211X1 dut_u_wr_g6291(.A0 (dut_u_wr_b_timer[2]), .A1
       (dut_u_wr_n_4313), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_4262), .Y (dut_u_wr_n_4185));
  MXI2XL dut_u_wr_g6292(.A (dut_u_wr_n_4223), .B (dut_u_wr_n_4220), .S0
       (dut_u_wr_outst_cnt[5]), .Y (dut_u_wr_n_4187));
  AOI221X1 dut_u_wr_g6293(.A0 (dut_u_wr_n_4329), .A1 (dut_u_wr_n_4266),
       .B0 (dut_u_wr_outst_cnt[1]), .B1 (dut_u_wr_n_4211), .C0
       (dut_u_wr_n_4216), .Y (dut_u_wr_n_4176));
  NAND3BXL dut_u_wr_g6294(.AN (dut_u_wr_n_4322), .B (dut_u_wr_n_4270),
       .C (dut_u_wr_drain_cnt[4]), .Y (dut_u_wr_n_4177));
  XNOR2X1 dut_u_wr_g6295(.A (dut_u_wr_outst_cnt[0]), .B
       (dut_u_wr_n_4210), .Y (dut_u_wr_n_4178));
  INVX1 dut_u_wr_g6296(.A (dut_u_wr_n_4263), .Y (dut_u_wr_n_4191));
  INVX1 dut_u_wr_g6297(.A (dut_u_wr_n_4262), .Y (dut_u_wr_n_4193));
  NOR2XL dut_u_wr_g6298(.A (dut_u_wr_n_4229), .B (dut_epoch_clr), .Y
       (dut_u_wr_n_4196));
  NAND2X1 dut_u_wr_g6299(.A (dut_u_wr_drain_cnt[1]), .B
       (dut_u_wr_n_4224), .Y (dut_u_wr_n_4197));
  OR2XL dut_u_wr_g6300(.A (dut_u_wr_drain_cnt[3]), .B
       (dut_u_wr_n_4221), .Y (dut_u_wr_n_4195));
  NOR2XL dut_u_wr_g6301(.A (dut_u_wr_n_4223), .B (dut_u_wr_n_4220), .Y
       (dut_u_wr_n_4200));
  INVX1 dut_u_wr_g6303(.A (dut_u_wr_n_4203), .Y (dut_u_wr_n_4202));
  AOI21XL dut_u_wr_g6304(.A0 (dut_u_wr_n_4374), .A1 (dut_u_wr_n_4284),
       .B0 (dut_u_wr_n_4343), .Y (dut_u_wr_n_4204));
  AOI21X1 dut_u_wr_g6305(.A0 (dut_u_wr_n_4376), .A1 (dut_u_wr_n_4281),
       .B0 (dut_u_wr_n_4272), .Y (dut_u_wr_n_4205));
  AOI22X1 dut_u_wr_g6306(.A0 (dut_u_wr_n_4317), .A1 (dut_u_wr_n_4266),
       .B0 (dut_u_wr_n_2458), .B1 (dut_u_wr_n_4265), .Y
       (dut_u_wr_n_4206));
  AOI21X1 dut_u_wr_g6307(.A0 (dut_u_wr_n_4268), .A1 (dut_u_wr_n_4341),
       .B0 (dut_u_wr_n_4224), .Y (dut_u_wr_n_4203));
  AO21XL dut_u_wr_g6308(.A0 (dut_u_wr_n_4340), .A1 (dut_u_wr_n_4266),
       .B0 (dut_u_wr_n_4222), .Y (dut_u_wr_n_4207));
  INVX1 dut_u_wr_g6309(.A (dut_u_wr_n_4211), .Y (dut_u_wr_n_4210));
  NAND2X1 dut_u_wr_g6310(.A (dut_u_wr_n_4270), .B (dut_u_wr_n_4339), .Y
       (dut_u_wr_n_4212));
  NAND2XL dut_u_wr_g6311(.A (dut_u_wr_n_4271), .B (dut_u_wr_n_4269), .Y
       (dut_u_wr_n_4214));
  NAND2XL dut_u_wr_g6312(.A (dut_u_wr_n_4383), .B (dut_u_wr_n_4266), .Y
       (dut_u_wr_n_4215));
  NOR2XL dut_u_wr_g6313(.A (dut_u_wr_n_4329), .B (dut_u_wr_n_4264), .Y
       (dut_u_wr_n_4216));
  NOR2X1 dut_u_wr_g6316(.A (dut_u_wr_n_4265), .B (dut_u_wr_n_4266), .Y
       (dut_u_wr_n_4211));
  NAND3BXL dut_u_wr_g6317(.AN (dut_u_wr_n_4384), .B (dut_u_wr_n_4270),
       .C (dut_u_wr_n_4461), .Y (dut_u_wr_n_4225));
  NOR2X1 dut_u_wr_g6318(.A (dut_u_wr_n_4352), .B (dut_u_wr_n_4272), .Y
       (dut_u_wr_n_4228));
  AOI221X1 dut_u_wr_g6319(.A0 (dut_u_wr_n_4331), .A1 (n_224), .B0
       (dut_flush), .B1 (dut_u_wr_n_452), .C0 (dut_wr_timeout_pulse),
       .Y (dut_u_wr_n_4229));
  NOR3BX1 dut_u_wr_g6320(.AN (dut_u_wr_outst_cnt[4]), .B
       (dut_u_wr_n_4317), .C (dut_u_wr_n_4267), .Y (dut_u_wr_n_4220));
  NAND2BX1 dut_u_wr_g6321(.AN (dut_u_wr_n_4341), .B (dut_u_wr_n_4268),
       .Y (dut_u_wr_n_4221));
  NOR3BXL dut_u_wr_g6322(.AN (dut_u_wr_n_4380), .B
       (dut_u_wr_outst_cnt[2]), .C (dut_u_wr_n_4264), .Y
       (dut_u_wr_n_4222));
  NOR3X1 dut_u_wr_g6323(.A (dut_u_wr_outst_cnt[4]), .B
       (dut_u_wr_n_2458), .C (dut_u_wr_n_4264), .Y (dut_u_wr_n_4223));
  NOR3X1 dut_u_wr_g6324(.A (dut_u_wr_n_4315), .B (dut_u_wr_n_4316), .C
       (dut_epoch_clr), .Y (dut_u_wr_n_4224));
  INVX1 dut_u_wr_g6350(.A (dut_u_wr_n_4264), .Y (dut_u_wr_n_4265));
  INVX1 dut_u_wr_g6351(.A (dut_u_wr_n_4266), .Y (dut_u_wr_n_4267));
  INVX1 dut_u_wr_g6352(.A (dut_u_wr_n_4268), .Y (dut_u_wr_n_4269));
  INVX1 dut_u_wr_g6353(.A (dut_u_wr_n_4270), .Y (dut_u_wr_n_4271));
  NOR2XL dut_u_wr_g6354(.A (dut_u_wr_outst_cnt[4]), .B
       (dut_u_wr_n_4317), .Y (dut_u_wr_n_4280));
  OAI211X1 dut_u_wr_g6355(.A0 (dut_u_wr_b_timer[0]), .A1
       (dut_u_wr_b_timer[1]), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_4381), .Y (dut_u_wr_n_4281));
  OAI211X1 dut_u_wr_g6356(.A0 (dut_u_wr_w_timer[0]), .A1
       (dut_u_wr_w_timer[1]), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_4356), .Y (dut_u_wr_n_4284));
  MXI2XL dut_u_wr_g6357(.A (dut_u_wr_drain_cnt[3]), .B
       (dut_u_wr_n_4428), .S0 (dut_u_wr_n_4330), .Y (dut_u_wr_n_4287));
  OAI32X1 dut_u_wr_g6358(.A0 (dut_u_wr_wpair_state[0]), .A1
       (dut_u_wr_n_3048), .A2 (dut_epoch_clr), .B0 (dut_u_wr_n_4335),
       .B1 (dut_u_wr_n_4342), .Y (dut_u_wr_n_4289));
  NAND2X1 dut_u_wr_g6372(.A (dut_u_wr_b_timer[2]), .B
       (dut_u_wr_n_4313), .Y (dut_u_wr_n_4262));
  NAND2X1 dut_u_wr_g6373(.A (dut_u_wr_w_timer[2]), .B
       (dut_u_wr_n_4311), .Y (dut_u_wr_n_4263));
  NAND2X1 dut_u_wr_g6375(.A (dut_u_wr_n_4318), .B (dut_u_wr_n_4385), .Y
       (dut_u_wr_n_4264));
  NOR2X1 dut_u_wr_g6376(.A (dut_u_wr_n_4318), .B (dut_u_wr_n_4385), .Y
       (dut_u_wr_n_4266));
  NOR2BX1 dut_u_wr_g6377(.AN (dut_u_wr_n_4315), .B (dut_epoch_clr), .Y
       (dut_u_wr_n_4268));
  NOR2BX1 dut_u_wr_g6378(.AN (dut_u_wr_n_4316), .B (dut_epoch_clr), .Y
       (dut_u_wr_n_4270));
  OR3X1 dut_u_wr_g6379(.A (dut_wr_timeout_pulse), .B (dut_u_wr_n_4318),
       .C (dut_epoch_clr), .Y (dut_u_wr_n_4272));
  INVX1 dut_u_wr_g6380(.A (dut_u_wr_n_4356), .Y (dut_u_wr_n_4311));
  INVX1 dut_u_wr_g6381(.A (dut_u_wr_n_4381), .Y (dut_u_wr_n_4313));
  NOR2BX1 dut_u_wr_g6382(.AN (dut_u_wr_n_4331), .B (dut_u_wr_n_4377),
       .Y (dut_u_wr_n_4315));
  NOR2BX1 dut_u_wr_g6383(.AN (dut_u_wr_n_4377), .B (dut_u_wr_n_4331),
       .Y (dut_u_wr_n_4316));
  NAND2X1 dut_u_wr_g6384(.A (dut_u_wr_outst_cnt[3]), .B
       (dut_u_wr_n_4340), .Y (dut_u_wr_n_4317));
  NAND2X1 dut_u_wr_g6385(.A (dut_u_wr_n_4331), .B (dut_u_wr_n_4355), .Y
       (dut_u_wr_n_4318));
  AOI2BB1XL dut_u_wr_g6386(.A0N (dut_u_wr_downstream_aw_fire), .A1N
       (dut_u_wr_downstream_aw_done), .B0 (dut_u_wr_n_4342), .Y
       (dut_u_wr_n_4323));
  NOR2XL dut_u_wr_g6387(.A (dut_u_wr_n_4350), .B (dut_u_wr_n_4343), .Y
       (dut_u_wr_n_4325));
  AOI2BB1XL dut_u_wr_g6388(.A0N (dut_u_wr_downstream_w_fire), .A1N
       (dut_u_wr_downstream_w_done), .B0 (dut_u_wr_n_4342), .Y
       (dut_u_wr_n_4326));
  NAND2X1 dut_u_wr_g6389(.A (dut_u_wr_drain_cnt[3]), .B
       (dut_u_wr_n_4330), .Y (dut_u_wr_n_4322));
  NOR2X1 dut_u_wr_g6390(.A (dut_u_wr_outst_cnt[2]), .B
       (dut_u_wr_n_4383), .Y (dut_u_wr_n_4332));
  AND2X1 dut_u_wr_g6392(.A (dut_u_wr_n_4379), .B (dut_u_wr_n_3048), .Y
       (dut_u_wr_n_4335));
  NOR2BX1 dut_u_wr_g6393(.AN (dut_u_wr_n_4383), .B (dut_u_wr_n_4380),
       .Y (dut_u_wr_n_4329));
  NOR2X1 dut_u_wr_g6394(.A (dut_u_wr_n_4461), .B (dut_u_wr_n_4384), .Y
       (dut_u_wr_n_4330));
  NAND2X1 dut_u_wr_g6395(.A (s_bready), .B (n_224), .Y
       (dut_u_wr_n_4331));
  MXI2XL dut_u_wr_g6396(.A (dut_u_wr_w_timer_run), .B
       (dut_u_wr_n_4467), .S0 (dut_u_wr_w_timer[0]), .Y
       (dut_u_wr_n_4350));
  XNOR2X1 dut_u_wr_g6397(.A (dut_u_wr_b_timer_run), .B
       (dut_u_wr_b_timer[0]), .Y (dut_u_wr_n_4352));
  AND2X1 dut_u_wr_g6398(.A (dut_u_wr_n_4382), .B (dut_u_wr_n_4384), .Y
       (dut_u_wr_n_4339));
  NOR2BX1 dut_u_wr_g6399(.AN (dut_u_wr_outst_cnt[2]), .B
       (dut_u_wr_n_4383), .Y (dut_u_wr_n_4340));
  OR2XL dut_u_wr_g6400(.A (dut_u_wr_drain_cnt[2]), .B
       (dut_u_wr_n_4382), .Y (dut_u_wr_n_4341));
  NAND2X1 dut_u_wr_g6401(.A (dut_u_wr_n_4385), .B (dut_u_wr_w_perm), .Y
       (dut_u_wr_n_4342));
  NAND2X1 dut_u_wr_g6402(.A (dut_u_wr_n_4366), .B (dut_u_wr_n_4385), .Y
       (dut_u_wr_n_4343));
  NAND2X1 dut_u_wr_g6403(.A (dut_u_wr_n_4467), .B
       (dut_u_wr_w_timer[8]), .Y (dut_u_wr_n_4358));
  NAND2X1 dut_u_wr_g6404(.A (dut_u_wr_n_4432), .B
       (dut_u_wr_b_timer[9]), .Y (dut_u_wr_n_4359));
  NAND2X1 dut_u_wr_g6405(.A (dut_u_wr_n_4432), .B
       (dut_u_wr_b_timer[13]), .Y (dut_u_wr_n_4361));
  NAND2X1 dut_u_wr_g6406(.A (dut_u_wr_n_4432), .B
       (dut_u_wr_b_timer[2]), .Y (dut_u_wr_n_4362));
  NAND2X1 dut_u_wr_g6407(.A (dut_u_wr_n_4432), .B
       (dut_u_wr_b_timer[14]), .Y (dut_u_wr_n_4363));
  NAND2X1 dut_u_wr_g6408(.A (dut_u_wr_n_4467), .B
       (dut_u_wr_w_timer[4]), .Y (dut_u_wr_n_4364));
  NAND2X1 dut_u_wr_g6409(.A (dut_u_wr_n_4467), .B
       (dut_u_wr_w_timer[5]), .Y (dut_u_wr_n_4365));
  NOR2X1 dut_u_wr_g6410(.A (dut_wr_w_fault_pulse), .B (dut_epoch_clr),
       .Y (dut_u_wr_n_4366));
  NAND2X1 dut_u_wr_g6411(.A (dut_u_wr_n_4432), .B
       (dut_u_wr_b_timer[3]), .Y (dut_u_wr_n_4367));
  NAND2X1 dut_u_wr_g6412(.A (dut_u_wr_n_4467), .B
       (dut_u_wr_w_timer[6]), .Y (dut_u_wr_n_4368));
  NAND2X1 dut_u_wr_g6413(.A (dut_u_wr_n_4432), .B
       (dut_u_wr_b_timer[4]), .Y (dut_u_wr_n_4369));
  NAND2X1 dut_u_wr_g6414(.A (dut_u_wr_n_4432), .B
       (dut_u_wr_b_timer[5]), .Y (dut_u_wr_n_4370));
  NAND2X1 dut_u_wr_g6415(.A (dut_u_wr_n_4467), .B
       (dut_u_wr_w_timer[11]), .Y (dut_u_wr_n_4371));
  NAND2X1 dut_u_wr_g6416(.A (dut_u_wr_n_4467), .B
       (dut_u_wr_w_timer[13]), .Y (dut_u_wr_n_4372));
  NAND2X1 dut_u_wr_g6417(.A (dut_u_wr_n_4467), .B
       (dut_u_wr_w_timer[7]), .Y (dut_u_wr_n_4373));
  NAND2X1 dut_u_wr_g6418(.A (dut_u_wr_n_4467), .B
       (dut_u_wr_w_timer[1]), .Y (dut_u_wr_n_4374));
  NAND2X1 dut_u_wr_g6419(.A (dut_u_wr_n_4432), .B
       (dut_u_wr_b_timer[7]), .Y (dut_u_wr_n_4375));
  NAND2X1 dut_u_wr_g6420(.A (dut_u_wr_n_4432), .B
       (dut_u_wr_b_timer[1]), .Y (dut_u_wr_n_4376));
  NAND2X1 dut_u_wr_g6421(.A (dut_u_wr_n_455), .B (s_bvalid), .Y
       (dut_u_wr_n_4355));
  NAND2X1 dut_u_wr_g6422(.A (dut_u_wr_w_timer[1]), .B
       (dut_u_wr_w_timer[0]), .Y (dut_u_wr_n_4356));
  OR2X2 dut_u_wr_g6423(.A (dut_u_wr_n_2536), .B (dut_u_wr_n_4400), .Y
       (dut_u_wr_n_4357));
  NAND2X1 dut_u_wr_g6424(.A (dut_u_wr_n_4467), .B
       (dut_u_wr_w_timer[14]), .Y (dut_u_wr_n_4386));
  NAND2X1 dut_u_wr_g6425(.A (dut_u_wr_n_4467), .B
       (dut_u_wr_w_timer[9]), .Y (dut_u_wr_n_4387));
  NAND2X1 dut_u_wr_g6426(.A (dut_u_wr_n_4467), .B
       (dut_u_wr_w_timer[10]), .Y (dut_u_wr_n_4388));
  NAND2X1 dut_u_wr_g6427(.A (dut_u_wr_n_4432), .B
       (dut_u_wr_b_timer[10]), .Y (dut_u_wr_n_4389));
  NAND2X1 dut_u_wr_g6428(.A (dut_u_wr_n_4432), .B
       (dut_u_wr_b_timer[6]), .Y (dut_u_wr_n_4390));
  NAND2X1 dut_u_wr_g6429(.A (dut_u_wr_n_4467), .B
       (dut_u_wr_w_timer[12]), .Y (dut_u_wr_n_4391));
  NAND2X1 dut_u_wr_g6430(.A (dut_u_wr_n_4432), .B
       (dut_u_wr_b_timer[12]), .Y (dut_u_wr_n_4392));
  NAND2X1 dut_u_wr_g6431(.A (dut_u_wr_n_4467), .B
       (dut_u_wr_w_timer[2]), .Y (dut_u_wr_n_4393));
  NAND2X1 dut_u_wr_g6433(.A (dut_u_wr_n_4432), .B
       (dut_u_wr_b_timer[8]), .Y (dut_u_wr_n_4396));
  NAND2X1 dut_u_wr_g6434(.A (dut_u_wr_n_4467), .B
       (dut_u_wr_w_timer[3]), .Y (dut_u_wr_n_4397));
  NAND2X1 dut_u_wr_g6435(.A (dut_u_wr_n_4432), .B
       (dut_u_wr_b_timer[11]), .Y (dut_u_wr_n_4398));
  NAND2X1 dut_u_wr_g6436(.A (m_bvalid), .B (dut_u_wr_n_454), .Y
       (dut_u_wr_n_4377));
  NOR2X1 dut_u_wr_g6438(.A (dut_wr_w_fault_pulse), .B (dut_flush), .Y
       (dut_u_wr_n_4379));
  NOR2X1 dut_u_wr_g6439(.A (dut_u_wr_outst_cnt[1]), .B
       (dut_u_wr_outst_cnt[0]), .Y (dut_u_wr_n_4380));
  NAND2X1 dut_u_wr_g6440(.A (dut_u_wr_b_timer[1]), .B
       (dut_u_wr_b_timer[0]), .Y (dut_u_wr_n_4381));
  OR2XL dut_u_wr_g6441(.A (dut_u_wr_drain_cnt[1]), .B
       (dut_u_wr_drain_cnt[0]), .Y (dut_u_wr_n_4382));
  NAND2X1 dut_u_wr_g6442(.A (dut_u_wr_outst_cnt[1]), .B
       (dut_u_wr_outst_cnt[0]), .Y (dut_u_wr_n_4383));
  NAND2X1 dut_u_wr_g6443(.A (dut_u_wr_drain_cnt[1]), .B
       (dut_u_wr_drain_cnt[0]), .Y (dut_u_wr_n_4384));
  INVXL dut_u_wr_g6445(.A (s_awready), .Y (dut_u_wr_n_4400));
  INVX1 dut_u_wr_g6448(.A (dut_u_wr_drain_cnt[5]), .Y
       (dut_u_wr_n_4430));
  INVX1 dut_u_wr_g6449(.A (dut_u_wr_b_timer_run), .Y (dut_u_wr_n_4432));
  INVX1 dut_u_wr_g6452(.A (dut_u_wr_w_timer_run), .Y (dut_u_wr_n_4467));
  DFFRX1 \dut_u_wr_drain_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4140), .Q (dut_u_wr_drain_cnt[2]), .QN
       (dut_u_wr_n_4461));
  DFFRX1 \dut_u_wr_drain_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4160), .Q (dut_u_wr_drain_cnt[3]), .QN
       (dut_u_wr_n_4428));
  DFFRX1 \dut_u_wr_drain_cnt_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4121), .Q (dut_u_wr_drain_cnt[4]), .QN
       (dut_u_wr_n_4464));
  DFFRX1 \dut_u_wr_wpair_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_4289), .Q (dut_u_wr_wpair_state[1]), .QN
       (dut_u_wr_n_3048));
  INVX1 dut_u_rd_g1265(.A (dut_u_rd_n_336), .Y (dut_rd_upstream_empty));
  OR4X1 dut_u_rd_g1307(.A (dut_u_rd_outst_cnt[1]), .B
       (dut_u_rd_outst_cnt[0]), .C (dut_u_rd_outst_cnt[6]), .D
       (dut_u_rd_n_1538), .Y (dut_u_rd_n_336));
  OR4X1 dut_u_rd_g1308(.A (dut_u_rd_outst_cnt[2]), .B
       (dut_u_rd_outst_cnt[3]), .C (dut_u_rd_outst_cnt[4]), .D
       (dut_u_rd_outst_cnt[5]), .Y (dut_u_rd_n_1538));
  OR2XL dut_u_rd_g1309(.A (dut_u_rd_n_336), .B (dut_u_rd_n_323), .Y
       (dut_rd_busy));
  OR4X1 dut_u_rd_g1310(.A (dut_u_rd_drain_cnt[5]), .B
       (dut_u_rd_drain_cnt[6]), .C (dut_u_rd_drain_cnt[2]), .D
       (dut_u_rd_n_1541), .Y (dut_u_rd_n_323));
  OR4X1 dut_u_rd_g1311(.A (dut_u_rd_drain_cnt[3]), .B
       (dut_u_rd_drain_cnt[4]), .C (dut_u_rd_drain_cnt[1]), .D
       (dut_u_rd_drain_cnt[0]), .Y (dut_u_rd_n_1541));
  NOR2BX1 dut_u_rd_g2091(.AN (dut_u_rd_timer_run), .B
       (dut_u_rd_n_1949), .Y (dut_rd_timeout_pulse));
  NAND3BXL dut_u_rd_g2094(.AN (dut_flush), .B (s_arvalid), .C
       (dut_u_rd_n_1950), .Y (dut_u_rd_n_1945));
  NAND3BXL dut_u_rd_g2095(.AN (dut_flush), .B (m_arready), .C
       (dut_u_rd_n_1950), .Y (dut_u_rd_n_1946));
  NAND4XL dut_u_rd_g2096(.A (dut_u_rd_n_1997), .B (dut_u_rd_n_1996), .C
       (dut_u_rd_n_1995), .D (dut_u_rd_n_1994), .Y (dut_u_rd_n_1949));
  OR2X1 dut_u_rd_g2097(.A (dut_u_rd_n_324), .B (dut_u_rd_n_323), .Y
       (m_rready));
  OR4X1 dut_u_rd_g2098(.A (dut_u_rd_outst_cnt[4]), .B
       (dut_u_rd_outst_cnt[5]), .C (dut_u_rd_n_2006), .D
       (dut_u_rd_n_571), .Y (dut_u_rd_n_1950));
  AO21X1 dut_u_rd_g2099(.A0 (\m_r[resp] [1]), .A1 (dut_u_rd_n_321), .B0
       (dut_u_rd_n_1999), .Y (\s_r[resp] [1]));
  AO21X1 dut_u_rd_g2100(.A0 (dut_u_rd_n_2001), .A1 (dut_u_rd_n_321),
       .B0 (dut_u_rd_n_1999), .Y (s_rvalid));
  AND2X1 dut_u_rd_g2101(.A (dut_u_rd_n_321), .B (\m_r[data] [17]), .Y
       (\s_r[data] [17]));
  AND2X1 dut_u_rd_g2102(.A (dut_u_rd_n_321), .B (\m_r[data] [31]), .Y
       (\s_r[data] [31]));
  AND2X1 dut_u_rd_g2103(.A (dut_u_rd_n_321), .B (\m_r[resp] [0]), .Y
       (\s_r[resp] [0]));
  AND2X1 dut_u_rd_g2104(.A (dut_u_rd_n_321), .B (\m_r[data] [18]), .Y
       (\s_r[data] [18]));
  AND2X1 dut_u_rd_g2105(.A (dut_u_rd_n_321), .B (\m_r[data] [16]), .Y
       (\s_r[data] [16]));
  AND2X1 dut_u_rd_g2106(.A (dut_u_rd_n_321), .B (\m_r[data] [15]), .Y
       (\s_r[data] [15]));
  AND2X1 dut_u_rd_g2107(.A (dut_u_rd_n_321), .B (\m_r[data] [14]), .Y
       (\s_r[data] [14]));
  AND2X1 dut_u_rd_g2108(.A (dut_u_rd_n_321), .B (\m_r[data] [13]), .Y
       (\s_r[data] [13]));
  AND2X1 dut_u_rd_g2109(.A (dut_u_rd_n_321), .B (\m_r[data] [12]), .Y
       (\s_r[data] [12]));
  AND2X1 dut_u_rd_g2110(.A (dut_u_rd_n_321), .B (\m_r[data] [11]), .Y
       (\s_r[data] [11]));
  AND2X1 dut_u_rd_g2111(.A (dut_u_rd_n_321), .B (\m_r[data] [30]), .Y
       (\s_r[data] [30]));
  AND2X1 dut_u_rd_g2112(.A (dut_u_rd_n_321), .B (\m_r[data] [10]), .Y
       (\s_r[data] [10]));
  AND2X1 dut_u_rd_g2113(.A (dut_u_rd_n_321), .B (\m_r[data] [9]), .Y
       (\s_r[data] [9]));
  AND2X1 dut_u_rd_g2114(.A (dut_u_rd_n_321), .B (\m_r[data] [29]), .Y
       (\s_r[data] [29]));
  AND2X1 dut_u_rd_g2115(.A (dut_u_rd_n_321), .B (\m_r[data] [8]), .Y
       (\s_r[data] [8]));
  AND2X1 dut_u_rd_g2116(.A (dut_u_rd_n_321), .B (\m_r[data] [7]), .Y
       (\s_r[data] [7]));
  AND2X1 dut_u_rd_g2117(.A (dut_u_rd_n_321), .B (\m_r[data] [28]), .Y
       (\s_r[data] [28]));
  AND2X1 dut_u_rd_g2118(.A (dut_u_rd_n_321), .B (\m_r[data] [6]), .Y
       (\s_r[data] [6]));
  AND2X1 dut_u_rd_g2119(.A (dut_u_rd_n_321), .B (\m_r[data] [5]), .Y
       (\s_r[data] [5]));
  AND2X1 dut_u_rd_g2120(.A (dut_u_rd_n_321), .B (\m_r[data] [27]), .Y
       (\s_r[data] [27]));
  AND2X1 dut_u_rd_g2121(.A (dut_u_rd_n_321), .B (\m_r[data] [4]), .Y
       (\s_r[data] [4]));
  AND2X1 dut_u_rd_g2122(.A (dut_u_rd_n_321), .B (\m_r[data] [3]), .Y
       (\s_r[data] [3]));
  AND2X1 dut_u_rd_g2123(.A (dut_u_rd_n_321), .B (\m_r[data] [26]), .Y
       (\s_r[data] [26]));
  AND2X1 dut_u_rd_g2124(.A (dut_u_rd_n_321), .B (\m_r[data] [2]), .Y
       (\s_r[data] [2]));
  AND2X1 dut_u_rd_g2125(.A (dut_u_rd_n_321), .B (\m_r[data] [1]), .Y
       (\s_r[data] [1]));
  AND2X1 dut_u_rd_g2126(.A (dut_u_rd_n_321), .B (\m_r[data] [25]), .Y
       (\s_r[data] [25]));
  AND2X1 dut_u_rd_g2127(.A (dut_u_rd_n_321), .B (\m_r[data] [0]), .Y
       (\s_r[data] [0]));
  AND2X1 dut_u_rd_g2128(.A (dut_u_rd_n_321), .B (\m_r[data] [24]), .Y
       (\s_r[data] [24]));
  AND2X1 dut_u_rd_g2129(.A (dut_u_rd_n_321), .B (\m_r[data] [23]), .Y
       (\s_r[data] [23]));
  AND2X1 dut_u_rd_g2130(.A (dut_u_rd_n_321), .B (\m_r[data] [21]), .Y
       (\s_r[data] [21]));
  AND2X1 dut_u_rd_g2131(.A (dut_u_rd_n_321), .B (\m_r[data] [22]), .Y
       (\s_r[data] [22]));
  AND2X1 dut_u_rd_g2132(.A (dut_u_rd_n_321), .B (\m_r[data] [20]), .Y
       (\s_r[data] [20]));
  AND2X1 dut_u_rd_g2133(.A (dut_u_rd_n_321), .B (\m_r[data] [19]), .Y
       (\s_r[data] [19]));
  NOR4X1 dut_u_rd_g2134(.A (dut_u_rd_timer[13]), .B
       (dut_u_rd_timer[12]), .C (dut_u_rd_timer[14]), .D
       (dut_u_rd_timer[15]), .Y (dut_u_rd_n_1994));
  NOR4X1 dut_u_rd_g2135(.A (dut_u_rd_timer[0]), .B (dut_u_rd_timer[1]),
       .C (dut_u_rd_timer[7]), .D (dut_u_rd_timer[6]), .Y
       (dut_u_rd_n_1995));
  NOR4BX1 dut_u_rd_g2136(.AN (dut_u_rd_timer[8]), .B
       (dut_u_rd_timer[3]), .C (dut_u_rd_timer[9]), .D
       (dut_u_rd_timer[2]), .Y (dut_u_rd_n_1996));
  NOR4X1 dut_u_rd_g2137(.A (dut_u_rd_timer[4]), .B (dut_u_rd_timer[5]),
       .C (dut_u_rd_timer[10]), .D (dut_u_rd_timer[11]), .Y
       (dut_u_rd_n_1997));
  OR4X1 dut_u_rd_g2139(.A (dut_u_rd_outst_cnt[2]), .B
       (dut_u_rd_outst_cnt[0]), .C (dut_u_rd_outst_cnt[1]), .D
       (dut_u_rd_outst_cnt[3]), .Y (dut_u_rd_n_571));
  AND2XL dut_u_rd_g2140(.A (s_rready), .B (dut_u_rd_n_321), .Y
       (dut_u_rd_n_324));
  NOR2BX1 dut_u_rd_g2142(.AN (dut_u_rd_rd_state[1]), .B
       (dut_u_rd_rd_state[0]), .Y (dut_u_rd_n_1999));
  NOR2BX1 dut_u_rd_g2144(.AN (m_rvalid), .B (dut_u_rd_n_323), .Y
       (dut_u_rd_n_2001));
  AND2X1 dut_u_rd_g2145(.A (dut_u_rd_rd_state[0]), .B
       (dut_u_rd_n_2009), .Y (dut_u_rd_n_321));
  NOR2BX2 dut_u_rd_g2(.AN (dut_u_rd_n_321), .B (dut_u_rd_n_2001), .Y
       (dut_u_rd_timer_run));
  SDFFRHQX1 \dut_u_rd_drain_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3141), .SI (dut_u_rd_n_3137), .SE
       (dut_u_rd_drain_cnt[0]), .Q (dut_u_rd_drain_cnt[0]));
  DFFRHQX1 \dut_u_rd_drain_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3096), .Q (dut_u_rd_drain_cnt[1]));
  SDFFRHQX1 \dut_u_rd_drain_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3108), .SI (dut_u_rd_n_3071), .SE
       (dut_u_rd_drain_cnt[3]), .Q (dut_u_rd_drain_cnt[3]));
  SDFFRHQX1 \dut_u_rd_drain_cnt_reg[5] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3082), .SI (dut_u_rd_n_3036), .SE
       (dut_u_rd_drain_cnt[5]), .Q (dut_u_rd_drain_cnt[5]));
  SDFFRHQX1 \dut_u_rd_drain_cnt_reg[6] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3283), .SI (dut_u_rd_n_3027), .SE
       (dut_u_rd_drain_cnt[6]), .Q (dut_u_rd_drain_cnt[6]));
  DFFRHQX1 \dut_u_rd_outst_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3053), .Q (dut_u_rd_outst_cnt[1]));
  DFFRHQX1 \dut_u_rd_outst_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3037), .Q (dut_u_rd_outst_cnt[2]));
  DFFRHQX1 \dut_u_rd_outst_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3039), .Q (dut_u_rd_outst_cnt[3]));
  DFFRHQX1 \dut_u_rd_outst_cnt_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3030), .Q (dut_u_rd_outst_cnt[4]));
  DFFRHQX1 \dut_u_rd_outst_cnt_reg[5] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3041), .Q (dut_u_rd_outst_cnt[5]));
  DFFRHQX1 \dut_u_rd_rd_state_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3013), .Q (dut_u_rd_rd_state[0]));
  DFFRHQX1 \dut_u_rd_timer_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3139), .Q (dut_u_rd_timer[0]));
  DFFRHQX1 \dut_u_rd_timer_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3115), .Q (dut_u_rd_timer[1]));
  DFFRHQX1 \dut_u_rd_timer_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3052), .Q (dut_u_rd_timer[2]));
  DFFRHQX1 \dut_u_rd_timer_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3022), .Q (dut_u_rd_timer[3]));
  DFFRHQX1 \dut_u_rd_timer_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3011), .Q (dut_u_rd_timer[4]));
  DFFRHQX1 \dut_u_rd_timer_reg[5] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3004), .Q (dut_u_rd_timer[5]));
  DFFRHQX1 \dut_u_rd_timer_reg[6] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2997), .Q (dut_u_rd_timer[6]));
  DFFRHQX1 \dut_u_rd_timer_reg[7] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2990), .Q (dut_u_rd_timer[7]));
  DFFRHQX1 \dut_u_rd_timer_reg[8] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2983), .Q (dut_u_rd_timer[8]));
  DFFRHQX1 \dut_u_rd_timer_reg[9] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2976), .Q (dut_u_rd_timer[9]));
  DFFRHQX1 \dut_u_rd_timer_reg[10] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2969), .Q (dut_u_rd_timer[10]));
  DFFRHQX1 \dut_u_rd_timer_reg[11] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2962), .Q (dut_u_rd_timer[11]));
  DFFRHQX1 \dut_u_rd_timer_reg[12] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2955), .Q (dut_u_rd_timer[12]));
  DFFRHQX1 \dut_u_rd_timer_reg[13] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2948), .Q (dut_u_rd_timer[13]));
  DFFRHQX1 \dut_u_rd_timer_reg[14] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2940), .Q (dut_u_rd_timer[14]));
  DFFRHQX1 \dut_u_rd_timer_reg[15] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2935), .Q (dut_u_rd_timer[15]));
  NOR2XL dut_u_rd_g5150(.A (dut_u_rd_n_2938), .B (dut_u_rd_n_3160), .Y
       (dut_u_rd_n_2935));
  AOI22X1 dut_u_rd_g5152(.A0 (dut_u_rd_timer_run), .A1
       (dut_u_rd_n_2942), .B0 (dut_u_rd_n_3265), .B1
       (dut_u_rd_timer[15]), .Y (dut_u_rd_n_2938));
  AOI21XL dut_u_rd_g5153(.A0 (dut_u_rd_n_3218), .A1 (dut_u_rd_n_2943),
       .B0 (dut_u_rd_n_3160), .Y (dut_u_rd_n_2940));
  XNOR2X1 dut_u_rd_g5154(.A (dut_u_rd_timer[15]), .B (dut_u_rd_n_2949),
       .Y (dut_u_rd_n_2942));
  OAI211X1 dut_u_rd_g5156(.A0 (dut_u_rd_timer[14]), .A1
       (dut_u_rd_n_2953), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2949), .Y (dut_u_rd_n_2943));
  AOI21XL dut_u_rd_g5157(.A0 (dut_u_rd_n_3216), .A1 (dut_u_rd_n_2950),
       .B0 (dut_u_rd_n_3160), .Y (dut_u_rd_n_2948));
  OAI211X1 dut_u_rd_g5159(.A0 (dut_u_rd_timer[13]), .A1
       (dut_u_rd_n_2960), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2956), .Y (dut_u_rd_n_2950));
  NAND2X1 dut_u_rd_g5160(.A (dut_u_rd_timer[14]), .B (dut_u_rd_n_2953),
       .Y (dut_u_rd_n_2949));
  INVX1 dut_u_rd_g5161(.A (dut_u_rd_n_2956), .Y (dut_u_rd_n_2953));
  AOI21XL dut_u_rd_g5162(.A0 (dut_u_rd_n_3202), .A1 (dut_u_rd_n_2957),
       .B0 (dut_u_rd_n_3160), .Y (dut_u_rd_n_2955));
  OAI211X1 dut_u_rd_g5164(.A0 (dut_u_rd_timer[12]), .A1
       (dut_u_rd_n_2967), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2963), .Y (dut_u_rd_n_2957));
  NAND2X1 dut_u_rd_g5165(.A (dut_u_rd_timer[13]), .B (dut_u_rd_n_2960),
       .Y (dut_u_rd_n_2956));
  INVX1 dut_u_rd_g5166(.A (dut_u_rd_n_2963), .Y (dut_u_rd_n_2960));
  AOI21XL dut_u_rd_g5167(.A0 (dut_u_rd_n_3215), .A1 (dut_u_rd_n_2964),
       .B0 (dut_u_rd_n_3160), .Y (dut_u_rd_n_2962));
  OAI211X1 dut_u_rd_g5169(.A0 (dut_u_rd_timer[11]), .A1
       (dut_u_rd_n_2974), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2970), .Y (dut_u_rd_n_2964));
  NAND2X1 dut_u_rd_g5170(.A (dut_u_rd_timer[12]), .B (dut_u_rd_n_2967),
       .Y (dut_u_rd_n_2963));
  INVX1 dut_u_rd_g5171(.A (dut_u_rd_n_2970), .Y (dut_u_rd_n_2967));
  AOI21XL dut_u_rd_g5172(.A0 (dut_u_rd_n_3206), .A1 (dut_u_rd_n_2971),
       .B0 (dut_u_rd_n_3160), .Y (dut_u_rd_n_2969));
  OAI211X1 dut_u_rd_g5174(.A0 (dut_u_rd_timer[10]), .A1
       (dut_u_rd_n_2981), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2977), .Y (dut_u_rd_n_2971));
  NAND2X1 dut_u_rd_g5175(.A (dut_u_rd_timer[11]), .B (dut_u_rd_n_2974),
       .Y (dut_u_rd_n_2970));
  INVX1 dut_u_rd_g5176(.A (dut_u_rd_n_2977), .Y (dut_u_rd_n_2974));
  AOI21XL dut_u_rd_g5177(.A0 (dut_u_rd_n_3205), .A1 (dut_u_rd_n_2978),
       .B0 (dut_u_rd_n_3160), .Y (dut_u_rd_n_2976));
  OAI211X1 dut_u_rd_g5179(.A0 (dut_u_rd_timer[9]), .A1
       (dut_u_rd_n_2988), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2984), .Y (dut_u_rd_n_2978));
  NAND2X1 dut_u_rd_g5180(.A (dut_u_rd_timer[10]), .B (dut_u_rd_n_2981),
       .Y (dut_u_rd_n_2977));
  INVX1 dut_u_rd_g5181(.A (dut_u_rd_n_2984), .Y (dut_u_rd_n_2981));
  AOI21XL dut_u_rd_g5182(.A0 (dut_u_rd_n_3198), .A1 (dut_u_rd_n_2985),
       .B0 (dut_u_rd_n_3160), .Y (dut_u_rd_n_2983));
  OAI211X1 dut_u_rd_g5184(.A0 (dut_u_rd_timer[8]), .A1
       (dut_u_rd_n_2995), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2991), .Y (dut_u_rd_n_2985));
  NAND2X1 dut_u_rd_g5185(.A (dut_u_rd_timer[9]), .B (dut_u_rd_n_2988),
       .Y (dut_u_rd_n_2984));
  INVX1 dut_u_rd_g5186(.A (dut_u_rd_n_2991), .Y (dut_u_rd_n_2988));
  AOI21XL dut_u_rd_g5187(.A0 (dut_u_rd_n_3217), .A1 (dut_u_rd_n_2992),
       .B0 (dut_u_rd_n_3160), .Y (dut_u_rd_n_2990));
  OAI211X1 dut_u_rd_g5189(.A0 (dut_u_rd_timer[7]), .A1
       (dut_u_rd_n_3002), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2998), .Y (dut_u_rd_n_2992));
  NAND2X1 dut_u_rd_g5190(.A (dut_u_rd_timer[8]), .B (dut_u_rd_n_2995),
       .Y (dut_u_rd_n_2991));
  INVX1 dut_u_rd_g5191(.A (dut_u_rd_n_2998), .Y (dut_u_rd_n_2995));
  AOI21XL dut_u_rd_g5192(.A0 (dut_u_rd_n_3219), .A1 (dut_u_rd_n_2999),
       .B0 (dut_u_rd_n_3160), .Y (dut_u_rd_n_2997));
  OAI211X1 dut_u_rd_g5194(.A0 (dut_u_rd_timer[6]), .A1
       (dut_u_rd_n_3009), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_3005), .Y (dut_u_rd_n_2999));
  NAND2X1 dut_u_rd_g5195(.A (dut_u_rd_timer[7]), .B (dut_u_rd_n_3002),
       .Y (dut_u_rd_n_2998));
  INVX1 dut_u_rd_g5196(.A (dut_u_rd_n_3005), .Y (dut_u_rd_n_3002));
  AOI21XL dut_u_rd_g5197(.A0 (dut_u_rd_n_3204), .A1 (dut_u_rd_n_3006),
       .B0 (dut_u_rd_n_3160), .Y (dut_u_rd_n_3004));
  OAI211X1 dut_u_rd_g5199(.A0 (dut_u_rd_timer[5]), .A1
       (dut_u_rd_n_3020), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_3015), .Y (dut_u_rd_n_3006));
  NAND2X1 dut_u_rd_g5200(.A (dut_u_rd_timer[6]), .B (dut_u_rd_n_3009),
       .Y (dut_u_rd_n_3005));
  INVX1 dut_u_rd_g5201(.A (dut_u_rd_n_3015), .Y (dut_u_rd_n_3009));
  AOI21XL dut_u_rd_g5203(.A0 (dut_u_rd_n_3203), .A1 (dut_u_rd_n_3016),
       .B0 (dut_u_rd_n_3160), .Y (dut_u_rd_n_3011));
  OAI211X1 dut_u_rd_g5205(.A0 (dut_u_rd_n_3209), .A1 (dut_u_rd_n_3189),
       .B0 (dut_u_rd_n_3181), .C0 (dut_u_rd_n_3018), .Y
       (dut_u_rd_n_3013));
  OAI211X1 dut_u_rd_g5208(.A0 (dut_u_rd_timer[4]), .A1
       (dut_u_rd_n_3050), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_3029), .Y (dut_u_rd_n_3016));
  OAI32X1 dut_u_rd_g5209(.A0 (dut_u_rd_n_3059), .A1 (dut_u_rd_n_3034),
       .A2 (dut_u_rd_n_3026), .B0 (dut_u_rd_n_3180), .B1
       (dut_u_rd_n_3188), .Y (dut_u_rd_n_3018));
  NAND2X1 dut_u_rd_g5210(.A (dut_u_rd_timer[5]), .B (dut_u_rd_n_3020),
       .Y (dut_u_rd_n_3015));
  INVX1 dut_u_rd_g5211(.A (dut_u_rd_n_3029), .Y (dut_u_rd_n_3020));
  AOI21XL dut_u_rd_g5213(.A0 (dut_u_rd_n_3207), .A1 (dut_u_rd_n_3043),
       .B0 (dut_u_rd_n_3160), .Y (dut_u_rd_n_3022));
  OAI211X1 dut_u_rd_g5219(.A0 (dut_u_rd_n_3237), .A1 (dut_u_rd_n_3056),
       .B0 (dut_u_rd_n_3114), .C0 (dut_u_rd_n_3118), .Y
       (dut_u_rd_n_3023));
  NOR2BX1 dut_u_rd_g5220(.AN (dut_u_rd_n_3034), .B (dut_epoch_clr), .Y
       (dut_u_rd_n_3024));
  NAND4XL dut_u_rd_g5221(.A (dut_u_rd_n_3060), .B (dut_u_rd_n_3057), .C
       (dut_u_rd_n_3058), .D (dut_u_rd_n_3282), .Y (dut_u_rd_n_3026));
  OAI211X1 dut_u_rd_g5222(.A0 (dut_u_rd_drain_cnt[5]), .A1
       (dut_u_rd_n_3152), .B0 (dut_u_rd_n_3128), .C0 (dut_u_rd_n_3035),
       .Y (dut_u_rd_n_3027));
  NOR2X1 dut_u_rd_g5224(.A (dut_epoch_clr), .B (dut_u_rd_n_3057), .Y
       (dut_u_rd_n_3030));
  NAND2X1 dut_u_rd_g5225(.A (dut_u_rd_timer[4]), .B (dut_u_rd_n_3050),
       .Y (dut_u_rd_n_3029));
  INVX1 dut_u_rd_g5229(.A (dut_u_rd_n_3036), .Y (dut_u_rd_n_3035));
  NOR2X1 dut_u_rd_g5230(.A (dut_epoch_clr), .B (dut_u_rd_n_3058), .Y
       (dut_u_rd_n_3037));
  NOR2BX1 dut_u_rd_g5231(.AN (dut_u_rd_n_3059), .B (dut_epoch_clr), .Y
       (dut_u_rd_n_3039));
  NOR2X1 dut_u_rd_g5232(.A (dut_epoch_clr), .B (dut_u_rd_n_3060), .Y
       (dut_u_rd_n_3041));
  OAI211X1 dut_u_rd_g5233(.A0 (dut_u_rd_timer[3]), .A1
       (dut_u_rd_n_3104), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_3081), .Y (dut_u_rd_n_3043));
  XNOR2X1 dut_u_rd_g5234(.A (dut_u_rd_outst_cnt[6]), .B
       (dut_u_rd_n_3075), .Y (dut_u_rd_n_3034));
  OAI221X1 dut_u_rd_g5235(.A0 (dut_u_rd_drain_cnt[4]), .A1
       (dut_u_rd_n_3152), .B0 (dut_u_rd_n_3237), .B1 (dut_u_rd_n_3151),
       .C0 (dut_u_rd_n_3056), .Y (dut_u_rd_n_3036));
  INVX1 dut_u_rd_g5236(.A (dut_u_rd_n_3081), .Y (dut_u_rd_n_3050));
  AOI21XL dut_u_rd_g5237(.A0 (dut_u_rd_n_3201), .A1 (dut_u_rd_n_3094),
       .B0 (dut_u_rd_n_3160), .Y (dut_u_rd_n_3052));
  NOR2X1 dut_u_rd_g5238(.A (dut_epoch_clr), .B (dut_u_rd_n_3070), .Y
       (dut_u_rd_n_3053));
  OAI221X1 dut_u_rd_g5239(.A0 (dut_u_rd_n_3261), .A1 (dut_u_rd_n_3090),
       .B0 (dut_u_rd_n_3152), .B1 (dut_u_rd_n_3186), .C0
       (dut_u_rd_n_3136), .Y (dut_u_rd_n_3054));
  AOI221X1 dut_u_rd_g5242(.A0 (dut_u_rd_n_3263), .A1 (dut_u_rd_n_3153),
       .B0 (dut_u_rd_drain_cnt[3]), .B1 (dut_u_rd_n_3150), .C0
       (dut_u_rd_n_3071), .Y (dut_u_rd_n_3056));
  AOI221X1 dut_u_rd_g5243(.A0 (dut_u_rd_n_3129), .A1 (dut_u_rd_n_3148),
       .B0 (dut_u_rd_outst_cnt[4]), .B1 (dut_u_rd_n_3085), .C0
       (dut_u_rd_n_3138), .Y (dut_u_rd_n_3057));
  MXI2XL dut_u_rd_g5244(.A (dut_u_rd_n_3110), .B (dut_u_rd_n_3084), .S0
       (dut_u_rd_outst_cnt[2]), .Y (dut_u_rd_n_3058));
  XNOR2X1 dut_u_rd_g5245(.A (dut_u_rd_outst_cnt[3]), .B
       (dut_u_rd_n_3097), .Y (dut_u_rd_n_3059));
  XNOR2X1 dut_u_rd_g5246(.A (dut_u_rd_outst_cnt[5]), .B
       (dut_u_rd_n_3087), .Y (dut_u_rd_n_3060));
  NOR2BX1 dut_u_rd_g5247(.AN (dut_u_rd_n_3091), .B (dut_epoch_clr), .Y
       (dut_u_rd_n_3066));
  AOI21X1 dut_u_rd_g5252(.A0 (dut_u_rd_outst_cnt[1]), .A1
       (dut_u_rd_n_3125), .B0 (dut_u_rd_n_3092), .Y (dut_u_rd_n_3070));
  MXI2XL dut_u_rd_g5253(.A (dut_u_rd_n_3138), .B (dut_u_rd_n_3112), .S0
       (dut_u_rd_outst_cnt[5]), .Y (dut_u_rd_n_3075));
  OAI221X1 dut_u_rd_g5254(.A0 (dut_u_rd_drain_cnt[2]), .A1
       (dut_u_rd_n_3152), .B0 (dut_u_rd_n_3151), .B1 (dut_u_rd_n_3261),
       .C0 (dut_u_rd_n_3090), .Y (dut_u_rd_n_3071));
  NAND2XL dut_u_rd_g5255(.A (dut_u_rd_n_3114), .B (dut_u_rd_n_3113), .Y
       (dut_u_rd_n_3082));
  OAI221X1 dut_u_rd_g5256(.A0 (dut_u_rd_n_3285), .A1 (dut_u_rd_n_3149),
       .B0 (dut_u_rd_n_3196), .B1 (dut_u_rd_n_3146), .C0
       (dut_u_rd_n_3124), .Y (dut_u_rd_n_3084));
  NAND2X1 dut_u_rd_g5257(.A (dut_u_rd_n_3116), .B (dut_u_rd_n_3124), .Y
       (dut_u_rd_n_3085));
  OR2XL dut_u_rd_g5258(.A (dut_u_rd_n_3138), .B (dut_u_rd_n_3112), .Y
       (dut_u_rd_n_3087));
  NAND2X1 dut_u_rd_g5259(.A (dut_u_rd_timer[3]), .B (dut_u_rd_n_3104),
       .Y (dut_u_rd_n_3081));
  OAI211X1 dut_u_rd_g5261(.A0 (dut_u_rd_n_3191), .A1 (dut_u_rd_n_3149),
       .B0 (dut_u_rd_n_3130), .C0 (dut_u_rd_n_3123), .Y
       (dut_u_rd_n_3092));
  OAI211X1 dut_u_rd_g5262(.A0 (dut_u_rd_timer[2]), .A1
       (dut_u_rd_n_3173), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_3158), .Y (dut_u_rd_n_3094));
  OAI211X1 dut_u_rd_g5263(.A0 (dut_u_rd_n_3152), .A1 (dut_u_rd_n_3184),
       .B0 (dut_u_rd_n_3126), .C0 (dut_u_rd_n_3106), .Y
       (dut_u_rd_n_3096));
  MX2XL dut_u_rd_g5264(.A (dut_u_rd_n_3123), .B (dut_u_rd_n_3122), .S0
       (dut_u_rd_outst_cnt[2]), .Y (dut_u_rd_n_3097));
  AOI221X1 dut_u_rd_g5265(.A0 (dut_u_rd_n_3153), .A1 (dut_u_rd_n_3213),
       .B0 (dut_u_rd_n_3150), .B1 (dut_u_rd_n_3210), .C0
       (dut_u_rd_n_3137), .Y (dut_u_rd_n_3090));
  AOI22X1 dut_u_rd_g5266(.A0 (dut_u_rd_n_3239), .A1 (dut_u_rd_n_3125),
       .B0 (dut_u_rd_outst_cnt[0]), .B1 (dut_u_rd_n_3124), .Y
       (dut_u_rd_n_3091));
  INVX1 dut_u_rd_g5267(.A (dut_u_rd_n_3158), .Y (dut_u_rd_n_3104));
  NAND2XL dut_u_rd_g5268(.A (dut_u_rd_drain_cnt[1]), .B
       (dut_u_rd_n_3137), .Y (dut_u_rd_n_3106));
  NAND2XL dut_u_rd_g5269(.A (dut_u_rd_n_3136), .B (dut_u_rd_n_3135), .Y
       (dut_u_rd_n_3108));
  NAND2X1 dut_u_rd_g5270(.A (dut_u_rd_n_3123), .B (dut_u_rd_n_3122), .Y
       (dut_u_rd_n_3110));
  AOI21XL dut_u_rd_g5273(.A0 (dut_u_rd_n_3200), .A1 (dut_u_rd_n_3167),
       .B0 (dut_u_rd_n_3160), .Y (dut_u_rd_n_3115));
  AOI22X1 dut_u_rd_g5274(.A0 (dut_u_rd_n_3159), .A1 (dut_u_rd_n_3148),
       .B0 (dut_u_rd_n_571), .B1 (dut_u_rd_n_3147), .Y
       (dut_u_rd_n_3116));
  NAND3BXL dut_u_rd_g5275(.AN (dut_u_rd_n_3135), .B
       (dut_u_rd_drain_cnt[3]), .C (dut_u_rd_n_3237), .Y
       (dut_u_rd_n_3118));
  NOR3BX1 dut_u_rd_g5276(.AN (dut_u_rd_outst_cnt[4]), .B
       (dut_u_rd_n_3159), .C (dut_u_rd_n_3149), .Y (dut_u_rd_n_3112));
  NAND3BXL dut_u_rd_g5277(.AN (dut_u_rd_n_3135), .B
       (dut_u_rd_drain_cnt[4]), .C (dut_u_rd_drain_cnt[3]), .Y
       (dut_u_rd_n_3113));
  NAND3BXL dut_u_rd_g5278(.AN (dut_u_rd_n_3136), .B (dut_u_rd_n_3237),
       .C (dut_u_rd_n_3263), .Y (dut_u_rd_n_3114));
  INVX1 dut_u_rd_g5279(.A (dut_u_rd_n_3124), .Y (dut_u_rd_n_3125));
  NAND2XL dut_u_rd_g5280(.A (dut_u_rd_n_3150), .B (dut_u_rd_n_3184), .Y
       (dut_u_rd_n_3126));
  NAND2XL dut_u_rd_g5281(.A (dut_u_rd_n_3150), .B
       (dut_u_rd_drain_cnt[5]), .Y (dut_u_rd_n_3128));
  NOR2XL dut_u_rd_g5282(.A (dut_u_rd_outst_cnt[4]), .B
       (dut_u_rd_n_3159), .Y (dut_u_rd_n_3129));
  NAND2XL dut_u_rd_g5283(.A (dut_u_rd_n_3285), .B (dut_u_rd_n_3147), .Y
       (dut_u_rd_n_3130));
  NAND2X1 dut_u_rd_g5284(.A (dut_u_rd_n_3285), .B (dut_u_rd_n_3148), .Y
       (dut_u_rd_n_3122));
  NAND2X1 dut_u_rd_g5285(.A (dut_u_rd_n_3196), .B (dut_u_rd_n_3147), .Y
       (dut_u_rd_n_3123));
  NAND2X1 dut_u_rd_g5286(.A (dut_u_rd_n_3146), .B (dut_u_rd_n_3149), .Y
       (dut_u_rd_n_3124));
  NOR2XL dut_u_rd_g5287(.A (dut_u_rd_n_3190), .B (dut_u_rd_n_3160), .Y
       (dut_u_rd_n_3139));
  OAI22X1 dut_u_rd_g5288(.A0 (dut_u_rd_n_3284), .A1 (dut_u_rd_n_3208),
       .B0 (dut_u_rd_n_3193), .B1 (dut_epoch_clr), .Y
       (dut_u_rd_n_3140));
  NAND2X1 dut_u_rd_g5289(.A (dut_u_rd_n_3151), .B (dut_u_rd_n_3152), .Y
       (dut_u_rd_n_3141));
  NAND3BXL dut_u_rd_g5290(.AN (dut_u_rd_n_3213), .B (dut_u_rd_n_3153),
       .C (dut_u_rd_drain_cnt[2]), .Y (dut_u_rd_n_3135));
  NAND3BXL dut_u_rd_g5291(.AN (dut_u_rd_n_3210), .B (dut_u_rd_n_3150),
       .C (dut_u_rd_n_3261), .Y (dut_u_rd_n_3136));
  MX2X1 dut_u_rd_g5292(.A (dut_u_rd_n_3180), .B (dut_u_rd_n_3177), .S0
       (dut_u_rd_n_3197), .Y (dut_u_rd_n_3137));
  NOR3X1 dut_u_rd_g5293(.A (dut_u_rd_outst_cnt[4]), .B
       (dut_u_rd_n_571), .C (dut_u_rd_n_3146), .Y (dut_u_rd_n_3138));
  INVX1 dut_u_rd_g5294(.A (dut_u_rd_n_3146), .Y (dut_u_rd_n_3147));
  INVX1 dut_u_rd_g5295(.A (dut_u_rd_n_3148), .Y (dut_u_rd_n_3149));
  INVX1 dut_u_rd_g5296(.A (dut_u_rd_n_3150), .Y (dut_u_rd_n_3151));
  INVX1 dut_u_rd_g5297(.A (dut_u_rd_n_3152), .Y (dut_u_rd_n_3153));
  NAND2X1 dut_u_rd_g5298(.A (dut_u_rd_n_3211), .B (dut_u_rd_n_3175), .Y
       (dut_u_rd_n_3146));
  NOR2X1 dut_u_rd_g5299(.A (dut_u_rd_n_3211), .B (dut_u_rd_n_3175), .Y
       (dut_u_rd_n_3148));
  NOR2X1 dut_u_rd_g5300(.A (dut_u_rd_n_3197), .B (dut_u_rd_n_3284), .Y
       (dut_u_rd_n_3150));
  NAND2X1 dut_u_rd_g5301(.A (dut_u_rd_n_3197), .B (dut_u_rd_n_3180), .Y
       (dut_u_rd_n_3152));
  OAI211X1 dut_u_rd_g5302(.A0 (dut_u_rd_timer[0]), .A1
       (dut_u_rd_timer[1]), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_3212), .Y (dut_u_rd_n_3167));
  NAND2X1 dut_u_rd_g5303(.A (dut_u_rd_timer[2]), .B (dut_u_rd_n_3173),
       .Y (dut_u_rd_n_3158));
  NAND3X1 dut_u_rd_g5304(.A (dut_u_rd_outst_cnt[3]), .B
       (dut_u_rd_outst_cnt[2]), .C (dut_u_rd_n_3285), .Y
       (dut_u_rd_n_3159));
  OR3X1 dut_u_rd_g5305(.A (dut_rd_timeout_pulse), .B (dut_u_rd_n_3175),
       .C (dut_epoch_clr), .Y (dut_u_rd_n_3160));
  INVX1 dut_u_rd_g5306(.A (dut_u_rd_n_3212), .Y (dut_u_rd_n_3173));
  INVXL dut_u_rd_g5307(.A (dut_u_rd_n_3284), .Y (dut_u_rd_n_3177));
  NAND2BX1 dut_u_rd_g5308(.AN (dut_u_rd_n_3209), .B (dut_u_rd_n_3185),
       .Y (dut_u_rd_n_3175));
  OR4X1 dut_u_rd_g5310(.A (dut_u_rd_n_3211), .B (dut_u_rd_rd_state[1]),
       .C (dut_u_rd_rd_state[0]), .D (logic_0_1_net), .Y
       (dut_u_rd_n_3181));
  NOR2X1 dut_u_rd_g5311(.A (dut_u_rd_n_3185), .B (dut_epoch_clr), .Y
       (dut_u_rd_n_3180));
  OR2XL dut_u_rd_g5312(.A (dut_u_rd_drain_cnt[2]), .B
       (dut_u_rd_n_3213), .Y (dut_u_rd_n_3186));
  NAND2X1 dut_u_rd_g5313(.A (dut_u_rd_n_3213), .B (dut_u_rd_n_3210), .Y
       (dut_u_rd_n_3184));
  NAND2BX1 dut_u_rd_g5314(.AN (dut_u_rd_n_3208), .B (s_rready), .Y
       (dut_u_rd_n_3185));
  INVX1 dut_u_rd_g5315(.A (dut_u_rd_n_3189), .Y (dut_u_rd_n_3188));
  XNOR2X1 dut_u_rd_g5316(.A (dut_u_rd_timer_run), .B
       (dut_u_rd_timer[0]), .Y (dut_u_rd_n_3190));
  MXI2XL dut_u_rd_g5317(.A (dut_u_rd_outst_cnt[0]), .B
       (dut_u_rd_n_3239), .S0 (dut_u_rd_outst_cnt[1]), .Y
       (dut_u_rd_n_3191));
  AOI21XL dut_u_rd_g5318(.A0 (dut_flush), .A1 (dut_u_rd_n_321), .B0
       (dut_rd_timeout_pulse), .Y (dut_u_rd_n_3193));
  NAND3BXL dut_u_rd_g5319(.AN (dut_rd_timeout_pulse), .B
       (dut_u_rd_n_321), .C (dut_u_rd_n_316), .Y (dut_u_rd_n_3189));
  NAND2X1 dut_u_rd_g5320(.A (dut_u_rd_n_3265), .B (dut_u_rd_timer[8]),
       .Y (dut_u_rd_n_3198));
  NAND2X1 dut_u_rd_g5321(.A (dut_u_rd_n_3265), .B (dut_u_rd_timer[1]),
       .Y (dut_u_rd_n_3200));
  NAND2X1 dut_u_rd_g5322(.A (dut_u_rd_n_3265), .B (dut_u_rd_timer[2]),
       .Y (dut_u_rd_n_3201));
  NAND2X1 dut_u_rd_g5323(.A (dut_u_rd_n_3265), .B (dut_u_rd_timer[12]),
       .Y (dut_u_rd_n_3202));
  NAND2X1 dut_u_rd_g5324(.A (dut_u_rd_n_3265), .B (dut_u_rd_timer[4]),
       .Y (dut_u_rd_n_3203));
  NAND2X1 dut_u_rd_g5325(.A (dut_u_rd_n_3265), .B (dut_u_rd_timer[5]),
       .Y (dut_u_rd_n_3204));
  NAND2X1 dut_u_rd_g5326(.A (dut_u_rd_n_3265), .B (dut_u_rd_timer[9]),
       .Y (dut_u_rd_n_3205));
  NAND2X1 dut_u_rd_g5327(.A (dut_u_rd_n_3265), .B (dut_u_rd_timer[10]),
       .Y (dut_u_rd_n_3206));
  NAND2X1 dut_u_rd_g5328(.A (dut_u_rd_n_3265), .B (dut_u_rd_timer[3]),
       .Y (dut_u_rd_n_3207));
  NOR2X1 dut_u_rd_g5329(.A (dut_u_rd_outst_cnt[1]), .B
       (dut_u_rd_outst_cnt[0]), .Y (dut_u_rd_n_3196));
  NAND2X1 dut_u_rd_g5330(.A (m_rvalid), .B (dut_u_rd_n_323), .Y
       (dut_u_rd_n_3197));
  NAND2X1 dut_u_rd_g5331(.A (dut_u_rd_n_3265), .B (dut_u_rd_timer[11]),
       .Y (dut_u_rd_n_3215));
  NAND2X1 dut_u_rd_g5332(.A (dut_u_rd_n_3265), .B (dut_u_rd_timer[13]),
       .Y (dut_u_rd_n_3216));
  NAND2X1 dut_u_rd_g5333(.A (dut_u_rd_n_3265), .B (dut_u_rd_timer[7]),
       .Y (dut_u_rd_n_3217));
  NAND2X1 dut_u_rd_g5334(.A (dut_u_rd_n_3265), .B (dut_u_rd_timer[14]),
       .Y (dut_u_rd_n_3218));
  NAND2X1 dut_u_rd_g5335(.A (dut_u_rd_n_3265), .B (dut_u_rd_timer[6]),
       .Y (dut_u_rd_n_3219));
  NAND2BX1 dut_u_rd_g5336(.AN (dut_u_rd_rd_state[0]), .B
       (dut_u_rd_rd_state[1]), .Y (dut_u_rd_n_3208));
  AND2XL dut_u_rd_g5337(.A (dut_u_rd_n_324), .B (s_rvalid), .Y
       (dut_u_rd_n_3209));
  OR2X1 dut_u_rd_g5338(.A (dut_u_rd_drain_cnt[1]), .B
       (dut_u_rd_drain_cnt[0]), .Y (dut_u_rd_n_3210));
  NAND2X1 dut_u_rd_g5339(.A (s_arvalid), .B (s_arready), .Y
       (dut_u_rd_n_3211));
  NAND2X1 dut_u_rd_g5340(.A (dut_u_rd_timer[1]), .B
       (dut_u_rd_timer[0]), .Y (dut_u_rd_n_3212));
  NAND2X1 dut_u_rd_g5341(.A (dut_u_rd_drain_cnt[1]), .B
       (dut_u_rd_drain_cnt[0]), .Y (dut_u_rd_n_3213));
  INVX1 dut_u_rd_g5350(.A (dut_u_rd_drain_cnt[3]), .Y
       (dut_u_rd_n_3263));
  INVX1 dut_u_rd_g5351(.A (dut_u_rd_timer_run), .Y (dut_u_rd_n_3265));
  NOR2BX1 dut_u_rd_g2148(.AN (dut_u_rd_n_3070), .B (dut_u_rd_n_3091),
       .Y (dut_u_rd_n_3282));
  MXI2XL dut_u_rd_g5352(.A (dut_u_rd_n_3114), .B (dut_u_rd_n_3113), .S0
       (dut_u_rd_drain_cnt[5]), .Y (dut_u_rd_n_3283));
  NAND2BX1 dut_u_rd_g5353(.AN (dut_epoch_clr), .B (dut_u_rd_n_3185), .Y
       (dut_u_rd_n_3284));
  NOR2BX1 dut_u_rd_g5354(.AN (dut_u_rd_outst_cnt[1]), .B
       (dut_u_rd_n_3239), .Y (dut_u_rd_n_3285));
  INVXL g6462(.A (dut_flush), .Y (dut_u_rd_n_316));
  INVX1 g6463(.A (dut_u_rd_n_1945), .Y (m_arvalid));
  INVX1 g6464(.A (dut_u_rd_n_1946), .Y (s_arready));
  INVXL g6465(.A (dut_u_wr_n_4379), .Y (dut_u_wr_n_4334));
  INVXL g6466(.A (s_wready), .Y (dut_u_wr_n_4385));
  NAND2BX1 g2(.AN (dut_u_wr_n_4177), .B (dut_u_wr_drain_cnt[5]), .Y
       (n_222));
  OAI21X1 g6467(.A0 (dut_u_wr_n_4334), .A1 (dut_u_wr_n_4342), .B0
       (dut_u_wr_n_4357), .Y (n_223));
  NOR2BX1 dut_u_wr_g6468(.AN (dut_u_wr_wr_state[1]), .B
       (dut_u_wr_wr_state[0]), .Y (n_224));
  DFFRX1 \dut_mode_reg[0] (.RN (rst_n), .CK (clk), .D (n_10), .Q
       (dut_mode[0]), .QN (dut_n_418));
  DFFRX1 \dut_mode_reg[1] (.RN (rst_n), .CK (clk), .D (n_8), .Q
       (dut_mode[1]), .QN (dut_n_419));
  DFFRX1 \dut_u_rd_outst_cnt_reg[6] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3024), .Q (dut_u_rd_outst_cnt[6]), .QN
       (dut_u_rd_n_2006));
  DFFRX1 \dut_u_rd_rd_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3140), .Q (dut_u_rd_rd_state[1]), .QN
       (dut_u_rd_n_2009));
  DFFRX1 \dut_u_rd_drain_cnt_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3023), .Q (dut_u_rd_drain_cnt[4]), .QN
       (dut_u_rd_n_3237));
  DFFRX1 \dut_u_rd_outst_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3066), .Q (dut_u_rd_outst_cnt[0]), .QN
       (dut_u_rd_n_3239));
  DFFRX1 \dut_u_rd_drain_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_3054), .Q (dut_u_rd_drain_cnt[2]), .QN
       (dut_u_rd_n_3261));
  AOI2BB1XL g6483(.A0N (dut_u_wr_downstream_w_fire), .A1N
       (dut_u_wr_downstream_w_done), .B0 (dut_u_wr_n_3027), .Y (n_225));
  TIELO tie_0_cell(.Y (logic_0_1_net));
endmodule

