
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Aug 29 2026 17:49:23 PDT (Aug 30 2026 00:49:23 UTC)

// Verification Directory fv/tp_lvl_tw9 

module tp_lvl_tw9(clk, rst_n, s_awvalid, \s_aw[prot] , \s_aw[addr] ,
     s_wvalid, \s_w[strb] , \s_w[data] , s_arvalid, \s_ar[prot] ,
     \s_ar[addr] , s_bready, s_rready, s_awready, s_wready, s_arready,
     s_bvalid, \s_b[resp] , s_rvalid, \s_r[resp] , \s_r[data] ,
     m_awvalid, \m_aw[prot] , \m_aw[addr] , m_wvalid, \m_w[strb] ,
     \m_w[data] , m_arvalid, \m_ar[prot] , \m_ar[addr] , m_bready,
     m_rready, m_awready, m_wready, m_arready, m_bvalid, \m_b[resp] ,
     m_rvalid, \m_r[resp] , \m_r[data] , enable_reg, clear_reg, irq,
     status_reg, guard_busy);
  input clk, rst_n, s_awvalid, s_wvalid, s_arvalid, s_bready, s_rready,
       m_awready, m_wready, m_arready, m_bvalid, m_rvalid;
  input [2:0] \s_aw[prot] , \s_ar[prot] , enable_reg, clear_reg;
  input [31:0] \s_aw[addr] , \s_w[data] , \s_ar[addr] , \m_r[data] ;
  input [3:0] \s_w[strb] ;
  input [1:0] \m_b[resp] , \m_r[resp] ;
  output s_awready, s_wready, s_arready, s_bvalid, s_rvalid, m_awvalid,
       m_wvalid, m_arvalid, m_bready, m_rready, irq, guard_busy;
  output [1:0] \s_b[resp] , \s_r[resp] ;
  output [31:0] \s_r[data] , \m_aw[addr] , \m_w[data] , \m_ar[addr] ;
  output [2:0] \m_aw[prot] , \m_ar[prot] , status_reg;
  output [3:0] \m_w[strb] ;
  wire clk, rst_n, s_awvalid, s_wvalid, s_arvalid, s_bready, s_rready,
       m_awready, m_wready, m_arready, m_bvalid, m_rvalid;
  wire [2:0] \s_aw[prot] , \s_ar[prot] , enable_reg, clear_reg;
  wire [31:0] \s_aw[addr] , \s_w[data] , \s_ar[addr] , \m_r[data] ;
  wire [3:0] \s_w[strb] ;
  wire [1:0] \m_b[resp] , \m_r[resp] ;
  wire s_awready, s_wready, s_arready, s_bvalid, s_rvalid, m_awvalid,
       m_wvalid, m_arvalid, m_bready, m_rready, irq, guard_busy;
  wire [1:0] \s_b[resp] , \s_r[resp] ;
  wire [31:0] \s_r[data] , \m_aw[addr] , \m_w[data] , \m_ar[addr] ;
  wire [2:0] \m_aw[prot] , \m_ar[prot] , status_reg;
  wire [3:0] \m_w[strb] ;
  wire [1:0] dut_mode;
  wire [2:0] dut_rcvy_ack;
  wire [3:0] dut_u_wr_outst_cnt;
  wire [1:0] dut_u_wr_wpair_state;
  wire [8:0] dut_u_wr_w_timer;
  wire [8:0] dut_u_wr_b_timer;
  wire [3:0] dut_u_wr_drain_cnt;
  wire [1:0] dut_u_wr_wr_state;
  wire [3:0] dut_u_rd_outst_cnt;
  wire [3:0] dut_u_rd_drain_cnt;
  wire [8:0] dut_u_rd_timer;
  wire [1:0] dut_u_rd_rd_state;
  wire dut_epoch_clr, dut_flush, dut_n_418, dut_n_419, dut_rd_busy,
       dut_rd_timeout_pulse, dut_u_rd_n_252, dut_u_rd_n_257;
  wire dut_u_rd_n_259, dut_u_rd_n_260, dut_u_rd_n_272, dut_u_rd_n_1597,
       dut_u_rd_n_1603, dut_u_rd_n_1622, dut_u_rd_n_1632,
       dut_u_rd_n_1643;
  wire dut_u_rd_n_1647, dut_u_rd_n_1652, dut_u_rd_n_1657,
       dut_u_rd_n_1898, dut_u_rd_n_1901, dut_u_rd_n_1903,
       dut_u_rd_n_1905, dut_u_rd_n_1906;
  wire dut_u_rd_n_1911, dut_u_rd_n_1912, dut_u_rd_n_1913,
       dut_u_rd_n_1916, dut_u_rd_n_1918, dut_u_rd_n_1919,
       dut_u_rd_n_1920, dut_u_rd_n_1923;
  wire dut_u_rd_n_1925, dut_u_rd_n_1926, dut_u_rd_n_1927,
       dut_u_rd_n_1928, dut_u_rd_n_1930, dut_u_rd_n_1933,
       dut_u_rd_n_1935, dut_u_rd_n_1936;
  wire dut_u_rd_n_1937, dut_u_rd_n_1940, dut_u_rd_n_1941,
       dut_u_rd_n_1946, dut_u_rd_n_1947, dut_u_rd_n_1948,
       dut_u_rd_n_1950, dut_u_rd_n_1954;
  wire dut_u_rd_n_1956, dut_u_rd_n_1958, dut_u_rd_n_1959,
       dut_u_rd_n_1960, dut_u_rd_n_1963, dut_u_rd_n_1966,
       dut_u_rd_n_1967, dut_u_rd_n_1968;
  wire dut_u_rd_n_1972, dut_u_rd_n_1973, dut_u_rd_n_1974,
       dut_u_rd_n_1976, dut_u_rd_n_1980, dut_u_rd_n_1981,
       dut_u_rd_n_1982, dut_u_rd_n_1988;
  wire dut_u_rd_n_1993, dut_u_rd_n_1996, dut_u_rd_n_1998,
       dut_u_rd_n_2000, dut_u_rd_n_2001, dut_u_rd_n_2002,
       dut_u_rd_n_2003, dut_u_rd_n_2004;
  wire dut_u_rd_n_2008, dut_u_rd_n_2009, dut_u_rd_n_2010,
       dut_u_rd_n_2011, dut_u_rd_n_2012, dut_u_rd_n_2013,
       dut_u_rd_n_2017, dut_u_rd_n_2018;
  wire dut_u_rd_n_2019, dut_u_rd_n_2020, dut_u_rd_n_2021,
       dut_u_rd_n_2027, dut_u_rd_n_2028, dut_u_rd_n_2032,
       dut_u_rd_n_2033, dut_u_rd_n_2037;
  wire dut_u_rd_n_2039, dut_u_rd_n_2040, dut_u_rd_n_2044,
       dut_u_rd_n_2047, dut_u_rd_n_2048, dut_u_rd_n_2050,
       dut_u_rd_n_2051, dut_u_rd_n_2052;
  wire dut_u_rd_n_2055, dut_u_rd_n_2056, dut_u_rd_n_2057,
       dut_u_rd_n_2058, dut_u_rd_n_2060, dut_u_rd_n_2061,
       dut_u_rd_n_2062, dut_u_rd_n_2063;
  wire dut_u_rd_n_2064, dut_u_rd_n_2066, dut_u_rd_n_2067,
       dut_u_rd_n_2068, dut_u_rd_n_2069, dut_u_rd_n_2070,
       dut_u_rd_n_2071, dut_u_rd_n_2072;
  wire dut_u_rd_n_2099, dut_u_rd_n_2109, dut_u_rd_n_2110,
       dut_u_rd_n_2111, dut_u_rd_timer_run, dut_u_wr_b_timer_run,
       dut_u_wr_downstream_aw_done, dut_u_wr_downstream_aw_fire;
  wire dut_u_wr_downstream_w_done, dut_u_wr_downstream_w_fire,
       dut_u_wr_n_360, dut_u_wr_n_362, dut_u_wr_n_363, dut_u_wr_n_374,
       dut_u_wr_n_2029, dut_u_wr_n_2440;
  wire dut_u_wr_n_2446, dut_u_wr_n_2456, dut_u_wr_n_2458,
       dut_u_wr_n_2459, dut_u_wr_n_2461, dut_u_wr_n_2469,
       dut_u_wr_n_2470, dut_u_wr_n_2471;
  wire dut_u_wr_n_2473, dut_u_wr_n_2474, dut_u_wr_n_2475,
       dut_u_wr_n_2476, dut_u_wr_n_2478, dut_u_wr_n_2479,
       dut_u_wr_n_2801, dut_u_wr_n_2802;
  wire dut_u_wr_n_2803, dut_u_wr_n_2805, dut_u_wr_n_2807,
       dut_u_wr_n_2809, dut_u_wr_n_2811, dut_u_wr_n_2812,
       dut_u_wr_n_2813, dut_u_wr_n_2817;
  wire dut_u_wr_n_2823, dut_u_wr_n_2824, dut_u_wr_n_2825,
       dut_u_wr_n_2827, dut_u_wr_n_2828, dut_u_wr_n_2830,
       dut_u_wr_n_2833, dut_u_wr_n_2835;
  wire dut_u_wr_n_2837, dut_u_wr_n_2838, dut_u_wr_n_2840,
       dut_u_wr_n_2841, dut_u_wr_n_2842, dut_u_wr_n_2844,
       dut_u_wr_n_2848, dut_u_wr_n_2850;
  wire dut_u_wr_n_2852, dut_u_wr_n_2853, dut_u_wr_n_2857,
       dut_u_wr_n_2858, dut_u_wr_n_2859, dut_u_wr_n_2861,
       dut_u_wr_n_2865, dut_u_wr_n_2867;
  wire dut_u_wr_n_2869, dut_u_wr_n_2871, dut_u_wr_n_2872,
       dut_u_wr_n_2873, dut_u_wr_n_2875, dut_u_wr_n_2879,
       dut_u_wr_n_2882, dut_u_wr_n_2883;
  wire dut_u_wr_n_2884, dut_u_wr_n_2886, dut_u_wr_n_2888,
       dut_u_wr_n_2892, dut_u_wr_n_2894, dut_u_wr_n_2896,
       dut_u_wr_n_2898, dut_u_wr_n_2900;
  wire dut_u_wr_n_2901, dut_u_wr_n_2902, dut_u_wr_n_2906,
       dut_u_wr_n_2909, dut_u_wr_n_2910, dut_u_wr_n_2912,
       dut_u_wr_n_2917, dut_u_wr_n_2918;
  wire dut_u_wr_n_2919, dut_u_wr_n_2922, dut_u_wr_n_2924,
       dut_u_wr_n_2926, dut_u_wr_n_2927, dut_u_wr_n_2931,
       dut_u_wr_n_2932, dut_u_wr_n_2934;
  wire dut_u_wr_n_2936, dut_u_wr_n_2941, dut_u_wr_n_2943,
       dut_u_wr_n_2945, dut_u_wr_n_2948, dut_u_wr_n_2949,
       dut_u_wr_n_2952, dut_u_wr_n_2956;
  wire dut_u_wr_n_2957, dut_u_wr_n_2959, dut_u_wr_n_2960,
       dut_u_wr_n_2964, dut_u_wr_n_2965, dut_u_wr_n_2966,
       dut_u_wr_n_2967, dut_u_wr_n_2968;
  wire dut_u_wr_n_2994, dut_u_wr_n_2995, dut_u_wr_n_2996,
       dut_u_wr_n_2997, dut_u_wr_n_2998, dut_u_wr_n_3000,
       dut_u_wr_n_3002, dut_u_wr_n_3003;
  wire dut_u_wr_n_3004, dut_u_wr_n_3008, dut_u_wr_n_3011,
       dut_u_wr_n_3014, dut_u_wr_n_3036, dut_u_wr_n_3038,
       dut_u_wr_n_3040, dut_u_wr_n_3041;
  wire dut_u_wr_n_3042, dut_u_wr_n_3043, dut_u_wr_n_3044,
       dut_u_wr_n_3045, dut_u_wr_n_3051, dut_u_wr_n_3053,
       dut_u_wr_n_3057, dut_u_wr_n_3058;
  wire dut_u_wr_n_3060, dut_u_wr_n_3061, dut_u_wr_n_3062,
       dut_u_wr_n_3063, dut_u_wr_n_3064, dut_u_wr_n_3069,
       dut_u_wr_n_3070, dut_u_wr_n_3074;
  wire dut_u_wr_n_3075, dut_u_wr_n_3076, dut_u_wr_n_3079,
       dut_u_wr_n_3080, dut_u_wr_n_3082, dut_u_wr_n_3083,
       dut_u_wr_n_3084, dut_u_wr_n_3102;
  wire dut_u_wr_n_3104, dut_u_wr_n_3105, dut_u_wr_n_3107,
       dut_u_wr_n_3108, dut_u_wr_n_3109, dut_u_wr_n_3110,
       dut_u_wr_n_3111, dut_u_wr_n_3113;
  wire dut_u_wr_n_3114, dut_u_wr_n_3115, dut_u_wr_n_3116,
       dut_u_wr_n_3117, dut_u_wr_n_3119, dut_u_wr_n_3120,
       dut_u_wr_n_3121, dut_u_wr_n_3122;
  wire dut_u_wr_n_3123, dut_u_wr_n_3124, dut_u_wr_n_3125,
       dut_u_wr_n_3126, dut_u_wr_n_3127, dut_u_wr_n_3131,
       dut_u_wr_n_3144, dut_u_wr_n_3147;
  wire dut_u_wr_n_3151, dut_u_wr_n_3152, dut_u_wr_n_3175,
       dut_u_wr_n_3209, dut_u_wr_n_3210, dut_u_wr_w_perm_BAR,
       dut_u_wr_w_timer_run, dut_wr_busy;
  wire dut_wr_timeout_pulse, dut_wr_w_fault_pulse, logic_0_1_net, n_0,
       n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_221, n_222, n_223, n_224, n_225, n_227, n_228;
  wire n_229, n_230;
  assign \m_ar[addr] [0] = \s_ar[addr] [0];
  assign \m_ar[addr] [1] = \s_ar[addr] [1];
  assign \m_ar[addr] [2] = \s_ar[addr] [2];
  assign \m_ar[addr] [3] = \s_ar[addr] [3];
  assign \m_ar[addr] [4] = \s_ar[addr] [4];
  assign \m_ar[addr] [5] = \s_ar[addr] [5];
  assign \m_ar[addr] [6] = \s_ar[addr] [6];
  assign \m_ar[addr] [7] = \s_ar[addr] [7];
  assign \m_ar[addr] [8] = \s_ar[addr] [8];
  assign \m_ar[addr] [9] = \s_ar[addr] [9];
  assign \m_ar[addr] [10] = \s_ar[addr] [10];
  assign \m_ar[addr] [11] = \s_ar[addr] [11];
  assign \m_ar[addr] [12] = \s_ar[addr] [12];
  assign \m_ar[addr] [13] = \s_ar[addr] [13];
  assign \m_ar[addr] [14] = \s_ar[addr] [14];
  assign \m_ar[addr] [15] = \s_ar[addr] [15];
  assign \m_ar[addr] [16] = \s_ar[addr] [16];
  assign \m_ar[addr] [17] = \s_ar[addr] [17];
  assign \m_ar[addr] [18] = \s_ar[addr] [18];
  assign \m_ar[addr] [19] = \s_ar[addr] [19];
  assign \m_ar[addr] [20] = \s_ar[addr] [20];
  assign \m_ar[addr] [21] = \s_ar[addr] [21];
  assign \m_ar[addr] [22] = \s_ar[addr] [22];
  assign \m_ar[addr] [23] = \s_ar[addr] [23];
  assign \m_ar[addr] [24] = \s_ar[addr] [24];
  assign \m_ar[addr] [25] = \s_ar[addr] [25];
  assign \m_ar[addr] [26] = \s_ar[addr] [26];
  assign \m_ar[addr] [27] = \s_ar[addr] [27];
  assign \m_ar[addr] [28] = \s_ar[addr] [28];
  assign \m_ar[addr] [29] = \s_ar[addr] [29];
  assign \m_ar[addr] [30] = \s_ar[addr] [30];
  assign \m_ar[addr] [31] = \s_ar[addr] [31];
  assign \m_ar[prot] [0] = \s_ar[prot] [0];
  assign \m_ar[prot] [1] = \s_ar[prot] [1];
  assign \m_ar[prot] [2] = \s_ar[prot] [2];
  assign \m_w[data] [0] = \s_w[data] [0];
  assign \m_w[data] [1] = \s_w[data] [1];
  assign \m_w[data] [2] = \s_w[data] [2];
  assign \m_w[data] [3] = \s_w[data] [3];
  assign \m_w[data] [4] = \s_w[data] [4];
  assign \m_w[data] [5] = \s_w[data] [5];
  assign \m_w[data] [6] = \s_w[data] [6];
  assign \m_w[data] [7] = \s_w[data] [7];
  assign \m_w[data] [8] = \s_w[data] [8];
  assign \m_w[data] [9] = \s_w[data] [9];
  assign \m_w[data] [10] = \s_w[data] [10];
  assign \m_w[data] [11] = \s_w[data] [11];
  assign \m_w[data] [12] = \s_w[data] [12];
  assign \m_w[data] [13] = \s_w[data] [13];
  assign \m_w[data] [14] = \s_w[data] [14];
  assign \m_w[data] [15] = \s_w[data] [15];
  assign \m_w[data] [16] = \s_w[data] [16];
  assign \m_w[data] [17] = \s_w[data] [17];
  assign \m_w[data] [18] = \s_w[data] [18];
  assign \m_w[data] [19] = \s_w[data] [19];
  assign \m_w[data] [20] = \s_w[data] [20];
  assign \m_w[data] [21] = \s_w[data] [21];
  assign \m_w[data] [22] = \s_w[data] [22];
  assign \m_w[data] [23] = \s_w[data] [23];
  assign \m_w[data] [24] = \s_w[data] [24];
  assign \m_w[data] [25] = \s_w[data] [25];
  assign \m_w[data] [26] = \s_w[data] [26];
  assign \m_w[data] [27] = \s_w[data] [27];
  assign \m_w[data] [28] = \s_w[data] [28];
  assign \m_w[data] [29] = \s_w[data] [29];
  assign \m_w[data] [30] = \s_w[data] [30];
  assign \m_w[data] [31] = \s_w[data] [31];
  assign \m_w[strb] [0] = \s_w[strb] [0];
  assign \m_w[strb] [1] = \s_w[strb] [1];
  assign \m_w[strb] [2] = \s_w[strb] [2];
  assign \m_w[strb] [3] = \s_w[strb] [3];
  AND4X1 g271(.A (n_13), .B (dut_mode[1]), .C (dut_n_418), .D (n_228),
       .Y (dut_epoch_clr));
  OR3XL g272(.A (dut_rcvy_ack[0]), .B (dut_rcvy_ack[1]), .C
       (dut_rcvy_ack[2]), .Y (n_13));
  DFFRHQX1 \dut_u_irq_rcvy_ack_reg[2] (.RN (rst_n), .CK (clk), .D
       (clear_reg[2]), .Q (dut_rcvy_ack[2]));
  DFFRHQX1 \dut_u_irq_rcvy_ack_reg[1] (.RN (rst_n), .CK (clk), .D
       (clear_reg[1]), .Q (dut_rcvy_ack[1]));
  DFFRHQX1 \dut_u_irq_rcvy_ack_reg[0] (.RN (rst_n), .CK (clk), .D
       (clear_reg[0]), .Q (dut_rcvy_ack[0]));
  NAND2X1 g276(.A (dut_n_418), .B (dut_n_419), .Y (dut_flush));
  AND2X1 g222(.A (n_12), .B (n_228), .Y (irq));
  OAI2BB1X1 g223(.A0N (enable_reg[0]), .A1N (status_reg[0]), .B0
       (n_11), .Y (n_12));
  AOI22X1 g224(.A0 (enable_reg[1]), .A1 (status_reg[1]), .B0
       (enable_reg[2]), .B1 (status_reg[2]), .Y (n_11));
  OR2X1 g225(.A (dut_rd_busy), .B (dut_wr_busy), .Y (guard_busy));
  NOR2BX1 g366(.AN (n_9), .B (dut_mode[1]), .Y (n_10));
  OAI22XL g368(.A0 (dut_mode[0]), .A1 (n_4), .B0 (dut_n_418), .B1
       (n_228), .Y (n_9));
  DFFRHQX1 \dut_u_irq_status_reg_reg[0] (.RN (rst_n), .CK (clk), .D
       (n_7), .Q (status_reg[0]));
  DFFRHQX1 \dut_u_irq_status_reg_reg[1] (.RN (rst_n), .CK (clk), .D
       (n_6), .Q (status_reg[1]));
  OAI33X1 g371(.A0 (dut_mode[0]), .A1 (dut_n_419), .A2 (dut_epoch_clr),
       .B0 (dut_n_418), .B1 (dut_mode[1]), .B2 (n_0), .Y (n_8));
  DFFRHQX1 \dut_u_irq_status_reg_reg[2] (.RN (rst_n), .CK (clk), .D
       (n_5), .Q (status_reg[2]));
  OR2XL g373(.A (n_3), .B (dut_rd_timeout_pulse), .Y (n_7));
  OR2XL g374(.A (n_2), .B (dut_wr_w_fault_pulse), .Y (n_6));
  OR2XL g375(.A (n_1), .B (dut_wr_timeout_pulse), .Y (n_5));
  NOR3XL g376(.A (dut_wr_w_fault_pulse), .B (dut_rd_timeout_pulse), .C
       (dut_wr_timeout_pulse), .Y (n_4));
  NOR2BX1 g377(.AN (status_reg[0]), .B (clear_reg[0]), .Y (n_3));
  NOR2BX1 g378(.AN (status_reg[1]), .B (clear_reg[1]), .Y (n_2));
  NOR2BX1 g379(.AN (status_reg[2]), .B (clear_reg[2]), .Y (n_1));
  INVX1 g380(.A (n_228), .Y (n_0));
  INVX1 dut_u_wr_g1900(.A (s_awvalid), .Y (dut_u_wr_n_2029));
  OA21X1 dut_u_wr_g2008(.A0 (dut_u_wr_downstream_aw_done), .A1
       (dut_u_wr_downstream_aw_fire), .B0 (n_225), .Y (s_wready));
  AND2X1 dut_u_wr_g2010(.A (m_awvalid), .B (m_awready), .Y
       (dut_u_wr_downstream_aw_fire));
  AND2XL dut_u_wr_g2011(.A (m_wready), .B (m_wvalid), .Y
       (dut_u_wr_downstream_w_fire));
  OR4X1 dut_u_wr_g1931(.A (dut_u_wr_outst_cnt[0]), .B
       (dut_u_wr_outst_cnt[1]), .C (dut_u_wr_outst_cnt[2]), .D
       (dut_u_wr_outst_cnt[3]), .Y (dut_u_wr_n_374));
  AND3XL dut_u_wr_g2706(.A (dut_u_wr_n_2469), .B (dut_u_wr_n_2459), .C
       (dut_u_wr_b_timer_run), .Y (dut_wr_timeout_pulse));
  OR2X1 dut_u_wr_g2707(.A (dut_u_wr_n_2476), .B (dut_u_wr_n_2440), .Y
       (s_bvalid));
  NOR2XL dut_u_wr_g2708(.A (dut_u_wr_n_2478), .B (dut_u_wr_n_2446), .Y
       (dut_u_wr_n_2440));
  AND2X1 dut_u_wr_g2709(.A (dut_u_wr_n_2446), .B (dut_u_wr_n_360), .Y
       (dut_u_wr_b_timer_run));
  AND3XL dut_u_wr_g2710(.A (dut_u_wr_w_timer_run), .B
       (dut_u_wr_n_2470), .C (dut_u_wr_n_2458), .Y
       (dut_wr_w_fault_pulse));
  AND2X1 dut_u_wr_g2711(.A (dut_u_wr_n_2456), .B (dut_u_wr_n_2473), .Y
       (s_awready));
  OR2X1 dut_u_wr_g2712(.A (dut_u_wr_n_362), .B (dut_u_wr_n_363), .Y
       (m_bready));
  NOR2X2 dut_u_wr_g2713(.A (dut_u_wr_downstream_w_done), .B
       (dut_u_wr_n_2461), .Y (m_wvalid));
  NOR2X2 dut_u_wr_g2714(.A (dut_u_wr_downstream_aw_done), .B
       (dut_u_wr_n_2461), .Y (m_awvalid));
  NAND2BX1 dut_u_wr_g2715(.AN (dut_u_wr_n_362), .B (m_bvalid), .Y
       (dut_u_wr_n_2446));
  AO21X1 dut_u_wr_g2716(.A0 (\m_b[resp] [1]), .A1 (dut_u_wr_n_360), .B0
       (dut_u_wr_n_2476), .Y (\s_b[resp] [1]));
  OR4X1 dut_u_wr_g2717(.A (dut_u_wr_wpair_state[0]), .B
       (dut_u_wr_wpair_state[1]), .C (dut_u_wr_n_374), .D
       (dut_u_wr_n_362), .Y (dut_wr_busy));
  NOR3X1 dut_u_wr_g2718(.A (dut_u_wr_wpair_state[0]), .B (dut_flush),
       .C (dut_u_wr_n_2471), .Y (dut_u_wr_n_2456));
  NOR4X1 dut_u_wr_g2719(.A (dut_u_wr_w_timer[7]), .B
       (dut_u_wr_w_timer[3]), .C (dut_u_wr_w_timer[2]), .D
       (dut_u_wr_n_2474), .Y (dut_u_wr_n_2458));
  NOR4X1 dut_u_wr_g2720(.A (dut_u_wr_b_timer[7]), .B
       (dut_u_wr_b_timer[3]), .C (dut_u_wr_b_timer[2]), .D
       (dut_u_wr_n_2475), .Y (dut_u_wr_n_2459));
  AND2X1 dut_u_wr_g2722(.A (dut_u_wr_n_360), .B (\m_b[resp] [0]), .Y
       (\s_b[resp] [0]));
  NAND2XL dut_u_wr_g2723(.A (dut_u_wr_wpair_state[0]), .B
       (dut_u_wr_n_2473), .Y (dut_u_wr_w_perm_BAR));
  NOR2BX1 dut_u_wr_g2724(.AN (s_bready), .B (dut_u_wr_n_2478), .Y
       (dut_u_wr_n_363));
  NAND3X1 dut_u_wr_g2725(.A (s_wvalid), .B (dut_u_wr_wpair_state[0]),
       .C (dut_u_wr_n_2473), .Y (dut_u_wr_n_2461));
  NOR4X1 dut_u_wr_g2726(.A (dut_u_wr_b_timer[0]), .B
       (dut_u_wr_b_timer[1]), .C (dut_u_wr_b_timer[5]), .D
       (dut_u_wr_b_timer[4]), .Y (dut_u_wr_n_2469));
  NOR4X1 dut_u_wr_g2727(.A (dut_u_wr_w_timer[0]), .B
       (dut_u_wr_w_timer[1]), .C (dut_u_wr_w_timer[5]), .D
       (dut_u_wr_w_timer[4]), .Y (dut_u_wr_n_2470));
  NOR4BX1 dut_u_wr_g2728(.AN (dut_u_wr_outst_cnt[3]), .B
       (dut_u_wr_outst_cnt[0]), .C (dut_u_wr_outst_cnt[2]), .D
       (dut_u_wr_outst_cnt[1]), .Y (dut_u_wr_n_2471));
  NOR2X1 dut_u_wr_g2729(.A (dut_u_wr_wpair_state[1]), .B
       (dut_u_wr_n_2479), .Y (dut_u_wr_w_timer_run));
  OR4X1 dut_u_wr_g2730(.A (dut_u_wr_drain_cnt[3]), .B
       (dut_u_wr_drain_cnt[2]), .C (dut_u_wr_drain_cnt[1]), .D
       (dut_u_wr_drain_cnt[0]), .Y (dut_u_wr_n_362));
  NAND2BX1 dut_u_wr_g2731(.AN (dut_u_wr_w_timer[6]), .B
       (dut_u_wr_w_timer[8]), .Y (dut_u_wr_n_2474));
  NAND2BX1 dut_u_wr_g2732(.AN (dut_u_wr_b_timer[6]), .B
       (dut_u_wr_b_timer[8]), .Y (dut_u_wr_n_2475));
  INVX1 dut_u_wr_g2734(.A (dut_u_wr_n_360), .Y (dut_u_wr_n_2478));
  NAND2BX1 dut_u_wr_g2735(.AN (s_wvalid), .B (dut_u_wr_wpair_state[0]),
       .Y (dut_u_wr_n_2479));
  NOR2BX1 dut_u_wr_g2736(.AN (dut_u_wr_wr_state[1]), .B
       (dut_u_wr_wr_state[0]), .Y (dut_u_wr_n_2476));
  NOR2BX1 dut_u_wr_g2737(.AN (dut_u_wr_wr_state[0]), .B
       (dut_u_wr_wr_state[1]), .Y (dut_u_wr_n_360));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][0] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [0]), .SI (\m_aw[addr] [0]), .SE (dut_u_wr_n_3084),
       .Q (\m_aw[addr] [0]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][1] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [1]), .SI (\m_aw[addr] [1]), .SE (dut_u_wr_n_3084),
       .Q (\m_aw[addr] [1]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][2] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [2]), .SI (\m_aw[addr] [2]), .SE (dut_u_wr_n_3084),
       .Q (\m_aw[addr] [2]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][3] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [3]), .SI (\m_aw[addr] [3]), .SE (dut_u_wr_n_3084),
       .Q (\m_aw[addr] [3]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][4] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [4]), .SI (\m_aw[addr] [4]), .SE (dut_u_wr_n_3084),
       .Q (\m_aw[addr] [4]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][5] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [5]), .SI (\m_aw[addr] [5]), .SE (dut_u_wr_n_3084),
       .Q (\m_aw[addr] [5]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][6] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [6]), .SI (\m_aw[addr] [6]), .SE (dut_u_wr_n_3084),
       .Q (\m_aw[addr] [6]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][7] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [7]), .SI (\m_aw[addr] [7]), .SE (dut_u_wr_n_3084),
       .Q (\m_aw[addr] [7]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][8] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [8]), .SI (\m_aw[addr] [8]), .SE (dut_u_wr_n_3084),
       .Q (\m_aw[addr] [8]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][9] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [9]), .SI (\m_aw[addr] [9]), .SE (dut_u_wr_n_3084),
       .Q (\m_aw[addr] [9]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][10] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [10]), .SI (\m_aw[addr] [10]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [10]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][11] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [11]), .SI (\m_aw[addr] [11]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [11]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][12] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [12]), .SI (\m_aw[addr] [12]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [12]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][13] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [13]), .SI (\m_aw[addr] [13]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [13]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][14] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [14]), .SI (\m_aw[addr] [14]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [14]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][15] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [15]), .SI (\m_aw[addr] [15]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [15]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][16] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [16]), .SI (\m_aw[addr] [16]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [16]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][17] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [17]), .SI (\m_aw[addr] [17]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [17]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][18] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [18]), .SI (\m_aw[addr] [18]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [18]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][19] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [19]), .SI (\m_aw[addr] [19]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [19]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][20] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [20]), .SI (\m_aw[addr] [20]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [20]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][21] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [21]), .SI (\m_aw[addr] [21]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [21]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][22] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [22]), .SI (\m_aw[addr] [22]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [22]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][23] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [23]), .SI (\m_aw[addr] [23]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [23]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][24] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [24]), .SI (\m_aw[addr] [24]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [24]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][25] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [25]), .SI (\m_aw[addr] [25]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [25]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][26] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [26]), .SI (\m_aw[addr] [26]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [26]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][27] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [27]), .SI (\m_aw[addr] [27]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [27]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][28] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [28]), .SI (\m_aw[addr] [28]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [28]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][29] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [29]), .SI (\m_aw[addr] [29]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [29]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][30] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [30]), .SI (\m_aw[addr] [30]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [30]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[addr][31] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [31]), .SI (\m_aw[addr] [31]), .SE
       (dut_u_wr_n_3084), .Q (\m_aw[addr] [31]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[prot][0] (.RN (rst_n), .CK (clk), .D
       (\s_aw[prot] [0]), .SI (\m_aw[prot] [0]), .SE (dut_u_wr_n_3084),
       .Q (\m_aw[prot] [0]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[prot][1] (.RN (rst_n), .CK (clk), .D
       (\s_aw[prot] [1]), .SI (\m_aw[prot] [1]), .SE (dut_u_wr_n_3084),
       .Q (\m_aw[prot] [1]));
  SDFFRHQX1 \dut_u_wr_aw_hold_reg[prot][2] (.RN (rst_n), .CK (clk), .D
       (\s_aw[prot] [2]), .SI (\m_aw[prot] [2]), .SE (dut_u_wr_n_3084),
       .Q (\m_aw[prot] [2]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2967), .Q (dut_u_wr_b_timer[0]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2948), .Q (dut_u_wr_b_timer[1]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2898), .Q (dut_u_wr_b_timer[2]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2871), .Q (dut_u_wr_b_timer[3]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2852), .Q (dut_u_wr_b_timer[4]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[5] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2837), .Q (dut_u_wr_b_timer[5]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[6] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2823), .Q (dut_u_wr_b_timer[6]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[7] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2807), .Q (dut_u_wr_b_timer[7]));
  DFFRHQX1 \dut_u_wr_b_timer_reg[8] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2801), .Q (dut_u_wr_b_timer[8]));
  DFFRHQX1 dut_u_wr_downstream_aw_done_reg(.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3051), .Q (dut_u_wr_downstream_aw_done));
  DFFRHQX1 dut_u_wr_downstream_w_done_reg(.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3053), .Q (dut_u_wr_downstream_w_done));
  SDFFRHQX1 \dut_u_wr_drain_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2960), .SI (dut_u_wr_n_2964), .SE
       (dut_u_wr_drain_cnt[0]), .Q (dut_u_wr_drain_cnt[0]));
  DFFRHQX1 \dut_u_wr_drain_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2931), .Q (dut_u_wr_drain_cnt[1]));
  SDFFRHQX1 \dut_u_wr_drain_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2952), .SI (dut_u_wr_n_2927), .SE
       (dut_u_wr_drain_cnt[3]), .Q (dut_u_wr_drain_cnt[3]));
  DFFRHQX1 \dut_u_wr_outst_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2896), .Q (dut_u_wr_outst_cnt[0]));
  DFFRHQX1 \dut_u_wr_outst_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2886), .Q (dut_u_wr_outst_cnt[1]));
  DFFRHQX1 \dut_u_wr_outst_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2869), .Q (dut_u_wr_outst_cnt[3]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_3044), .Q (dut_u_wr_w_timer[0]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2956), .Q (dut_u_wr_w_timer[1]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2901), .Q (dut_u_wr_w_timer[2]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2872), .Q (dut_u_wr_w_timer[3]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2853), .Q (dut_u_wr_w_timer[4]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[5] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2838), .Q (dut_u_wr_w_timer[5]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[6] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2824), .Q (dut_u_wr_w_timer[6]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[7] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2809), .Q (dut_u_wr_w_timer[7]));
  DFFRHQX1 \dut_u_wr_w_timer_reg[8] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2802), .Q (dut_u_wr_w_timer[8]));
  DFFRHQX1 \dut_u_wr_wr_state_reg[0] (.RN (rst_n), .CK (clk), .D
       (n_227), .Q (dut_u_wr_wr_state[0]));
  DFFRHQX1 \dut_u_wr_wr_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2966), .Q (dut_u_wr_wr_state[1]));
  NOR2XL dut_u_wr_g3568(.A (dut_u_wr_n_2803), .B (dut_u_wr_n_3004), .Y
       (dut_u_wr_n_2801));
  NOR2X1 dut_u_wr_g3569(.A (dut_u_wr_n_2805), .B (dut_u_wr_n_3070), .Y
       (dut_u_wr_n_2802));
  AOI22X1 dut_u_wr_g3572(.A0 (dut_u_wr_b_timer_run), .A1
       (dut_u_wr_n_2811), .B0 (dut_u_wr_n_3175), .B1
       (dut_u_wr_b_timer[8]), .Y (dut_u_wr_n_2803));
  AOI22X1 dut_u_wr_g3573(.A0 (dut_u_wr_w_timer_run), .A1
       (dut_u_wr_n_2812), .B0 (dut_u_wr_n_3151), .B1
       (dut_u_wr_w_timer[8]), .Y (dut_u_wr_n_2805));
  AOI21X1 dut_u_wr_g3574(.A0 (dut_u_wr_n_3102), .A1 (dut_u_wr_n_2813),
       .B0 (dut_u_wr_n_3004), .Y (dut_u_wr_n_2807));
  AOI21X1 dut_u_wr_g3575(.A0 (dut_u_wr_n_3123), .A1 (dut_u_wr_n_2817),
       .B0 (dut_u_wr_n_3070), .Y (dut_u_wr_n_2809));
  XNOR2X1 dut_u_wr_g3576(.A (dut_u_wr_b_timer[8]), .B
       (dut_u_wr_n_2825), .Y (dut_u_wr_n_2811));
  XNOR2X1 dut_u_wr_g3577(.A (dut_u_wr_w_timer[8]), .B
       (dut_u_wr_n_2827), .Y (dut_u_wr_n_2812));
  OAI211X1 dut_u_wr_g3580(.A0 (dut_u_wr_b_timer[7]), .A1
       (dut_u_wr_n_2835), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_2825), .Y (dut_u_wr_n_2813));
  OAI211X1 dut_u_wr_g3581(.A0 (dut_u_wr_w_timer[7]), .A1
       (dut_u_wr_n_2833), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_2827), .Y (dut_u_wr_n_2817));
  AOI21X1 dut_u_wr_g3582(.A0 (dut_u_wr_n_3124), .A1 (dut_u_wr_n_2828),
       .B0 (dut_u_wr_n_3004), .Y (dut_u_wr_n_2823));
  AOI21X1 dut_u_wr_g3583(.A0 (dut_u_wr_n_3107), .A1 (dut_u_wr_n_2830),
       .B0 (dut_u_wr_n_3070), .Y (dut_u_wr_n_2824));
  NAND2X1 dut_u_wr_g3584(.A (dut_u_wr_b_timer[7]), .B
       (dut_u_wr_n_2835), .Y (dut_u_wr_n_2825));
  OAI211X1 dut_u_wr_g3587(.A0 (dut_u_wr_b_timer[6]), .A1
       (dut_u_wr_n_2850), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_2840), .Y (dut_u_wr_n_2828));
  OAI211X1 dut_u_wr_g3588(.A0 (dut_u_wr_w_timer[6]), .A1
       (dut_u_wr_n_2848), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_2841), .Y (dut_u_wr_n_2830));
  NAND2X1 dut_u_wr_g3589(.A (dut_u_wr_w_timer[7]), .B
       (dut_u_wr_n_2833), .Y (dut_u_wr_n_2827));
  INVX1 dut_u_wr_g3590(.A (dut_u_wr_n_2841), .Y (dut_u_wr_n_2833));
  INVX1 dut_u_wr_g3591(.A (dut_u_wr_n_2840), .Y (dut_u_wr_n_2835));
  AOI21XL dut_u_wr_g3592(.A0 (dut_u_wr_n_2842), .A1 (dut_u_wr_n_3110),
       .B0 (dut_u_wr_n_3004), .Y (dut_u_wr_n_2837));
  AOI21X1 dut_u_wr_g3593(.A0 (dut_u_wr_n_3125), .A1 (dut_u_wr_n_2844),
       .B0 (dut_u_wr_n_3070), .Y (dut_u_wr_n_2838));
  OAI211X1 dut_u_wr_g3598(.A0 (dut_u_wr_b_timer[5]), .A1
       (dut_u_wr_n_2865), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_2857), .Y (dut_u_wr_n_2842));
  OAI211X1 dut_u_wr_g3599(.A0 (dut_u_wr_w_timer[5]), .A1
       (dut_u_wr_n_2867), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_2858), .Y (dut_u_wr_n_2844));
  NAND2X1 dut_u_wr_g3600(.A (dut_u_wr_b_timer[6]), .B
       (dut_u_wr_n_2850), .Y (dut_u_wr_n_2840));
  NAND2X1 dut_u_wr_g3601(.A (dut_u_wr_w_timer[6]), .B
       (dut_u_wr_n_2848), .Y (dut_u_wr_n_2841));
  INVX1 dut_u_wr_g3602(.A (dut_u_wr_n_2858), .Y (dut_u_wr_n_2848));
  INVX1 dut_u_wr_g3603(.A (dut_u_wr_n_2857), .Y (dut_u_wr_n_2850));
  AOI21XL dut_u_wr_g3604(.A0 (dut_u_wr_n_2859), .A1 (dut_u_wr_n_3127),
       .B0 (dut_u_wr_n_3004), .Y (dut_u_wr_n_2852));
  AOI21X1 dut_u_wr_g3605(.A0 (dut_u_wr_n_3108), .A1 (dut_u_wr_n_2861),
       .B0 (dut_u_wr_n_3070), .Y (dut_u_wr_n_2853));
  OAI211X1 dut_u_wr_g3610(.A0 (dut_u_wr_b_timer[4]), .A1
       (dut_u_wr_n_2892), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_2879), .Y (dut_u_wr_n_2859));
  OAI211X1 dut_u_wr_g3611(.A0 (dut_u_wr_w_timer[4]), .A1
       (dut_u_wr_n_2894), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_2883), .Y (dut_u_wr_n_2861));
  NAND2X1 dut_u_wr_g3612(.A (dut_u_wr_b_timer[5]), .B
       (dut_u_wr_n_2865), .Y (dut_u_wr_n_2857));
  NAND2X1 dut_u_wr_g3613(.A (dut_u_wr_w_timer[5]), .B
       (dut_u_wr_n_2867), .Y (dut_u_wr_n_2858));
  INVX1 dut_u_wr_g3614(.A (dut_u_wr_n_2879), .Y (dut_u_wr_n_2865));
  INVX1 dut_u_wr_g3615(.A (dut_u_wr_n_2883), .Y (dut_u_wr_n_2867));
  NOR2BX1 dut_u_wr_g3616(.AN (n_230), .B (dut_epoch_clr), .Y
       (dut_u_wr_n_2869));
  AOI21XL dut_u_wr_g3618(.A0 (dut_u_wr_n_2888), .A1 (dut_u_wr_n_3111),
       .B0 (dut_u_wr_n_3004), .Y (dut_u_wr_n_2871));
  AOI21X1 dut_u_wr_g3619(.A0 (dut_u_wr_n_3126), .A1 (dut_u_wr_n_2884),
       .B0 (dut_u_wr_n_3070), .Y (dut_u_wr_n_2872));
  NAND4XL dut_u_wr_g3620(.A (dut_u_wr_n_3014), .B (dut_u_wr_n_2910), .C
       (dut_u_wr_n_2900), .D (dut_u_wr_n_2882), .Y (dut_u_wr_n_2873));
  NOR2X1 dut_u_wr_g3622(.A (dut_epoch_clr), .B (dut_u_wr_n_2882), .Y
       (dut_u_wr_n_2875));
  NAND2X1 dut_u_wr_g3625(.A (dut_u_wr_b_timer[4]), .B
       (dut_u_wr_n_2892), .Y (dut_u_wr_n_2879));
  OAI211X1 dut_u_wr_g3629(.A0 (dut_u_wr_w_timer[3]), .A1
       (dut_u_wr_n_2941), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_2918), .Y (dut_u_wr_n_2884));
  NOR2X1 dut_u_wr_g3630(.A (dut_epoch_clr), .B (dut_u_wr_n_2900), .Y
       (dut_u_wr_n_2886));
  OAI211X1 dut_u_wr_g3631(.A0 (dut_u_wr_b_timer[3]), .A1
       (dut_u_wr_n_2943), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_2919), .Y (dut_u_wr_n_2888));
  AOI221X1 dut_u_wr_g3632(.A0 (dut_u_wr_n_3058), .A1 (dut_u_wr_n_2998),
       .B0 (dut_u_wr_outst_cnt[2]), .B1 (dut_u_wr_n_2909), .C0
       (dut_u_wr_n_2906), .Y (dut_u_wr_n_2882));
  NAND2X1 dut_u_wr_g3633(.A (dut_u_wr_w_timer[4]), .B
       (dut_u_wr_n_2894), .Y (dut_u_wr_n_2883));
  INVX1 dut_u_wr_g3634(.A (dut_u_wr_n_2919), .Y (dut_u_wr_n_2892));
  INVX1 dut_u_wr_g3635(.A (dut_u_wr_n_2918), .Y (dut_u_wr_n_2894));
  NOR2X1 dut_u_wr_g3636(.A (dut_epoch_clr), .B (dut_u_wr_n_2910), .Y
       (dut_u_wr_n_2896));
  AOI21XL dut_u_wr_g3637(.A0 (dut_u_wr_n_2932), .A1 (dut_u_wr_n_3109),
       .B0 (dut_u_wr_n_3004), .Y (dut_u_wr_n_2898));
  AOI21X1 dut_u_wr_g3640(.A0 (dut_u_wr_n_3105), .A1 (dut_u_wr_n_2922),
       .B0 (dut_u_wr_n_3070), .Y (dut_u_wr_n_2901));
  AOI211XL dut_u_wr_g3641(.A0 (dut_u_wr_n_3062), .A1 (dut_u_wr_n_2998),
       .B0 (dut_u_wr_n_2917), .C0 (dut_u_wr_n_2909), .Y
       (dut_u_wr_n_2902));
  AOI221X1 dut_u_wr_g3642(.A0 (dut_u_wr_n_3069), .A1 (dut_u_wr_n_2997),
       .B0 (dut_u_wr_outst_cnt[1]), .B1 (dut_u_wr_n_2936), .C0
       (dut_u_wr_n_2924), .Y (dut_u_wr_n_2900));
  NOR2BX1 dut_u_wr_g3643(.AN (dut_u_wr_n_2917), .B (dut_u_wr_n_3116),
       .Y (dut_u_wr_n_2906));
  OAI222X1 dut_u_wr_g3647(.A0 (dut_u_wr_n_3000), .A1 (dut_u_wr_n_3057),
       .B0 (dut_u_wr_n_3144), .B1 (dut_u_wr_n_2949), .C0
       (dut_u_wr_n_2959), .C1 (dut_u_wr_n_3117), .Y (dut_u_wr_n_2912));
  OAI2BB1X1 dut_u_wr_g3648(.A0N (dut_u_wr_n_3116), .A1N
       (dut_u_wr_n_2997), .B0 (dut_u_wr_n_2965), .Y (dut_u_wr_n_2909));
  XOR2XL dut_u_wr_g3649(.A (dut_u_wr_outst_cnt[0]), .B
       (dut_u_wr_n_2936), .Y (dut_u_wr_n_2910));
  NOR2BX1 dut_u_wr_g3650(.AN (dut_u_wr_n_2997), .B
       (dut_u_wr_outst_cnt[2]), .Y (dut_u_wr_n_2917));
  NAND2X1 dut_u_wr_g3651(.A (dut_u_wr_w_timer[3]), .B
       (dut_u_wr_n_2941), .Y (dut_u_wr_n_2918));
  NAND2X1 dut_u_wr_g3652(.A (dut_u_wr_b_timer[3]), .B
       (dut_u_wr_n_2943), .Y (dut_u_wr_n_2919));
  OAI211X1 dut_u_wr_g3657(.A0 (dut_u_wr_w_timer[2]), .A1
       (dut_u_wr_n_3036), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_2996), .Y (dut_u_wr_n_2922));
  NOR2BX1 dut_u_wr_g3658(.AN (dut_u_wr_n_2998), .B (dut_u_wr_n_3069),
       .Y (dut_u_wr_n_2924));
  NAND3BXL dut_u_wr_g3659(.AN (dut_u_wr_n_3116), .B
       (dut_u_wr_outst_cnt[2]), .C (dut_u_wr_n_2997), .Y
       (dut_u_wr_n_2926));
  OAI211X1 dut_u_wr_g3660(.A0 (dut_u_wr_n_3000), .A1 (dut_u_wr_n_2968),
       .B0 (dut_u_wr_n_2959), .C0 (dut_u_wr_n_2949), .Y
       (dut_u_wr_n_2927));
  OAI211X1 dut_u_wr_g3661(.A0 (dut_u_wr_n_3002), .A1 (dut_u_wr_n_3060),
       .B0 (dut_u_wr_n_3209), .C0 (dut_u_wr_n_2945), .Y
       (dut_u_wr_n_2931));
  OAI211X1 dut_u_wr_g3662(.A0 (dut_u_wr_b_timer[2]), .A1
       (dut_u_wr_n_3038), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_2995), .Y (dut_u_wr_n_2932));
  NAND2BXL dut_u_wr_g3663(.AN (dut_u_wr_n_3062), .B (dut_u_wr_n_2998),
       .Y (dut_u_wr_n_2934));
  INVX1 dut_u_wr_g3664(.A (dut_u_wr_n_2965), .Y (dut_u_wr_n_2936));
  INVX1 dut_u_wr_g3665(.A (dut_u_wr_n_2996), .Y (dut_u_wr_n_2941));
  INVX1 dut_u_wr_g3666(.A (dut_u_wr_n_2995), .Y (dut_u_wr_n_2943));
  NAND2X1 dut_u_wr_g3667(.A (dut_u_wr_drain_cnt[1]), .B
       (dut_u_wr_n_2964), .Y (dut_u_wr_n_2945));
  AOI21XL dut_u_wr_g3668(.A0 (dut_u_wr_n_3011), .A1 (dut_u_wr_n_3122),
       .B0 (dut_u_wr_n_3004), .Y (dut_u_wr_n_2948));
  OAI32X1 dut_u_wr_g3672(.A0 (dut_u_wr_n_3144), .A1 (dut_u_wr_n_3002),
       .A2 (dut_u_wr_n_3117), .B0 (dut_u_wr_n_3000), .B1
       (dut_u_wr_n_3063), .Y (dut_u_wr_n_2952));
  AOI21X1 dut_u_wr_g3673(.A0 (dut_u_wr_n_3121), .A1 (dut_u_wr_n_3008),
       .B0 (dut_u_wr_n_3070), .Y (dut_u_wr_n_2956));
  OAI22X1 dut_u_wr_g3674(.A0 (dut_u_wr_n_2473), .A1 (dut_u_wr_n_2994),
       .B0 (dut_u_wr_n_3113), .B1 (dut_u_wr_n_3064), .Y
       (dut_u_wr_n_2957));
  AOI21X1 dut_u_wr_g3675(.A0 (dut_u_wr_n_3003), .A1 (dut_u_wr_n_3117),
       .B0 (dut_u_wr_n_2964), .Y (dut_u_wr_n_2949));
  NAND2XL dut_u_wr_g3676(.A (dut_u_wr_n_3000), .B (dut_u_wr_n_3002), .Y
       (dut_u_wr_n_2960));
  NAND2X1 dut_u_wr_g3678(.A (dut_u_wr_n_3003), .B (dut_u_wr_n_3144), .Y
       (dut_u_wr_n_2959));
  OAI22XL dut_u_wr_g3679(.A0 (dut_u_wr_n_3041), .A1 (dut_u_wr_n_3080),
       .B0 (dut_u_wr_n_3076), .B1 (dut_epoch_clr), .Y
       (dut_u_wr_n_2966));
  NOR2XL dut_u_wr_g3680(.A (dut_u_wr_n_3074), .B (dut_u_wr_n_3004), .Y
       (dut_u_wr_n_2967));
  MX2X1 dut_u_wr_g3681(.A (dut_u_wr_n_3042), .B (dut_u_wr_n_3040), .S0
       (dut_u_wr_n_3119), .Y (dut_u_wr_n_2964));
  XNOR2X1 dut_u_wr_g3682(.A (dut_u_wr_n_3043), .B (dut_u_wr_n_3120), .Y
       (dut_u_wr_n_2965));
  INVX1 dut_u_wr_g3683(.A (dut_u_wr_n_3063), .Y (dut_u_wr_n_2968));
  INVX1 dut_u_wr_g3709(.A (dut_u_wr_n_3002), .Y (dut_u_wr_n_3003));
  OAI211X1 dut_u_wr_g3710(.A0 (dut_u_wr_w_timer[0]), .A1
       (dut_u_wr_w_timer[1]), .B0 (dut_u_wr_w_timer_run), .C0
       (dut_u_wr_n_3082), .Y (dut_u_wr_n_3008));
  OAI211X1 dut_u_wr_g3711(.A0 (dut_u_wr_b_timer[0]), .A1
       (dut_u_wr_b_timer[1]), .B0 (dut_u_wr_b_timer_run), .C0
       (dut_u_wr_n_3083), .Y (dut_u_wr_n_3011));
  NAND2XL dut_u_wr_g3712(.A (dut_u_wr_n_3079), .B (n_223), .Y
       (dut_u_wr_n_3014));
  AND2X1 dut_u_wr_g3725(.A (dut_u_wr_n_3045), .B (dut_u_wr_n_3210), .Y
       (dut_u_wr_n_2994));
  NAND2X1 dut_u_wr_g3727(.A (dut_u_wr_b_timer[2]), .B
       (dut_u_wr_n_3038), .Y (dut_u_wr_n_2995));
  NAND2X1 dut_u_wr_g3728(.A (dut_u_wr_w_timer[2]), .B
       (dut_u_wr_n_3036), .Y (dut_u_wr_n_2996));
  NOR2X1 dut_u_wr_g3729(.A (dut_u_wr_n_3043), .B (dut_u_wr_n_3120), .Y
       (dut_u_wr_n_2997));
  AND2XL dut_u_wr_g3730(.A (dut_u_wr_n_3043), .B (dut_u_wr_n_3120), .Y
       (dut_u_wr_n_2998));
  NAND2BX1 dut_u_wr_g3731(.AN (dut_u_wr_n_3119), .B (dut_u_wr_n_3040),
       .Y (dut_u_wr_n_3000));
  NAND2X1 dut_u_wr_g3732(.A (dut_u_wr_n_3119), .B (dut_u_wr_n_3042), .Y
       (dut_u_wr_n_3002));
  OR3X1 dut_u_wr_g3734(.A (dut_wr_timeout_pulse), .B (dut_u_wr_n_3043),
       .C (dut_epoch_clr), .Y (dut_u_wr_n_3004));
  INVX1 dut_u_wr_g3735(.A (dut_u_wr_n_3082), .Y (dut_u_wr_n_3036));
  INVX1 dut_u_wr_g3736(.A (dut_u_wr_n_3083), .Y (dut_u_wr_n_3038));
  INVXL dut_u_wr_g3737(.A (dut_u_wr_n_3040), .Y (dut_u_wr_n_3041));
  NOR2X1 dut_u_wr_g3738(.A (dut_u_wr_n_3075), .B (dut_u_wr_n_3070), .Y
       (dut_u_wr_n_3044));
  NAND2BX1 dut_u_wr_g3739(.AN (dut_u_wr_n_3064), .B (dut_u_wr_n_3113),
       .Y (dut_u_wr_n_3045));
  NOR2BX1 dut_u_wr_g3740(.AN (dut_u_wr_n_3061), .B (dut_epoch_clr), .Y
       (dut_u_wr_n_3040));
  NOR2X1 dut_u_wr_g3741(.A (dut_u_wr_n_3061), .B (dut_epoch_clr), .Y
       (dut_u_wr_n_3042));
  NAND2X1 dut_u_wr_g3742(.A (dut_u_wr_n_3061), .B (dut_u_wr_n_3079), .Y
       (dut_u_wr_n_3043));
  AOI2BB1X1 dut_u_wr_g3743(.A0N (dut_u_wr_downstream_aw_done), .A1N
       (dut_u_wr_downstream_aw_fire), .B0 (dut_u_wr_n_3064), .Y
       (dut_u_wr_n_3051));
  AOI2BB1X1 dut_u_wr_g3744(.A0N (dut_u_wr_downstream_w_done), .A1N
       (dut_u_wr_downstream_w_fire), .B0 (dut_u_wr_n_3064), .Y
       (dut_u_wr_n_3053));
  OA21X1 dut_u_wr_g3746(.A0 (dut_u_wr_n_3144), .A1 (dut_u_wr_n_3115),
       .B0 (dut_u_wr_n_3063), .Y (dut_u_wr_n_3057));
  OAI21X1 dut_u_wr_g3747(.A0 (dut_u_wr_n_3147), .A1 (dut_u_wr_n_3114),
       .B0 (dut_u_wr_n_3062), .Y (dut_u_wr_n_3058));
  NAND2BX1 dut_u_wr_g3749(.AN (dut_u_wr_n_3115), .B (dut_u_wr_n_3117),
       .Y (dut_u_wr_n_3060));
  NAND2BX1 dut_u_wr_g3750(.AN (dut_u_wr_n_3080), .B (s_bready), .Y
       (dut_u_wr_n_3061));
  NAND2X1 dut_u_wr_g3751(.A (dut_u_wr_n_3147), .B (dut_u_wr_n_3114), .Y
       (dut_u_wr_n_3062));
  NAND2X1 dut_u_wr_g3752(.A (dut_u_wr_n_3144), .B (dut_u_wr_n_3115), .Y
       (dut_u_wr_n_3063));
  NAND2BX1 dut_u_wr_g3753(.AN (dut_u_wr_w_perm_BAR), .B
       (dut_u_wr_n_3120), .Y (dut_u_wr_n_3064));
  XNOR2X1 dut_u_wr_g3754(.A (dut_u_wr_b_timer_run), .B
       (dut_u_wr_b_timer[0]), .Y (dut_u_wr_n_3074));
  XNOR2X1 dut_u_wr_g3755(.A (dut_u_wr_w_timer_run), .B
       (dut_u_wr_w_timer[0]), .Y (dut_u_wr_n_3075));
  AOI21XL dut_u_wr_g3756(.A0 (dut_flush), .A1 (dut_u_wr_n_360), .B0
       (dut_wr_timeout_pulse), .Y (dut_u_wr_n_3076));
  NOR2BX1 dut_u_wr_g3757(.AN (dut_u_wr_n_3116), .B (dut_u_wr_n_3114),
       .Y (dut_u_wr_n_3069));
  NAND2X1 dut_u_wr_g3758(.A (dut_u_wr_n_3104), .B (dut_u_wr_n_3120), .Y
       (dut_u_wr_n_3070));
  NAND2X1 dut_u_wr_g3759(.A (dut_u_wr_n_3175), .B
       (dut_u_wr_b_timer[7]), .Y (dut_u_wr_n_3102));
  NOR2XL dut_u_wr_g3760(.A (dut_wr_w_fault_pulse), .B (dut_epoch_clr),
       .Y (dut_u_wr_n_3104));
  NAND2X1 dut_u_wr_g3761(.A (dut_u_wr_n_3151), .B
       (dut_u_wr_w_timer[2]), .Y (dut_u_wr_n_3105));
  NAND2X1 dut_u_wr_g3762(.A (dut_u_wr_n_3151), .B
       (dut_u_wr_w_timer[6]), .Y (dut_u_wr_n_3107));
  NAND2X1 dut_u_wr_g3763(.A (dut_u_wr_n_3151), .B
       (dut_u_wr_w_timer[4]), .Y (dut_u_wr_n_3108));
  NAND2X1 dut_u_wr_g3764(.A (dut_u_wr_n_3175), .B
       (dut_u_wr_b_timer[2]), .Y (dut_u_wr_n_3109));
  NAND2X1 dut_u_wr_g3765(.A (dut_u_wr_n_3175), .B
       (dut_u_wr_b_timer[5]), .Y (dut_u_wr_n_3110));
  NAND2X1 dut_u_wr_g3766(.A (dut_u_wr_n_3175), .B
       (dut_u_wr_b_timer[3]), .Y (dut_u_wr_n_3111));
  NAND2X1 dut_u_wr_g3767(.A (dut_u_wr_n_363), .B (s_bvalid), .Y
       (dut_u_wr_n_3079));
  NAND2BX1 dut_u_wr_g3768(.AN (dut_u_wr_wr_state[0]), .B
       (dut_u_wr_wr_state[1]), .Y (dut_u_wr_n_3080));
  NAND2X1 dut_u_wr_g3770(.A (dut_u_wr_w_timer[1]), .B
       (dut_u_wr_w_timer[0]), .Y (dut_u_wr_n_3082));
  NAND2X1 dut_u_wr_g3771(.A (dut_u_wr_b_timer[1]), .B
       (dut_u_wr_b_timer[0]), .Y (dut_u_wr_n_3083));
  OR2X2 dut_u_wr_g3772(.A (dut_u_wr_n_2029), .B (dut_u_wr_n_3152), .Y
       (dut_u_wr_n_3084));
  NAND2X1 dut_u_wr_g3773(.A (dut_u_wr_n_3151), .B
       (dut_u_wr_w_timer[1]), .Y (dut_u_wr_n_3121));
  NAND2X1 dut_u_wr_g3774(.A (dut_u_wr_n_3175), .B
       (dut_u_wr_b_timer[1]), .Y (dut_u_wr_n_3122));
  NAND2X1 dut_u_wr_g3775(.A (dut_u_wr_n_3151), .B
       (dut_u_wr_w_timer[7]), .Y (dut_u_wr_n_3123));
  NAND2X1 dut_u_wr_g3776(.A (dut_u_wr_n_3175), .B
       (dut_u_wr_b_timer[6]), .Y (dut_u_wr_n_3124));
  NAND2X1 dut_u_wr_g3777(.A (dut_u_wr_n_3151), .B
       (dut_u_wr_w_timer[5]), .Y (dut_u_wr_n_3125));
  NAND2X1 dut_u_wr_g3778(.A (dut_u_wr_n_3151), .B
       (dut_u_wr_w_timer[3]), .Y (dut_u_wr_n_3126));
  NAND2X1 dut_u_wr_g3779(.A (dut_u_wr_n_3175), .B
       (dut_u_wr_b_timer[4]), .Y (dut_u_wr_n_3127));
  NOR2X1 dut_u_wr_g3780(.A (dut_wr_w_fault_pulse), .B (dut_flush), .Y
       (dut_u_wr_n_3113));
  NOR2X1 dut_u_wr_g3781(.A (dut_u_wr_outst_cnt[1]), .B
       (dut_u_wr_outst_cnt[0]), .Y (dut_u_wr_n_3114));
  NOR2X1 dut_u_wr_g3782(.A (dut_u_wr_drain_cnt[1]), .B
       (dut_u_wr_drain_cnt[0]), .Y (dut_u_wr_n_3115));
  NAND2X1 dut_u_wr_g3783(.A (dut_u_wr_outst_cnt[1]), .B
       (dut_u_wr_outst_cnt[0]), .Y (dut_u_wr_n_3116));
  NAND2X1 dut_u_wr_g3784(.A (dut_u_wr_drain_cnt[1]), .B
       (dut_u_wr_drain_cnt[0]), .Y (dut_u_wr_n_3117));
  NAND2X1 dut_u_wr_g3785(.A (m_bvalid), .B (dut_u_wr_n_362), .Y
       (dut_u_wr_n_3119));
  INVX1 dut_u_wr_g3791(.A (dut_u_wr_w_timer_run), .Y (dut_u_wr_n_3151));
  INVXL dut_u_wr_g3792(.A (s_awready), .Y (dut_u_wr_n_3152));
  INVX1 dut_u_wr_g3794(.A (dut_u_wr_b_timer_run), .Y (dut_u_wr_n_3175));
  NAND2BX1 dut_u_wr_g2(.AN (dut_u_wr_n_3000), .B (dut_u_wr_n_3060), .Y
       (dut_u_wr_n_3209));
  NAND2BX1 dut_u_wr_g3795(.AN (dut_epoch_clr), .B (dut_u_wr_n_3131), .Y
       (dut_u_wr_n_3210));
  OR4X1 dut_u_rd_g1153(.A (dut_u_rd_outst_cnt[0]), .B
       (dut_u_rd_outst_cnt[1]), .C (dut_u_rd_outst_cnt[2]), .D
       (dut_u_rd_outst_cnt[3]), .Y (dut_u_rd_n_272));
  OR2XL dut_u_rd_g1154(.A (dut_u_rd_n_272), .B (dut_u_rd_n_259), .Y
       (dut_rd_busy));
  OR4X1 dut_u_rd_g1155(.A (dut_u_rd_drain_cnt[3]), .B
       (dut_u_rd_drain_cnt[2]), .C (dut_u_rd_drain_cnt[1]), .D
       (dut_u_rd_drain_cnt[0]), .Y (dut_u_rd_n_259));
  AND3XL dut_u_rd_g1935(.A (dut_u_rd_n_1632), .B (dut_u_rd_n_1603), .C
       (dut_u_rd_timer_run), .Y (dut_rd_timeout_pulse));
  AND3X1 dut_u_rd_g1936(.A (s_arvalid), .B (dut_u_rd_n_1622), .C
       (dut_u_rd_n_252), .Y (m_arvalid));
  OR2X1 dut_u_rd_g1938(.A (dut_u_rd_n_259), .B (dut_u_rd_n_260), .Y
       (m_rready));
  NAND3BXL dut_u_rd_g1939(.AN (dut_flush), .B (m_arready), .C
       (dut_u_rd_n_1622), .Y (dut_u_rd_n_1597));
  AO21X1 dut_u_rd_g1940(.A0 (\m_r[resp] [1]), .A1 (dut_u_rd_n_257), .B0
       (n_224), .Y (\s_r[resp] [1]));
  AO21X1 dut_u_rd_g1941(.A0 (dut_u_rd_n_257), .A1 (dut_u_rd_n_1647),
       .B0 (n_224), .Y (s_rvalid));
  NOR4X1 dut_u_rd_g1942(.A (dut_u_rd_timer[7]), .B (dut_u_rd_timer[3]),
       .C (dut_u_rd_timer[2]), .D (dut_u_rd_n_1643), .Y
       (dut_u_rd_n_1603));
  AND2X1 dut_u_rd_g1943(.A (dut_u_rd_n_257), .B (\m_r[data] [25]), .Y
       (\s_r[data] [25]));
  AND2X1 dut_u_rd_g1944(.A (dut_u_rd_n_257), .B (\m_r[data] [12]), .Y
       (\s_r[data] [12]));
  AND2X1 dut_u_rd_g1945(.A (dut_u_rd_n_257), .B (\m_r[data] [11]), .Y
       (\s_r[data] [11]));
  AND2X1 dut_u_rd_g1946(.A (dut_u_rd_n_257), .B (\m_r[data] [27]), .Y
       (\s_r[data] [27]));
  AND2X1 dut_u_rd_g1947(.A (dut_u_rd_n_257), .B (\m_r[data] [10]), .Y
       (\s_r[data] [10]));
  AND2X1 dut_u_rd_g1948(.A (dut_u_rd_n_257), .B (\m_r[data] [9]), .Y
       (\s_r[data] [9]));
  AND2X1 dut_u_rd_g1949(.A (dut_u_rd_n_257), .B (\m_r[data] [26]), .Y
       (\s_r[data] [26]));
  AND2X1 dut_u_rd_g1950(.A (dut_u_rd_n_257), .B (\m_r[data] [8]), .Y
       (\s_r[data] [8]));
  AND2X1 dut_u_rd_g1951(.A (dut_u_rd_n_257), .B (\m_r[data] [7]), .Y
       (\s_r[data] [7]));
  AND2X1 dut_u_rd_g1952(.A (dut_u_rd_n_257), .B (\m_r[data] [28]), .Y
       (\s_r[data] [28]));
  AND2X1 dut_u_rd_g1953(.A (dut_u_rd_n_257), .B (\m_r[data] [6]), .Y
       (\s_r[data] [6]));
  AND2X1 dut_u_rd_g1954(.A (dut_u_rd_n_257), .B (\m_r[data] [5]), .Y
       (\s_r[data] [5]));
  AND2X1 dut_u_rd_g1955(.A (dut_u_rd_n_257), .B (\m_r[data] [23]), .Y
       (\s_r[data] [23]));
  AND2X1 dut_u_rd_g1956(.A (dut_u_rd_n_257), .B (\m_r[data] [4]), .Y
       (\s_r[data] [4]));
  AND2X1 dut_u_rd_g1957(.A (dut_u_rd_n_257), .B (\m_r[data] [3]), .Y
       (\s_r[data] [3]));
  AND2X1 dut_u_rd_g1958(.A (dut_u_rd_n_257), .B (\m_r[data] [2]), .Y
       (\s_r[data] [2]));
  AND2X1 dut_u_rd_g1959(.A (dut_u_rd_n_257), .B (\m_r[data] [1]), .Y
       (\s_r[data] [1]));
  AND2X1 dut_u_rd_g1960(.A (dut_u_rd_n_257), .B (\m_r[data] [22]), .Y
       (\s_r[data] [22]));
  AND2X1 dut_u_rd_g1961(.A (dut_u_rd_n_257), .B (\m_r[data] [30]), .Y
       (\s_r[data] [30]));
  AND2X1 dut_u_rd_g1962(.A (dut_u_rd_n_257), .B (\m_r[data] [24]), .Y
       (\s_r[data] [24]));
  AND2X1 dut_u_rd_g1963(.A (dut_u_rd_n_257), .B (\m_r[data] [21]), .Y
       (\s_r[data] [21]));
  AND2X1 dut_u_rd_g1964(.A (dut_u_rd_n_257), .B (\m_r[data] [20]), .Y
       (\s_r[data] [20]));
  AND2X1 dut_u_rd_g1965(.A (dut_u_rd_n_257), .B (\m_r[data] [19]), .Y
       (\s_r[data] [19]));
  AND2X1 dut_u_rd_g1966(.A (dut_u_rd_n_257), .B (\m_r[data] [31]), .Y
       (\s_r[data] [31]));
  AND2X1 dut_u_rd_g1967(.A (dut_u_rd_n_257), .B (\m_r[data] [18]), .Y
       (\s_r[data] [18]));
  NOR4X1 dut_u_rd_g1968(.A (dut_u_rd_timer[0]), .B (dut_u_rd_timer[1]),
       .C (dut_u_rd_timer[5]), .D (dut_u_rd_timer[4]), .Y
       (dut_u_rd_n_1632));
  AND2X1 dut_u_rd_g1969(.A (dut_u_rd_n_257), .B (\m_r[data] [17]), .Y
       (\s_r[data] [17]));
  AND2X1 dut_u_rd_g1970(.A (dut_u_rd_n_257), .B (\m_r[data] [0]), .Y
       (\s_r[data] [0]));
  AND2X1 dut_u_rd_g1971(.A (dut_u_rd_n_257), .B (\m_r[resp] [0]), .Y
       (\s_r[resp] [0]));
  AND2X1 dut_u_rd_g1972(.A (dut_u_rd_n_257), .B (\m_r[data] [16]), .Y
       (\s_r[data] [16]));
  AND2X1 dut_u_rd_g1973(.A (dut_u_rd_n_257), .B (\m_r[data] [15]), .Y
       (\s_r[data] [15]));
  AND2X1 dut_u_rd_g1974(.A (dut_u_rd_n_257), .B (\m_r[data] [29]), .Y
       (\s_r[data] [29]));
  AND2X1 dut_u_rd_g1975(.A (dut_u_rd_n_257), .B (\m_r[data] [14]), .Y
       (\s_r[data] [14]));
  AND2X1 dut_u_rd_g1976(.A (dut_u_rd_n_257), .B (\m_r[data] [13]), .Y
       (\s_r[data] [13]));
  OR4X1 dut_u_rd_g1977(.A (dut_u_rd_outst_cnt[0]), .B
       (dut_u_rd_outst_cnt[1]), .C (dut_u_rd_outst_cnt[2]), .D
       (dut_u_rd_n_1652), .Y (dut_u_rd_n_1622));
  AND2XL dut_u_rd_g1979(.A (s_rready), .B (dut_u_rd_n_257), .Y
       (dut_u_rd_n_260));
  NAND2BX1 dut_u_rd_g1980(.AN (dut_u_rd_timer[6]), .B
       (dut_u_rd_timer[8]), .Y (dut_u_rd_n_1643));
  NOR2BX1 dut_u_rd_g1984(.AN (m_rvalid), .B (dut_u_rd_n_259), .Y
       (dut_u_rd_n_1647));
  AND2X1 dut_u_rd_g1985(.A (dut_u_rd_rd_state[0]), .B
       (dut_u_rd_n_1657), .Y (dut_u_rd_n_257));
  NOR2BX1 dut_u_rd_g2(.AN (dut_u_rd_n_257), .B (dut_u_rd_n_1647), .Y
       (dut_u_rd_timer_run));
  SDFFRHQX1 \dut_u_rd_drain_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2004), .SI (dut_u_rd_n_2010), .SE
       (dut_u_rd_drain_cnt[0]), .Q (dut_u_rd_drain_cnt[0]));
  DFFRHQX1 \dut_u_rd_drain_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_1968), .Q (dut_u_rd_drain_cnt[1]));
  SDFFRHQX1 \dut_u_rd_drain_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_1998), .SI (dut_u_rd_n_1981), .SE
       (dut_u_rd_drain_cnt[2]), .Q (dut_u_rd_drain_cnt[2]));
  SDFFRHQX1 \dut_u_rd_drain_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2110), .SI (dut_u_rd_n_1967), .SE
       (dut_u_rd_drain_cnt[3]), .Q (dut_u_rd_drain_cnt[3]));
  DFFRHQX1 \dut_u_rd_outst_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_1956), .Q (dut_u_rd_outst_cnt[0]));
  DFFRHQX1 \dut_u_rd_outst_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_1950), .Q (dut_u_rd_outst_cnt[1]));
  DFFRHQX1 \dut_u_rd_outst_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_1935), .Q (dut_u_rd_outst_cnt[2]));
  DFFRHQX1 \dut_u_rd_rd_state_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_1926), .Q (dut_u_rd_rd_state[0]));
  DFFRHQX1 \dut_u_rd_timer_reg[0] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2013), .Q (dut_u_rd_timer[0]));
  DFFRHQX1 \dut_u_rd_timer_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2000), .Q (dut_u_rd_timer[1]));
  DFFRHQX1 \dut_u_rd_timer_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_1959), .Q (dut_u_rd_timer[2]));
  DFFRHQX1 \dut_u_rd_timer_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_1936), .Q (dut_u_rd_timer[3]));
  DFFRHQX1 \dut_u_rd_timer_reg[4] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_1925), .Q (dut_u_rd_timer[4]));
  DFFRHQX1 \dut_u_rd_timer_reg[5] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_1918), .Q (dut_u_rd_timer[5]));
  DFFRHQX1 \dut_u_rd_timer_reg[6] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_1911), .Q (dut_u_rd_timer[6]));
  DFFRHQX1 \dut_u_rd_timer_reg[7] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_1903), .Q (dut_u_rd_timer[7]));
  DFFRHQX1 \dut_u_rd_timer_reg[8] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_1898), .Q (dut_u_rd_timer[8]));
  NOR2XL dut_u_rd_g3099(.A (dut_u_rd_n_1901), .B (dut_u_rd_n_2028), .Y
       (dut_u_rd_n_1898));
  AOI22X1 dut_u_rd_g3101(.A0 (dut_u_rd_timer_run), .A1
       (dut_u_rd_n_1905), .B0 (dut_u_rd_n_2099), .B1
       (dut_u_rd_timer[8]), .Y (dut_u_rd_n_1901));
  AOI21XL dut_u_rd_g3102(.A0 (dut_u_rd_n_1906), .A1 (dut_u_rd_n_2061),
       .B0 (dut_u_rd_n_2028), .Y (dut_u_rd_n_1903));
  XNOR2X1 dut_u_rd_g3103(.A (dut_u_rd_timer[8]), .B (dut_u_rd_n_1912),
       .Y (dut_u_rd_n_1905));
  OAI211X1 dut_u_rd_g3105(.A0 (dut_u_rd_timer[7]), .A1
       (dut_u_rd_n_1916), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_1912), .Y (dut_u_rd_n_1906));
  AOI21XL dut_u_rd_g3106(.A0 (dut_u_rd_n_1913), .A1 (dut_u_rd_n_2070),
       .B0 (dut_u_rd_n_2028), .Y (dut_u_rd_n_1911));
  OAI211X1 dut_u_rd_g3108(.A0 (dut_u_rd_timer[6]), .A1
       (dut_u_rd_n_1923), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_1919), .Y (dut_u_rd_n_1913));
  NAND2X1 dut_u_rd_g3109(.A (dut_u_rd_timer[7]), .B (dut_u_rd_n_1916),
       .Y (dut_u_rd_n_1912));
  INVX1 dut_u_rd_g3110(.A (dut_u_rd_n_1919), .Y (dut_u_rd_n_1916));
  AOI21XL dut_u_rd_g3111(.A0 (dut_u_rd_n_1920), .A1 (dut_u_rd_n_2069),
       .B0 (dut_u_rd_n_2028), .Y (dut_u_rd_n_1918));
  OAI211X1 dut_u_rd_g3113(.A0 (dut_u_rd_timer[5]), .A1
       (dut_u_rd_n_1933), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_1927), .Y (dut_u_rd_n_1920));
  NAND2X1 dut_u_rd_g3114(.A (dut_u_rd_timer[6]), .B (dut_u_rd_n_1923),
       .Y (dut_u_rd_n_1919));
  INVX1 dut_u_rd_g3115(.A (dut_u_rd_n_1927), .Y (dut_u_rd_n_1923));
  AOI21XL dut_u_rd_g3117(.A0 (dut_u_rd_n_1930), .A1 (dut_u_rd_n_2071),
       .B0 (dut_u_rd_n_2028), .Y (dut_u_rd_n_1925));
  OAI211X1 dut_u_rd_g3118(.A0 (dut_u_rd_n_2063), .A1 (dut_u_rd_n_2050),
       .B0 (dut_u_rd_n_2044), .C0 (dut_u_rd_n_1928), .Y
       (dut_u_rd_n_1926));
  OAI2BB1X1 dut_u_rd_g3121(.A0N (dut_u_rd_n_2039), .A1N
       (dut_u_rd_n_2050), .B0 (dut_u_rd_n_1937), .Y (dut_u_rd_n_1928));
  OAI211X1 dut_u_rd_g3122(.A0 (dut_u_rd_timer[4]), .A1
       (dut_u_rd_n_1954), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_1947), .Y (dut_u_rd_n_1930));
  NAND2X1 dut_u_rd_g3123(.A (dut_u_rd_timer[5]), .B (dut_u_rd_n_1933),
       .Y (dut_u_rd_n_1927));
  INVX1 dut_u_rd_g3124(.A (dut_u_rd_n_1947), .Y (dut_u_rd_n_1933));
  NOR2X1 dut_u_rd_g3125(.A (dut_epoch_clr), .B (dut_u_rd_n_1940), .Y
       (dut_u_rd_n_1935));
  AOI21XL dut_u_rd_g3127(.A0 (dut_u_rd_n_1948), .A1 (dut_u_rd_n_2060),
       .B0 (dut_u_rd_n_2028), .Y (dut_u_rd_n_1936));
  NAND4XL dut_u_rd_g3128(.A (dut_u_rd_n_1966), .B (dut_u_rd_n_1958), .C
       (dut_u_rd_n_1946), .D (dut_u_rd_n_1940), .Y (dut_u_rd_n_1937));
  NOR2X1 dut_u_rd_g3131(.A (dut_epoch_clr), .B (dut_u_rd_n_1946), .Y
       (dut_u_rd_n_1941));
  AOI221X1 dut_u_rd_g3132(.A0 (dut_u_rd_n_2051), .A1 (dut_u_rd_n_2018),
       .B0 (dut_u_rd_outst_cnt[2]), .B1 (dut_u_rd_n_1960), .C0
       (dut_u_rd_n_1982), .Y (dut_u_rd_n_1940));
  OAI211X1 dut_u_rd_g3136(.A0 (dut_u_rd_timer[3]), .A1
       (dut_u_rd_n_1996), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_1972), .Y (dut_u_rd_n_1948));
  NOR2X1 dut_u_rd_g3137(.A (dut_epoch_clr), .B (dut_u_rd_n_1958), .Y
       (dut_u_rd_n_1950));
  XNOR2X1 dut_u_rd_g3138(.A (dut_u_rd_outst_cnt[3]), .B
       (dut_u_rd_n_1963), .Y (dut_u_rd_n_1946));
  NAND2X1 dut_u_rd_g3139(.A (dut_u_rd_timer[4]), .B (dut_u_rd_n_1954),
       .Y (dut_u_rd_n_1947));
  INVX1 dut_u_rd_g3140(.A (dut_u_rd_n_1972), .Y (dut_u_rd_n_1954));
  NOR2XL dut_u_rd_g3141(.A (dut_epoch_clr), .B (dut_u_rd_n_1966), .Y
       (dut_u_rd_n_1956));
  AOI21XL dut_u_rd_g3143(.A0 (dut_u_rd_n_1988), .A1 (dut_u_rd_n_2058),
       .B0 (dut_u_rd_n_2028), .Y (dut_u_rd_n_1959));
  OAI211X1 dut_u_rd_g3144(.A0 (dut_u_rd_n_2064), .A1 (dut_u_rd_n_2027),
       .B0 (dut_u_rd_n_1993), .C0 (dut_u_rd_n_1973), .Y
       (dut_u_rd_n_1960));
  AOI221X1 dut_u_rd_g3145(.A0 (dut_u_rd_n_2047), .A1 (dut_u_rd_n_2018),
       .B0 (dut_u_rd_outst_cnt[1]), .B1 (dut_u_rd_n_2012), .C0
       (dut_u_rd_n_1976), .Y (dut_u_rd_n_1958));
  NAND2BXL dut_u_rd_g3146(.AN (dut_u_rd_n_1982), .B (dut_u_rd_n_1974),
       .Y (dut_u_rd_n_1963));
  OAI211X1 dut_u_rd_g3148(.A0 (dut_u_rd_n_2019), .A1
       (dut_u_rd_drain_cnt[2]), .B0 (dut_u_rd_n_2002), .C0
       (dut_u_rd_n_1980), .Y (dut_u_rd_n_1967));
  OAI211X1 dut_u_rd_g3149(.A0 (dut_u_rd_n_2021), .A1 (dut_u_rd_n_2056),
       .B0 (dut_u_rd_n_2009), .C0 (dut_u_rd_n_2109), .Y
       (dut_u_rd_n_1968));
  MXI2XL dut_u_rd_g3150(.A (dut_u_rd_n_1993), .B (dut_u_rd_n_2012), .S0
       (dut_u_rd_outst_cnt[0]), .Y (dut_u_rd_n_1966));
  NAND2XL dut_u_rd_g3151(.A (dut_u_rd_n_2067), .B (dut_u_rd_n_2018), .Y
       (dut_u_rd_n_1973));
  NAND3BXL dut_u_rd_g3152(.AN (dut_u_rd_n_2067), .B
       (dut_u_rd_outst_cnt[2]), .C (dut_u_rd_n_2018), .Y
       (dut_u_rd_n_1974));
  NOR2XL dut_u_rd_g3153(.A (dut_u_rd_n_2047), .B (dut_u_rd_n_2027), .Y
       (dut_u_rd_n_1976));
  NAND2X1 dut_u_rd_g3154(.A (dut_u_rd_timer[3]), .B (dut_u_rd_n_1996),
       .Y (dut_u_rd_n_1972));
  INVX1 dut_u_rd_g3156(.A (dut_u_rd_n_1981), .Y (dut_u_rd_n_1980));
  OAI211X1 dut_u_rd_g3159(.A0 (dut_u_rd_timer[2]), .A1
       (dut_u_rd_n_2037), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2017), .Y (dut_u_rd_n_1988));
  OAI211X1 dut_u_rd_g3160(.A0 (dut_u_rd_n_2021), .A1 (dut_u_rd_n_2066),
       .B0 (dut_u_rd_n_2011), .C0 (dut_u_rd_n_2008), .Y
       (dut_u_rd_n_1981));
  NOR3BX1 dut_u_rd_g3161(.AN (dut_u_rd_n_2064), .B
       (dut_u_rd_outst_cnt[2]), .C (dut_u_rd_n_2027), .Y
       (dut_u_rd_n_1982));
  INVX1 dut_u_rd_g3162(.A (dut_u_rd_n_2012), .Y (dut_u_rd_n_1993));
  INVX1 dut_u_rd_g3163(.A (dut_u_rd_n_2017), .Y (dut_u_rd_n_1996));
  NAND2XL dut_u_rd_g3166(.A (dut_u_rd_n_2009), .B (dut_u_rd_n_2001), .Y
       (dut_u_rd_n_1998));
  AOI21XL dut_u_rd_g3167(.A0 (dut_u_rd_n_2033), .A1 (dut_u_rd_n_2062),
       .B0 (dut_u_rd_n_2028), .Y (dut_u_rd_n_2000));
  NAND2XL dut_u_rd_g3168(.A (dut_u_rd_n_2020), .B
       (dut_u_rd_drain_cnt[2]), .Y (dut_u_rd_n_2002));
  NOR2XL dut_u_rd_g3169(.A (dut_u_rd_n_2032), .B (dut_epoch_clr), .Y
       (dut_u_rd_n_2003));
  NAND2XL dut_u_rd_g3170(.A (dut_u_rd_n_2021), .B (dut_u_rd_n_2019), .Y
       (dut_u_rd_n_2004));
  OR2XL dut_u_rd_g3171(.A (dut_u_rd_n_2019), .B (dut_u_rd_n_2056), .Y
       (dut_u_rd_n_2001));
  INVX1 dut_u_rd_g3173(.A (dut_u_rd_n_2011), .Y (dut_u_rd_n_2010));
  NOR2XL dut_u_rd_g3174(.A (dut_u_rd_n_2052), .B (dut_u_rd_n_2028), .Y
       (dut_u_rd_n_2013));
  NAND2BXL dut_u_rd_g3175(.AN (dut_u_rd_n_2019), .B (dut_u_rd_n_2056),
       .Y (dut_u_rd_n_2008));
  NAND2X1 dut_u_rd_g3176(.A (dut_u_rd_n_2020), .B (dut_u_rd_n_2066), .Y
       (dut_u_rd_n_2009));
  MX2XL dut_u_rd_g3177(.A (dut_u_rd_n_2039), .B (dut_u_rd_n_2111), .S0
       (dut_u_rd_n_2057), .Y (dut_u_rd_n_2011));
  CLKXOR2X1 dut_u_rd_g3178(.A (dut_u_rd_n_2068), .B (dut_u_rd_n_2040),
       .Y (dut_u_rd_n_2012));
  INVX1 dut_u_rd_g3179(.A (dut_u_rd_n_2020), .Y (dut_u_rd_n_2021));
  NAND2X1 dut_u_rd_g3180(.A (dut_u_rd_timer[2]), .B (dut_u_rd_n_2037),
       .Y (dut_u_rd_n_2017));
  NOR2X1 dut_u_rd_g3181(.A (dut_u_rd_n_2068), .B (dut_u_rd_n_2040), .Y
       (dut_u_rd_n_2018));
  NAND2BX1 dut_u_rd_g3182(.AN (dut_u_rd_n_2039), .B (dut_u_rd_n_2057),
       .Y (dut_u_rd_n_2019));
  NOR2X1 dut_u_rd_g3183(.A (dut_u_rd_n_2057), .B (dut_u_rd_n_2111), .Y
       (dut_u_rd_n_2020));
  AOI221X1 dut_u_rd_g3184(.A0 (dut_u_rd_n_2072), .A1 (n_224), .B0
       (dut_flush), .B1 (dut_u_rd_n_257), .C0 (dut_rd_timeout_pulse),
       .Y (dut_u_rd_n_2032));
  OAI211X1 dut_u_rd_g3185(.A0 (dut_u_rd_timer[0]), .A1
       (dut_u_rd_timer[1]), .B0 (dut_u_rd_timer_run), .C0
       (dut_u_rd_n_2055), .Y (dut_u_rd_n_2033));
  NAND2X1 dut_u_rd_g3186(.A (dut_u_rd_n_2068), .B (dut_u_rd_n_2040), .Y
       (dut_u_rd_n_2027));
  OR3X1 dut_u_rd_g3187(.A (dut_rd_timeout_pulse), .B (dut_u_rd_n_2040),
       .C (dut_epoch_clr), .Y (dut_u_rd_n_2028));
  INVX1 dut_u_rd_g3188(.A (dut_u_rd_n_2055), .Y (dut_u_rd_n_2037));
  OR2XL dut_u_rd_g3189(.A (dut_u_rd_n_2048), .B (dut_epoch_clr), .Y
       (dut_u_rd_n_2039));
  NAND2BX1 dut_u_rd_g3190(.AN (dut_u_rd_n_2063), .B (dut_u_rd_n_2048),
       .Y (dut_u_rd_n_2040));
  OR4X1 dut_u_rd_g3191(.A (dut_u_rd_n_2068), .B (dut_u_rd_rd_state[1]),
       .C (dut_u_rd_rd_state[0]), .D (logic_0_1_net), .Y
       (dut_u_rd_n_2044));
  NOR2BX1 dut_u_rd_g3193(.AN (dut_u_rd_n_2067), .B (dut_u_rd_n_2064),
       .Y (dut_u_rd_n_2047));
  NAND2X1 dut_u_rd_g3194(.A (s_rready), .B (n_224), .Y
       (dut_u_rd_n_2048));
  NOR2XL dut_u_rd_g3195(.A (dut_u_rd_outst_cnt[2]), .B
       (dut_u_rd_n_2067), .Y (dut_u_rd_n_2051));
  XNOR2X1 dut_u_rd_g3196(.A (dut_u_rd_timer_run), .B
       (dut_u_rd_timer[0]), .Y (dut_u_rd_n_2052));
  NAND3BXL dut_u_rd_g3197(.AN (dut_rd_timeout_pulse), .B
       (dut_u_rd_n_257), .C (dut_u_rd_n_252), .Y (dut_u_rd_n_2050));
  NAND2X1 dut_u_rd_g3198(.A (dut_u_rd_n_2099), .B (dut_u_rd_timer[2]),
       .Y (dut_u_rd_n_2058));
  NAND2X1 dut_u_rd_g3199(.A (dut_u_rd_n_2099), .B (dut_u_rd_timer[3]),
       .Y (dut_u_rd_n_2060));
  NAND2X1 dut_u_rd_g3200(.A (dut_u_rd_n_2099), .B (dut_u_rd_timer[7]),
       .Y (dut_u_rd_n_2061));
  NAND2X1 dut_u_rd_g3201(.A (dut_u_rd_n_2099), .B (dut_u_rd_timer[1]),
       .Y (dut_u_rd_n_2062));
  NAND2X1 dut_u_rd_g3203(.A (dut_u_rd_timer[1]), .B
       (dut_u_rd_timer[0]), .Y (dut_u_rd_n_2055));
  NAND2X1 dut_u_rd_g3204(.A (dut_u_rd_drain_cnt[1]), .B
       (dut_u_rd_drain_cnt[0]), .Y (dut_u_rd_n_2056));
  NAND2X1 dut_u_rd_g3205(.A (m_rvalid), .B (dut_u_rd_n_259), .Y
       (dut_u_rd_n_2057));
  NAND2X1 dut_u_rd_g3207(.A (dut_u_rd_n_2099), .B (dut_u_rd_timer[5]),
       .Y (dut_u_rd_n_2069));
  NAND2X1 dut_u_rd_g3208(.A (dut_u_rd_n_2099), .B (dut_u_rd_timer[6]),
       .Y (dut_u_rd_n_2070));
  NAND2X1 dut_u_rd_g3209(.A (dut_u_rd_n_2099), .B (dut_u_rd_timer[4]),
       .Y (dut_u_rd_n_2071));
  AND2XL dut_u_rd_g3210(.A (dut_u_rd_n_260), .B (s_rvalid), .Y
       (dut_u_rd_n_2063));
  NOR2X1 dut_u_rd_g3211(.A (dut_u_rd_outst_cnt[1]), .B
       (dut_u_rd_outst_cnt[0]), .Y (dut_u_rd_n_2064));
  NOR2X1 dut_u_rd_g3212(.A (dut_u_rd_drain_cnt[1]), .B
       (dut_u_rd_drain_cnt[0]), .Y (dut_u_rd_n_2066));
  NAND2X1 dut_u_rd_g3213(.A (dut_u_rd_outst_cnt[1]), .B
       (dut_u_rd_outst_cnt[0]), .Y (dut_u_rd_n_2067));
  NAND2X1 dut_u_rd_g3214(.A (s_arvalid), .B (s_arready), .Y
       (dut_u_rd_n_2068));
  INVX1 dut_u_rd_g3215(.A (s_rready), .Y (dut_u_rd_n_2072));
  INVX1 dut_u_rd_g3218(.A (dut_u_rd_timer_run), .Y (dut_u_rd_n_2099));
  AOI2BB2X1 dut_u_rd_g1988(.A0N (dut_u_rd_n_2008), .A1N
       (dut_u_rd_n_2066), .B0 (dut_u_rd_n_2010), .B1
       (dut_u_rd_drain_cnt[1]), .Y (dut_u_rd_n_2109));
  MXI2XL dut_u_rd_g3219(.A (dut_u_rd_n_2009), .B (dut_u_rd_n_2001), .S0
       (dut_u_rd_drain_cnt[2]), .Y (dut_u_rd_n_2110));
  NAND2BX1 dut_u_rd_g3220(.AN (dut_epoch_clr), .B (dut_u_rd_n_2048), .Y
       (dut_u_rd_n_2111));
  INVXL g3797(.A (dut_flush), .Y (dut_u_rd_n_252));
  INVX1 g3798(.A (dut_u_rd_n_1597), .Y (s_arready));
  INVXL g3799(.A (s_wready), .Y (dut_u_wr_n_3120));
  OAI22X1 g2(.A0 (n_223), .A1 (dut_u_wr_n_3042), .B0 (n_230), .B1
       (dut_u_wr_n_2873), .Y (n_221));
  OAI21X1 g3800(.A0 (dut_u_wr_n_3131), .A1 (dut_u_wr_n_2994), .B0
       (dut_u_wr_n_3084), .Y (n_222));
  NOR3BX1 g3801(.AN (dut_u_wr_n_360), .B (dut_wr_timeout_pulse), .C
       (dut_flush), .Y (n_223));
  NOR2BX1 dut_u_rd_g3802(.AN (dut_u_rd_rd_state[1]), .B
       (dut_u_rd_rd_state[0]), .Y (n_224));
  DFFRX1 \dut_mode_reg[0] (.RN (rst_n), .CK (clk), .D (n_10), .Q
       (dut_mode[0]), .QN (dut_n_418));
  DFFRX1 \dut_mode_reg[1] (.RN (rst_n), .CK (clk), .D (n_8), .Q
       (dut_mode[1]), .QN (dut_n_419));
  DFFRX1 \dut_u_wr_wpair_state_reg[0] (.RN (rst_n), .CK (clk), .D
       (n_222), .Q (dut_u_wr_wpair_state[0]), .QN (dut_u_wr_n_3131));
  DFFRX1 \dut_u_wr_drain_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2912), .Q (dut_u_wr_drain_cnt[2]), .QN
       (dut_u_wr_n_3144));
  DFFRX1 \dut_u_wr_outst_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2875), .Q (dut_u_wr_outst_cnt[2]), .QN
       (dut_u_wr_n_3147));
  DFFRX1 \dut_u_rd_outst_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_1941), .Q (dut_u_rd_outst_cnt[3]), .QN
       (dut_u_rd_n_1652));
  DFFRX1 \dut_u_rd_rd_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_rd_n_2003), .Q (dut_u_rd_rd_state[1]), .QN
       (dut_u_rd_n_1657));
  DFFRX1 \dut_u_wr_wpair_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (dut_u_wr_n_2957), .Q (dut_u_wr_wpair_state[1]), .QN
       (dut_u_wr_n_2473));
  AOI2BB1XL g3819(.A0N (dut_u_wr_downstream_w_done), .A1N
       (dut_u_wr_downstream_w_fire), .B0 (dut_u_wr_n_2461), .Y (n_225));
  OAI31X1 g3821(.A0 (dut_u_wr_wr_state[0]), .A1 (dut_u_wr_wr_state[1]),
       .A2 (dut_u_wr_n_3120), .B0 (n_221), .Y (n_227));
  NOR3X1 g3822(.A (dut_u_wr_wpair_state[0]), .B (dut_u_wr_n_374), .C
       (dut_u_rd_n_272), .Y (n_228));
  MXI2XL g3823(.A (n_229), .B (dut_u_wr_n_2902), .S0
       (dut_u_wr_outst_cnt[3]), .Y (n_230));
  AND2X1 g3(.A (dut_u_wr_n_2934), .B (dut_u_wr_n_2926), .Y (n_229));
  TIELO tie_0_cell(.Y (logic_0_1_net));
endmodule

