
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Aug 29 2026 15:01:07 PDT (Aug 29 2026 22:01:07 UTC)

// Verification Directory fv/tp_lvl 

module tp_lvl(clk, rst_n, s_awvalid, \s_aw[prot] , \s_aw[addr] ,
     s_wvalid, \s_w[strb] , \s_w[data] , s_arvalid, \s_ar[prot] ,
     \s_ar[addr] , s_bready, s_rready, s_awready, s_wready, s_arready,
     s_bvalid, \s_b[resp] , s_rvalid, \s_r[resp] , \s_r[data] ,
     m_awvalid, \m_aw[prot] , \m_aw[addr] , m_wvalid, \m_w[strb] ,
     \m_w[data] , m_arvalid, \m_ar[prot] , \m_ar[addr] , m_bready,
     m_rready, m_awready, m_wready, m_arready, m_bvalid, \m_b[resp] ,
     m_rvalid, \m_r[resp] , \m_r[data] , enable_reg, clear_reg, irq,
     status_reg, guard_busy);
  input clk, rst_n, s_awvalid, s_wvalid, s_arvalid, s_bready, s_rready,
       m_awready, m_wready, m_arready, m_bvalid, m_rvalid;
  input [2:0] \s_aw[prot] , \s_ar[prot] , enable_reg, clear_reg;
  input [31:0] \s_aw[addr] , \s_w[data] , \s_ar[addr] , \m_r[data] ;
  input [3:0] \s_w[strb] ;
  input [1:0] \m_b[resp] , \m_r[resp] ;
  output s_awready, s_wready, s_arready, s_bvalid, s_rvalid, m_awvalid,
       m_wvalid, m_arvalid, m_bready, m_rready, irq, guard_busy;
  output [1:0] \s_b[resp] , \s_r[resp] ;
  output [31:0] \s_r[data] , \m_aw[addr] , \m_w[data] , \m_ar[addr] ;
  output [2:0] \m_aw[prot] , \m_ar[prot] , status_reg;
  output [3:0] \m_w[strb] ;
  wire clk, rst_n, s_awvalid, s_wvalid, s_arvalid, s_bready, s_rready,
       m_awready, m_wready, m_arready, m_bvalid, m_rvalid;
  wire [2:0] \s_aw[prot] , \s_ar[prot] , enable_reg, clear_reg;
  wire [31:0] \s_aw[addr] , \s_w[data] , \s_ar[addr] , \m_r[data] ;
  wire [3:0] \s_w[strb] ;
  wire [1:0] \m_b[resp] , \m_r[resp] ;
  wire s_awready, s_wready, s_arready, s_bvalid, s_rvalid, m_awvalid,
       m_wvalid, m_arvalid, m_bready, m_rready, irq, guard_busy;
  wire [1:0] \s_b[resp] , \s_r[resp] ;
  wire [31:0] \s_r[data] , \m_aw[addr] , \m_w[data] , \m_ar[addr] ;
  wire [2:0] \m_aw[prot] , \m_ar[prot] , status_reg;
  wire [3:0] \m_w[strb] ;
  wire [1:0] mode;
  wire [2:0] rcvy_ack;
  wire [3:0] u_wr_outst_cnt;
  wire [1:0] u_wr_wpair_state;
  wire [15:0] u_wr_w_timer;
  wire [15:0] u_wr_b_timer;
  wire [3:0] u_wr_drain_cnt;
  wire [1:0] u_wr_wr_state;
  wire [3:0] u_rd_outst_cnt;
  wire [3:0] u_rd_drain_cnt;
  wire [15:0] u_rd_timer;
  wire [1:0] u_rd_rd_state;
  wire epoch_clr, flush, logic_0_1_net, logic_1_1_net, n_0, n_1, n_2,
       n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_224, n_225, n_226;
  wire n_227, n_228, n_229, n_230, n_231, n_232, n_234, rd_busy;
  wire rd_timeout_pulse, u_rd_n_285, u_rd_n_287, u_rd_n_288,
       u_rd_n_300, u_rd_n_1710, u_rd_n_1715, u_rd_n_1716;
  wire u_rd_n_1741, u_rd_n_1756, u_rd_n_1758, u_rd_n_1759, u_rd_n_1760,
       u_rd_n_1765, u_rd_n_1766, u_rd_n_1771;
  wire u_rd_n_1773, u_rd_n_2093, u_rd_n_2096, u_rd_n_2098, u_rd_n_2100,
       u_rd_n_2101, u_rd_n_2106, u_rd_n_2107;
  wire u_rd_n_2108, u_rd_n_2111, u_rd_n_2113, u_rd_n_2114, u_rd_n_2115,
       u_rd_n_2118, u_rd_n_2120, u_rd_n_2121;
  wire u_rd_n_2122, u_rd_n_2125, u_rd_n_2127, u_rd_n_2128, u_rd_n_2129,
       u_rd_n_2132, u_rd_n_2134, u_rd_n_2135;
  wire u_rd_n_2136, u_rd_n_2139, u_rd_n_2141, u_rd_n_2142, u_rd_n_2143,
       u_rd_n_2146, u_rd_n_2148, u_rd_n_2149;
  wire u_rd_n_2150, u_rd_n_2153, u_rd_n_2155, u_rd_n_2156, u_rd_n_2157,
       u_rd_n_2160, u_rd_n_2162, u_rd_n_2163;
  wire u_rd_n_2164, u_rd_n_2167, u_rd_n_2169, u_rd_n_2170, u_rd_n_2171,
       u_rd_n_2173, u_rd_n_2174, u_rd_n_2175;
  wire u_rd_n_2178, u_rd_n_2180, u_rd_n_2182, u_rd_n_2185, u_rd_n_2186,
       u_rd_n_2188, u_rd_n_2189, u_rd_n_2194;
  wire u_rd_n_2195, u_rd_n_2196, u_rd_n_2198, u_rd_n_2202, u_rd_n_2204,
       u_rd_n_2205, u_rd_n_2207, u_rd_n_2208;
  wire u_rd_n_2209, u_rd_n_2211, u_rd_n_2213, u_rd_n_2214, u_rd_n_2217,
       u_rd_n_2218, u_rd_n_2219, u_rd_n_2223;
  wire u_rd_n_2227, u_rd_n_2231, u_rd_n_2233, u_rd_n_2238, u_rd_n_2240,
       u_rd_n_2242, u_rd_n_2243, u_rd_n_2244;
  wire u_rd_n_2245, u_rd_n_2246, u_rd_n_2249, u_rd_n_2250, u_rd_n_2251,
       u_rd_n_2252, u_rd_n_2259, u_rd_n_2262;
  wire u_rd_n_2263, u_rd_n_2264, u_rd_n_2265, u_rd_n_2270, u_rd_n_2271,
       u_rd_n_2272, u_rd_n_2275, u_rd_n_2278;
  wire u_rd_n_2280, u_rd_n_2282, u_rd_n_2285, u_rd_n_2286, u_rd_n_2288,
       u_rd_n_2289, u_rd_n_2290, u_rd_n_2291;
  wire u_rd_n_2292, u_rd_n_2294, u_rd_n_2295, u_rd_n_2296, u_rd_n_2298,
       u_rd_n_2299, u_rd_n_2300, u_rd_n_2301;
  wire u_rd_n_2302, u_rd_n_2303, u_rd_n_2304, u_rd_n_2305, u_rd_n_2306,
       u_rd_n_2307, u_rd_n_2308, u_rd_n_2310;
  wire u_rd_n_2312, u_rd_n_2313, u_rd_n_2314, u_rd_n_2315, u_rd_n_2316,
       u_rd_n_2317, u_rd_n_2319, u_rd_n_2334;
  wire u_rd_n_2366, u_rd_n_2367, u_rd_timer_run,
       u_wr_downstream_aw_done, u_wr_downstream_w_done, u_wr_n_145,
       u_wr_n_158, u_wr_n_230;
  wire u_wr_n_318, u_wr_n_396, u_wr_n_398, u_wr_n_430, u_wr_n_435,
       u_wr_n_712, u_wr_n_819, u_wr_n_1627;
  wire u_wr_n_1641, u_wr_n_1867, u_wr_n_2038, u_wr_n_2043, u_wr_n_2054,
       u_wr_n_2115, u_wr_n_2120, u_wr_n_2544;
  wire u_wr_n_2550, u_wr_n_2552, u_wr_n_2559, u_wr_n_2561, u_wr_n_2562,
       u_wr_n_2565, u_wr_n_2567, u_wr_n_2568;
  wire u_wr_n_2570, u_wr_n_2571, u_wr_n_2572, u_wr_n_2573, u_wr_n_2574,
       u_wr_n_2575, u_wr_n_2576, u_wr_n_2577;
  wire u_wr_n_2578, u_wr_n_2579, u_wr_n_2580, u_wr_n_3406, u_wr_n_3407,
       u_wr_n_3408, u_wr_n_3410, u_wr_n_3412;
  wire u_wr_n_3414, u_wr_n_3416, u_wr_n_3417, u_wr_n_3418, u_wr_n_3422,
       u_wr_n_3428, u_wr_n_3429, u_wr_n_3430;
  wire u_wr_n_3432, u_wr_n_3433, u_wr_n_3435, u_wr_n_3438, u_wr_n_3440,
       u_wr_n_3442, u_wr_n_3443, u_wr_n_3444;
  wire u_wr_n_3446, u_wr_n_3447, u_wr_n_3449, u_wr_n_3452, u_wr_n_3454,
       u_wr_n_3456, u_wr_n_3457, u_wr_n_3458;
  wire u_wr_n_3460, u_wr_n_3461, u_wr_n_3463, u_wr_n_3466, u_wr_n_3468,
       u_wr_n_3470, u_wr_n_3471, u_wr_n_3472;
  wire u_wr_n_3474, u_wr_n_3475, u_wr_n_3477, u_wr_n_3480, u_wr_n_3482,
       u_wr_n_3484, u_wr_n_3485, u_wr_n_3486;
  wire u_wr_n_3488, u_wr_n_3489, u_wr_n_3491, u_wr_n_3494, u_wr_n_3496,
       u_wr_n_3498, u_wr_n_3499, u_wr_n_3500;
  wire u_wr_n_3502, u_wr_n_3503, u_wr_n_3505, u_wr_n_3508, u_wr_n_3510,
       u_wr_n_3512, u_wr_n_3513, u_wr_n_3514;
  wire u_wr_n_3516, u_wr_n_3517, u_wr_n_3519, u_wr_n_3522, u_wr_n_3524,
       u_wr_n_3526, u_wr_n_3527, u_wr_n_3528;
  wire u_wr_n_3530, u_wr_n_3531, u_wr_n_3533, u_wr_n_3536, u_wr_n_3538,
       u_wr_n_3540, u_wr_n_3541, u_wr_n_3542;
  wire u_wr_n_3544, u_wr_n_3545, u_wr_n_3547, u_wr_n_3550, u_wr_n_3552,
       u_wr_n_3554, u_wr_n_3555, u_wr_n_3556;
  wire u_wr_n_3558, u_wr_n_3559, u_wr_n_3562, u_wr_n_3565, u_wr_n_3567,
       u_wr_n_3569, u_wr_n_3570, u_wr_n_3571;
  wire u_wr_n_3573, u_wr_n_3574, u_wr_n_3577, u_wr_n_3580, u_wr_n_3581,
       u_wr_n_3583, u_wr_n_3585, u_wr_n_3587;
  wire u_wr_n_3589, u_wr_n_3592, u_wr_n_3594, u_wr_n_3596, u_wr_n_3598,
       u_wr_n_3599, u_wr_n_3600, u_wr_n_3601;
  wire u_wr_n_3603, u_wr_n_3605, u_wr_n_3606, u_wr_n_3607, u_wr_n_3614,
       u_wr_n_3615, u_wr_n_3616, u_wr_n_3620;
  wire u_wr_n_3624, u_wr_n_3626, u_wr_n_3629, u_wr_n_3630, u_wr_n_3634,
       u_wr_n_3635, u_wr_n_3637, u_wr_n_3639;
  wire u_wr_n_3641, u_wr_n_3643, u_wr_n_3644, u_wr_n_3646, u_wr_n_3650,
       u_wr_n_3651, u_wr_n_3652, u_wr_n_3653;
  wire u_wr_n_3654, u_wr_n_3655, u_wr_n_3656, u_wr_n_3660, u_wr_n_3661,
       u_wr_n_3662, u_wr_n_3663, u_wr_n_3664;
  wire u_wr_n_3670, u_wr_n_3671, u_wr_n_3678, u_wr_n_3679, u_wr_n_3681,
       u_wr_n_3682, u_wr_n_3684, u_wr_n_3714;
  wire u_wr_n_3715, u_wr_n_3716, u_wr_n_3717, u_wr_n_3718, u_wr_n_3719,
       u_wr_n_3720, u_wr_n_3721, u_wr_n_3723;
  wire u_wr_n_3724, u_wr_n_3725, u_wr_n_3728, u_wr_n_3731, u_wr_n_3733,
       u_wr_n_3734, u_wr_n_3756, u_wr_n_3758;
  wire u_wr_n_3760, u_wr_n_3768, u_wr_n_3770, u_wr_n_3772, u_wr_n_3773,
       u_wr_n_3774, u_wr_n_3775, u_wr_n_3776;
  wire u_wr_n_3777, u_wr_n_3778, u_wr_n_3779, u_wr_n_3780, u_wr_n_3781,
       u_wr_n_3782, u_wr_n_3783, u_wr_n_3784;
  wire u_wr_n_3785, u_wr_n_3786, u_wr_n_3787, u_wr_n_3788, u_wr_n_3792,
       u_wr_n_3793, u_wr_n_3794, u_wr_n_3795;
  wire u_wr_n_3796, u_wr_n_3797, u_wr_n_3798, u_wr_n_3799, u_wr_n_3800,
       u_wr_n_3801, u_wr_n_3802, u_wr_n_3803;
  wire u_wr_n_3804, u_wr_n_3807, u_wr_n_3808, u_wr_n_3809, u_wr_n_3810,
       u_wr_n_3811, u_wr_n_3812, u_wr_n_3816;
  wire u_wr_n_3817, u_wr_n_3818, u_wr_n_3819, u_wr_n_3820, u_wr_n_3821,
       u_wr_n_3822, u_wr_n_3828, u_wr_n_3829;
  wire u_wr_n_3830, u_wr_n_3831, u_wr_n_3832, u_wr_n_3833, u_wr_n_3836,
       u_wr_n_3838, u_wr_n_3839, u_wr_n_3840;
  wire u_wr_n_3841, u_wr_n_3842, u_wr_n_3843, u_wr_n_3845, u_wr_n_3848,
       u_wr_n_3867, u_wr_n_3871, u_wr_n_3875;
  wire u_wr_n_3877, u_wr_n_3946, u_wr_n_3950, wr_busy,
       wr_timeout_pulse, wr_w_fault_pulse;
  assign \m_ar[addr] [0] = \s_ar[addr] [0];
  assign \m_ar[addr] [1] = \s_ar[addr] [1];
  assign \m_ar[addr] [2] = \s_ar[addr] [2];
  assign \m_ar[addr] [3] = \s_ar[addr] [3];
  assign \m_ar[addr] [4] = \s_ar[addr] [4];
  assign \m_ar[addr] [5] = \s_ar[addr] [5];
  assign \m_ar[addr] [6] = \s_ar[addr] [6];
  assign \m_ar[addr] [7] = \s_ar[addr] [7];
  assign \m_ar[addr] [8] = \s_ar[addr] [8];
  assign \m_ar[addr] [9] = \s_ar[addr] [9];
  assign \m_ar[addr] [10] = \s_ar[addr] [10];
  assign \m_ar[addr] [11] = \s_ar[addr] [11];
  assign \m_ar[addr] [12] = \s_ar[addr] [12];
  assign \m_ar[addr] [13] = \s_ar[addr] [13];
  assign \m_ar[addr] [14] = \s_ar[addr] [14];
  assign \m_ar[addr] [15] = \s_ar[addr] [15];
  assign \m_ar[addr] [16] = \s_ar[addr] [16];
  assign \m_ar[addr] [17] = \s_ar[addr] [17];
  assign \m_ar[addr] [18] = \s_ar[addr] [18];
  assign \m_ar[addr] [19] = \s_ar[addr] [19];
  assign \m_ar[addr] [20] = \s_ar[addr] [20];
  assign \m_ar[addr] [21] = \s_ar[addr] [21];
  assign \m_ar[addr] [22] = \s_ar[addr] [22];
  assign \m_ar[addr] [23] = \s_ar[addr] [23];
  assign \m_ar[addr] [24] = \s_ar[addr] [24];
  assign \m_ar[addr] [25] = \s_ar[addr] [25];
  assign \m_ar[addr] [26] = \s_ar[addr] [26];
  assign \m_ar[addr] [27] = \s_ar[addr] [27];
  assign \m_ar[addr] [28] = \s_ar[addr] [28];
  assign \m_ar[addr] [29] = \s_ar[addr] [29];
  assign \m_ar[addr] [30] = \s_ar[addr] [30];
  assign \m_ar[addr] [31] = \s_ar[addr] [31];
  assign \m_ar[prot] [0] = \s_ar[prot] [0];
  assign \m_ar[prot] [1] = \s_ar[prot] [1];
  assign \m_ar[prot] [2] = \s_ar[prot] [2];
  assign \m_w[data] [0] = \s_w[data] [0];
  assign \m_w[data] [1] = \s_w[data] [1];
  assign \m_w[data] [2] = \s_w[data] [2];
  assign \m_w[data] [3] = \s_w[data] [3];
  assign \m_w[data] [4] = \s_w[data] [4];
  assign \m_w[data] [5] = \s_w[data] [5];
  assign \m_w[data] [6] = \s_w[data] [6];
  assign \m_w[data] [7] = \s_w[data] [7];
  assign \m_w[data] [8] = \s_w[data] [8];
  assign \m_w[data] [9] = \s_w[data] [9];
  assign \m_w[data] [10] = \s_w[data] [10];
  assign \m_w[data] [11] = \s_w[data] [11];
  assign \m_w[data] [12] = \s_w[data] [12];
  assign \m_w[data] [13] = \s_w[data] [13];
  assign \m_w[data] [14] = \s_w[data] [14];
  assign \m_w[data] [15] = \s_w[data] [15];
  assign \m_w[data] [16] = \s_w[data] [16];
  assign \m_w[data] [17] = \s_w[data] [17];
  assign \m_w[data] [18] = \s_w[data] [18];
  assign \m_w[data] [19] = \s_w[data] [19];
  assign \m_w[data] [20] = \s_w[data] [20];
  assign \m_w[data] [21] = \s_w[data] [21];
  assign \m_w[data] [22] = \s_w[data] [22];
  assign \m_w[data] [23] = \s_w[data] [23];
  assign \m_w[data] [24] = \s_w[data] [24];
  assign \m_w[data] [25] = \s_w[data] [25];
  assign \m_w[data] [26] = \s_w[data] [26];
  assign \m_w[data] [27] = \s_w[data] [27];
  assign \m_w[data] [28] = \s_w[data] [28];
  assign \m_w[data] [29] = \s_w[data] [29];
  assign \m_w[data] [30] = \s_w[data] [30];
  assign \m_w[data] [31] = \s_w[data] [31];
  assign \m_w[strb] [0] = \s_w[strb] [0];
  assign \m_w[strb] [1] = \s_w[strb] [1];
  assign \m_w[strb] [2] = \s_w[strb] [2];
  assign \m_w[strb] [3] = \s_w[strb] [3];
  AND2X1 g266(.A (n_14), .B (n_234), .Y (epoch_clr));
  NOR3XL g267(.A (n_13), .B (mode[0]), .C (n_15), .Y (n_14));
  NOR3X1 g268(.A (rcvy_ack[0]), .B (rcvy_ack[2]), .C (rcvy_ack[1]), .Y
       (n_13));
  DFFRHQX1 \u_irq_rcvy_ack_reg[2] (.RN (rst_n), .CK (clk), .D
       (clear_reg[2]), .Q (rcvy_ack[2]));
  DFFRHQX1 \u_irq_rcvy_ack_reg[1] (.RN (rst_n), .CK (clk), .D
       (clear_reg[1]), .Q (rcvy_ack[1]));
  DFFRHQX1 \u_irq_rcvy_ack_reg[0] (.RN (rst_n), .CK (clk), .D
       (clear_reg[0]), .Q (rcvy_ack[0]));
  NAND2X1 g160(.A (n_16), .B (n_15), .Y (flush));
  AND2X1 g223(.A (n_234), .B (n_12), .Y (irq));
  OAI2BB1X1 g224(.A0N (enable_reg[1]), .A1N (status_reg[1]), .B0
       (n_11), .Y (n_12));
  AOI22X1 g225(.A0 (enable_reg[0]), .A1 (status_reg[0]), .B0
       (enable_reg[2]), .B1 (status_reg[2]), .Y (n_11));
  OR2X1 g226(.A (rd_busy), .B (wr_busy), .Y (guard_busy));
  NOR2BX1 g367(.AN (n_9), .B (mode[1]), .Y (n_10));
  OAI22X1 g369(.A0 (mode[0]), .A1 (n_4), .B0 (n_16), .B1 (n_234), .Y
       (n_9));
  DFFRHQX1 \u_irq_status_reg_reg[0] (.RN (rst_n), .CK (clk), .D (n_7),
       .Q (status_reg[0]));
  DFFRHQX1 \u_irq_status_reg_reg[1] (.RN (rst_n), .CK (clk), .D (n_6),
       .Q (status_reg[1]));
  OAI33X1 g372(.A0 (n_15), .A1 (mode[0]), .A2 (epoch_clr), .B0
       (mode[1]), .B1 (n_16), .B2 (n_0), .Y (n_8));
  DFFRHQX1 \u_irq_status_reg_reg[2] (.RN (rst_n), .CK (clk), .D (n_5),
       .Q (status_reg[2]));
  OR2XL g374(.A (n_3), .B (rd_timeout_pulse), .Y (n_7));
  OR2XL g375(.A (n_2), .B (wr_w_fault_pulse), .Y (n_6));
  OR2XL g376(.A (n_1), .B (wr_timeout_pulse), .Y (n_5));
  NOR3X1 g377(.A (wr_w_fault_pulse), .B (rd_timeout_pulse), .C
       (wr_timeout_pulse), .Y (n_4));
  NOR2BX1 g378(.AN (status_reg[0]), .B (clear_reg[0]), .Y (n_3));
  NOR2BX1 g379(.AN (status_reg[1]), .B (clear_reg[1]), .Y (n_2));
  NOR2BX1 g380(.AN (status_reg[2]), .B (clear_reg[2]), .Y (n_1));
  INVX1 g381(.A (n_234), .Y (n_0));
  INVXL u_wr_g1891(.A (u_wr_n_2038), .Y (u_wr_n_2115));
  INVX1 u_wr_g1893(.A (u_wr_n_1641), .Y (wr_w_fault_pulse));
  INVX1 u_wr_g1892(.A (u_wr_n_1627), .Y (wr_timeout_pulse));
  INVX1 u_wr_g1890(.A (s_awvalid), .Y (u_wr_n_2120));
  OR4X1 u_wr_g1916(.A (u_wr_outst_cnt[0]), .B (u_wr_outst_cnt[1]), .C
       (u_wr_outst_cnt[2]), .D (u_wr_outst_cnt[3]), .Y (u_wr_n_430));
  AND2X1 u_wr_g1936(.A (n_224), .B (u_wr_n_396), .Y (m_awvalid));
  AND2X1 u_wr_g1937(.A (n_224), .B (u_wr_n_398), .Y (m_wvalid));
  OR3XL u_wr_g2691(.A (u_wr_n_2043), .B (u_wr_wpair_state[1]), .C
       (u_wr_n_435), .Y (u_wr_n_1641));
  OR2XL u_wr_g2692(.A (u_wr_n_1867), .B (u_wr_n_2580), .Y
       (u_wr_n_1627));
  OR2XL u_wr_g2693(.A (s_wvalid), .B (u_wr_n_2038), .Y (u_wr_n_2043));
  OR2X1 u_wr_g2694(.A (u_wr_n_2544), .B (u_wr_n_2577), .Y (s_bvalid));
  OR2XL u_wr_g2695(.A (u_wr_n_230), .B (u_wr_n_2550), .Y (u_wr_n_1867));
  NOR2BX1 u_wr_g2696(.AN (u_wr_n_230), .B (u_wr_n_2580), .Y
       (u_wr_n_2544));
  AND3X1 u_wr_g2697(.A (n_224), .B (u_wr_n_2561), .C (u_wr_n_2559), .Y
       (s_wready));
  NAND4XL u_wr_g2699(.A (u_wr_n_2570), .B (u_wr_n_2574), .C
       (u_wr_n_2572), .D (u_wr_n_2573), .Y (u_wr_n_2550));
  NAND4XL u_wr_g2700(.A (u_wr_n_2571), .B (u_wr_n_2562), .C
       (u_wr_n_2575), .D (u_wr_n_2576), .Y (u_wr_n_2038));
  NOR3XL u_wr_g2701(.A (u_wr_n_2578), .B (flush), .C (u_wr_n_2568), .Y
       (u_wr_n_2552));
  AND2XL u_wr_g2702(.A (m_bvalid), .B (u_wr_n_145), .Y (u_wr_n_230));
  NAND2X2 u_wr_g2703(.A (u_wr_n_2567), .B (u_wr_n_145), .Y (m_bready));
  NAND2X1 u_wr_g2704(.A (u_wr_n_145), .B (u_wr_n_2565), .Y (wr_busy));
  AO21X1 u_wr_g2705(.A0 (\m_b[resp] [1]), .A1 (u_wr_n_2579), .B0
       (u_wr_n_2577), .Y (\s_b[resp] [1]));
  NOR4BX1 u_wr_g2708(.AN (u_wr_w_timer[8]), .B (u_wr_w_timer[4]), .C
       (u_wr_w_timer[6]), .D (u_wr_w_timer[5]), .Y (u_wr_n_2562));
  AND2X1 u_wr_g2709(.A (u_wr_n_2579), .B (\m_b[resp] [0]), .Y
       (\s_b[resp] [0]));
  NOR2X1 u_wr_g2710(.A (u_wr_n_2578), .B (u_wr_n_430), .Y
       (u_wr_n_2565));
  NAND2X1 u_wr_g2711(.A (s_bready), .B (u_wr_n_2579), .Y (u_wr_n_2567));
  NOR4BX1 u_wr_g2712(.AN (u_wr_outst_cnt[3]), .B (u_wr_outst_cnt[2]),
       .C (u_wr_outst_cnt[1]), .D (u_wr_outst_cnt[0]), .Y
       (u_wr_n_2568));
  OAI2BB1X1 u_wr_g2713(.A0N (m_awready), .A1N (m_awvalid), .B0
       (u_wr_n_396), .Y (u_wr_n_2559));
  OAI2BB1X1 u_wr_g2714(.A0N (m_wready), .A1N (m_wvalid), .B0
       (u_wr_n_398), .Y (u_wr_n_2561));
  NOR4X1 u_wr_g2715(.A (u_wr_b_timer[1]), .B (u_wr_b_timer[0]), .C
       (u_wr_b_timer[2]), .D (u_wr_b_timer[3]), .Y (u_wr_n_2570));
  NOR4X1 u_wr_g2716(.A (u_wr_w_timer[11]), .B (u_wr_w_timer[12]), .C
       (u_wr_w_timer[10]), .D (u_wr_w_timer[9]), .Y (u_wr_n_2571));
  NOR4X1 u_wr_g2717(.A (u_wr_b_timer[15]), .B (u_wr_b_timer[9]), .C
       (u_wr_b_timer[14]), .D (u_wr_b_timer[13]), .Y (u_wr_n_2572));
  NOR4X1 u_wr_g2718(.A (u_wr_b_timer[5]), .B (u_wr_b_timer[4]), .C
       (u_wr_b_timer[6]), .D (u_wr_b_timer[7]), .Y (u_wr_n_2573));
  NOR4BX1 u_wr_g2719(.AN (u_wr_b_timer[8]), .B (u_wr_b_timer[11]), .C
       (u_wr_b_timer[12]), .D (u_wr_b_timer[10]), .Y (u_wr_n_2574));
  NOR4X1 u_wr_g2720(.A (u_wr_w_timer[1]), .B (u_wr_w_timer[0]), .C
       (u_wr_w_timer[2]), .D (u_wr_w_timer[3]), .Y (u_wr_n_2575));
  NOR4X1 u_wr_g2721(.A (u_wr_w_timer[15]), .B (u_wr_w_timer[7]), .C
       (u_wr_w_timer[14]), .D (u_wr_w_timer[13]), .Y (u_wr_n_2576));
  NOR4X2 u_wr_g2722(.A (u_wr_drain_cnt[2]), .B (u_wr_drain_cnt[1]), .C
       (u_wr_drain_cnt[3]), .D (u_wr_drain_cnt[0]), .Y (u_wr_n_145));
  NOR2BX1 u_wr_g2723(.AN (u_wr_wr_state[1]), .B (u_wr_wr_state[0]), .Y
       (u_wr_n_2577));
  INVX1 u_wr_g2724(.A (u_wr_n_2579), .Y (u_wr_n_2580));
  NAND2BX1 u_wr_g2725(.AN (u_wr_wpair_state[1]), .B (u_wr_n_435), .Y
       (u_wr_n_2578));
  NOR2X1 u_wr_g2726(.A (u_wr_wr_state[1]), .B (u_wr_n_158), .Y
       (u_wr_n_2579));
  INVXL u_wr_g2729(.A (flush), .Y (u_wr_n_712));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][0] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [0]), .SI (\m_aw[addr] [0]), .SE (u_wr_n_3832), .Q
       (\m_aw[addr] [0]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][1] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [1]), .SI (\m_aw[addr] [1]), .SE (u_wr_n_3832), .Q
       (\m_aw[addr] [1]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][2] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [2]), .SI (\m_aw[addr] [2]), .SE (u_wr_n_3832), .Q
       (\m_aw[addr] [2]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][3] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [3]), .SI (\m_aw[addr] [3]), .SE (u_wr_n_3832), .Q
       (\m_aw[addr] [3]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][4] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [4]), .SI (\m_aw[addr] [4]), .SE (u_wr_n_3832), .Q
       (\m_aw[addr] [4]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][5] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [5]), .SI (\m_aw[addr] [5]), .SE (u_wr_n_3832), .Q
       (\m_aw[addr] [5]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][6] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [6]), .SI (\m_aw[addr] [6]), .SE (u_wr_n_3832), .Q
       (\m_aw[addr] [6]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][7] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [7]), .SI (\m_aw[addr] [7]), .SE (u_wr_n_3832), .Q
       (\m_aw[addr] [7]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][8] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [8]), .SI (\m_aw[addr] [8]), .SE (u_wr_n_3832), .Q
       (\m_aw[addr] [8]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][9] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [9]), .SI (\m_aw[addr] [9]), .SE (u_wr_n_3832), .Q
       (\m_aw[addr] [9]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][10] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [10]), .SI (\m_aw[addr] [10]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [10]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][11] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [11]), .SI (\m_aw[addr] [11]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [11]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][12] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [12]), .SI (\m_aw[addr] [12]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [12]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][13] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [13]), .SI (\m_aw[addr] [13]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [13]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][14] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [14]), .SI (\m_aw[addr] [14]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [14]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][15] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [15]), .SI (\m_aw[addr] [15]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [15]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][16] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [16]), .SI (\m_aw[addr] [16]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [16]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][17] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [17]), .SI (\m_aw[addr] [17]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [17]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][18] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [18]), .SI (\m_aw[addr] [18]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [18]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][19] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [19]), .SI (\m_aw[addr] [19]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [19]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][20] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [20]), .SI (\m_aw[addr] [20]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [20]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][21] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [21]), .SI (\m_aw[addr] [21]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [21]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][22] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [22]), .SI (\m_aw[addr] [22]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [22]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][23] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [23]), .SI (\m_aw[addr] [23]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [23]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][24] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [24]), .SI (\m_aw[addr] [24]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [24]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][25] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [25]), .SI (\m_aw[addr] [25]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [25]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][26] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [26]), .SI (\m_aw[addr] [26]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [26]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][27] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [27]), .SI (\m_aw[addr] [27]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [27]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][28] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [28]), .SI (\m_aw[addr] [28]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [28]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][29] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [29]), .SI (\m_aw[addr] [29]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [29]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][30] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [30]), .SI (\m_aw[addr] [30]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [30]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][31] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [31]), .SI (\m_aw[addr] [31]), .SE (u_wr_n_3832),
       .Q (\m_aw[addr] [31]));
  SDFFRHQX1 \u_wr_aw_hold_reg[prot][0] (.RN (rst_n), .CK (clk), .D
       (\s_aw[prot] [0]), .SI (\m_aw[prot] [0]), .SE (u_wr_n_3832), .Q
       (\m_aw[prot] [0]));
  SDFFRHQX1 \u_wr_aw_hold_reg[prot][1] (.RN (rst_n), .CK (clk), .D
       (\s_aw[prot] [1]), .SI (\m_aw[prot] [1]), .SE (u_wr_n_3832), .Q
       (\m_aw[prot] [1]));
  SDFFRHQX1 \u_wr_aw_hold_reg[prot][2] (.RN (rst_n), .CK (clk), .D
       (\s_aw[prot] [2]), .SI (\m_aw[prot] [2]), .SE (u_wr_n_3832), .Q
       (\m_aw[prot] [2]));
  DFFRHQX1 \u_wr_b_timer_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3652), .Q (u_wr_b_timer[0]));
  DFFRHQX1 \u_wr_b_timer_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3654), .Q (u_wr_b_timer[1]));
  DFFRHQX1 \u_wr_b_timer_reg[2] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3599), .Q (u_wr_b_timer[2]));
  DFFRHQX1 \u_wr_b_timer_reg[3] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3570), .Q (u_wr_b_timer[3]));
  DFFRHQX1 \u_wr_b_timer_reg[4] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3555), .Q (u_wr_b_timer[4]));
  DFFRHQX1 \u_wr_b_timer_reg[5] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3541), .Q (u_wr_b_timer[5]));
  DFFRHQX1 \u_wr_b_timer_reg[6] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3527), .Q (u_wr_b_timer[6]));
  DFFRHQX1 \u_wr_b_timer_reg[7] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3513), .Q (u_wr_b_timer[7]));
  DFFRHQX1 \u_wr_b_timer_reg[8] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3499), .Q (u_wr_b_timer[8]));
  DFFRHQX1 \u_wr_b_timer_reg[9] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3485), .Q (u_wr_b_timer[9]));
  DFFRHQX1 \u_wr_b_timer_reg[10] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3471), .Q (u_wr_b_timer[10]));
  DFFRHQX1 \u_wr_b_timer_reg[11] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3457), .Q (u_wr_b_timer[11]));
  DFFRHQX1 \u_wr_b_timer_reg[12] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3443), .Q (u_wr_b_timer[12]));
  DFFRHQX1 \u_wr_b_timer_reg[13] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3429), .Q (u_wr_b_timer[13]));
  DFFRHQX1 \u_wr_b_timer_reg[14] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3414), .Q (u_wr_b_timer[14]));
  DFFRHQX1 \u_wr_b_timer_reg[15] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3407), .Q (u_wr_b_timer[15]));
  DFFRHQX1 \u_wr_drain_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3601), .Q (u_wr_drain_cnt[1]));
  SDFFRHQX1 \u_wr_drain_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3616), .SI (u_wr_n_3626), .SE (u_wr_drain_cnt[3]), .Q
       (u_wr_drain_cnt[3]));
  DFFRHQX1 \u_wr_outst_cnt_reg[1] (.RN (rst_n), .CK (clk), .D (n_226),
       .Q (u_wr_outst_cnt[1]));
  DFFRHQX1 \u_wr_w_timer_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3678), .Q (u_wr_w_timer[0]));
  DFFRHQX1 \u_wr_w_timer_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3653), .Q (u_wr_w_timer[1]));
  DFFRHQX1 \u_wr_w_timer_reg[2] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3598), .Q (u_wr_w_timer[2]));
  DFFRHQX1 \u_wr_w_timer_reg[3] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3569), .Q (u_wr_w_timer[3]));
  DFFRHQX1 \u_wr_w_timer_reg[4] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3554), .Q (u_wr_w_timer[4]));
  DFFRHQX1 \u_wr_w_timer_reg[5] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3540), .Q (u_wr_w_timer[5]));
  DFFRHQX1 \u_wr_w_timer_reg[6] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3526), .Q (u_wr_w_timer[6]));
  DFFRHQX1 \u_wr_w_timer_reg[7] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3512), .Q (u_wr_w_timer[7]));
  DFFRHQX1 \u_wr_w_timer_reg[8] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3498), .Q (u_wr_w_timer[8]));
  DFFRHQX1 \u_wr_w_timer_reg[9] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3484), .Q (u_wr_w_timer[9]));
  DFFRHQX1 \u_wr_w_timer_reg[10] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3470), .Q (u_wr_w_timer[10]));
  DFFRHQX1 \u_wr_w_timer_reg[11] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3456), .Q (u_wr_w_timer[11]));
  DFFRHQX1 \u_wr_w_timer_reg[12] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3442), .Q (u_wr_w_timer[12]));
  DFFRHQX1 \u_wr_w_timer_reg[13] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3428), .Q (u_wr_w_timer[13]));
  DFFRHQX1 \u_wr_w_timer_reg[14] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3412), .Q (u_wr_w_timer[14]));
  DFFRHQX1 \u_wr_w_timer_reg[15] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3406), .Q (u_wr_w_timer[15]));
  NOR2X1 u_wr_g5083(.A (u_wr_n_3760), .B (u_wr_n_3408), .Y
       (u_wr_n_3406));
  NOR2X1 u_wr_g5084(.A (u_wr_n_3671), .B (u_wr_n_3410), .Y
       (u_wr_n_3407));
  AOI22X1 u_wr_g5087(.A0 (u_wr_n_3820), .A1 (u_wr_n_3416), .B0
       (u_wr_w_timer[15]), .B1 (u_wr_n_3821), .Y (u_wr_n_3408));
  AOI22X1 u_wr_g5088(.A0 (u_wr_n_3811), .A1 (u_wr_n_3417), .B0
       (u_wr_b_timer[15]), .B1 (u_wr_n_3812), .Y (u_wr_n_3410));
  AOI21XL u_wr_g5089(.A0 (u_wr_n_3800), .A1 (u_wr_n_3418), .B0
       (u_wr_n_3760), .Y (u_wr_n_3412));
  AOI21XL u_wr_g5090(.A0 (u_wr_n_3802), .A1 (u_wr_n_3422), .B0
       (u_wr_n_3671), .Y (u_wr_n_3414));
  XNOR2X1 u_wr_g5091(.A (u_wr_w_timer[15]), .B (u_wr_n_3430), .Y
       (u_wr_n_3416));
  XNOR2X1 u_wr_g5092(.A (u_wr_b_timer[15]), .B (u_wr_n_3432), .Y
       (u_wr_n_3417));
  OAI211X1 u_wr_g5095(.A0 (u_wr_w_timer[14]), .A1 (u_wr_n_3440), .B0
       (u_wr_n_3820), .C0 (u_wr_n_3430), .Y (u_wr_n_3418));
  OAI211X1 u_wr_g5096(.A0 (u_wr_b_timer[14]), .A1 (u_wr_n_3438), .B0
       (u_wr_n_3811), .C0 (u_wr_n_3432), .Y (u_wr_n_3422));
  AOI21XL u_wr_g5097(.A0 (u_wr_n_3797), .A1 (u_wr_n_3433), .B0
       (u_wr_n_3760), .Y (u_wr_n_3428));
  AOI21XL u_wr_g5098(.A0 (u_wr_n_3801), .A1 (u_wr_n_3435), .B0
       (u_wr_n_3671), .Y (u_wr_n_3429));
  NAND2X1 u_wr_g5099(.A (u_wr_w_timer[14]), .B (u_wr_n_3440), .Y
       (u_wr_n_3430));
  OAI211X1 u_wr_g5102(.A0 (u_wr_w_timer[13]), .A1 (u_wr_n_3452), .B0
       (u_wr_n_3820), .C0 (u_wr_n_3444), .Y (u_wr_n_3433));
  OAI211X1 u_wr_g5103(.A0 (u_wr_b_timer[13]), .A1 (u_wr_n_3454), .B0
       (u_wr_n_3811), .C0 (u_wr_n_3446), .Y (u_wr_n_3435));
  NAND2X1 u_wr_g5104(.A (u_wr_b_timer[14]), .B (u_wr_n_3438), .Y
       (u_wr_n_3432));
  INVX1 u_wr_g5105(.A (u_wr_n_3446), .Y (u_wr_n_3438));
  INVX1 u_wr_g5106(.A (u_wr_n_3444), .Y (u_wr_n_3440));
  AOI21XL u_wr_g5107(.A0 (u_wr_n_3781), .A1 (u_wr_n_3447), .B0
       (u_wr_n_3760), .Y (u_wr_n_3442));
  AOI21XL u_wr_g5108(.A0 (u_wr_n_3799), .A1 (u_wr_n_3449), .B0
       (u_wr_n_3671), .Y (u_wr_n_3443));
  NAND2X1 u_wr_g5109(.A (u_wr_w_timer[13]), .B (u_wr_n_3452), .Y
       (u_wr_n_3444));
  OAI211X1 u_wr_g5112(.A0 (u_wr_w_timer[12]), .A1 (u_wr_n_3466), .B0
       (u_wr_n_3820), .C0 (u_wr_n_3458), .Y (u_wr_n_3447));
  OAI211X1 u_wr_g5113(.A0 (u_wr_b_timer[12]), .A1 (u_wr_n_3468), .B0
       (u_wr_n_3811), .C0 (u_wr_n_3460), .Y (u_wr_n_3449));
  NAND2X1 u_wr_g5114(.A (u_wr_b_timer[13]), .B (u_wr_n_3454), .Y
       (u_wr_n_3446));
  INVX1 u_wr_g5115(.A (u_wr_n_3458), .Y (u_wr_n_3452));
  INVX1 u_wr_g5116(.A (u_wr_n_3460), .Y (u_wr_n_3454));
  AOI21XL u_wr_g5117(.A0 (u_wr_n_3780), .A1 (u_wr_n_3461), .B0
       (u_wr_n_3760), .Y (u_wr_n_3456));
  AOI21XL u_wr_g5118(.A0 (u_wr_n_3796), .A1 (u_wr_n_3463), .B0
       (u_wr_n_3671), .Y (u_wr_n_3457));
  NAND2X1 u_wr_g5119(.A (u_wr_w_timer[12]), .B (u_wr_n_3466), .Y
       (u_wr_n_3458));
  OAI211X1 u_wr_g5122(.A0 (u_wr_w_timer[11]), .A1 (u_wr_n_3482), .B0
       (u_wr_n_3820), .C0 (u_wr_n_3472), .Y (u_wr_n_3461));
  OAI211X1 u_wr_g5123(.A0 (u_wr_b_timer[11]), .A1 (u_wr_n_3480), .B0
       (u_wr_n_3811), .C0 (u_wr_n_3474), .Y (u_wr_n_3463));
  NAND2X1 u_wr_g5124(.A (u_wr_b_timer[12]), .B (u_wr_n_3468), .Y
       (u_wr_n_3460));
  INVX1 u_wr_g5125(.A (u_wr_n_3472), .Y (u_wr_n_3466));
  INVX1 u_wr_g5126(.A (u_wr_n_3474), .Y (u_wr_n_3468));
  AOI21X1 u_wr_g5127(.A0 (u_wr_n_3779), .A1 (u_wr_n_3475), .B0
       (u_wr_n_3760), .Y (u_wr_n_3470));
  AOI21XL u_wr_g5128(.A0 (u_wr_n_3795), .A1 (u_wr_n_3477), .B0
       (u_wr_n_3671), .Y (u_wr_n_3471));
  NAND2X1 u_wr_g5129(.A (u_wr_w_timer[11]), .B (u_wr_n_3482), .Y
       (u_wr_n_3472));
  OAI211X1 u_wr_g5132(.A0 (u_wr_w_timer[10]), .A1 (u_wr_n_3496), .B0
       (u_wr_n_3820), .C0 (u_wr_n_3486), .Y (u_wr_n_3475));
  OAI211X1 u_wr_g5133(.A0 (u_wr_b_timer[10]), .A1 (u_wr_n_3494), .B0
       (u_wr_n_3811), .C0 (u_wr_n_3488), .Y (u_wr_n_3477));
  NAND2X1 u_wr_g5134(.A (u_wr_b_timer[11]), .B (u_wr_n_3480), .Y
       (u_wr_n_3474));
  INVX1 u_wr_g5135(.A (u_wr_n_3488), .Y (u_wr_n_3480));
  INVX1 u_wr_g5136(.A (u_wr_n_3486), .Y (u_wr_n_3482));
  AOI21X1 u_wr_g5137(.A0 (u_wr_n_3778), .A1 (u_wr_n_3489), .B0
       (u_wr_n_3760), .Y (u_wr_n_3484));
  AOI21XL u_wr_g5138(.A0 (u_wr_n_3794), .A1 (u_wr_n_3491), .B0
       (u_wr_n_3671), .Y (u_wr_n_3485));
  NAND2X1 u_wr_g5139(.A (u_wr_w_timer[10]), .B (u_wr_n_3496), .Y
       (u_wr_n_3486));
  OAI211X1 u_wr_g5142(.A0 (u_wr_w_timer[9]), .A1 (u_wr_n_3510), .B0
       (u_wr_n_3820), .C0 (u_wr_n_3500), .Y (u_wr_n_3489));
  OAI211X1 u_wr_g5143(.A0 (u_wr_b_timer[9]), .A1 (u_wr_n_3508), .B0
       (u_wr_n_3811), .C0 (u_wr_n_3502), .Y (u_wr_n_3491));
  NAND2X1 u_wr_g5144(.A (u_wr_b_timer[10]), .B (u_wr_n_3494), .Y
       (u_wr_n_3488));
  INVX1 u_wr_g5145(.A (u_wr_n_3502), .Y (u_wr_n_3494));
  INVX1 u_wr_g5146(.A (u_wr_n_3500), .Y (u_wr_n_3496));
  AOI21X1 u_wr_g5147(.A0 (u_wr_n_3776), .A1 (u_wr_n_3503), .B0
       (u_wr_n_3760), .Y (u_wr_n_3498));
  AOI21XL u_wr_g5148(.A0 (u_wr_n_3793), .A1 (u_wr_n_3505), .B0
       (u_wr_n_3671), .Y (u_wr_n_3499));
  NAND2X1 u_wr_g5149(.A (u_wr_w_timer[9]), .B (u_wr_n_3510), .Y
       (u_wr_n_3500));
  OAI211X1 u_wr_g5152(.A0 (u_wr_w_timer[8]), .A1 (u_wr_n_3524), .B0
       (u_wr_n_3820), .C0 (u_wr_n_3514), .Y (u_wr_n_3503));
  OAI211X1 u_wr_g5153(.A0 (u_wr_b_timer[8]), .A1 (u_wr_n_3522), .B0
       (u_wr_n_3811), .C0 (u_wr_n_3516), .Y (u_wr_n_3505));
  NAND2X1 u_wr_g5154(.A (u_wr_b_timer[9]), .B (u_wr_n_3508), .Y
       (u_wr_n_3502));
  INVX1 u_wr_g5155(.A (u_wr_n_3516), .Y (u_wr_n_3508));
  INVX1 u_wr_g5156(.A (u_wr_n_3514), .Y (u_wr_n_3510));
  AOI21X1 u_wr_g5157(.A0 (u_wr_n_3777), .A1 (u_wr_n_3517), .B0
       (u_wr_n_3760), .Y (u_wr_n_3512));
  AOI21XL u_wr_g5158(.A0 (u_wr_n_3803), .A1 (u_wr_n_3519), .B0
       (u_wr_n_3671), .Y (u_wr_n_3513));
  NAND2X1 u_wr_g5159(.A (u_wr_w_timer[8]), .B (u_wr_n_3524), .Y
       (u_wr_n_3514));
  OAI211X1 u_wr_g5162(.A0 (u_wr_w_timer[7]), .A1 (u_wr_n_3536), .B0
       (u_wr_n_3820), .C0 (u_wr_n_3528), .Y (u_wr_n_3517));
  OAI211X1 u_wr_g5163(.A0 (u_wr_b_timer[7]), .A1 (u_wr_n_3538), .B0
       (u_wr_n_3811), .C0 (u_wr_n_3530), .Y (u_wr_n_3519));
  NAND2X1 u_wr_g5164(.A (u_wr_b_timer[8]), .B (u_wr_n_3522), .Y
       (u_wr_n_3516));
  INVX1 u_wr_g5165(.A (u_wr_n_3530), .Y (u_wr_n_3522));
  INVX1 u_wr_g5166(.A (u_wr_n_3528), .Y (u_wr_n_3524));
  AOI21X1 u_wr_g5167(.A0 (u_wr_n_3792), .A1 (u_wr_n_3531), .B0
       (u_wr_n_3760), .Y (u_wr_n_3526));
  AOI21XL u_wr_g5168(.A0 (u_wr_n_3768), .A1 (u_wr_n_3533), .B0
       (u_wr_n_3671), .Y (u_wr_n_3527));
  NAND2X1 u_wr_g5169(.A (u_wr_w_timer[7]), .B (u_wr_n_3536), .Y
       (u_wr_n_3528));
  OAI211X1 u_wr_g5172(.A0 (u_wr_w_timer[6]), .A1 (u_wr_n_3550), .B0
       (u_wr_n_3820), .C0 (u_wr_n_3542), .Y (u_wr_n_3531));
  OAI211X1 u_wr_g5173(.A0 (u_wr_b_timer[6]), .A1 (u_wr_n_3552), .B0
       (u_wr_n_3811), .C0 (u_wr_n_3544), .Y (u_wr_n_3533));
  NAND2X1 u_wr_g5174(.A (u_wr_b_timer[7]), .B (u_wr_n_3538), .Y
       (u_wr_n_3530));
  INVX1 u_wr_g5175(.A (u_wr_n_3542), .Y (u_wr_n_3536));
  INVX1 u_wr_g5176(.A (u_wr_n_3544), .Y (u_wr_n_3538));
  AOI21X1 u_wr_g5177(.A0 (u_wr_n_3775), .A1 (u_wr_n_3545), .B0
       (u_wr_n_3760), .Y (u_wr_n_3540));
  AOI21XL u_wr_g5178(.A0 (u_wr_n_3784), .A1 (u_wr_n_3547), .B0
       (u_wr_n_3671), .Y (u_wr_n_3541));
  NAND2X1 u_wr_g5179(.A (u_wr_w_timer[6]), .B (u_wr_n_3550), .Y
       (u_wr_n_3542));
  OAI211X1 u_wr_g5182(.A0 (u_wr_w_timer[5]), .A1 (u_wr_n_3567), .B0
       (u_wr_n_3820), .C0 (u_wr_n_3556), .Y (u_wr_n_3545));
  OAI211X1 u_wr_g5183(.A0 (u_wr_b_timer[5]), .A1 (u_wr_n_3565), .B0
       (u_wr_n_3811), .C0 (u_wr_n_3558), .Y (u_wr_n_3547));
  NAND2X1 u_wr_g5184(.A (u_wr_b_timer[6]), .B (u_wr_n_3552), .Y
       (u_wr_n_3544));
  INVX1 u_wr_g5185(.A (u_wr_n_3556), .Y (u_wr_n_3550));
  INVX1 u_wr_g5186(.A (u_wr_n_3558), .Y (u_wr_n_3552));
  AOI21X1 u_wr_g5187(.A0 (u_wr_n_3774), .A1 (u_wr_n_3559), .B0
       (u_wr_n_3760), .Y (u_wr_n_3554));
  AOI21XL u_wr_g5188(.A0 (u_wr_n_3782), .A1 (u_wr_n_3562), .B0
       (u_wr_n_3671), .Y (u_wr_n_3555));
  NAND2X1 u_wr_g5190(.A (u_wr_w_timer[5]), .B (u_wr_n_3567), .Y
       (u_wr_n_3556));
  OAI211X1 u_wr_g5194(.A0 (u_wr_w_timer[4]), .A1 (u_wr_n_3592), .B0
       (u_wr_n_3820), .C0 (u_wr_n_3577), .Y (u_wr_n_3559));
  OAI211X1 u_wr_g5196(.A0 (u_wr_b_timer[4]), .A1 (u_wr_n_3594), .B0
       (u_wr_n_3811), .C0 (u_wr_n_3580), .Y (u_wr_n_3562));
  NAND2X1 u_wr_g5197(.A (u_wr_b_timer[5]), .B (u_wr_n_3565), .Y
       (u_wr_n_3558));
  INVX1 u_wr_g5198(.A (u_wr_n_3580), .Y (u_wr_n_3565));
  INVX1 u_wr_g5199(.A (u_wr_n_3577), .Y (u_wr_n_3567));
  AOI21X1 u_wr_g5200(.A0 (u_wr_n_3772), .A1 (u_wr_n_3589), .B0
       (u_wr_n_3760), .Y (u_wr_n_3569));
  AOI21XL u_wr_g5202(.A0 (u_wr_n_3581), .A1 (u_wr_n_3783), .B0
       (u_wr_n_3671), .Y (u_wr_n_3570));
  OAI211X1 u_wr_g5203(.A0 (logic_0_1_net), .A1 (u_wr_n_3585), .B0
       (u_wr_n_3630), .C0 (u_wr_n_3650), .Y (u_wr_n_3571));
  AOI33XL u_wr_g5206(.A0 (u_wr_n_3841), .A1 (u_wr_n_3838), .A2
       (u_wr_n_3596), .B0 (u_wr_n_3875), .B1 (u_wr_n_158), .B2
       (s_wready), .Y (u_wr_n_3573));
  OAI211X1 u_wr_g5207(.A0 (u_wr_outst_cnt[3]), .A1 (u_wr_n_3650), .B0
       (u_wr_n_3644), .C0 (u_wr_n_3587), .Y (u_wr_n_3574));
  NAND2X1 u_wr_g5209(.A (u_wr_w_timer[4]), .B (u_wr_n_3592), .Y
       (u_wr_n_3577));
  OAI211X1 u_wr_g5214(.A0 (u_wr_b_timer[3]), .A1 (u_wr_n_3639), .B0
       (u_wr_n_3615), .C0 (u_wr_n_3811), .Y (u_wr_n_3581));
  NOR2X1 u_wr_g5215(.A (epoch_clr), .B (u_wr_n_3603), .Y (u_wr_n_3583));
  AOI22X1 u_wr_g5217(.A0 (u_wr_outst_cnt[2]), .A1 (u_wr_n_3605), .B0
       (u_wr_n_3808), .B1 (n_229), .Y (u_wr_n_3585));
  OAI211X1 u_wr_g5218(.A0 (u_wr_n_3682), .A1 (u_wr_n_3605), .B0
       (u_wr_outst_cnt[3]), .C0 (logic_1_1_net), .Y (u_wr_n_3587));
  OAI211X1 u_wr_g5219(.A0 (u_wr_w_timer[3]), .A1 (u_wr_n_3641), .B0
       (u_wr_n_3820), .C0 (u_wr_n_3614), .Y (u_wr_n_3589));
  NAND2X1 u_wr_g5220(.A (u_wr_b_timer[4]), .B (u_wr_n_3594), .Y
       (u_wr_n_3580));
  INVX1 u_wr_g5221(.A (u_wr_n_3614), .Y (u_wr_n_3592));
  INVX1 u_wr_g5222(.A (u_wr_n_3615), .Y (u_wr_n_3594));
  NAND2BX1 u_wr_g5223(.AN (u_wr_n_3828), .B (u_wr_n_3606), .Y
       (u_wr_n_3596));
  AOI21X1 u_wr_g5224(.A0 (u_wr_n_3773), .A1 (u_wr_n_3635), .B0
       (u_wr_n_3760), .Y (u_wr_n_3598));
  AOI21XL u_wr_g5225(.A0 (u_wr_n_3637), .A1 (u_wr_n_3798), .B0
       (u_wr_n_3671), .Y (u_wr_n_3599));
  OAI211X1 u_wr_g5226(.A0 (u_wr_n_3816), .A1 (u_wr_n_3716), .B0
       (u_wr_n_3643), .C0 (u_wr_n_3620), .Y (u_wr_n_3600));
  MXI2XL u_wr_g5227(.A (u_wr_n_3629), .B (u_wr_n_3634), .S0
       (u_wr_drain_cnt[1]), .Y (u_wr_n_3601));
  XNOR2X1 u_wr_g5228(.A (u_wr_outst_cnt[0]), .B (u_wr_n_3651), .Y
       (u_wr_n_3603));
  NAND2BXL u_wr_g5231(.AN (u_wr_n_3651), .B (u_wr_outst_cnt[1]), .Y
       (u_wr_n_3607));
  MX2XL u_wr_g5232(.A (u_wr_n_3817), .B (s_wready), .S0 (n_229), .Y
       (u_wr_n_3605));
  AOI22X1 u_wr_g5233(.A0 (u_wr_n_3655), .A1 (u_wr_n_3845), .B0
       (u_wr_n_430), .B1 (s_wready), .Y (u_wr_n_3606));
  OAI31X1 u_wr_g5234(.A0 (u_wr_n_3867), .A1 (u_wr_n_3816), .A2
       (u_wr_n_3787), .B0 (u_wr_n_3643), .Y (u_wr_n_3616));
  OAI2BB1X1 u_wr_g5235(.A0N (u_wr_n_3664), .A1N (u_wr_n_3670), .B0
       (u_wr_drain_cnt[2]), .Y (u_wr_n_3620));
  NAND2X1 u_wr_g5236(.A (u_wr_w_timer[3]), .B (u_wr_n_3641), .Y
       (u_wr_n_3614));
  NAND2X1 u_wr_g5237(.A (u_wr_b_timer[3]), .B (u_wr_n_3639), .Y
       (u_wr_n_3615));
  OAI221X1 u_wr_g5242(.A0 (u_wr_drain_cnt[0]), .A1 (u_wr_n_3663), .B0
       (u_wr_n_3831), .B1 (u_wr_n_3785), .C0 (u_wr_n_3684), .Y
       (u_wr_n_3624));
  OAI211X1 u_wr_g5243(.A0 (u_wr_n_3807), .A1 (u_wr_n_3721), .B0
       (u_wr_n_3716), .C0 (u_wr_n_3670), .Y (u_wr_n_3626));
  AOI22XL u_wr_g5244(.A0 (u_wr_n_318), .A1 (u_wr_n_3662), .B0
       (u_wr_n_3830), .B1 (u_wr_n_3786), .Y (u_wr_n_3629));
  NAND3BXL u_wr_g5245(.AN (u_wr_n_3817), .B (u_wr_n_3950), .C
       (u_wr_n_3661), .Y (u_wr_n_3630));
  AOI211XL u_wr_g5247(.A0 (u_wr_drain_cnt[0]), .A1 (u_wr_n_3720), .B0
       (u_wr_n_3715), .C0 (u_wr_n_3714), .Y (u_wr_n_3634));
  OAI211X1 u_wr_g5248(.A0 (u_wr_w_timer[2]), .A1 (u_wr_n_3758), .B0
       (u_wr_n_3820), .C0 (u_wr_n_3719), .Y (u_wr_n_3635));
  OAI211X1 u_wr_g5249(.A0 (u_wr_b_timer[2]), .A1 (u_wr_n_3756), .B0
       (u_wr_n_3717), .C0 (u_wr_n_3811), .Y (u_wr_n_3637));
  INVX1 u_wr_g5250(.A (u_wr_n_3717), .Y (u_wr_n_3639));
  INVX1 u_wr_g5251(.A (u_wr_n_3719), .Y (u_wr_n_3641));
  NAND2X1 u_wr_g5252(.A (u_wr_n_3661), .B (u_wr_n_3731), .Y
       (u_wr_n_3644));
  NAND2X1 u_wr_g5255(.A (u_wr_n_3819), .B (u_wr_n_3661), .Y
       (u_wr_n_3646));
  NAND2X1 u_wr_g5256(.A (u_wr_n_3807), .B (u_wr_n_3662), .Y
       (u_wr_n_3643));
  NOR2XL u_wr_g5258(.A (u_wr_n_3733), .B (u_wr_n_3671), .Y
       (u_wr_n_3652));
  AOI21X1 u_wr_g5259(.A0 (u_wr_n_3770), .A1 (u_wr_n_3728), .B0
       (u_wr_n_3760), .Y (u_wr_n_3653));
  AOI21XL u_wr_g5260(.A0 (u_wr_n_3725), .A1 (u_wr_n_3804), .B0
       (u_wr_n_3671), .Y (u_wr_n_3654));
  OAI31X1 u_wr_g5262(.A0 (u_wr_wpair_state[0]), .A1 (u_wr_n_3871), .A2
       (epoch_clr), .B0 (u_wr_n_3681), .Y (u_wr_n_3656));
  OR2XL u_wr_g5263(.A (u_wr_n_3809), .B (u_wr_n_3660), .Y
       (u_wr_n_3650));
  OAI22X1 u_wr_g5264(.A0 (n_229), .A1 (u_wr_n_3845), .B0 (u_wr_n_3723),
       .B1 (s_wready), .Y (u_wr_n_3651));
  INVX1 u_wr_g5265(.A (u_wr_n_3663), .Y (u_wr_n_3662));
  OR2XL u_wr_g5266(.A (u_wr_n_3839), .B (u_wr_n_3721), .Y
       (u_wr_n_3664));
  NAND2X1 u_wr_g5269(.A (n_229), .B (u_wr_n_3810), .Y (u_wr_n_3660));
  NOR2X1 u_wr_g5270(.A (epoch_clr), .B (n_229), .Y (u_wr_n_3661));
  NAND2X1 u_wr_g5271(.A (m_bvalid), .B (u_wr_n_3720), .Y (u_wr_n_3663));
  NOR2X1 u_wr_g5273(.A (u_wr_n_3734), .B (u_wr_n_3760), .Y
       (u_wr_n_3678));
  NOR4BX1 u_wr_g5274(.AN (u_wr_n_3819), .B (u_wr_outst_cnt[3]), .C
       (u_wr_n_819), .D (u_wr_n_3808), .Y (u_wr_n_3679));
  OAI2BB1X1 u_wr_g5275(.A0N (u_wr_n_712), .A1N (u_wr_n_2043), .B0
       (u_wr_n_3718), .Y (u_wr_n_3681));
  NOR2BX1 u_wr_g5276(.AN (u_wr_n_3809), .B (u_wr_n_3723), .Y
       (u_wr_n_3682));
  OAI31X1 u_wr_g5277(.A0 (u_wr_n_3946), .A1 (u_wr_drain_cnt[0]), .A2
       (u_wr_n_145), .B0 (u_wr_n_3715), .Y (u_wr_n_3684));
  AOI21X1 u_wr_g5279(.A0 (u_wr_n_3816), .A1 (u_wr_n_3786), .B0
       (u_wr_n_3714), .Y (u_wr_n_3670));
  OR2X1 u_wr_g5280(.A (u_wr_n_3836), .B (n_229), .Y (u_wr_n_3671));
  INVX1 u_wr_g5305(.A (u_wr_n_3720), .Y (u_wr_n_3721));
  INVX1 u_wr_g5306(.A (n_229), .Y (u_wr_n_3723));
  NOR2BX1 u_wr_g5307(.AN (u_wr_n_3788), .B (epoch_clr), .Y
       (u_wr_n_3724));
  OAI211X1 u_wr_g5308(.A0 (u_wr_b_timer[0]), .A1 (u_wr_b_timer[1]), .B0
       (u_wr_n_3843), .C0 (u_wr_n_3811), .Y (u_wr_n_3725));
  OAI211X1 u_wr_g5309(.A0 (u_wr_w_timer[0]), .A1 (u_wr_w_timer[1]), .B0
       (u_wr_n_3842), .C0 (u_wr_n_3820), .Y (u_wr_n_3728));
  OAI32X1 u_wr_g5310(.A0 (u_wr_outst_cnt[3]), .A1 (u_wr_n_3950), .A2
       (u_wr_n_3817), .B0 (u_wr_outst_cnt[2]), .B1 (u_wr_n_3877), .Y
       (u_wr_n_3731));
  XNOR2X1 u_wr_g5311(.A (u_wr_b_timer[0]), .B (u_wr_n_3811), .Y
       (u_wr_n_3733));
  XNOR2X1 u_wr_g5312(.A (u_wr_w_timer[0]), .B (u_wr_n_3820), .Y
       (u_wr_n_3734));
  NOR2XL u_wr_g5313(.A (m_bvalid), .B (u_wr_n_3785), .Y (u_wr_n_3714));
  NOR2XL u_wr_g5321(.A (u_wr_n_3830), .B (u_wr_n_3787), .Y
       (u_wr_n_3715));
  NAND2XL u_wr_g5323(.A (u_wr_n_3867), .B (u_wr_n_3786), .Y
       (u_wr_n_3716));
  NAND2X1 u_wr_g5327(.A (u_wr_b_timer[2]), .B (u_wr_n_3756), .Y
       (u_wr_n_3717));
  NOR3BX1 u_wr_g5328(.AN (u_wr_n_3810), .B (u_wr_wpair_state[1]), .C
       (u_wr_n_435), .Y (u_wr_n_3718));
  NAND2X1 u_wr_g5329(.A (u_wr_w_timer[2]), .B (u_wr_n_3758), .Y
       (u_wr_n_3719));
  NOR2X1 u_wr_g5330(.A (u_wr_n_145), .B (u_wr_n_3785), .Y
       (u_wr_n_3720));
  INVX1 u_wr_g5332(.A (u_wr_n_3843), .Y (u_wr_n_3756));
  INVX1 u_wr_g5333(.A (u_wr_n_3842), .Y (u_wr_n_3758));
  NAND2X1 u_wr_g5334(.A (u_wr_b_timer[6]), .B (u_wr_n_3812), .Y
       (u_wr_n_3768));
  NAND2XL u_wr_g5335(.A (u_wr_w_timer[1]), .B (u_wr_n_3821), .Y
       (u_wr_n_3770));
  NAND2XL u_wr_g5336(.A (u_wr_w_timer[3]), .B (u_wr_n_3821), .Y
       (u_wr_n_3772));
  NAND2XL u_wr_g5337(.A (u_wr_w_timer[2]), .B (u_wr_n_3821), .Y
       (u_wr_n_3773));
  NAND2XL u_wr_g5338(.A (u_wr_w_timer[4]), .B (u_wr_n_3821), .Y
       (u_wr_n_3774));
  NAND2XL u_wr_g5339(.A (u_wr_w_timer[5]), .B (u_wr_n_3821), .Y
       (u_wr_n_3775));
  NAND2XL u_wr_g5340(.A (u_wr_w_timer[8]), .B (u_wr_n_3821), .Y
       (u_wr_n_3776));
  NAND2XL u_wr_g5341(.A (u_wr_w_timer[7]), .B (u_wr_n_3821), .Y
       (u_wr_n_3777));
  NAND2XL u_wr_g5342(.A (u_wr_w_timer[9]), .B (u_wr_n_3821), .Y
       (u_wr_n_3778));
  NAND2XL u_wr_g5343(.A (u_wr_w_timer[10]), .B (u_wr_n_3821), .Y
       (u_wr_n_3779));
  NAND2XL u_wr_g5344(.A (u_wr_w_timer[11]), .B (u_wr_n_3821), .Y
       (u_wr_n_3780));
  NAND2XL u_wr_g5345(.A (u_wr_w_timer[12]), .B (u_wr_n_3821), .Y
       (u_wr_n_3781));
  NAND2X1 u_wr_g5346(.A (u_wr_b_timer[4]), .B (u_wr_n_3812), .Y
       (u_wr_n_3782));
  NAND2X1 u_wr_g5347(.A (u_wr_b_timer[3]), .B (u_wr_n_3812), .Y
       (u_wr_n_3783));
  NAND2X1 u_wr_g5348(.A (u_wr_b_timer[5]), .B (u_wr_n_3812), .Y
       (u_wr_n_3784));
  NAND2X1 u_wr_g5349(.A (u_wr_n_1641), .B (u_wr_n_3810), .Y
       (u_wr_n_3760));
  INVX1 u_wr_g5350(.A (u_wr_n_3786), .Y (u_wr_n_3787));
  OAI32X1 u_wr_g5351(.A0 (s_bready), .A1 (u_wr_wr_state[0]), .A2
       (u_wr_n_3875), .B0 (u_wr_n_3840), .B1 (u_wr_n_3838), .Y
       (u_wr_n_3788));
  NAND2XL u_wr_g5352(.A (u_wr_w_timer[6]), .B (u_wr_n_3821), .Y
       (u_wr_n_3792));
  NAND2X1 u_wr_g5353(.A (u_wr_b_timer[8]), .B (u_wr_n_3812), .Y
       (u_wr_n_3793));
  NAND2X1 u_wr_g5354(.A (u_wr_b_timer[9]), .B (u_wr_n_3812), .Y
       (u_wr_n_3794));
  NAND2X1 u_wr_g5355(.A (u_wr_b_timer[10]), .B (u_wr_n_3812), .Y
       (u_wr_n_3795));
  NAND2X1 u_wr_g5356(.A (u_wr_b_timer[11]), .B (u_wr_n_3812), .Y
       (u_wr_n_3796));
  NAND2XL u_wr_g5357(.A (u_wr_w_timer[13]), .B (u_wr_n_3821), .Y
       (u_wr_n_3797));
  NAND2X1 u_wr_g5358(.A (u_wr_b_timer[2]), .B (u_wr_n_3812), .Y
       (u_wr_n_3798));
  NAND2X1 u_wr_g5359(.A (u_wr_b_timer[12]), .B (u_wr_n_3812), .Y
       (u_wr_n_3799));
  NAND2XL u_wr_g5360(.A (u_wr_w_timer[14]), .B (u_wr_n_3821), .Y
       (u_wr_n_3800));
  NAND2X1 u_wr_g5361(.A (u_wr_b_timer[13]), .B (u_wr_n_3812), .Y
       (u_wr_n_3801));
  NAND2X1 u_wr_g5362(.A (u_wr_b_timer[14]), .B (u_wr_n_3812), .Y
       (u_wr_n_3802));
  NAND2X1 u_wr_g5363(.A (u_wr_b_timer[7]), .B (u_wr_n_3812), .Y
       (u_wr_n_3803));
  NAND2X1 u_wr_g5364(.A (u_wr_b_timer[1]), .B (u_wr_n_3812), .Y
       (u_wr_n_3804));
  NAND2X1 u_wr_g5365(.A (u_wr_n_3818), .B (u_wr_n_2054), .Y
       (u_wr_n_3785));
  NOR2X1 u_wr_g5366(.A (u_wr_n_3818), .B (epoch_clr), .Y (u_wr_n_3786));
  INVX1 u_wr_g5367(.A (u_wr_n_3811), .Y (u_wr_n_3812));
  AND2XL u_wr_g5368(.A (u_wr_n_3867), .B (u_wr_n_3839), .Y
       (u_wr_n_3807));
  NOR2X1 u_wr_g5369(.A (u_wr_n_3950), .B (u_wr_n_3829), .Y
       (u_wr_n_3808));
  NAND2X1 u_wr_g5370(.A (u_wr_n_3950), .B (u_wr_n_3829), .Y
       (u_wr_n_3809));
  NOR2X1 u_wr_g5371(.A (epoch_clr), .B (s_wready), .Y (u_wr_n_3810));
  NOR2X2 u_wr_g5372(.A (u_wr_n_3840), .B (u_wr_n_230), .Y
       (u_wr_n_3811));
  INVX1 u_wr_g5373(.A (u_wr_n_3820), .Y (u_wr_n_3821));
  MX2XL u_wr_g5374(.A (u_wr_n_2115), .B (s_wready), .S0 (s_wvalid), .Y
       (u_wr_n_3822));
  NAND3X1 u_wr_g5375(.A (u_wr_n_3946), .B (u_wr_drain_cnt[1]), .C
       (u_wr_drain_cnt[0]), .Y (u_wr_n_3816));
  NAND3X1 u_wr_g5376(.A (u_wr_outst_cnt[1]), .B (u_wr_outst_cnt[0]), .C
       (s_wready), .Y (u_wr_n_3817));
  NAND3X1 u_wr_g5377(.A (s_bready), .B (u_wr_wr_state[1]), .C
       (u_wr_n_158), .Y (u_wr_n_3818));
  XNOR2X1 u_wr_g5378(.A (u_wr_outst_cnt[1]), .B (u_wr_n_819), .Y
       (u_wr_n_3819));
  AND2X1 u_wr_g5379(.A (u_wr_n_3833), .B (u_wr_n_3871), .Y
       (u_wr_n_3820));
  INVX1 u_wr_g5380(.A (u_wr_n_3830), .Y (u_wr_n_3831));
  NOR2X1 u_wr_g5381(.A (s_wvalid), .B (u_wr_n_435), .Y (u_wr_n_3833));
  NAND2X1 u_wr_g5382(.A (u_wr_n_2054), .B (u_wr_n_1627), .Y
       (u_wr_n_3836));
  NAND2X1 u_wr_g5383(.A (s_bready), .B (s_bvalid), .Y (u_wr_n_3828));
  NOR2X1 u_wr_g5384(.A (u_wr_outst_cnt[1]), .B (u_wr_outst_cnt[0]), .Y
       (u_wr_n_3829));
  NOR2X1 u_wr_g5385(.A (m_bvalid), .B (u_wr_n_318), .Y (u_wr_n_3830));
  OR2X2 u_wr_g5386(.A (u_wr_n_2120), .B (u_wr_n_3848), .Y
       (u_wr_n_3832));
  INVX1 u_wr_g5387(.A (u_wr_n_3840), .Y (u_wr_n_3841));
  INVX1 u_wr_g5388(.A (s_wready), .Y (u_wr_n_3845));
  NOR2BX1 u_wr_g5389(.AN (u_wr_n_1867), .B (flush), .Y (u_wr_n_3838));
  NOR2X1 u_wr_g5390(.A (u_wr_drain_cnt[1]), .B (u_wr_drain_cnt[0]), .Y
       (u_wr_n_3839));
  NAND2X1 u_wr_g5391(.A (u_wr_wr_state[0]), .B (u_wr_n_3875), .Y
       (u_wr_n_3840));
  NAND2X1 u_wr_g5392(.A (u_wr_w_timer[1]), .B (u_wr_w_timer[0]), .Y
       (u_wr_n_3842));
  NAND2X1 u_wr_g5393(.A (u_wr_b_timer[1]), .B (u_wr_b_timer[0]), .Y
       (u_wr_n_3843));
  INVXL u_wr_g5395(.A (s_awready), .Y (u_wr_n_3848));
  INVX1 u_wr_g5403(.A (m_bvalid), .Y (u_wr_n_3946));
  INVX1 u_wr_g5405(.A (epoch_clr), .Y (u_wr_n_2054));
  DFFRX1 \u_wr_drain_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3600), .Q (u_wr_drain_cnt[2]), .QN (u_wr_n_3867));
  DFFRX1 \u_wr_outst_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3571), .Q (u_wr_outst_cnt[2]), .QN (u_wr_n_3950));
  DFFRX1 \u_wr_outst_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3574), .Q (u_wr_outst_cnt[3]), .QN (u_wr_n_3877));
  DFFRX1 \u_wr_wpair_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_227),
       .Q (u_wr_wpair_state[0]), .QN (u_wr_n_435));
  DFFRX1 \u_wr_wpair_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3656), .Q (u_wr_wpair_state[1]), .QN (u_wr_n_3871));
  DFFRX1 \u_wr_wr_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_225), .Q
       (u_wr_wr_state[0]), .QN (u_wr_n_158));
  DFFRX1 \u_wr_wr_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3724), .Q (u_wr_wr_state[1]), .QN (u_wr_n_3875));
  OR4X1 u_rd_g1177(.A (u_rd_outst_cnt[0]), .B (u_rd_outst_cnt[1]), .C
       (u_rd_outst_cnt[2]), .D (u_rd_outst_cnt[3]), .Y (u_rd_n_300));
  OR2XL u_rd_g1178(.A (u_rd_n_287), .B (u_rd_n_300), .Y (rd_busy));
  OR4X1 u_rd_g1179(.A (u_rd_drain_cnt[3]), .B (u_rd_drain_cnt[2]), .C
       (u_rd_drain_cnt[1]), .D (u_rd_drain_cnt[0]), .Y (u_rd_n_287));
  NOR2BX1 u_rd_g1970(.AN (u_rd_timer_run), .B (u_rd_n_1710), .Y
       (rd_timeout_pulse));
  NAND4XL u_rd_g1973(.A (u_rd_n_1760), .B (u_rd_n_1759), .C
       (u_rd_n_1758), .D (u_rd_n_1756), .Y (u_rd_n_1710));
  OR2X1 u_rd_g1974(.A (u_rd_n_288), .B (u_rd_n_287), .Y (m_rready));
  AO21X1 u_rd_g1975(.A0 (u_rd_n_1765), .A1 (u_rd_n_285), .B0
       (u_rd_n_1766), .Y (s_rvalid));
  NAND3BXL u_rd_g1976(.AN (flush), .B (s_arvalid), .C (u_rd_n_1741), .Y
       (u_rd_n_1715));
  NAND3BXL u_rd_g1977(.AN (flush), .B (m_arready), .C (u_rd_n_1741), .Y
       (u_rd_n_1716));
  AO21X1 u_rd_g1978(.A0 (\m_r[resp] [1]), .A1 (u_rd_n_285), .B0
       (u_rd_n_1766), .Y (\s_r[resp] [1]));
  AND2X1 u_rd_g1979(.A (u_rd_n_285), .B (\m_r[data] [19]), .Y
       (\s_r[data] [19]));
  AND2X1 u_rd_g1980(.A (u_rd_n_285), .B (\m_r[data] [18]), .Y
       (\s_r[data] [18]));
  AND2X1 u_rd_g1981(.A (u_rd_n_285), .B (\m_r[resp] [0]), .Y
       (\s_r[resp] [0]));
  AND2X1 u_rd_g1982(.A (u_rd_n_285), .B (\m_r[data] [17]), .Y
       (\s_r[data] [17]));
  AND2X1 u_rd_g1983(.A (u_rd_n_285), .B (\m_r[data] [16]), .Y
       (\s_r[data] [16]));
  AND2X1 u_rd_g1984(.A (u_rd_n_285), .B (\m_r[data] [15]), .Y
       (\s_r[data] [15]));
  AND2X1 u_rd_g1985(.A (u_rd_n_285), .B (\m_r[data] [14]), .Y
       (\s_r[data] [14]));
  AND2X1 u_rd_g1986(.A (u_rd_n_285), .B (\m_r[data] [13]), .Y
       (\s_r[data] [13]));
  AND2X1 u_rd_g1987(.A (u_rd_n_285), .B (\m_r[data] [12]), .Y
       (\s_r[data] [12]));
  AND2X1 u_rd_g1988(.A (u_rd_n_285), .B (\m_r[data] [31]), .Y
       (\s_r[data] [31]));
  AND2X1 u_rd_g1989(.A (u_rd_n_285), .B (\m_r[data] [11]), .Y
       (\s_r[data] [11]));
  AND2X1 u_rd_g1990(.A (u_rd_n_285), .B (\m_r[data] [10]), .Y
       (\s_r[data] [10]));
  AND2X1 u_rd_g1991(.A (u_rd_n_285), .B (\m_r[data] [30]), .Y
       (\s_r[data] [30]));
  AND2X1 u_rd_g1992(.A (u_rd_n_285), .B (\m_r[data] [9]), .Y
       (\s_r[data] [9]));
  AND2X1 u_rd_g1993(.A (u_rd_n_285), .B (\m_r[data] [8]), .Y
       (\s_r[data] [8]));
  AND2X1 u_rd_g1994(.A (u_rd_n_285), .B (\m_r[data] [29]), .Y
       (\s_r[data] [29]));
  AND2X1 u_rd_g1995(.A (u_rd_n_285), .B (\m_r[data] [7]), .Y
       (\s_r[data] [7]));
  AND2X1 u_rd_g1996(.A (u_rd_n_285), .B (\m_r[data] [6]), .Y
       (\s_r[data] [6]));
  AND2X1 u_rd_g1997(.A (u_rd_n_285), .B (\m_r[data] [28]), .Y
       (\s_r[data] [28]));
  AND2X1 u_rd_g1998(.A (u_rd_n_285), .B (\m_r[data] [5]), .Y
       (\s_r[data] [5]));
  AND2X1 u_rd_g1999(.A (u_rd_n_285), .B (\m_r[data] [4]), .Y
       (\s_r[data] [4]));
  AND2X1 u_rd_g2000(.A (u_rd_n_285), .B (\m_r[data] [26]), .Y
       (\s_r[data] [26]));
  AND2X1 u_rd_g2001(.A (u_rd_n_285), .B (\m_r[data] [3]), .Y
       (\s_r[data] [3]));
  AND2X1 u_rd_g2002(.A (u_rd_n_285), .B (\m_r[data] [2]), .Y
       (\s_r[data] [2]));
  AND2X1 u_rd_g2003(.A (u_rd_n_285), .B (\m_r[data] [1]), .Y
       (\s_r[data] [1]));
  AND2X1 u_rd_g2004(.A (u_rd_n_285), .B (\m_r[data] [0]), .Y
       (\s_r[data] [0]));
  AND2X1 u_rd_g2005(.A (u_rd_n_285), .B (\m_r[data] [27]), .Y
       (\s_r[data] [27]));
  AND2X1 u_rd_g2006(.A (u_rd_n_285), .B (\m_r[data] [25]), .Y
       (\s_r[data] [25]));
  AND2X1 u_rd_g2007(.A (u_rd_n_285), .B (\m_r[data] [24]), .Y
       (\s_r[data] [24]));
  AND2X1 u_rd_g2008(.A (u_rd_n_285), .B (\m_r[data] [23]), .Y
       (\s_r[data] [23]));
  AND2X1 u_rd_g2009(.A (u_rd_n_285), .B (\m_r[data] [22]), .Y
       (\s_r[data] [22]));
  AND2X1 u_rd_g2010(.A (u_rd_n_285), .B (\m_r[data] [21]), .Y
       (\s_r[data] [21]));
  NOR4X1 u_rd_g2011(.A (u_rd_timer[6]), .B (u_rd_timer[7]), .C
       (u_rd_timer[5]), .D (u_rd_timer[4]), .Y (u_rd_n_1756));
  AND2X1 u_rd_g2012(.A (u_rd_n_285), .B (\m_r[data] [20]), .Y
       (\s_r[data] [20]));
  NOR4X1 u_rd_g2013(.A (u_rd_timer[13]), .B (u_rd_timer[12]), .C
       (u_rd_timer[14]), .D (u_rd_timer[15]), .Y (u_rd_n_1758));
  NOR4BX1 u_rd_g2014(.AN (u_rd_timer[8]), .B (u_rd_timer[10]), .C
       (u_rd_timer[9]), .D (u_rd_timer[11]), .Y (u_rd_n_1759));
  NOR4X1 u_rd_g2015(.A (u_rd_timer[2]), .B (u_rd_timer[3]), .C
       (u_rd_timer[1]), .D (u_rd_timer[0]), .Y (u_rd_n_1760));
  OR4X1 u_rd_g2016(.A (u_rd_outst_cnt[0]), .B (u_rd_outst_cnt[1]), .C
       (u_rd_outst_cnt[2]), .D (u_rd_n_1773), .Y (u_rd_n_1741));
  AND2XL u_rd_g2018(.A (s_rready), .B (u_rd_n_285), .Y (u_rd_n_288));
  AND2X1 u_rd_g2021(.A (u_rd_rd_state[0]), .B (u_rd_n_1771), .Y
       (u_rd_n_285));
  NOR2BX1 u_rd_g2022(.AN (m_rvalid), .B (u_rd_n_287), .Y (u_rd_n_1765));
  NOR2X1 u_rd_g2023(.A (u_rd_rd_state[0]), .B (u_rd_n_1771), .Y
       (u_rd_n_1766));
  NOR2BX2 u_rd_g2(.AN (u_rd_n_285), .B (u_rd_n_1765), .Y
       (u_rd_timer_run));
  DFFRHQX1 \u_rd_drain_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2233), .Q (u_rd_drain_cnt[0]));
  DFFRHQX1 \u_rd_drain_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2204), .Q (u_rd_drain_cnt[1]));
  SDFFRHQX1 \u_rd_drain_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2240), .SI (u_rd_n_2217), .SE (u_rd_drain_cnt[2]), .Q
       (u_rd_drain_cnt[2]));
  DFFRHQX1 \u_rd_drain_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2196), .Q (u_rd_drain_cnt[3]));
  DFFRHQX1 \u_rd_outst_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2205), .Q (u_rd_outst_cnt[0]));
  DFFRHQX1 \u_rd_outst_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2180), .Q (u_rd_outst_cnt[1]));
  DFFRHQX1 \u_rd_outst_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2186), .Q (u_rd_outst_cnt[2]));
  DFFRHQX1 \u_rd_rd_state_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2170), .Q (u_rd_rd_state[0]));
  DFFRHQX1 \u_rd_timer_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2242), .Q (u_rd_timer[0]));
  DFFRHQX1 \u_rd_timer_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2243), .Q (u_rd_timer[1]));
  DFFRHQX1 \u_rd_timer_reg[2] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2207), .Q (u_rd_timer[2]));
  DFFRHQX1 \u_rd_timer_reg[3] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2185), .Q (u_rd_timer[3]));
  DFFRHQX1 \u_rd_timer_reg[4] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2169), .Q (u_rd_timer[4]));
  DFFRHQX1 \u_rd_timer_reg[5] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2162), .Q (u_rd_timer[5]));
  DFFRHQX1 \u_rd_timer_reg[6] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2155), .Q (u_rd_timer[6]));
  DFFRHQX1 \u_rd_timer_reg[7] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2148), .Q (u_rd_timer[7]));
  DFFRHQX1 \u_rd_timer_reg[8] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2141), .Q (u_rd_timer[8]));
  DFFRHQX1 \u_rd_timer_reg[9] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2134), .Q (u_rd_timer[9]));
  DFFRHQX1 \u_rd_timer_reg[10] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2127), .Q (u_rd_timer[10]));
  DFFRHQX1 \u_rd_timer_reg[11] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2120), .Q (u_rd_timer[11]));
  DFFRHQX1 \u_rd_timer_reg[12] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2113), .Q (u_rd_timer[12]));
  DFFRHQX1 \u_rd_timer_reg[13] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2106), .Q (u_rd_timer[13]));
  DFFRHQX1 \u_rd_timer_reg[14] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2098), .Q (u_rd_timer[14]));
  DFFRHQX1 \u_rd_timer_reg[15] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2093), .Q (u_rd_timer[15]));
  NOR2XL u_rd_g3518(.A (u_rd_n_2096), .B (u_rd_n_2252), .Y
       (u_rd_n_2093));
  AOI22X1 u_rd_g3520(.A0 (u_rd_timer_run), .A1 (u_rd_n_2100), .B0
       (u_rd_n_2366), .B1 (u_rd_timer[15]), .Y (u_rd_n_2096));
  AOI21XL u_rd_g3521(.A0 (u_rd_n_2299), .A1 (u_rd_n_2101), .B0
       (u_rd_n_2252), .Y (u_rd_n_2098));
  XNOR2X1 u_rd_g3522(.A (u_rd_timer[15]), .B (u_rd_n_2107), .Y
       (u_rd_n_2100));
  OAI211X1 u_rd_g3524(.A0 (u_rd_timer[14]), .A1 (u_rd_n_2111), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2107), .Y (u_rd_n_2101));
  AOI21XL u_rd_g3525(.A0 (u_rd_n_2302), .A1 (u_rd_n_2108), .B0
       (u_rd_n_2252), .Y (u_rd_n_2106));
  OAI211X1 u_rd_g3527(.A0 (u_rd_timer[13]), .A1 (u_rd_n_2118), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2114), .Y (u_rd_n_2108));
  NAND2X1 u_rd_g3528(.A (u_rd_timer[14]), .B (u_rd_n_2111), .Y
       (u_rd_n_2107));
  INVX1 u_rd_g3529(.A (u_rd_n_2114), .Y (u_rd_n_2111));
  AOI21XL u_rd_g3530(.A0 (u_rd_n_2305), .A1 (u_rd_n_2115), .B0
       (u_rd_n_2252), .Y (u_rd_n_2113));
  OAI211X1 u_rd_g3532(.A0 (u_rd_timer[12]), .A1 (u_rd_n_2125), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2121), .Y (u_rd_n_2115));
  NAND2X1 u_rd_g3533(.A (u_rd_timer[13]), .B (u_rd_n_2118), .Y
       (u_rd_n_2114));
  INVX1 u_rd_g3534(.A (u_rd_n_2121), .Y (u_rd_n_2118));
  AOI21XL u_rd_g3535(.A0 (u_rd_n_2296), .A1 (u_rd_n_2122), .B0
       (u_rd_n_2252), .Y (u_rd_n_2120));
  OAI211X1 u_rd_g3537(.A0 (u_rd_timer[11]), .A1 (u_rd_n_2132), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2128), .Y (u_rd_n_2122));
  NAND2X1 u_rd_g3538(.A (u_rd_timer[12]), .B (u_rd_n_2125), .Y
       (u_rd_n_2121));
  INVX1 u_rd_g3539(.A (u_rd_n_2128), .Y (u_rd_n_2125));
  AOI21XL u_rd_g3540(.A0 (u_rd_n_2316), .A1 (u_rd_n_2129), .B0
       (u_rd_n_2252), .Y (u_rd_n_2127));
  OAI211X1 u_rd_g3542(.A0 (u_rd_timer[10]), .A1 (u_rd_n_2139), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2135), .Y (u_rd_n_2129));
  NAND2X1 u_rd_g3543(.A (u_rd_timer[11]), .B (u_rd_n_2132), .Y
       (u_rd_n_2128));
  INVX1 u_rd_g3544(.A (u_rd_n_2135), .Y (u_rd_n_2132));
  AOI21XL u_rd_g3545(.A0 (u_rd_n_2313), .A1 (u_rd_n_2136), .B0
       (u_rd_n_2252), .Y (u_rd_n_2134));
  OAI211X1 u_rd_g3547(.A0 (u_rd_timer[9]), .A1 (u_rd_n_2146), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2142), .Y (u_rd_n_2136));
  NAND2X1 u_rd_g3548(.A (u_rd_timer[10]), .B (u_rd_n_2139), .Y
       (u_rd_n_2135));
  INVX1 u_rd_g3549(.A (u_rd_n_2142), .Y (u_rd_n_2139));
  AOI21XL u_rd_g3550(.A0 (u_rd_n_2303), .A1 (u_rd_n_2143), .B0
       (u_rd_n_2252), .Y (u_rd_n_2141));
  OAI211X1 u_rd_g3552(.A0 (u_rd_timer[8]), .A1 (u_rd_n_2153), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2149), .Y (u_rd_n_2143));
  NAND2X1 u_rd_g3553(.A (u_rd_timer[9]), .B (u_rd_n_2146), .Y
       (u_rd_n_2142));
  INVX1 u_rd_g3554(.A (u_rd_n_2149), .Y (u_rd_n_2146));
  AOI21XL u_rd_g3555(.A0 (u_rd_n_2312), .A1 (u_rd_n_2150), .B0
       (u_rd_n_2252), .Y (u_rd_n_2148));
  OAI211X1 u_rd_g3557(.A0 (u_rd_timer[7]), .A1 (u_rd_n_2160), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2156), .Y (u_rd_n_2150));
  NAND2X1 u_rd_g3558(.A (u_rd_timer[8]), .B (u_rd_n_2153), .Y
       (u_rd_n_2149));
  INVX1 u_rd_g3559(.A (u_rd_n_2156), .Y (u_rd_n_2153));
  AOI21XL u_rd_g3560(.A0 (u_rd_n_2314), .A1 (u_rd_n_2157), .B0
       (u_rd_n_2252), .Y (u_rd_n_2155));
  OAI211X1 u_rd_g3562(.A0 (u_rd_timer[6]), .A1 (u_rd_n_2167), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2163), .Y (u_rd_n_2157));
  NAND2X1 u_rd_g3563(.A (u_rd_timer[7]), .B (u_rd_n_2160), .Y
       (u_rd_n_2156));
  INVX1 u_rd_g3564(.A (u_rd_n_2163), .Y (u_rd_n_2160));
  AOI21X1 u_rd_g3565(.A0 (u_rd_n_2315), .A1 (u_rd_n_2164), .B0
       (u_rd_n_2252), .Y (u_rd_n_2162));
  OAI211X1 u_rd_g3568(.A0 (u_rd_timer[5]), .A1 (u_rd_n_2178), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2173), .Y (u_rd_n_2164));
  NAND2X1 u_rd_g3569(.A (u_rd_timer[6]), .B (u_rd_n_2167), .Y
       (u_rd_n_2163));
  INVX1 u_rd_g3570(.A (u_rd_n_2173), .Y (u_rd_n_2167));
  AOI21X1 u_rd_g3571(.A0 (u_rd_n_2300), .A1 (u_rd_n_2175), .B0
       (u_rd_n_2252), .Y (u_rd_n_2169));
  OAI211X1 u_rd_g3572(.A0 (u_rd_n_2306), .A1 (u_rd_n_2290), .B0
       (u_rd_n_2286), .C0 (u_rd_n_2171), .Y (u_rd_n_2170));
  OAI2BB1X1 u_rd_g3573(.A0N (u_rd_n_2285), .A1N (u_rd_n_2290), .B0
       (u_rd_n_2174), .Y (u_rd_n_2171));
  NAND4XL u_rd_g3577(.A (u_rd_n_2213), .B (u_rd_n_2194), .C
       (u_rd_n_2188), .D (u_rd_n_2189), .Y (u_rd_n_2174));
  OAI211X1 u_rd_g3578(.A0 (u_rd_timer[4]), .A1 (u_rd_n_2202), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2195), .Y (u_rd_n_2175));
  NAND2X1 u_rd_g3579(.A (u_rd_timer[5]), .B (u_rd_n_2178), .Y
       (u_rd_n_2173));
  INVX1 u_rd_g3580(.A (u_rd_n_2195), .Y (u_rd_n_2178));
  NOR2X1 u_rd_g3581(.A (epoch_clr), .B (u_rd_n_2188), .Y (u_rd_n_2180));
  NOR2XL u_rd_g3583(.A (epoch_clr), .B (u_rd_n_2189), .Y (u_rd_n_2182));
  AOI21X1 u_rd_g3584(.A0 (u_rd_n_2319), .A1 (u_rd_n_2198), .B0
       (u_rd_n_2252), .Y (u_rd_n_2185));
  NOR2X1 u_rd_g3585(.A (epoch_clr), .B (u_rd_n_2194), .Y (u_rd_n_2186));
  AOI221X1 u_rd_g3587(.A0 (u_rd_outst_cnt[0]), .A1 (u_rd_n_2219), .B0
       (u_rd_outst_cnt[1]), .B1 (u_rd_n_2208), .C0 (u_rd_n_2367), .Y
       (u_rd_n_2188));
  XNOR2X1 u_rd_g3588(.A (u_rd_outst_cnt[3]), .B (u_rd_n_2209), .Y
       (u_rd_n_2189));
  MXI2XL u_rd_g3593(.A (n_230), .B (u_rd_n_2214), .S0
       (u_rd_drain_cnt[3]), .Y (u_rd_n_2196));
  OAI211X1 u_rd_g3594(.A0 (u_rd_timer[3]), .A1 (u_rd_n_2238), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2218), .Y (u_rd_n_2198));
  XNOR2X1 u_rd_g3595(.A (u_rd_outst_cnt[2]), .B (u_rd_n_2211), .Y
       (u_rd_n_2194));
  NAND2X1 u_rd_g3596(.A (u_rd_timer[4]), .B (u_rd_n_2202), .Y
       (u_rd_n_2195));
  INVX1 u_rd_g3597(.A (u_rd_n_2218), .Y (u_rd_n_2202));
  OAI211X1 u_rd_g3598(.A0 (u_rd_n_2264), .A1 (u_rd_n_2288), .B0
       (u_rd_n_2245), .C0 (u_rd_n_2227), .Y (u_rd_n_2204));
  NOR2X1 u_rd_g3599(.A (epoch_clr), .B (u_rd_n_2213), .Y (u_rd_n_2205));
  AOI21X1 u_rd_g3600(.A0 (u_rd_n_2301), .A1 (u_rd_n_2231), .B0
       (u_rd_n_2252), .Y (u_rd_n_2207));
  OAI211X1 u_rd_g3601(.A0 (u_rd_outst_cnt[0]), .A1 (u_rd_n_2263), .B0
       (u_rd_n_2289), .C0 (u_rd_n_2251), .Y (u_rd_n_2208));
  MX2XL u_rd_g3602(.A (u_rd_n_2367), .B (u_rd_n_2223), .S0
       (u_rd_outst_cnt[2]), .Y (u_rd_n_2209));
  OR2XL u_rd_g3603(.A (u_rd_n_2367), .B (u_rd_n_2223), .Y
       (u_rd_n_2211));
  AOI221X1 u_rd_g3605(.A0 (u_rd_n_2334), .A1 (u_rd_n_2265), .B0
       (u_rd_drain_cnt[2]), .B1 (u_rd_n_2270), .C0 (u_rd_n_2217), .Y
       (u_rd_n_2214));
  XNOR2X1 u_rd_g3606(.A (u_rd_outst_cnt[0]), .B (u_rd_n_2251), .Y
       (u_rd_n_2213));
  NOR2X1 u_rd_g3607(.A (u_rd_outst_cnt[1]), .B (u_rd_n_2263), .Y
       (u_rd_n_2219));
  OAI221X1 u_rd_g3608(.A0 (u_rd_n_2271), .A1 (u_rd_n_2307), .B0
       (u_rd_n_2295), .B1 (u_rd_n_2264), .C0 (u_rd_n_2249), .Y
       (u_rd_n_2217));
  NAND2X1 u_rd_g3609(.A (u_rd_timer[3]), .B (u_rd_n_2238), .Y
       (u_rd_n_2218));
  AOI22X1 u_rd_g3613(.A0 (u_rd_drain_cnt[1]), .A1 (u_rd_n_2250), .B0
       (u_rd_n_2270), .B1 (u_rd_n_2295), .Y (u_rd_n_2227));
  OAI211X1 u_rd_g3614(.A0 (u_rd_timer[2]), .A1 (u_rd_n_2278), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2262), .Y (u_rd_n_2231));
  MXI2XL u_rd_g3615(.A (u_rd_n_2259), .B (u_rd_n_2249), .S0
       (u_rd_drain_cnt[0]), .Y (u_rd_n_2233));
  NOR2X1 u_rd_g3616(.A (u_rd_n_2304), .B (u_rd_n_2263), .Y
       (u_rd_n_2223));
  INVX1 u_rd_g3617(.A (u_rd_n_2262), .Y (u_rd_n_2238));
  NAND2XL u_rd_g3618(.A (u_rd_n_2245), .B (u_rd_n_2244), .Y
       (u_rd_n_2240));
  NOR2XL u_rd_g3620(.A (u_rd_n_2292), .B (u_rd_n_2252), .Y
       (u_rd_n_2242));
  AOI21X1 u_rd_g3621(.A0 (u_rd_n_2298), .A1 (u_rd_n_2272), .B0
       (u_rd_n_2252), .Y (u_rd_n_2243));
  NOR2XL u_rd_g3622(.A (u_rd_n_2275), .B (epoch_clr), .Y (u_rd_n_2246));
  NAND2X1 u_rd_g3623(.A (u_rd_n_2265), .B (u_rd_n_2295), .Y
       (u_rd_n_2244));
  NAND2X1 u_rd_g3624(.A (u_rd_n_2270), .B (u_rd_n_2307), .Y
       (u_rd_n_2245));
  INVX1 u_rd_g3625(.A (u_rd_n_2249), .Y (u_rd_n_2250));
  NOR2X1 u_rd_g3626(.A (u_rd_n_2270), .B (u_rd_n_2265), .Y
       (u_rd_n_2259));
  OA22X1 u_rd_g3627(.A0 (u_rd_n_2308), .A1 (u_rd_n_2285), .B0
       (u_rd_n_2282), .B1 (epoch_clr), .Y (u_rd_n_2249));
  XNOR2X1 u_rd_g3628(.A (u_rd_n_2310), .B (u_rd_n_2280), .Y
       (u_rd_n_2251));
  OR3X1 u_rd_g3629(.A (rd_timeout_pulse), .B (u_rd_n_2280), .C
       (epoch_clr), .Y (u_rd_n_2252));
  INVX1 u_rd_g3630(.A (u_rd_n_2264), .Y (u_rd_n_2265));
  NAND2X1 u_rd_g3631(.A (u_rd_timer[2]), .B (u_rd_n_2278), .Y
       (u_rd_n_2262));
  OR2X1 u_rd_g3632(.A (u_rd_n_2310), .B (u_rd_n_2280), .Y
       (u_rd_n_2263));
  NAND2BX1 u_rd_g3633(.AN (u_rd_n_2285), .B (u_rd_n_2308), .Y
       (u_rd_n_2264));
  INVX1 u_rd_g3634(.A (u_rd_n_2271), .Y (u_rd_n_2270));
  OAI211X1 u_rd_g3635(.A0 (u_rd_timer[0]), .A1 (u_rd_timer[1]), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2294), .Y (u_rd_n_2272));
  AOI221X1 u_rd_g3636(.A0 (u_rd_n_2317), .A1 (u_rd_rd_state[1]), .B0
       (u_rd_n_285), .B1 (flush), .C0 (rd_timeout_pulse), .Y
       (u_rd_n_2275));
  NAND3BXL u_rd_g3638(.AN (u_rd_n_2308), .B (u_rd_n_2291), .C
       (u_wr_n_2054), .Y (u_rd_n_2271));
  INVX1 u_rd_g3639(.A (u_rd_n_2294), .Y (u_rd_n_2278));
  NAND2XL u_rd_g3641(.A (u_rd_n_2308), .B (u_rd_n_2291), .Y
       (u_rd_n_2282));
  NAND2BX1 u_rd_g3642(.AN (u_rd_n_2306), .B (u_rd_n_2291), .Y
       (u_rd_n_2280));
  OR4X1 u_rd_g3643(.A (u_rd_rd_state[1]), .B (u_rd_rd_state[0]), .C
       (u_rd_n_2310), .D (logic_0_1_net), .Y (u_rd_n_2286));
  OR2XL u_rd_g3644(.A (u_rd_n_2291), .B (epoch_clr), .Y (u_rd_n_2285));
  OR2XL u_rd_g3645(.A (u_rd_n_2307), .B (u_rd_n_2295), .Y
       (u_rd_n_2288));
  NAND2X1 u_rd_g3646(.A (u_rd_outst_cnt[0]), .B (u_rd_n_2310), .Y
       (u_rd_n_2289));
  XNOR2X1 u_rd_g3647(.A (u_rd_timer_run), .B (u_rd_timer[0]), .Y
       (u_rd_n_2292));
  NAND3BXL u_rd_g3648(.AN (rd_timeout_pulse), .B (u_rd_n_285), .C
       (u_wr_n_712), .Y (u_rd_n_2290));
  NAND3BXL u_rd_g3649(.AN (u_rd_rd_state[0]), .B (s_rready), .C
       (u_rd_rd_state[1]), .Y (u_rd_n_2291));
  NAND2X1 u_rd_g3650(.A (u_rd_n_2366), .B (u_rd_timer[11]), .Y
       (u_rd_n_2296));
  NAND2X1 u_rd_g3651(.A (u_rd_n_2366), .B (u_rd_timer[1]), .Y
       (u_rd_n_2298));
  NAND2X1 u_rd_g3652(.A (u_rd_n_2366), .B (u_rd_timer[14]), .Y
       (u_rd_n_2299));
  NAND2X1 u_rd_g3653(.A (u_rd_n_2366), .B (u_rd_timer[4]), .Y
       (u_rd_n_2300));
  NAND2X1 u_rd_g3654(.A (u_rd_n_2366), .B (u_rd_timer[2]), .Y
       (u_rd_n_2301));
  NAND2X1 u_rd_g3655(.A (u_rd_n_2366), .B (u_rd_timer[13]), .Y
       (u_rd_n_2302));
  NAND2X1 u_rd_g3656(.A (u_rd_n_2366), .B (u_rd_timer[8]), .Y
       (u_rd_n_2303));
  NAND2X1 u_rd_g3657(.A (u_rd_outst_cnt[1]), .B (u_rd_outst_cnt[0]), .Y
       (u_rd_n_2304));
  NAND2X1 u_rd_g3658(.A (u_rd_n_2366), .B (u_rd_timer[12]), .Y
       (u_rd_n_2305));
  NAND2X1 u_rd_g3659(.A (u_rd_timer[1]), .B (u_rd_timer[0]), .Y
       (u_rd_n_2294));
  AND2X1 u_rd_g3660(.A (u_rd_drain_cnt[1]), .B (u_rd_drain_cnt[0]), .Y
       (u_rd_n_2295));
  NAND2X1 u_rd_g3662(.A (u_rd_n_2366), .B (u_rd_timer[7]), .Y
       (u_rd_n_2312));
  NAND2X1 u_rd_g3663(.A (u_rd_n_2366), .B (u_rd_timer[9]), .Y
       (u_rd_n_2313));
  NAND2X1 u_rd_g3664(.A (u_rd_n_2366), .B (u_rd_timer[6]), .Y
       (u_rd_n_2314));
  NAND2X1 u_rd_g3665(.A (u_rd_n_2366), .B (u_rd_timer[5]), .Y
       (u_rd_n_2315));
  NAND2X1 u_rd_g3666(.A (u_rd_n_2366), .B (u_rd_timer[10]), .Y
       (u_rd_n_2316));
  NOR2X1 u_rd_g3667(.A (s_rready), .B (u_rd_rd_state[0]), .Y
       (u_rd_n_2317));
  NAND2X1 u_rd_g3668(.A (u_rd_n_2366), .B (u_rd_timer[3]), .Y
       (u_rd_n_2319));
  AND2XL u_rd_g3669(.A (u_rd_n_288), .B (s_rvalid), .Y (u_rd_n_2306));
  NOR2X1 u_rd_g3670(.A (u_rd_drain_cnt[1]), .B (u_rd_drain_cnt[0]), .Y
       (u_rd_n_2307));
  NAND2X1 u_rd_g3671(.A (m_rvalid), .B (u_rd_n_287), .Y (u_rd_n_2308));
  NAND2X1 u_rd_g3672(.A (s_arvalid), .B (s_arready), .Y (u_rd_n_2310));
  INVX1 u_rd_g3673(.A (u_rd_drain_cnt[2]), .Y (u_rd_n_2334));
  INVX1 u_rd_g3675(.A (u_rd_timer_run), .Y (u_rd_n_2366));
  NOR4BBX1 u_rd_g2026(.AN (u_rd_n_2310), .BN (u_rd_n_2280), .C
       (u_rd_outst_cnt[0]), .D (u_rd_outst_cnt[1]), .Y (u_rd_n_2367));
  CLKBUFX2 g5421(.A (u_wr_n_2552), .Y (s_awready));
  INVXL g5422(.A (u_wr_n_3679), .Y (u_wr_n_3655));
  INVX1 g5423(.A (u_rd_n_1715), .Y (m_arvalid));
  INVX1 g5424(.A (u_rd_n_1716), .Y (s_arready));
  NOR3BX1 g2(.AN (s_wvalid), .B (u_wr_wpair_state[1]), .C (u_wr_n_435),
       .Y (n_224));
  OAI21X1 g5426(.A0 (u_wr_n_3787), .A1 (u_wr_n_3606), .B0
       (u_wr_n_3573), .Y (n_225));
  OAI221X1 g5427(.A0 (u_wr_n_3819), .A1 (u_wr_n_3660), .B0
       (u_wr_n_3646), .B1 (u_wr_n_3845), .C0 (u_wr_n_3607), .Y (n_226));
  NOR2BX1 g5428(.AN (n_228), .B (u_wr_wpair_state[1]), .Y (n_227));
  OAI31X1 g5429(.A0 (u_wr_n_435), .A1 (flush), .A2 (u_wr_n_3822), .B0
       (u_wr_n_3832), .Y (n_228));
  OAI21X1 g5430(.A0 (u_wr_wr_state[1]), .A1 (u_wr_n_3828), .B0
       (u_wr_n_3818), .Y (n_229));
  OR2XL g5431(.A (u_rd_n_2244), .B (u_rd_n_2334), .Y (n_230));
  DFFRX1 \mode_reg[1] (.RN (rst_n), .CK (clk), .D (n_8), .Q (mode[1]),
       .QN (n_15));
  DFFRX1 \mode_reg[0] (.RN (rst_n), .CK (clk), .D (n_10), .Q (mode[0]),
       .QN (n_16));
  DFFRX1 u_wr_downstream_w_done_reg(.RN (rst_n), .CK (clk), .D (n_232),
       .Q (u_wr_downstream_w_done), .QN (u_wr_n_398));
  DFFRX1 u_wr_downstream_aw_done_reg(.RN (rst_n), .CK (clk), .D
       (n_231), .Q (u_wr_downstream_aw_done), .QN (u_wr_n_396));
  DFFRX1 \u_wr_drain_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3624), .Q (u_wr_drain_cnt[0]), .QN (u_wr_n_318));
  DFFRX1 \u_wr_outst_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3583), .Q (u_wr_outst_cnt[0]), .QN (u_wr_n_819));
  DFFRX1 \u_rd_rd_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2246), .Q (u_rd_rd_state[1]), .QN (u_rd_n_1771));
  DFFRX1 \u_rd_outst_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2182), .Q (u_rd_outst_cnt[3]), .QN (u_rd_n_1773));
  AND2XL g5448(.A (u_wr_n_3718), .B (u_wr_n_2559), .Y (n_231));
  AND2XL g5449(.A (u_wr_n_3718), .B (u_wr_n_2561), .Y (n_232));
  NOR3X1 g5451(.A (u_wr_wpair_state[0]), .B (u_wr_n_430), .C
       (u_rd_n_300), .Y (n_234));
  TIELO tie_0_cell(.Y (logic_0_1_net));
  TIEHI tie_1_cell(.Y (logic_1_1_net));
endmodule

