
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Aug 29 2026 17:42:47 PDT (Aug 30 2026 00:42:47 UTC)

// Verification Directory fv/tp_lvl 

module tp_lvl(clk, rst_n, s_awvalid, \s_aw[prot] , \s_aw[addr] ,
     s_wvalid, \s_w[strb] , \s_w[data] , s_arvalid, \s_ar[prot] ,
     \s_ar[addr] , s_bready, s_rready, s_awready, s_wready, s_arready,
     s_bvalid, \s_b[resp] , s_rvalid, \s_r[resp] , \s_r[data] ,
     m_awvalid, \m_aw[prot] , \m_aw[addr] , m_wvalid, \m_w[strb] ,
     \m_w[data] , m_arvalid, \m_ar[prot] , \m_ar[addr] , m_bready,
     m_rready, m_awready, m_wready, m_arready, m_bvalid, \m_b[resp] ,
     m_rvalid, \m_r[resp] , \m_r[data] , enable_reg, clear_reg, irq,
     status_reg, guard_busy);
  input clk, rst_n, s_awvalid, s_wvalid, s_arvalid, s_bready, s_rready,
       m_awready, m_wready, m_arready, m_bvalid, m_rvalid;
  input [2:0] \s_aw[prot] , \s_ar[prot] , enable_reg, clear_reg;
  input [31:0] \s_aw[addr] , \s_w[data] , \s_ar[addr] , \m_r[data] ;
  input [3:0] \s_w[strb] ;
  input [1:0] \m_b[resp] , \m_r[resp] ;
  output s_awready, s_wready, s_arready, s_bvalid, s_rvalid, m_awvalid,
       m_wvalid, m_arvalid, m_bready, m_rready, irq, guard_busy;
  output [1:0] \s_b[resp] , \s_r[resp] ;
  output [31:0] \s_r[data] , \m_aw[addr] , \m_w[data] , \m_ar[addr] ;
  output [2:0] \m_aw[prot] , \m_ar[prot] , status_reg;
  output [3:0] \m_w[strb] ;
  wire clk, rst_n, s_awvalid, s_wvalid, s_arvalid, s_bready, s_rready,
       m_awready, m_wready, m_arready, m_bvalid, m_rvalid;
  wire [2:0] \s_aw[prot] , \s_ar[prot] , enable_reg, clear_reg;
  wire [31:0] \s_aw[addr] , \s_w[data] , \s_ar[addr] , \m_r[data] ;
  wire [3:0] \s_w[strb] ;
  wire [1:0] \m_b[resp] , \m_r[resp] ;
  wire s_awready, s_wready, s_arready, s_bvalid, s_rvalid, m_awvalid,
       m_wvalid, m_arvalid, m_bready, m_rready, irq, guard_busy;
  wire [1:0] \s_b[resp] , \s_r[resp] ;
  wire [31:0] \s_r[data] , \m_aw[addr] , \m_w[data] , \m_ar[addr] ;
  wire [2:0] \m_aw[prot] , \m_ar[prot] , status_reg;
  wire [3:0] \m_w[strb] ;
  wire [1:0] mode;
  wire [2:0] rcvy_ack;
  wire [3:0] u_wr_outst_cnt;
  wire [1:0] u_wr_wpair_state;
  wire [15:0] u_wr_w_timer;
  wire [15:0] u_wr_b_timer;
  wire [3:0] u_wr_drain_cnt;
  wire [1:0] u_wr_wr_state;
  wire [3:0] u_rd_outst_cnt;
  wire [3:0] u_rd_drain_cnt;
  wire [15:0] u_rd_timer;
  wire [1:0] u_rd_rd_state;
  wire epoch_clr, flush, logic_0_1_net, logic_1_1_net, n_0, n_1, n_2,
       n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_224, n_225, n_226;
  wire n_227, n_228, n_229, n_230, n_231, n_232, n_233, n_234;
  wire n_236, rd_busy, rd_timeout_pulse, u_rd_n_280, u_rd_n_285,
       u_rd_n_287, u_rd_n_288, u_rd_n_300;
  wire u_rd_n_1700, u_rd_n_1705, u_rd_n_1729, u_rd_n_1744, u_rd_n_1746,
       u_rd_n_1747, u_rd_n_1748, u_rd_n_1755;
  wire u_rd_n_1756, u_rd_n_1760, u_rd_n_1764, u_rd_n_2158, u_rd_n_2161,
       u_rd_n_2163, u_rd_n_2165, u_rd_n_2166;
  wire u_rd_n_2171, u_rd_n_2172, u_rd_n_2173, u_rd_n_2176, u_rd_n_2178,
       u_rd_n_2179, u_rd_n_2180, u_rd_n_2183;
  wire u_rd_n_2185, u_rd_n_2186, u_rd_n_2187, u_rd_n_2190, u_rd_n_2192,
       u_rd_n_2193, u_rd_n_2194, u_rd_n_2197;
  wire u_rd_n_2199, u_rd_n_2200, u_rd_n_2201, u_rd_n_2204, u_rd_n_2206,
       u_rd_n_2207, u_rd_n_2208, u_rd_n_2211;
  wire u_rd_n_2213, u_rd_n_2214, u_rd_n_2215, u_rd_n_2218, u_rd_n_2220,
       u_rd_n_2221, u_rd_n_2222, u_rd_n_2225;
  wire u_rd_n_2227, u_rd_n_2228, u_rd_n_2229, u_rd_n_2232, u_rd_n_2234,
       u_rd_n_2235, u_rd_n_2236, u_rd_n_2238;
  wire u_rd_n_2239, u_rd_n_2240, u_rd_n_2243, u_rd_n_2245, u_rd_n_2247,
       u_rd_n_2250, u_rd_n_2251, u_rd_n_2253;
  wire u_rd_n_2254, u_rd_n_2258, u_rd_n_2259, u_rd_n_2260, u_rd_n_2262,
       u_rd_n_2266, u_rd_n_2268, u_rd_n_2270;
  wire u_rd_n_2271, u_rd_n_2272, u_rd_n_2274, u_rd_n_2275, u_rd_n_2277,
       u_rd_n_2278, u_rd_n_2280, u_rd_n_2284;
  wire u_rd_n_2285, u_rd_n_2287, u_rd_n_2288, u_rd_n_2293, u_rd_n_2297,
       u_rd_n_2299, u_rd_n_2302, u_rd_n_2303;
  wire u_rd_n_2306, u_rd_n_2307, u_rd_n_2308, u_rd_n_2309, u_rd_n_2314,
       u_rd_n_2315, u_rd_n_2316, u_rd_n_2317;
  wire u_rd_n_2320, u_rd_n_2321, u_rd_n_2322, u_rd_n_2323, u_rd_n_2324,
       u_rd_n_2335, u_rd_n_2336, u_rd_n_2337;
  wire u_rd_n_2340, u_rd_n_2342, u_rd_n_2345, u_rd_n_2346, u_rd_n_2349,
       u_rd_n_2350, u_rd_n_2353, u_rd_n_2355;
  wire u_rd_n_2356, u_rd_n_2358, u_rd_n_2359, u_rd_n_2360, u_rd_n_2361,
       u_rd_n_2362, u_rd_n_2364, u_rd_n_2366;
  wire u_rd_n_2367, u_rd_n_2368, u_rd_n_2369, u_rd_n_2370, u_rd_n_2373,
       u_rd_n_2374, u_rd_n_2375, u_rd_n_2377;
  wire u_rd_n_2378, u_rd_n_2379, u_rd_n_2380, u_rd_n_2381, u_rd_n_2382,
       u_rd_n_2383, u_rd_n_2384, u_rd_n_2394;
  wire u_rd_n_2411, u_rd_n_2428, u_rd_n_2430, u_rd_n_2434, u_rd_n_2435,
       u_rd_timer_run, u_wr_downstream_aw_done, u_wr_downstream_w_done;
  wire u_wr_n_145, u_wr_n_158, u_wr_n_230, u_wr_n_318, u_wr_n_396,
       u_wr_n_398, u_wr_n_430, u_wr_n_435;
  wire u_wr_n_1627, u_wr_n_1641, u_wr_n_1867, u_wr_n_2038, u_wr_n_2043,
       u_wr_n_2054, u_wr_n_2115, u_wr_n_2120;
  wire u_wr_n_2540, u_wr_n_2542, u_wr_n_2550, u_wr_n_2552, u_wr_n_2553,
       u_wr_n_2555, u_wr_n_2557, u_wr_n_2558;
  wire u_wr_n_2560, u_wr_n_2561, u_wr_n_2562, u_wr_n_2563, u_wr_n_2564,
       u_wr_n_2565, u_wr_n_2566, u_wr_n_2567;
  wire u_wr_n_2568, u_wr_n_2569, u_wr_n_3556, u_wr_n_3557, u_wr_n_3558,
       u_wr_n_3560, u_wr_n_3562, u_wr_n_3564;
  wire u_wr_n_3566, u_wr_n_3567, u_wr_n_3568, u_wr_n_3572, u_wr_n_3578,
       u_wr_n_3579, u_wr_n_3580, u_wr_n_3582;
  wire u_wr_n_3583, u_wr_n_3585, u_wr_n_3588, u_wr_n_3590, u_wr_n_3592,
       u_wr_n_3593, u_wr_n_3594, u_wr_n_3596;
  wire u_wr_n_3597, u_wr_n_3599, u_wr_n_3602, u_wr_n_3604, u_wr_n_3606,
       u_wr_n_3607, u_wr_n_3608, u_wr_n_3610;
  wire u_wr_n_3611, u_wr_n_3613, u_wr_n_3616, u_wr_n_3618, u_wr_n_3620,
       u_wr_n_3621, u_wr_n_3622, u_wr_n_3624;
  wire u_wr_n_3625, u_wr_n_3627, u_wr_n_3630, u_wr_n_3632, u_wr_n_3634,
       u_wr_n_3635, u_wr_n_3636, u_wr_n_3638;
  wire u_wr_n_3639, u_wr_n_3641, u_wr_n_3644, u_wr_n_3646, u_wr_n_3648,
       u_wr_n_3649, u_wr_n_3650, u_wr_n_3652;
  wire u_wr_n_3653, u_wr_n_3655, u_wr_n_3658, u_wr_n_3660, u_wr_n_3662,
       u_wr_n_3663, u_wr_n_3664, u_wr_n_3666;
  wire u_wr_n_3667, u_wr_n_3669, u_wr_n_3672, u_wr_n_3674, u_wr_n_3676,
       u_wr_n_3677, u_wr_n_3678, u_wr_n_3680;
  wire u_wr_n_3681, u_wr_n_3683, u_wr_n_3686, u_wr_n_3688, u_wr_n_3690,
       u_wr_n_3691, u_wr_n_3692, u_wr_n_3694;
  wire u_wr_n_3695, u_wr_n_3697, u_wr_n_3700, u_wr_n_3702, u_wr_n_3704,
       u_wr_n_3705, u_wr_n_3706, u_wr_n_3708;
  wire u_wr_n_3709, u_wr_n_3712, u_wr_n_3715, u_wr_n_3717, u_wr_n_3719,
       u_wr_n_3720, u_wr_n_3721, u_wr_n_3724;
  wire u_wr_n_3725, u_wr_n_3726, u_wr_n_3729, u_wr_n_3731, u_wr_n_3736,
       u_wr_n_3738, u_wr_n_3740, u_wr_n_3741;
  wire u_wr_n_3743, u_wr_n_3744, u_wr_n_3746, u_wr_n_3747, u_wr_n_3749,
       u_wr_n_3752, u_wr_n_3755, u_wr_n_3756;
  wire u_wr_n_3758, u_wr_n_3761, u_wr_n_3762, u_wr_n_3763, u_wr_n_3765,
       u_wr_n_3771, u_wr_n_3772, u_wr_n_3773;
  wire u_wr_n_3775, u_wr_n_3776, u_wr_n_3779, u_wr_n_3781, u_wr_n_3784,
       u_wr_n_3786, u_wr_n_3788, u_wr_n_3789;
  wire u_wr_n_3790, u_wr_n_3791, u_wr_n_3792, u_wr_n_3793, u_wr_n_3794,
       u_wr_n_3798, u_wr_n_3801, u_wr_n_3802;
  wire u_wr_n_3803, u_wr_n_3804, u_wr_n_3806, u_wr_n_3809, u_wr_n_3812,
       u_wr_n_3813, u_wr_n_3814, u_wr_n_3815;
  wire u_wr_n_3818, u_wr_n_3849, u_wr_n_3850, u_wr_n_3851, u_wr_n_3852,
       u_wr_n_3853, u_wr_n_3854, u_wr_n_3855;
  wire u_wr_n_3856, u_wr_n_3857, u_wr_n_3858, u_wr_n_3860, u_wr_n_3867,
       u_wr_n_3870, u_wr_n_3873, u_wr_n_3877;
  wire u_wr_n_3879, u_wr_n_3880, u_wr_n_3881, u_wr_n_3898, u_wr_n_3900,
       u_wr_n_3902, u_wr_n_3910, u_wr_n_3912;
  wire u_wr_n_3914, u_wr_n_3915, u_wr_n_3916, u_wr_n_3917, u_wr_n_3918,
       u_wr_n_3919, u_wr_n_3920, u_wr_n_3921;
  wire u_wr_n_3922, u_wr_n_3923, u_wr_n_3924, u_wr_n_3925, u_wr_n_3926,
       u_wr_n_3927, u_wr_n_3929, u_wr_n_3930;
  wire u_wr_n_3931, u_wr_n_3932, u_wr_n_3933, u_wr_n_3934, u_wr_n_3935,
       u_wr_n_3936, u_wr_n_3937, u_wr_n_3938;
  wire u_wr_n_3939, u_wr_n_3940, u_wr_n_3941, u_wr_n_3942, u_wr_n_3943,
       u_wr_n_3944, u_wr_n_3945, u_wr_n_3946;
  wire u_wr_n_3947, u_wr_n_3953, u_wr_n_3954, u_wr_n_3955, u_wr_n_3956,
       u_wr_n_3957, u_wr_n_3958, u_wr_n_3964;
  wire u_wr_n_3965, u_wr_n_3966, u_wr_n_3967, u_wr_n_3968, u_wr_n_3974,
       u_wr_n_3983, u_wr_n_3987, u_wr_n_3988;
  wire u_wr_n_3989, u_wr_n_3990, u_wr_n_3991, u_wr_n_3994, u_wr_n_3995,
       u_wr_n_4000, u_wr_n_4001, u_wr_n_4002;
  wire u_wr_n_4003, u_wr_n_4004, u_wr_n_4005, u_wr_n_4006, u_wr_n_4027,
       u_wr_n_4029, u_wr_n_4033, u_wr_n_4035;
  wire u_wr_n_4038, u_wr_n_4069, u_wr_n_4110, wr_busy,
       wr_timeout_pulse, wr_w_fault_pulse;
  assign \m_ar[addr] [0] = \s_ar[addr] [0];
  assign \m_ar[addr] [1] = \s_ar[addr] [1];
  assign \m_ar[addr] [2] = \s_ar[addr] [2];
  assign \m_ar[addr] [3] = \s_ar[addr] [3];
  assign \m_ar[addr] [4] = \s_ar[addr] [4];
  assign \m_ar[addr] [5] = \s_ar[addr] [5];
  assign \m_ar[addr] [6] = \s_ar[addr] [6];
  assign \m_ar[addr] [7] = \s_ar[addr] [7];
  assign \m_ar[addr] [8] = \s_ar[addr] [8];
  assign \m_ar[addr] [9] = \s_ar[addr] [9];
  assign \m_ar[addr] [10] = \s_ar[addr] [10];
  assign \m_ar[addr] [11] = \s_ar[addr] [11];
  assign \m_ar[addr] [12] = \s_ar[addr] [12];
  assign \m_ar[addr] [13] = \s_ar[addr] [13];
  assign \m_ar[addr] [14] = \s_ar[addr] [14];
  assign \m_ar[addr] [15] = \s_ar[addr] [15];
  assign \m_ar[addr] [16] = \s_ar[addr] [16];
  assign \m_ar[addr] [17] = \s_ar[addr] [17];
  assign \m_ar[addr] [18] = \s_ar[addr] [18];
  assign \m_ar[addr] [19] = \s_ar[addr] [19];
  assign \m_ar[addr] [20] = \s_ar[addr] [20];
  assign \m_ar[addr] [21] = \s_ar[addr] [21];
  assign \m_ar[addr] [22] = \s_ar[addr] [22];
  assign \m_ar[addr] [23] = \s_ar[addr] [23];
  assign \m_ar[addr] [24] = \s_ar[addr] [24];
  assign \m_ar[addr] [25] = \s_ar[addr] [25];
  assign \m_ar[addr] [26] = \s_ar[addr] [26];
  assign \m_ar[addr] [27] = \s_ar[addr] [27];
  assign \m_ar[addr] [28] = \s_ar[addr] [28];
  assign \m_ar[addr] [29] = \s_ar[addr] [29];
  assign \m_ar[addr] [30] = \s_ar[addr] [30];
  assign \m_ar[addr] [31] = \s_ar[addr] [31];
  assign \m_ar[prot] [0] = \s_ar[prot] [0];
  assign \m_ar[prot] [1] = \s_ar[prot] [1];
  assign \m_ar[prot] [2] = \s_ar[prot] [2];
  assign \m_w[data] [0] = \s_w[data] [0];
  assign \m_w[data] [1] = \s_w[data] [1];
  assign \m_w[data] [2] = \s_w[data] [2];
  assign \m_w[data] [3] = \s_w[data] [3];
  assign \m_w[data] [4] = \s_w[data] [4];
  assign \m_w[data] [5] = \s_w[data] [5];
  assign \m_w[data] [6] = \s_w[data] [6];
  assign \m_w[data] [7] = \s_w[data] [7];
  assign \m_w[data] [8] = \s_w[data] [8];
  assign \m_w[data] [9] = \s_w[data] [9];
  assign \m_w[data] [10] = \s_w[data] [10];
  assign \m_w[data] [11] = \s_w[data] [11];
  assign \m_w[data] [12] = \s_w[data] [12];
  assign \m_w[data] [13] = \s_w[data] [13];
  assign \m_w[data] [14] = \s_w[data] [14];
  assign \m_w[data] [15] = \s_w[data] [15];
  assign \m_w[data] [16] = \s_w[data] [16];
  assign \m_w[data] [17] = \s_w[data] [17];
  assign \m_w[data] [18] = \s_w[data] [18];
  assign \m_w[data] [19] = \s_w[data] [19];
  assign \m_w[data] [20] = \s_w[data] [20];
  assign \m_w[data] [21] = \s_w[data] [21];
  assign \m_w[data] [22] = \s_w[data] [22];
  assign \m_w[data] [23] = \s_w[data] [23];
  assign \m_w[data] [24] = \s_w[data] [24];
  assign \m_w[data] [25] = \s_w[data] [25];
  assign \m_w[data] [26] = \s_w[data] [26];
  assign \m_w[data] [27] = \s_w[data] [27];
  assign \m_w[data] [28] = \s_w[data] [28];
  assign \m_w[data] [29] = \s_w[data] [29];
  assign \m_w[data] [30] = \s_w[data] [30];
  assign \m_w[data] [31] = \s_w[data] [31];
  assign \m_w[strb] [0] = \s_w[strb] [0];
  assign \m_w[strb] [1] = \s_w[strb] [1];
  assign \m_w[strb] [2] = \s_w[strb] [2];
  assign \m_w[strb] [3] = \s_w[strb] [3];
  AND2X1 g263(.A (n_14), .B (n_236), .Y (epoch_clr));
  NOR2XL g264(.A (mode[0]), .B (n_13), .Y (n_14));
  OAI31X1 g265(.A0 (rcvy_ack[2]), .A1 (rcvy_ack[1]), .A2 (rcvy_ack[0]),
       .B0 (mode[1]), .Y (n_13));
  DFFRHQX1 \u_irq_rcvy_ack_reg[2] (.RN (rst_n), .CK (clk), .D
       (clear_reg[2]), .Q (rcvy_ack[2]));
  DFFRHQX1 \u_irq_rcvy_ack_reg[1] (.RN (rst_n), .CK (clk), .D
       (clear_reg[1]), .Q (rcvy_ack[1]));
  DFFRHQX1 \u_irq_rcvy_ack_reg[0] (.RN (rst_n), .CK (clk), .D
       (clear_reg[0]), .Q (rcvy_ack[0]));
  NAND2X1 g160(.A (n_15), .B (n_16), .Y (flush));
  AND2X1 g223(.A (n_236), .B (n_12), .Y (irq));
  OAI2BB1X1 g224(.A0N (enable_reg[0]), .A1N (status_reg[0]), .B0
       (n_11), .Y (n_12));
  AOI22X1 g225(.A0 (enable_reg[1]), .A1 (status_reg[1]), .B0
       (enable_reg[2]), .B1 (status_reg[2]), .Y (n_11));
  OR2X1 g226(.A (rd_busy), .B (wr_busy), .Y (guard_busy));
  NOR2BX1 g365(.AN (n_9), .B (mode[1]), .Y (n_10));
  OAI22X1 g367(.A0 (mode[0]), .A1 (n_4), .B0 (n_16), .B1 (n_236), .Y
       (n_9));
  DFFRHQX1 \u_irq_status_reg_reg[0] (.RN (rst_n), .CK (clk), .D (n_7),
       .Q (status_reg[0]));
  DFFRHQX1 \u_irq_status_reg_reg[1] (.RN (rst_n), .CK (clk), .D (n_6),
       .Q (status_reg[1]));
  OAI33X1 g370(.A0 (mode[0]), .A1 (n_15), .A2 (epoch_clr), .B0 (n_16),
       .B1 (mode[1]), .B2 (n_0), .Y (n_8));
  DFFRHQX1 \u_irq_status_reg_reg[2] (.RN (rst_n), .CK (clk), .D (n_5),
       .Q (status_reg[2]));
  OR2XL g372(.A (n_3), .B (rd_timeout_pulse), .Y (n_7));
  OR2XL g373(.A (n_2), .B (wr_w_fault_pulse), .Y (n_6));
  OR2XL g374(.A (n_1), .B (wr_timeout_pulse), .Y (n_5));
  NOR3X1 g375(.A (wr_w_fault_pulse), .B (rd_timeout_pulse), .C
       (wr_timeout_pulse), .Y (n_4));
  NOR2BX1 g376(.AN (status_reg[0]), .B (clear_reg[0]), .Y (n_3));
  NOR2BX1 g377(.AN (status_reg[1]), .B (clear_reg[1]), .Y (n_2));
  NOR2BX1 g378(.AN (status_reg[2]), .B (clear_reg[2]), .Y (n_1));
  INVX1 g379(.A (n_236), .Y (n_0));
  INVXL u_wr_g1891(.A (u_wr_n_2038), .Y (u_wr_n_2115));
  INVX1 u_wr_g1893(.A (u_wr_n_1641), .Y (wr_w_fault_pulse));
  INVX1 u_wr_g1892(.A (u_wr_n_1627), .Y (wr_timeout_pulse));
  INVX1 u_wr_g1890(.A (s_awvalid), .Y (u_wr_n_2120));
  OR4X1 u_wr_g1916(.A (u_wr_outst_cnt[0]), .B (u_wr_outst_cnt[1]), .C
       (u_wr_outst_cnt[2]), .D (u_wr_outst_cnt[3]), .Y (u_wr_n_430));
  AND2X1 u_wr_g1934(.A (u_wr_n_396), .B (n_224), .Y (m_awvalid));
  AND2X1 u_wr_g1935(.A (u_wr_n_398), .B (n_224), .Y (m_wvalid));
  NAND2BX1 u_wr_g2685(.AN (u_wr_n_1867), .B (u_wr_n_2569), .Y
       (u_wr_n_1627));
  OR3XL u_wr_g2686(.A (u_wr_n_2043), .B (u_wr_n_435), .C
       (u_wr_wpair_state[1]), .Y (u_wr_n_1641));
  OR2XL u_wr_g2687(.A (s_wvalid), .B (u_wr_n_2038), .Y (u_wr_n_2043));
  OR2XL u_wr_g2688(.A (u_wr_n_230), .B (u_wr_n_2542), .Y (u_wr_n_1867));
  AO21X1 u_wr_g2689(.A0 (u_wr_n_230), .A1 (u_wr_n_2569), .B0
       (u_wr_n_2567), .Y (s_bvalid));
  AND3X1 u_wr_g2691(.A (n_224), .B (u_wr_n_2552), .C (u_wr_n_2550), .Y
       (s_wready));
  NOR3XL u_wr_g2692(.A (u_wr_n_2558), .B (flush), .C (u_wr_n_2568), .Y
       (u_wr_n_2540));
  NAND4XL u_wr_g2693(.A (u_wr_n_2560), .B (u_wr_n_2564), .C
       (u_wr_n_2562), .D (u_wr_n_2563), .Y (u_wr_n_2542));
  NAND4XL u_wr_g2694(.A (u_wr_n_2561), .B (u_wr_n_2553), .C
       (u_wr_n_2565), .D (u_wr_n_2566), .Y (u_wr_n_2038));
  NAND2X2 u_wr_g2695(.A (u_wr_n_2557), .B (u_wr_n_145), .Y (m_bready));
  AND2XL u_wr_g2696(.A (m_bvalid), .B (u_wr_n_145), .Y (u_wr_n_230));
  NAND2X1 u_wr_g2697(.A (u_wr_n_2555), .B (u_wr_n_145), .Y (wr_busy));
  AO21X1 u_wr_g2698(.A0 (\m_b[resp] [1]), .A1 (u_wr_n_2569), .B0
       (u_wr_n_2567), .Y (\s_b[resp] [1]));
  NOR4BX1 u_wr_g2701(.AN (u_wr_w_timer[8]), .B (u_wr_w_timer[4]), .C
       (u_wr_w_timer[6]), .D (u_wr_w_timer[5]), .Y (u_wr_n_2553));
  AND2X1 u_wr_g2702(.A (u_wr_n_2569), .B (\m_b[resp] [0]), .Y
       (\s_b[resp] [0]));
  NOR2X1 u_wr_g2703(.A (u_wr_n_430), .B (u_wr_n_2568), .Y
       (u_wr_n_2555));
  NAND2X1 u_wr_g2704(.A (s_bready), .B (u_wr_n_2569), .Y (u_wr_n_2557));
  NOR4BX1 u_wr_g2705(.AN (u_wr_outst_cnt[3]), .B (u_wr_outst_cnt[2]),
       .C (u_wr_outst_cnt[1]), .D (u_wr_outst_cnt[0]), .Y
       (u_wr_n_2558));
  OAI2BB1X1 u_wr_g2706(.A0N (m_wready), .A1N (m_wvalid), .B0
       (u_wr_n_398), .Y (u_wr_n_2550));
  OAI2BB1X1 u_wr_g2707(.A0N (m_awready), .A1N (m_awvalid), .B0
       (u_wr_n_396), .Y (u_wr_n_2552));
  NOR4X1 u_wr_g2708(.A (u_wr_b_timer[1]), .B (u_wr_b_timer[0]), .C
       (u_wr_b_timer[2]), .D (u_wr_b_timer[3]), .Y (u_wr_n_2560));
  NOR4X1 u_wr_g2709(.A (u_wr_w_timer[11]), .B (u_wr_w_timer[12]), .C
       (u_wr_w_timer[10]), .D (u_wr_w_timer[9]), .Y (u_wr_n_2561));
  NOR4X1 u_wr_g2710(.A (u_wr_b_timer[15]), .B (u_wr_b_timer[9]), .C
       (u_wr_b_timer[14]), .D (u_wr_b_timer[13]), .Y (u_wr_n_2562));
  NOR4X1 u_wr_g2711(.A (u_wr_b_timer[5]), .B (u_wr_b_timer[4]), .C
       (u_wr_b_timer[6]), .D (u_wr_b_timer[7]), .Y (u_wr_n_2563));
  NOR4BX1 u_wr_g2712(.AN (u_wr_b_timer[8]), .B (u_wr_b_timer[11]), .C
       (u_wr_b_timer[12]), .D (u_wr_b_timer[10]), .Y (u_wr_n_2564));
  NOR4X1 u_wr_g2713(.A (u_wr_w_timer[1]), .B (u_wr_w_timer[0]), .C
       (u_wr_w_timer[2]), .D (u_wr_w_timer[3]), .Y (u_wr_n_2565));
  NOR4X1 u_wr_g2714(.A (u_wr_w_timer[15]), .B (u_wr_w_timer[7]), .C
       (u_wr_w_timer[14]), .D (u_wr_w_timer[13]), .Y (u_wr_n_2566));
  NOR4X1 u_wr_g2715(.A (u_wr_drain_cnt[3]), .B (u_wr_drain_cnt[1]), .C
       (u_wr_drain_cnt[2]), .D (u_wr_drain_cnt[0]), .Y (u_wr_n_145));
  NOR2BX1 u_wr_g2716(.AN (u_wr_wr_state[1]), .B (u_wr_wr_state[0]), .Y
       (u_wr_n_2567));
  NAND2BX1 u_wr_g2717(.AN (u_wr_wpair_state[1]), .B (u_wr_n_435), .Y
       (u_wr_n_2568));
  NOR2X1 u_wr_g2718(.A (u_wr_wr_state[1]), .B (u_wr_n_158), .Y
       (u_wr_n_2569));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][0] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [0]), .SI (\m_aw[addr] [0]), .SE (u_wr_n_3994), .Q
       (\m_aw[addr] [0]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][1] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [1]), .SI (\m_aw[addr] [1]), .SE (u_wr_n_3994), .Q
       (\m_aw[addr] [1]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][2] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [2]), .SI (\m_aw[addr] [2]), .SE (u_wr_n_3994), .Q
       (\m_aw[addr] [2]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][3] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [3]), .SI (\m_aw[addr] [3]), .SE (u_wr_n_3994), .Q
       (\m_aw[addr] [3]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][4] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [4]), .SI (\m_aw[addr] [4]), .SE (u_wr_n_3994), .Q
       (\m_aw[addr] [4]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][5] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [5]), .SI (\m_aw[addr] [5]), .SE (u_wr_n_3994), .Q
       (\m_aw[addr] [5]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][6] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [6]), .SI (\m_aw[addr] [6]), .SE (u_wr_n_3994), .Q
       (\m_aw[addr] [6]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][7] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [7]), .SI (\m_aw[addr] [7]), .SE (u_wr_n_3994), .Q
       (\m_aw[addr] [7]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][8] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [8]), .SI (\m_aw[addr] [8]), .SE (u_wr_n_3994), .Q
       (\m_aw[addr] [8]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][9] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [9]), .SI (\m_aw[addr] [9]), .SE (u_wr_n_3994), .Q
       (\m_aw[addr] [9]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][10] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [10]), .SI (\m_aw[addr] [10]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [10]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][11] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [11]), .SI (\m_aw[addr] [11]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [11]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][12] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [12]), .SI (\m_aw[addr] [12]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [12]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][13] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [13]), .SI (\m_aw[addr] [13]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [13]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][14] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [14]), .SI (\m_aw[addr] [14]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [14]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][15] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [15]), .SI (\m_aw[addr] [15]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [15]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][16] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [16]), .SI (\m_aw[addr] [16]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [16]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][17] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [17]), .SI (\m_aw[addr] [17]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [17]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][18] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [18]), .SI (\m_aw[addr] [18]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [18]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][19] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [19]), .SI (\m_aw[addr] [19]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [19]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][20] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [20]), .SI (\m_aw[addr] [20]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [20]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][21] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [21]), .SI (\m_aw[addr] [21]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [21]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][22] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [22]), .SI (\m_aw[addr] [22]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [22]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][23] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [23]), .SI (\m_aw[addr] [23]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [23]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][24] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [24]), .SI (\m_aw[addr] [24]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [24]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][25] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [25]), .SI (\m_aw[addr] [25]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [25]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][26] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [26]), .SI (\m_aw[addr] [26]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [26]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][27] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [27]), .SI (\m_aw[addr] [27]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [27]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][28] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [28]), .SI (\m_aw[addr] [28]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [28]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][29] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [29]), .SI (\m_aw[addr] [29]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [29]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][30] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [30]), .SI (\m_aw[addr] [30]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [30]));
  SDFFRHQX1 \u_wr_aw_hold_reg[addr][31] (.RN (rst_n), .CK (clk), .D
       (\s_aw[addr] [31]), .SI (\m_aw[addr] [31]), .SE (u_wr_n_3994),
       .Q (\m_aw[addr] [31]));
  SDFFRHQX1 \u_wr_aw_hold_reg[prot][0] (.RN (rst_n), .CK (clk), .D
       (\s_aw[prot] [0]), .SI (\m_aw[prot] [0]), .SE (u_wr_n_3994), .Q
       (\m_aw[prot] [0]));
  SDFFRHQX1 \u_wr_aw_hold_reg[prot][1] (.RN (rst_n), .CK (clk), .D
       (\s_aw[prot] [1]), .SI (\m_aw[prot] [1]), .SE (u_wr_n_3994), .Q
       (\m_aw[prot] [1]));
  SDFFRHQX1 \u_wr_aw_hold_reg[prot][2] (.RN (rst_n), .CK (clk), .D
       (\s_aw[prot] [2]), .SI (\m_aw[prot] [2]), .SE (u_wr_n_3994), .Q
       (\m_aw[prot] [2]));
  DFFRHQX1 \u_wr_b_timer_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3813), .Q (u_wr_b_timer[0]));
  DFFRHQX1 \u_wr_b_timer_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3798), .Q (u_wr_b_timer[1]));
  DFFRHQX1 \u_wr_b_timer_reg[2] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3747), .Q (u_wr_b_timer[2]));
  DFFRHQX1 \u_wr_b_timer_reg[3] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3720), .Q (u_wr_b_timer[3]));
  DFFRHQX1 \u_wr_b_timer_reg[4] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3705), .Q (u_wr_b_timer[4]));
  DFFRHQX1 \u_wr_b_timer_reg[5] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3691), .Q (u_wr_b_timer[5]));
  DFFRHQX1 \u_wr_b_timer_reg[6] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3677), .Q (u_wr_b_timer[6]));
  DFFRHQX1 \u_wr_b_timer_reg[7] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3663), .Q (u_wr_b_timer[7]));
  DFFRHQX1 \u_wr_b_timer_reg[8] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3649), .Q (u_wr_b_timer[8]));
  DFFRHQX1 \u_wr_b_timer_reg[9] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3635), .Q (u_wr_b_timer[9]));
  DFFRHQX1 \u_wr_b_timer_reg[10] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3621), .Q (u_wr_b_timer[10]));
  DFFRHQX1 \u_wr_b_timer_reg[11] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3607), .Q (u_wr_b_timer[11]));
  DFFRHQX1 \u_wr_b_timer_reg[12] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3593), .Q (u_wr_b_timer[12]));
  DFFRHQX1 \u_wr_b_timer_reg[13] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3579), .Q (u_wr_b_timer[13]));
  DFFRHQX1 \u_wr_b_timer_reg[14] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3564), .Q (u_wr_b_timer[14]));
  DFFRHQX1 \u_wr_b_timer_reg[15] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3557), .Q (u_wr_b_timer[15]));
  DFFRHQX1 \u_wr_drain_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3744), .Q (u_wr_drain_cnt[1]));
  SDFFRHQX1 \u_wr_drain_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3765), .SI (u_wr_n_3776), .SE (u_wr_drain_cnt[3]), .Q
       (u_wr_drain_cnt[3]));
  DFFRHQX1 \u_wr_outst_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3746), .Q (u_wr_outst_cnt[1]));
  DFFRHQX1 \u_wr_w_timer_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3812), .Q (u_wr_w_timer[0]));
  DFFRHQX1 \u_wr_w_timer_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3793), .Q (u_wr_w_timer[1]));
  DFFRHQX1 \u_wr_w_timer_reg[2] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3743), .Q (u_wr_w_timer[2]));
  DFFRHQX1 \u_wr_w_timer_reg[3] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3719), .Q (u_wr_w_timer[3]));
  DFFRHQX1 \u_wr_w_timer_reg[4] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3704), .Q (u_wr_w_timer[4]));
  DFFRHQX1 \u_wr_w_timer_reg[5] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3690), .Q (u_wr_w_timer[5]));
  DFFRHQX1 \u_wr_w_timer_reg[6] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3676), .Q (u_wr_w_timer[6]));
  DFFRHQX1 \u_wr_w_timer_reg[7] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3662), .Q (u_wr_w_timer[7]));
  DFFRHQX1 \u_wr_w_timer_reg[8] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3648), .Q (u_wr_w_timer[8]));
  DFFRHQX1 \u_wr_w_timer_reg[9] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3634), .Q (u_wr_w_timer[9]));
  DFFRHQX1 \u_wr_w_timer_reg[10] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3620), .Q (u_wr_w_timer[10]));
  DFFRHQX1 \u_wr_w_timer_reg[11] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3606), .Q (u_wr_w_timer[11]));
  DFFRHQX1 \u_wr_w_timer_reg[12] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3592), .Q (u_wr_w_timer[12]));
  DFFRHQX1 \u_wr_w_timer_reg[13] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3578), .Q (u_wr_w_timer[13]));
  DFFRHQX1 \u_wr_w_timer_reg[14] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3562), .Q (u_wr_w_timer[14]));
  DFFRHQX1 \u_wr_w_timer_reg[15] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3556), .Q (u_wr_w_timer[15]));
  DFFRHQX1 \u_wr_wr_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3873), .Q (u_wr_wr_state[1]));
  NOR2X1 u_wr_g5562(.A (u_wr_n_3902), .B (u_wr_n_3558), .Y
       (u_wr_n_3556));
  NOR2X1 u_wr_g5563(.A (u_wr_n_3860), .B (u_wr_n_3560), .Y
       (u_wr_n_3557));
  AOI22X1 u_wr_g5566(.A0 (u_wr_n_3968), .A1 (u_wr_n_3566), .B0
       (u_wr_w_timer[15]), .B1 (u_wr_n_3974), .Y (u_wr_n_3558));
  AOI22X1 u_wr_g5567(.A0 (u_wr_n_3957), .A1 (u_wr_n_3567), .B0
       (u_wr_b_timer[15]), .B1 (u_wr_n_3958), .Y (u_wr_n_3560));
  AOI21XL u_wr_g5568(.A0 (u_wr_n_3935), .A1 (u_wr_n_3568), .B0
       (u_wr_n_3902), .Y (u_wr_n_3562));
  AOI21XL u_wr_g5569(.A0 (u_wr_n_3946), .A1 (u_wr_n_3572), .B0
       (u_wr_n_3860), .Y (u_wr_n_3564));
  XNOR2X1 u_wr_g5570(.A (u_wr_w_timer[15]), .B (u_wr_n_3580), .Y
       (u_wr_n_3566));
  XNOR2X1 u_wr_g5571(.A (u_wr_b_timer[15]), .B (u_wr_n_3582), .Y
       (u_wr_n_3567));
  OAI211X1 u_wr_g5574(.A0 (u_wr_w_timer[14]), .A1 (u_wr_n_3590), .B0
       (u_wr_n_3968), .C0 (u_wr_n_3580), .Y (u_wr_n_3568));
  OAI211X1 u_wr_g5575(.A0 (u_wr_b_timer[14]), .A1 (u_wr_n_3588), .B0
       (u_wr_n_3957), .C0 (u_wr_n_3582), .Y (u_wr_n_3572));
  AOI21XL u_wr_g5576(.A0 (u_wr_n_3926), .A1 (u_wr_n_3583), .B0
       (u_wr_n_3902), .Y (u_wr_n_3578));
  AOI21XL u_wr_g5577(.A0 (u_wr_n_3945), .A1 (u_wr_n_3585), .B0
       (u_wr_n_3860), .Y (u_wr_n_3579));
  NAND2X1 u_wr_g5578(.A (u_wr_w_timer[14]), .B (u_wr_n_3590), .Y
       (u_wr_n_3580));
  OAI211X1 u_wr_g5581(.A0 (u_wr_w_timer[13]), .A1 (u_wr_n_3602), .B0
       (u_wr_n_3968), .C0 (u_wr_n_3594), .Y (u_wr_n_3583));
  OAI211X1 u_wr_g5582(.A0 (u_wr_b_timer[13]), .A1 (u_wr_n_3604), .B0
       (u_wr_n_3957), .C0 (u_wr_n_3596), .Y (u_wr_n_3585));
  NAND2X1 u_wr_g5583(.A (u_wr_b_timer[14]), .B (u_wr_n_3588), .Y
       (u_wr_n_3582));
  INVX1 u_wr_g5584(.A (u_wr_n_3596), .Y (u_wr_n_3588));
  INVX1 u_wr_g5585(.A (u_wr_n_3594), .Y (u_wr_n_3590));
  AOI21XL u_wr_g5586(.A0 (u_wr_n_3924), .A1 (u_wr_n_3597), .B0
       (u_wr_n_3902), .Y (u_wr_n_3592));
  AOI21X1 u_wr_g5587(.A0 (u_wr_n_3944), .A1 (u_wr_n_3599), .B0
       (u_wr_n_3860), .Y (u_wr_n_3593));
  NAND2X1 u_wr_g5588(.A (u_wr_w_timer[13]), .B (u_wr_n_3602), .Y
       (u_wr_n_3594));
  OAI211X1 u_wr_g5591(.A0 (u_wr_w_timer[12]), .A1 (u_wr_n_3616), .B0
       (u_wr_n_3968), .C0 (u_wr_n_3608), .Y (u_wr_n_3597));
  OAI211X1 u_wr_g5592(.A0 (u_wr_b_timer[12]), .A1 (u_wr_n_3618), .B0
       (u_wr_n_3957), .C0 (u_wr_n_3610), .Y (u_wr_n_3599));
  NAND2X1 u_wr_g5593(.A (u_wr_b_timer[13]), .B (u_wr_n_3604), .Y
       (u_wr_n_3596));
  INVX1 u_wr_g5594(.A (u_wr_n_3608), .Y (u_wr_n_3602));
  INVX1 u_wr_g5595(.A (u_wr_n_3610), .Y (u_wr_n_3604));
  AOI21XL u_wr_g5596(.A0 (u_wr_n_3922), .A1 (u_wr_n_3611), .B0
       (u_wr_n_3902), .Y (u_wr_n_3606));
  AOI21XL u_wr_g5597(.A0 (u_wr_n_3943), .A1 (u_wr_n_3613), .B0
       (u_wr_n_3860), .Y (u_wr_n_3607));
  NAND2X1 u_wr_g5598(.A (u_wr_w_timer[12]), .B (u_wr_n_3616), .Y
       (u_wr_n_3608));
  OAI211X1 u_wr_g5601(.A0 (u_wr_w_timer[11]), .A1 (u_wr_n_3632), .B0
       (u_wr_n_3968), .C0 (u_wr_n_3622), .Y (u_wr_n_3611));
  OAI211X1 u_wr_g5602(.A0 (u_wr_b_timer[11]), .A1 (u_wr_n_3630), .B0
       (u_wr_n_3957), .C0 (u_wr_n_3624), .Y (u_wr_n_3613));
  NAND2X1 u_wr_g5603(.A (u_wr_b_timer[12]), .B (u_wr_n_3618), .Y
       (u_wr_n_3610));
  INVX1 u_wr_g5604(.A (u_wr_n_3622), .Y (u_wr_n_3616));
  INVX1 u_wr_g5605(.A (u_wr_n_3624), .Y (u_wr_n_3618));
  AOI21XL u_wr_g5606(.A0 (u_wr_n_3921), .A1 (u_wr_n_3625), .B0
       (u_wr_n_3902), .Y (u_wr_n_3620));
  AOI21X1 u_wr_g5607(.A0 (u_wr_n_3942), .A1 (u_wr_n_3627), .B0
       (u_wr_n_3860), .Y (u_wr_n_3621));
  NAND2X1 u_wr_g5608(.A (u_wr_w_timer[11]), .B (u_wr_n_3632), .Y
       (u_wr_n_3622));
  OAI211X1 u_wr_g5611(.A0 (u_wr_w_timer[10]), .A1 (u_wr_n_3646), .B0
       (u_wr_n_3968), .C0 (u_wr_n_3636), .Y (u_wr_n_3625));
  OAI211X1 u_wr_g5612(.A0 (u_wr_b_timer[10]), .A1 (u_wr_n_3644), .B0
       (u_wr_n_3957), .C0 (u_wr_n_3638), .Y (u_wr_n_3627));
  NAND2X1 u_wr_g5613(.A (u_wr_b_timer[11]), .B (u_wr_n_3630), .Y
       (u_wr_n_3624));
  INVX1 u_wr_g5614(.A (u_wr_n_3638), .Y (u_wr_n_3630));
  INVX1 u_wr_g5615(.A (u_wr_n_3636), .Y (u_wr_n_3632));
  AOI21XL u_wr_g5616(.A0 (u_wr_n_3920), .A1 (u_wr_n_3639), .B0
       (u_wr_n_3902), .Y (u_wr_n_3634));
  AOI21XL u_wr_g5617(.A0 (u_wr_n_3941), .A1 (u_wr_n_3641), .B0
       (u_wr_n_3860), .Y (u_wr_n_3635));
  NAND2X1 u_wr_g5618(.A (u_wr_w_timer[10]), .B (u_wr_n_3646), .Y
       (u_wr_n_3636));
  OAI211X1 u_wr_g5621(.A0 (u_wr_w_timer[9]), .A1 (u_wr_n_3660), .B0
       (u_wr_n_3968), .C0 (u_wr_n_3650), .Y (u_wr_n_3639));
  OAI211X1 u_wr_g5622(.A0 (u_wr_b_timer[9]), .A1 (u_wr_n_3658), .B0
       (u_wr_n_3957), .C0 (u_wr_n_3652), .Y (u_wr_n_3641));
  NAND2X1 u_wr_g5623(.A (u_wr_b_timer[10]), .B (u_wr_n_3644), .Y
       (u_wr_n_3638));
  INVX1 u_wr_g5624(.A (u_wr_n_3652), .Y (u_wr_n_3644));
  INVX1 u_wr_g5625(.A (u_wr_n_3650), .Y (u_wr_n_3646));
  AOI21XL u_wr_g5626(.A0 (u_wr_n_3918), .A1 (u_wr_n_3653), .B0
       (u_wr_n_3902), .Y (u_wr_n_3648));
  AOI21XL u_wr_g5627(.A0 (u_wr_n_3940), .A1 (u_wr_n_3655), .B0
       (u_wr_n_3860), .Y (u_wr_n_3649));
  NAND2X1 u_wr_g5628(.A (u_wr_w_timer[9]), .B (u_wr_n_3660), .Y
       (u_wr_n_3650));
  OAI211X1 u_wr_g5631(.A0 (u_wr_w_timer[8]), .A1 (u_wr_n_3674), .B0
       (u_wr_n_3968), .C0 (u_wr_n_3664), .Y (u_wr_n_3653));
  OAI211X1 u_wr_g5632(.A0 (u_wr_b_timer[8]), .A1 (u_wr_n_3672), .B0
       (u_wr_n_3957), .C0 (u_wr_n_3666), .Y (u_wr_n_3655));
  NAND2X1 u_wr_g5633(.A (u_wr_b_timer[9]), .B (u_wr_n_3658), .Y
       (u_wr_n_3652));
  INVX1 u_wr_g5634(.A (u_wr_n_3666), .Y (u_wr_n_3658));
  INVX1 u_wr_g5635(.A (u_wr_n_3664), .Y (u_wr_n_3660));
  AOI21XL u_wr_g5636(.A0 (u_wr_n_3917), .A1 (u_wr_n_3667), .B0
       (u_wr_n_3902), .Y (u_wr_n_3662));
  AOI21X1 u_wr_g5637(.A0 (u_wr_n_3939), .A1 (u_wr_n_3669), .B0
       (u_wr_n_3860), .Y (u_wr_n_3663));
  NAND2X1 u_wr_g5638(.A (u_wr_w_timer[8]), .B (u_wr_n_3674), .Y
       (u_wr_n_3664));
  OAI211X1 u_wr_g5641(.A0 (u_wr_w_timer[7]), .A1 (u_wr_n_3686), .B0
       (u_wr_n_3968), .C0 (u_wr_n_3678), .Y (u_wr_n_3667));
  OAI211X1 u_wr_g5642(.A0 (u_wr_b_timer[7]), .A1 (u_wr_n_3688), .B0
       (u_wr_n_3957), .C0 (u_wr_n_3680), .Y (u_wr_n_3669));
  NAND2X1 u_wr_g5643(.A (u_wr_b_timer[8]), .B (u_wr_n_3672), .Y
       (u_wr_n_3666));
  INVX1 u_wr_g5644(.A (u_wr_n_3680), .Y (u_wr_n_3672));
  INVX1 u_wr_g5645(.A (u_wr_n_3678), .Y (u_wr_n_3674));
  AOI21XL u_wr_g5646(.A0 (u_wr_n_3916), .A1 (u_wr_n_3681), .B0
       (u_wr_n_3902), .Y (u_wr_n_3676));
  AOI21XL u_wr_g5647(.A0 (u_wr_n_3938), .A1 (u_wr_n_3683), .B0
       (u_wr_n_3860), .Y (u_wr_n_3677));
  NAND2X1 u_wr_g5648(.A (u_wr_w_timer[7]), .B (u_wr_n_3686), .Y
       (u_wr_n_3678));
  OAI211X1 u_wr_g5651(.A0 (u_wr_w_timer[6]), .A1 (u_wr_n_3700), .B0
       (u_wr_n_3968), .C0 (u_wr_n_3692), .Y (u_wr_n_3681));
  OAI211X1 u_wr_g5652(.A0 (u_wr_b_timer[6]), .A1 (u_wr_n_3702), .B0
       (u_wr_n_3957), .C0 (u_wr_n_3694), .Y (u_wr_n_3683));
  NAND2X1 u_wr_g5653(.A (u_wr_b_timer[7]), .B (u_wr_n_3688), .Y
       (u_wr_n_3680));
  INVX1 u_wr_g5654(.A (u_wr_n_3692), .Y (u_wr_n_3686));
  INVX1 u_wr_g5655(.A (u_wr_n_3694), .Y (u_wr_n_3688));
  AOI21XL u_wr_g5656(.A0 (u_wr_n_3919), .A1 (u_wr_n_3695), .B0
       (u_wr_n_3902), .Y (u_wr_n_3690));
  AOI21XL u_wr_g5657(.A0 (u_wr_n_3936), .A1 (u_wr_n_3697), .B0
       (u_wr_n_3860), .Y (u_wr_n_3691));
  NAND2X1 u_wr_g5658(.A (u_wr_w_timer[6]), .B (u_wr_n_3700), .Y
       (u_wr_n_3692));
  OAI211X1 u_wr_g5661(.A0 (u_wr_w_timer[5]), .A1 (u_wr_n_3717), .B0
       (u_wr_n_3968), .C0 (u_wr_n_3706), .Y (u_wr_n_3695));
  OAI211X1 u_wr_g5662(.A0 (u_wr_b_timer[5]), .A1 (u_wr_n_3715), .B0
       (u_wr_n_3957), .C0 (u_wr_n_3708), .Y (u_wr_n_3697));
  NAND2X1 u_wr_g5663(.A (u_wr_b_timer[6]), .B (u_wr_n_3702), .Y
       (u_wr_n_3694));
  INVX1 u_wr_g5664(.A (u_wr_n_3706), .Y (u_wr_n_3700));
  INVX1 u_wr_g5665(.A (u_wr_n_3708), .Y (u_wr_n_3702));
  AOI21XL u_wr_g5666(.A0 (u_wr_n_3915), .A1 (u_wr_n_3709), .B0
       (u_wr_n_3902), .Y (u_wr_n_3704));
  AOI21XL u_wr_g5667(.A0 (u_wr_n_3712), .A1 (u_wr_n_3937), .B0
       (u_wr_n_3860), .Y (u_wr_n_3705));
  NAND2X1 u_wr_g5669(.A (u_wr_w_timer[5]), .B (u_wr_n_3717), .Y
       (u_wr_n_3706));
  OAI211X1 u_wr_g5672(.A0 (u_wr_w_timer[4]), .A1 (u_wr_n_3736), .B0
       (u_wr_n_3968), .C0 (u_wr_n_3724), .Y (u_wr_n_3709));
  OAI211X1 u_wr_g5674(.A0 (u_wr_b_timer[4]), .A1 (u_wr_n_3738), .B0
       (u_wr_n_3725), .C0 (u_wr_n_3957), .Y (u_wr_n_3712));
  NAND2X1 u_wr_g5675(.A (u_wr_b_timer[5]), .B (u_wr_n_3715), .Y
       (u_wr_n_3708));
  INVX1 u_wr_g5676(.A (u_wr_n_3725), .Y (u_wr_n_3715));
  INVX1 u_wr_g5677(.A (u_wr_n_3724), .Y (u_wr_n_3717));
  AOI21XL u_wr_g5679(.A0 (u_wr_n_3914), .A1 (u_wr_n_3729), .B0
       (u_wr_n_3902), .Y (u_wr_n_3719));
  AOI21XL u_wr_g5680(.A0 (u_wr_n_3731), .A1 (u_wr_n_3910), .B0
       (u_wr_n_3860), .Y (u_wr_n_3720));
  AOI32X1 u_wr_g5682(.A0 (u_wr_n_3989), .A1 (u_wr_n_4001), .A2
       (u_wr_n_3741), .B0 (u_wr_n_4005), .B1 (s_wready), .Y
       (u_wr_n_3721));
  OAI211X1 u_wr_g5689(.A0 (u_wr_outst_cnt[3]), .A1 (u_wr_n_3801), .B0
       (u_wr_n_3804), .C0 (n_227), .Y (u_wr_n_3726));
  OAI211X1 u_wr_g5690(.A0 (u_wr_w_timer[3]), .A1 (u_wr_n_3786), .B0
       (u_wr_n_3968), .C0 (u_wr_n_3761), .Y (u_wr_n_3729));
  OAI211X1 u_wr_g5691(.A0 (u_wr_b_timer[3]), .A1 (u_wr_n_3784), .B0
       (u_wr_n_3762), .C0 (u_wr_n_3957), .Y (u_wr_n_3731));
  NAND2X1 u_wr_g5693(.A (u_wr_w_timer[4]), .B (u_wr_n_3736), .Y
       (u_wr_n_3724));
  NAND2X1 u_wr_g5694(.A (u_wr_b_timer[4]), .B (u_wr_n_3738), .Y
       (u_wr_n_3725));
  INVX1 u_wr_g5695(.A (u_wr_n_3761), .Y (u_wr_n_3736));
  INVX1 u_wr_g5696(.A (u_wr_n_3762), .Y (u_wr_n_3738));
  NOR2X1 u_wr_g5697(.A (epoch_clr), .B (u_wr_n_3756), .Y (u_wr_n_3740));
  NAND2BX1 u_wr_g5698(.AN (u_wr_n_3934), .B (u_wr_n_4110), .Y
       (u_wr_n_3741));
  AOI21XL u_wr_g5699(.A0 (u_wr_n_3912), .A1 (u_wr_n_3779), .B0
       (u_wr_n_3902), .Y (u_wr_n_3743));
  MXI2XL u_wr_g5701(.A (u_wr_n_3775), .B (u_wr_n_3791), .S0
       (u_wr_drain_cnt[1]), .Y (u_wr_n_3744));
  OAI21X1 u_wr_g5702(.A0 (u_wr_n_3967), .A1 (u_wr_n_3854), .B0
       (u_wr_n_3758), .Y (u_wr_n_3746));
  AOI21XL u_wr_g5703(.A0 (u_wr_n_3781), .A1 (u_wr_n_3925), .B0
       (u_wr_n_3860), .Y (u_wr_n_3747));
  AOI22X1 u_wr_g5705(.A0 (u_wr_outst_cnt[2]), .A1 (u_wr_n_3771), .B0
       (u_wr_n_3954), .B1 (u_wr_n_3933), .Y (u_wr_n_3749));
  OAI2BB1X1 u_wr_g5706(.A0N (u_wr_n_3955), .A1N (u_wr_n_3933), .B0
       (u_wr_n_3772), .Y (u_wr_n_3752));
  OAI211X1 u_wr_g5709(.A0 (u_wr_n_3964), .A1 (u_wr_n_3853), .B0
       (u_wr_n_3792), .C0 (u_wr_n_3763), .Y (u_wr_n_3755));
  XNOR2X1 u_wr_g5710(.A (u_wr_outst_cnt[0]), .B (u_wr_n_3789), .Y
       (u_wr_n_3756));
  AOI33XL u_wr_g5711(.A0 (u_wr_outst_cnt[1]), .A1 (logic_1_1_net), .A2
       (u_wr_n_3788), .B0 (u_wr_n_3855), .B1 (u_wr_n_3967), .B2
       (s_wready), .Y (u_wr_n_3758));
  OAI2BB1X1 u_wr_g5712(.A0N (u_wr_n_3806), .A1N (u_wr_n_3809), .B0
       (u_wr_drain_cnt[2]), .Y (u_wr_n_3763));
  OAI31X1 u_wr_g5713(.A0 (u_wr_n_4029), .A1 (u_wr_n_3964), .A2
       (u_wr_n_3932), .B0 (u_wr_n_3792), .Y (u_wr_n_3765));
  NAND2X1 u_wr_g5714(.A (u_wr_w_timer[3]), .B (u_wr_n_3786), .Y
       (u_wr_n_3761));
  NAND2X1 u_wr_g5715(.A (u_wr_b_timer[3]), .B (u_wr_n_3784), .Y
       (u_wr_n_3762));
  INVX1 u_wr_g5718(.A (u_wr_n_3772), .Y (u_wr_n_3771));
  OAI221X1 u_wr_g5719(.A0 (u_wr_drain_cnt[0]), .A1 (u_wr_n_3802), .B0
       (u_wr_n_4004), .B1 (u_wr_n_3929), .C0 (u_wr_n_3814), .Y
       (u_wr_n_3773));
  AOI22XL u_wr_g5720(.A0 (u_wr_n_318), .A1 (u_wr_n_3803), .B0
       (u_wr_n_4003), .B1 (u_wr_n_3931), .Y (u_wr_n_3775));
  OAI211X1 u_wr_g5721(.A0 (u_wr_n_3953), .A1 (u_wr_n_3858), .B0
       (u_wr_n_3853), .C0 (u_wr_n_3809), .Y (u_wr_n_3776));
  OAI211X1 u_wr_g5722(.A0 (u_wr_w_timer[2]), .A1 (u_wr_n_3900), .B0
       (u_wr_n_3968), .C0 (u_wr_n_3856), .Y (u_wr_n_3779));
  OAI211X1 u_wr_g5723(.A0 (u_wr_b_timer[2]), .A1 (u_wr_n_3898), .B0
       (u_wr_n_3857), .C0 (u_wr_n_3957), .Y (u_wr_n_3781));
  AOI21X1 u_wr_g5724(.A0 (u_wr_n_3934), .A1 (u_wr_n_3966), .B0
       (u_wr_n_3790), .Y (u_wr_n_3772));
  INVX1 u_wr_g5725(.A (u_wr_n_3857), .Y (u_wr_n_3784));
  INVX1 u_wr_g5726(.A (u_wr_n_3856), .Y (u_wr_n_3786));
  INVXL u_wr_g5727(.A (u_wr_n_3789), .Y (u_wr_n_3788));
  ADDHX1 u_wr_g5728(.A (u_wr_n_3933), .B (s_wready), .CO (u_wr_n_3790),
       .S (u_wr_n_3789));
  INVXL u_wr_g5733(.A (u_wr_n_3794), .Y (u_wr_n_3791));
  AOI21XL u_wr_g5734(.A0 (u_wr_n_3927), .A1 (u_wr_n_3870), .B0
       (u_wr_n_3902), .Y (u_wr_n_3793));
  OAI211X1 u_wr_g5735(.A0 (u_wr_n_318), .A1 (u_wr_n_3858), .B0
       (u_wr_n_3851), .C0 (u_wr_n_3849), .Y (u_wr_n_3794));
  AOI21XL u_wr_g5737(.A0 (u_wr_n_3867), .A1 (u_wr_n_3923), .B0
       (u_wr_n_3860), .Y (u_wr_n_3798));
  NAND2X1 u_wr_g5738(.A (u_wr_n_3953), .B (u_wr_n_3803), .Y
       (u_wr_n_3792));
  INVX1 u_wr_g5739(.A (u_wr_n_3803), .Y (u_wr_n_3802));
  NAND2X1 u_wr_g5740(.A (u_wr_n_3855), .B (u_wr_n_3877), .Y
       (u_wr_n_3804));
  OR2XL u_wr_g5743(.A (u_wr_n_4000), .B (u_wr_n_3858), .Y
       (u_wr_n_3806));
  OR2XL u_wr_g5744(.A (u_wr_n_3955), .B (u_wr_n_3854), .Y
       (u_wr_n_3801));
  NOR2BX1 u_wr_g5745(.AN (m_bvalid), .B (u_wr_n_3858), .Y
       (u_wr_n_3803));
  NOR2XL u_wr_g5748(.A (u_wr_n_3880), .B (u_wr_n_3902), .Y
       (u_wr_n_3812));
  NOR2XL u_wr_g5749(.A (u_wr_n_3879), .B (u_wr_n_3860), .Y
       (u_wr_n_3813));
  OAI31X1 u_wr_g5750(.A0 (u_wr_n_4027), .A1 (u_wr_drain_cnt[0]), .A2
       (u_wr_n_145), .B0 (u_wr_n_3850), .Y (u_wr_n_3814));
  NAND2X1 u_wr_g5751(.A (u_wr_n_4069), .B (u_wr_n_3855), .Y
       (u_wr_n_3815));
  OAI31X1 u_wr_g5753(.A0 (u_wr_wpair_state[0]), .A1 (u_wr_n_4033), .A2
       (epoch_clr), .B0 (u_wr_n_3881), .Y (u_wr_n_3818));
  AOI21X1 u_wr_g5754(.A0 (u_wr_n_3964), .A1 (u_wr_n_3931), .B0
       (u_wr_n_3852), .Y (u_wr_n_3809));
  INVX1 u_wr_g5782(.A (u_wr_n_3850), .Y (u_wr_n_3849));
  INVX1 u_wr_g5783(.A (u_wr_n_3852), .Y (u_wr_n_3851));
  OAI211X1 u_wr_g5784(.A0 (u_wr_b_timer[0]), .A1 (u_wr_b_timer[1]), .B0
       (u_wr_n_3991), .C0 (u_wr_n_3957), .Y (u_wr_n_3867));
  OAI211X1 u_wr_g5785(.A0 (u_wr_w_timer[0]), .A1 (u_wr_w_timer[1]), .B0
       (u_wr_n_3990), .C0 (u_wr_n_3968), .Y (u_wr_n_3870));
  NOR2BX1 u_wr_g5786(.AN (u_wr_n_3947), .B (epoch_clr), .Y
       (u_wr_n_3873));
  OAI32X1 u_wr_g5789(.A0 (u_wr_outst_cnt[3]), .A1 (u_wr_n_4069), .A2
       (u_wr_n_3966), .B0 (u_wr_outst_cnt[2]), .B1 (u_wr_n_4035), .Y
       (u_wr_n_3877));
  XNOR2X1 u_wr_g5790(.A (u_wr_b_timer[0]), .B (u_wr_n_3957), .Y
       (u_wr_n_3879));
  XNOR2X1 u_wr_g5791(.A (u_wr_w_timer[0]), .B (u_wr_n_3968), .Y
       (u_wr_n_3880));
  OAI2BB1X1 u_wr_g5792(.A0N (u_rd_n_280), .A1N (u_wr_n_2043), .B0
       (u_wr_n_3930), .Y (u_wr_n_3881));
  NOR2X1 u_wr_g5798(.A (u_wr_n_4003), .B (u_wr_n_3932), .Y
       (u_wr_n_3850));
  NOR2X1 u_wr_g5799(.A (m_bvalid), .B (u_wr_n_3929), .Y (u_wr_n_3852));
  NAND2X1 u_wr_g5800(.A (u_wr_n_4029), .B (u_wr_n_3931), .Y
       (u_wr_n_3853));
  NAND2X1 u_wr_g5801(.A (u_wr_n_3933), .B (u_wr_n_3965), .Y
       (u_wr_n_3854));
  NOR2X1 u_wr_g5806(.A (epoch_clr), .B (u_wr_n_3933), .Y (u_wr_n_3855));
  NAND2X1 u_wr_g5807(.A (u_wr_w_timer[2]), .B (u_wr_n_3900), .Y
       (u_wr_n_3856));
  NAND2X1 u_wr_g5808(.A (u_wr_b_timer[2]), .B (u_wr_n_3898), .Y
       (u_wr_n_3857));
  OR2X1 u_wr_g5809(.A (u_wr_n_145), .B (u_wr_n_3929), .Y (u_wr_n_3858));
  OR2X1 u_wr_g5810(.A (u_wr_n_4006), .B (u_wr_n_3933), .Y
       (u_wr_n_3860));
  INVX1 u_wr_g5811(.A (u_wr_n_3991), .Y (u_wr_n_3898));
  INVX1 u_wr_g5812(.A (u_wr_n_3990), .Y (u_wr_n_3900));
  NAND2XL u_wr_g5813(.A (u_wr_b_timer[3]), .B (u_wr_n_3958), .Y
       (u_wr_n_3910));
  NAND2XL u_wr_g5814(.A (u_wr_w_timer[2]), .B (u_wr_n_3974), .Y
       (u_wr_n_3912));
  NAND2XL u_wr_g5815(.A (u_wr_w_timer[3]), .B (u_wr_n_3974), .Y
       (u_wr_n_3914));
  NAND2XL u_wr_g5816(.A (u_wr_w_timer[4]), .B (u_wr_n_3974), .Y
       (u_wr_n_3915));
  NAND2XL u_wr_g5817(.A (u_wr_w_timer[6]), .B (u_wr_n_3974), .Y
       (u_wr_n_3916));
  NAND2XL u_wr_g5818(.A (u_wr_w_timer[7]), .B (u_wr_n_3974), .Y
       (u_wr_n_3917));
  NAND2XL u_wr_g5819(.A (u_wr_w_timer[8]), .B (u_wr_n_3974), .Y
       (u_wr_n_3918));
  NAND2XL u_wr_g5820(.A (u_wr_w_timer[5]), .B (u_wr_n_3974), .Y
       (u_wr_n_3919));
  NAND2XL u_wr_g5821(.A (u_wr_w_timer[9]), .B (u_wr_n_3974), .Y
       (u_wr_n_3920));
  NAND2XL u_wr_g5822(.A (u_wr_w_timer[10]), .B (u_wr_n_3974), .Y
       (u_wr_n_3921));
  NAND2XL u_wr_g5823(.A (u_wr_w_timer[11]), .B (u_wr_n_3974), .Y
       (u_wr_n_3922));
  NAND2XL u_wr_g5824(.A (u_wr_b_timer[1]), .B (u_wr_n_3958), .Y
       (u_wr_n_3923));
  NAND2XL u_wr_g5825(.A (u_wr_w_timer[12]), .B (u_wr_n_3974), .Y
       (u_wr_n_3924));
  NAND2XL u_wr_g5826(.A (u_wr_b_timer[2]), .B (u_wr_n_3958), .Y
       (u_wr_n_3925));
  NAND2XL u_wr_g5827(.A (u_wr_w_timer[13]), .B (u_wr_n_3974), .Y
       (u_wr_n_3926));
  NAND2XL u_wr_g5828(.A (u_wr_w_timer[1]), .B (u_wr_n_3974), .Y
       (u_wr_n_3927));
  NAND2X1 u_wr_g5829(.A (u_wr_n_1641), .B (u_wr_n_3965), .Y
       (u_wr_n_3902));
  INVX1 u_wr_g5830(.A (u_wr_n_3931), .Y (u_wr_n_3932));
  NAND2XL u_wr_g5832(.A (u_wr_w_timer[14]), .B (u_wr_n_3974), .Y
       (u_wr_n_3935));
  NAND2XL u_wr_g5833(.A (u_wr_b_timer[5]), .B (u_wr_n_3958), .Y
       (u_wr_n_3936));
  NAND2XL u_wr_g5834(.A (u_wr_b_timer[4]), .B (u_wr_n_3958), .Y
       (u_wr_n_3937));
  NAND2XL u_wr_g5835(.A (u_wr_b_timer[6]), .B (u_wr_n_3958), .Y
       (u_wr_n_3938));
  NAND2X1 u_wr_g5836(.A (u_wr_b_timer[7]), .B (u_wr_n_3958), .Y
       (u_wr_n_3939));
  NAND2XL u_wr_g5837(.A (u_wr_b_timer[8]), .B (u_wr_n_3958), .Y
       (u_wr_n_3940));
  NAND2XL u_wr_g5838(.A (u_wr_b_timer[9]), .B (u_wr_n_3958), .Y
       (u_wr_n_3941));
  NAND2X1 u_wr_g5839(.A (u_wr_b_timer[10]), .B (u_wr_n_3958), .Y
       (u_wr_n_3942));
  NAND2XL u_wr_g5840(.A (u_wr_b_timer[11]), .B (u_wr_n_3958), .Y
       (u_wr_n_3943));
  NAND2X1 u_wr_g5841(.A (u_wr_b_timer[12]), .B (u_wr_n_3958), .Y
       (u_wr_n_3944));
  NAND2XL u_wr_g5842(.A (u_wr_b_timer[13]), .B (u_wr_n_3958), .Y
       (u_wr_n_3945));
  NAND2XL u_wr_g5843(.A (u_wr_b_timer[14]), .B (u_wr_n_3958), .Y
       (u_wr_n_3946));
  OAI22XL u_wr_g5844(.A0 (u_wr_n_3988), .A1 (u_wr_n_4001), .B0
       (s_bready), .B1 (u_wr_n_4002), .Y (u_wr_n_3947));
  NAND2X1 u_wr_g5845(.A (u_wr_n_3956), .B (u_wr_n_2054), .Y
       (u_wr_n_3929));
  NOR3BX1 u_wr_g5846(.AN (u_wr_n_3965), .B (u_wr_wpair_state[1]), .C
       (u_wr_n_435), .Y (u_wr_n_3930));
  NOR2X1 u_wr_g5847(.A (u_wr_n_3956), .B (epoch_clr), .Y (u_wr_n_3931));
  INVX1 u_wr_g5849(.A (u_wr_n_3957), .Y (u_wr_n_3958));
  AND2XL u_wr_g5850(.A (u_wr_n_4029), .B (u_wr_n_4000), .Y
       (u_wr_n_3953));
  NOR2X1 u_wr_g5851(.A (u_wr_n_4069), .B (u_wr_n_3987), .Y
       (u_wr_n_3954));
  NAND2X1 u_wr_g5852(.A (u_wr_n_4069), .B (u_wr_n_3987), .Y
       (u_wr_n_3955));
  NAND2BX1 u_wr_g5853(.AN (u_wr_n_4002), .B (s_bready), .Y
       (u_wr_n_3956));
  NOR2X2 u_wr_g5854(.A (u_wr_n_3988), .B (u_wr_n_230), .Y
       (u_wr_n_3957));
  INVX1 u_wr_g5855(.A (u_wr_n_3968), .Y (u_wr_n_3974));
  MX2XL u_wr_g5856(.A (u_wr_n_2115), .B (s_wready), .S0 (s_wvalid), .Y
       (u_wr_n_3983));
  NAND3X1 u_wr_g5857(.A (u_wr_n_4027), .B (u_wr_drain_cnt[1]), .C
       (u_wr_drain_cnt[0]), .Y (u_wr_n_3964));
  NOR2X1 u_wr_g5858(.A (epoch_clr), .B (s_wready), .Y (u_wr_n_3965));
  NAND3X1 u_wr_g5859(.A (u_wr_outst_cnt[1]), .B (u_wr_outst_cnt[0]), .C
       (s_wready), .Y (u_wr_n_3966));
  XNOR2X1 u_wr_g5860(.A (u_wr_outst_cnt[1]), .B (n_229), .Y
       (u_wr_n_3967));
  NOR2X2 u_wr_g5861(.A (u_wr_n_435), .B (u_wr_n_3995), .Y
       (u_wr_n_3968));
  INVX1 u_wr_g5862(.A (u_wr_n_3988), .Y (u_wr_n_3989));
  OR2XL u_wr_g5864(.A (s_wvalid), .B (u_wr_wpair_state[1]), .Y
       (u_wr_n_3995));
  NOR2X1 u_wr_g5865(.A (u_wr_outst_cnt[1]), .B (u_wr_outst_cnt[0]), .Y
       (u_wr_n_3987));
  NAND2BX1 u_wr_g5866(.AN (u_wr_wr_state[1]), .B (u_wr_wr_state[0]), .Y
       (u_wr_n_3988));
  NAND2X1 u_wr_g5867(.A (u_wr_w_timer[1]), .B (u_wr_w_timer[0]), .Y
       (u_wr_n_3990));
  NAND2X1 u_wr_g5868(.A (u_wr_b_timer[1]), .B (u_wr_b_timer[0]), .Y
       (u_wr_n_3991));
  OR2X2 u_wr_g5870(.A (u_wr_n_2120), .B (u_wr_n_4038), .Y
       (u_wr_n_3994));
  INVX1 u_wr_g5871(.A (u_wr_n_4003), .Y (u_wr_n_4004));
  NOR2X1 u_wr_g5872(.A (u_wr_wr_state[1]), .B (u_wr_wr_state[0]), .Y
       (u_wr_n_4005));
  NAND2X1 u_wr_g5873(.A (u_wr_n_2054), .B (u_wr_n_1627), .Y
       (u_wr_n_4006));
  NAND2X1 u_wr_g5874(.A (s_bready), .B (s_bvalid), .Y (u_wr_n_3934));
  NOR2X1 u_wr_g5875(.A (u_wr_drain_cnt[1]), .B (u_wr_drain_cnt[0]), .Y
       (u_wr_n_4000));
  NOR2BX1 u_wr_g5876(.AN (u_wr_n_1867), .B (flush), .Y (u_wr_n_4001));
  NAND2BX1 u_wr_g5877(.AN (u_wr_wr_state[0]), .B (u_wr_wr_state[1]), .Y
       (u_wr_n_4002));
  NOR2X1 u_wr_g5878(.A (m_bvalid), .B (u_wr_n_318), .Y (u_wr_n_4003));
  INVX1 u_wr_g5880(.A (m_bvalid), .Y (u_wr_n_4027));
  INVX1 u_wr_g5884(.A (epoch_clr), .Y (u_wr_n_2054));
  INVXL u_wr_g5885(.A (s_awready), .Y (u_wr_n_4038));
  DFFRX1 \u_wr_drain_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3755), .Q (u_wr_drain_cnt[2]), .QN (u_wr_n_4029));
  DFFRX1 \u_wr_outst_cnt_reg[2] (.RN (rst_n), .CK (clk), .D (n_226), .Q
       (u_wr_outst_cnt[2]), .QN (u_wr_n_4069));
  DFFRX1 \u_wr_outst_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3726), .Q (u_wr_outst_cnt[3]), .QN (u_wr_n_4035));
  DFFRX1 \u_wr_wpair_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_230),
       .Q (u_wr_wpair_state[0]), .QN (u_wr_n_435));
  DFFRX1 \u_wr_wpair_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3818), .Q (u_wr_wpair_state[1]), .QN (u_wr_n_4033));
  MXI2XL u_wr_g2(.A (n_228), .B (u_wr_n_430), .S0 (s_wready), .Y
       (u_wr_n_4110));
  OR4X1 u_rd_g1177(.A (u_rd_outst_cnt[0]), .B (u_rd_outst_cnt[1]), .C
       (u_rd_outst_cnt[2]), .D (u_rd_outst_cnt[3]), .Y (u_rd_n_300));
  OR2XL u_rd_g1178(.A (u_rd_n_300), .B (u_rd_n_287), .Y (rd_busy));
  OR4X1 u_rd_g1179(.A (u_rd_drain_cnt[3]), .B (u_rd_drain_cnt[2]), .C
       (u_rd_drain_cnt[1]), .D (u_rd_drain_cnt[0]), .Y (u_rd_n_287));
  NOR2BX1 u_rd_g1956(.AN (u_rd_timer_run), .B (u_rd_n_1700), .Y
       (rd_timeout_pulse));
  AND3X1 u_rd_g1957(.A (s_arvalid), .B (u_rd_n_1729), .C (u_rd_n_280),
       .Y (m_arvalid));
  NAND4XL u_rd_g1959(.A (u_rd_n_1748), .B (u_rd_n_1747), .C
       (u_rd_n_1746), .D (u_rd_n_1744), .Y (u_rd_n_1700));
  OR2X1 u_rd_g1960(.A (u_rd_n_288), .B (u_rd_n_287), .Y (m_rready));
  AO21X1 u_rd_g1961(.A0 (u_rd_n_1755), .A1 (u_rd_n_285), .B0
       (u_rd_n_1756), .Y (s_rvalid));
  NAND3BXL u_rd_g1962(.AN (flush), .B (m_arready), .C (u_rd_n_1729), .Y
       (u_rd_n_1705));
  AO21X1 u_rd_g1963(.A0 (\m_r[resp] [1]), .A1 (u_rd_n_285), .B0
       (u_rd_n_1756), .Y (\s_r[resp] [1]));
  AND2X1 u_rd_g1964(.A (u_rd_n_285), .B (\m_r[data] [19]), .Y
       (\s_r[data] [19]));
  AND2X1 u_rd_g1965(.A (u_rd_n_285), .B (\m_r[data] [18]), .Y
       (\s_r[data] [18]));
  AND2X1 u_rd_g1966(.A (u_rd_n_285), .B (\m_r[resp] [0]), .Y
       (\s_r[resp] [0]));
  AND2X1 u_rd_g1967(.A (u_rd_n_285), .B (\m_r[data] [17]), .Y
       (\s_r[data] [17]));
  AND2X1 u_rd_g1968(.A (u_rd_n_285), .B (\m_r[data] [16]), .Y
       (\s_r[data] [16]));
  AND2X1 u_rd_g1969(.A (u_rd_n_285), .B (\m_r[data] [15]), .Y
       (\s_r[data] [15]));
  AND2X1 u_rd_g1970(.A (u_rd_n_285), .B (\m_r[data] [14]), .Y
       (\s_r[data] [14]));
  AND2X1 u_rd_g1971(.A (u_rd_n_285), .B (\m_r[data] [13]), .Y
       (\s_r[data] [13]));
  AND2X1 u_rd_g1972(.A (u_rd_n_285), .B (\m_r[data] [12]), .Y
       (\s_r[data] [12]));
  AND2X1 u_rd_g1973(.A (u_rd_n_285), .B (\m_r[data] [31]), .Y
       (\s_r[data] [31]));
  AND2X1 u_rd_g1974(.A (u_rd_n_285), .B (\m_r[data] [11]), .Y
       (\s_r[data] [11]));
  AND2X1 u_rd_g1975(.A (u_rd_n_285), .B (\m_r[data] [10]), .Y
       (\s_r[data] [10]));
  AND2X1 u_rd_g1976(.A (u_rd_n_285), .B (\m_r[data] [30]), .Y
       (\s_r[data] [30]));
  AND2X1 u_rd_g1977(.A (u_rd_n_285), .B (\m_r[data] [9]), .Y
       (\s_r[data] [9]));
  AND2X1 u_rd_g1978(.A (u_rd_n_285), .B (\m_r[data] [8]), .Y
       (\s_r[data] [8]));
  AND2X1 u_rd_g1979(.A (u_rd_n_285), .B (\m_r[data] [29]), .Y
       (\s_r[data] [29]));
  AND2X1 u_rd_g1980(.A (u_rd_n_285), .B (\m_r[data] [7]), .Y
       (\s_r[data] [7]));
  AND2X1 u_rd_g1981(.A (u_rd_n_285), .B (\m_r[data] [6]), .Y
       (\s_r[data] [6]));
  AND2X1 u_rd_g1982(.A (u_rd_n_285), .B (\m_r[data] [28]), .Y
       (\s_r[data] [28]));
  AND2X1 u_rd_g1983(.A (u_rd_n_285), .B (\m_r[data] [5]), .Y
       (\s_r[data] [5]));
  AND2X1 u_rd_g1984(.A (u_rd_n_285), .B (\m_r[data] [4]), .Y
       (\s_r[data] [4]));
  AND2X1 u_rd_g1985(.A (u_rd_n_285), .B (\m_r[data] [26]), .Y
       (\s_r[data] [26]));
  AND2X1 u_rd_g1986(.A (u_rd_n_285), .B (\m_r[data] [3]), .Y
       (\s_r[data] [3]));
  AND2X1 u_rd_g1987(.A (u_rd_n_285), .B (\m_r[data] [2]), .Y
       (\s_r[data] [2]));
  AND2X1 u_rd_g1988(.A (u_rd_n_285), .B (\m_r[data] [1]), .Y
       (\s_r[data] [1]));
  AND2X1 u_rd_g1989(.A (u_rd_n_285), .B (\m_r[data] [0]), .Y
       (\s_r[data] [0]));
  AND2X1 u_rd_g1990(.A (u_rd_n_285), .B (\m_r[data] [25]), .Y
       (\s_r[data] [25]));
  AND2X1 u_rd_g1991(.A (u_rd_n_285), .B (\m_r[data] [27]), .Y
       (\s_r[data] [27]));
  AND2X1 u_rd_g1992(.A (u_rd_n_285), .B (\m_r[data] [24]), .Y
       (\s_r[data] [24]));
  AND2X1 u_rd_g1993(.A (u_rd_n_285), .B (\m_r[data] [23]), .Y
       (\s_r[data] [23]));
  AND2X1 u_rd_g1994(.A (u_rd_n_285), .B (\m_r[data] [22]), .Y
       (\s_r[data] [22]));
  AND2X1 u_rd_g1995(.A (u_rd_n_285), .B (\m_r[data] [21]), .Y
       (\s_r[data] [21]));
  NOR4X1 u_rd_g1996(.A (u_rd_timer[13]), .B (u_rd_timer[12]), .C
       (u_rd_timer[14]), .D (u_rd_timer[15]), .Y (u_rd_n_1744));
  AND2X1 u_rd_g1997(.A (u_rd_n_285), .B (\m_r[data] [20]), .Y
       (\s_r[data] [20]));
  NOR4X1 u_rd_g1998(.A (u_rd_timer[0]), .B (u_rd_timer[1]), .C
       (u_rd_timer[7]), .D (u_rd_timer[6]), .Y (u_rd_n_1746));
  NOR4BX1 u_rd_g1999(.AN (u_rd_timer[8]), .B (u_rd_timer[3]), .C
       (u_rd_timer[9]), .D (u_rd_timer[2]), .Y (u_rd_n_1747));
  NOR4X1 u_rd_g2000(.A (u_rd_timer[4]), .B (u_rd_timer[5]), .C
       (u_rd_timer[10]), .D (u_rd_timer[11]), .Y (u_rd_n_1748));
  OR4X1 u_rd_g2001(.A (u_rd_outst_cnt[0]), .B (u_rd_outst_cnt[1]), .C
       (u_rd_outst_cnt[2]), .D (u_rd_n_1760), .Y (u_rd_n_1729));
  AND2XL u_rd_g2003(.A (s_rready), .B (u_rd_n_285), .Y (u_rd_n_288));
  AND2X1 u_rd_g2006(.A (u_rd_rd_state[0]), .B (u_rd_n_1764), .Y
       (u_rd_n_285));
  NOR2BX1 u_rd_g2007(.AN (m_rvalid), .B (u_rd_n_287), .Y (u_rd_n_1755));
  NOR2X1 u_rd_g2008(.A (u_rd_rd_state[0]), .B (u_rd_n_1764), .Y
       (u_rd_n_1756));
  NOR2BX2 u_rd_g2(.AN (u_rd_n_285), .B (u_rd_n_1755), .Y
       (u_rd_timer_run));
  DFFRHQX1 \u_rd_drain_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2288), .Q (u_rd_drain_cnt[0]));
  SDFFRHQX1 \u_rd_drain_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2299), .SI (u_rd_n_2287), .SE (u_rd_drain_cnt[2]), .Q
       (u_rd_drain_cnt[2]));
  DFFRHQX1 \u_rd_drain_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2260), .Q (u_rd_drain_cnt[3]));
  DFFRHQX1 \u_rd_outst_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2245), .Q (u_rd_outst_cnt[1]));
  DFFRHQX1 \u_rd_outst_cnt_reg[2] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2251), .Q (u_rd_outst_cnt[2]));
  DFFRHQX1 \u_rd_rd_state_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2235), .Q (u_rd_rd_state[0]));
  DFFRHQX1 \u_rd_timer_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2317), .Q (u_rd_timer[0]));
  DFFRHQX1 \u_rd_timer_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2302), .Q (u_rd_timer[1]));
  DFFRHQX1 \u_rd_timer_reg[2] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2270), .Q (u_rd_timer[2]));
  DFFRHQX1 \u_rd_timer_reg[3] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2250), .Q (u_rd_timer[3]));
  DFFRHQX1 \u_rd_timer_reg[4] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2234), .Q (u_rd_timer[4]));
  DFFRHQX1 \u_rd_timer_reg[5] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2227), .Q (u_rd_timer[5]));
  DFFRHQX1 \u_rd_timer_reg[6] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2220), .Q (u_rd_timer[6]));
  DFFRHQX1 \u_rd_timer_reg[7] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2213), .Q (u_rd_timer[7]));
  DFFRHQX1 \u_rd_timer_reg[8] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2206), .Q (u_rd_timer[8]));
  DFFRHQX1 \u_rd_timer_reg[9] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2199), .Q (u_rd_timer[9]));
  DFFRHQX1 \u_rd_timer_reg[10] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2192), .Q (u_rd_timer[10]));
  DFFRHQX1 \u_rd_timer_reg[11] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2185), .Q (u_rd_timer[11]));
  DFFRHQX1 \u_rd_timer_reg[12] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2178), .Q (u_rd_timer[12]));
  DFFRHQX1 \u_rd_timer_reg[13] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2171), .Q (u_rd_timer[13]));
  DFFRHQX1 \u_rd_timer_reg[14] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2163), .Q (u_rd_timer[14]));
  DFFRHQX1 \u_rd_timer_reg[15] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2158), .Q (u_rd_timer[15]));
  NOR2XL u_rd_g3728(.A (u_rd_n_2161), .B (u_rd_n_2324), .Y
       (u_rd_n_2158));
  AOI22X1 u_rd_g3730(.A0 (u_rd_timer_run), .A1 (u_rd_n_2165), .B0
       (u_rd_n_2434), .B1 (u_rd_timer[15]), .Y (u_rd_n_2161));
  AOI21XL u_rd_g3731(.A0 (u_rd_n_2368), .A1 (u_rd_n_2166), .B0
       (u_rd_n_2324), .Y (u_rd_n_2163));
  XNOR2X1 u_rd_g3732(.A (u_rd_timer[15]), .B (u_rd_n_2172), .Y
       (u_rd_n_2165));
  OAI211X1 u_rd_g3734(.A0 (u_rd_timer[14]), .A1 (u_rd_n_2176), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2172), .Y (u_rd_n_2166));
  AOI21XL u_rd_g3735(.A0 (u_rd_n_2366), .A1 (u_rd_n_2173), .B0
       (u_rd_n_2324), .Y (u_rd_n_2171));
  OAI211X1 u_rd_g3737(.A0 (u_rd_timer[13]), .A1 (u_rd_n_2183), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2179), .Y (u_rd_n_2173));
  NAND2X1 u_rd_g3738(.A (u_rd_timer[14]), .B (u_rd_n_2176), .Y
       (u_rd_n_2172));
  INVX1 u_rd_g3739(.A (u_rd_n_2179), .Y (u_rd_n_2176));
  AOI21XL u_rd_g3740(.A0 (u_rd_n_2369), .A1 (u_rd_n_2180), .B0
       (u_rd_n_2324), .Y (u_rd_n_2178));
  OAI211X1 u_rd_g3742(.A0 (u_rd_timer[12]), .A1 (u_rd_n_2190), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2186), .Y (u_rd_n_2180));
  NAND2X1 u_rd_g3743(.A (u_rd_timer[13]), .B (u_rd_n_2183), .Y
       (u_rd_n_2179));
  INVX1 u_rd_g3744(.A (u_rd_n_2186), .Y (u_rd_n_2183));
  AOI21XL u_rd_g3745(.A0 (u_rd_n_2384), .A1 (u_rd_n_2187), .B0
       (u_rd_n_2324), .Y (u_rd_n_2185));
  OAI211X1 u_rd_g3747(.A0 (u_rd_timer[11]), .A1 (u_rd_n_2197), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2193), .Y (u_rd_n_2187));
  NAND2X1 u_rd_g3748(.A (u_rd_timer[12]), .B (u_rd_n_2190), .Y
       (u_rd_n_2186));
  INVX1 u_rd_g3749(.A (u_rd_n_2193), .Y (u_rd_n_2190));
  AOI21XL u_rd_g3750(.A0 (u_rd_n_2379), .A1 (u_rd_n_2194), .B0
       (u_rd_n_2324), .Y (u_rd_n_2192));
  OAI211X1 u_rd_g3752(.A0 (u_rd_timer[10]), .A1 (u_rd_n_2204), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2200), .Y (u_rd_n_2194));
  NAND2X1 u_rd_g3753(.A (u_rd_timer[11]), .B (u_rd_n_2197), .Y
       (u_rd_n_2193));
  INVX1 u_rd_g3754(.A (u_rd_n_2200), .Y (u_rd_n_2197));
  AOI21XL u_rd_g3755(.A0 (u_rd_n_2382), .A1 (u_rd_n_2201), .B0
       (u_rd_n_2324), .Y (u_rd_n_2199));
  OAI211X1 u_rd_g3757(.A0 (u_rd_timer[9]), .A1 (u_rd_n_2211), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2207), .Y (u_rd_n_2201));
  NAND2X1 u_rd_g3758(.A (u_rd_timer[10]), .B (u_rd_n_2204), .Y
       (u_rd_n_2200));
  INVX1 u_rd_g3759(.A (u_rd_n_2207), .Y (u_rd_n_2204));
  AOI21XL u_rd_g3760(.A0 (u_rd_n_2377), .A1 (u_rd_n_2208), .B0
       (u_rd_n_2324), .Y (u_rd_n_2206));
  OAI211X1 u_rd_g3762(.A0 (u_rd_timer[8]), .A1 (u_rd_n_2218), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2214), .Y (u_rd_n_2208));
  NAND2X1 u_rd_g3763(.A (u_rd_timer[9]), .B (u_rd_n_2211), .Y
       (u_rd_n_2207));
  INVX1 u_rd_g3764(.A (u_rd_n_2214), .Y (u_rd_n_2211));
  AOI21XL u_rd_g3765(.A0 (u_rd_n_2381), .A1 (u_rd_n_2215), .B0
       (u_rd_n_2324), .Y (u_rd_n_2213));
  OAI211X1 u_rd_g3767(.A0 (u_rd_timer[7]), .A1 (u_rd_n_2225), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2221), .Y (u_rd_n_2215));
  NAND2X1 u_rd_g3768(.A (u_rd_timer[8]), .B (u_rd_n_2218), .Y
       (u_rd_n_2214));
  INVX1 u_rd_g3769(.A (u_rd_n_2221), .Y (u_rd_n_2218));
  AOI21XL u_rd_g3770(.A0 (u_rd_n_2380), .A1 (u_rd_n_2222), .B0
       (u_rd_n_2324), .Y (u_rd_n_2220));
  OAI211X1 u_rd_g3772(.A0 (u_rd_timer[6]), .A1 (u_rd_n_2232), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2228), .Y (u_rd_n_2222));
  NAND2X1 u_rd_g3773(.A (u_rd_timer[7]), .B (u_rd_n_2225), .Y
       (u_rd_n_2221));
  INVX1 u_rd_g3774(.A (u_rd_n_2228), .Y (u_rd_n_2225));
  AOI21XL u_rd_g3775(.A0 (u_rd_n_2367), .A1 (u_rd_n_2229), .B0
       (u_rd_n_2324), .Y (u_rd_n_2227));
  OAI211X1 u_rd_g3778(.A0 (u_rd_timer[5]), .A1 (u_rd_n_2243), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2238), .Y (u_rd_n_2229));
  NAND2X1 u_rd_g3779(.A (u_rd_timer[6]), .B (u_rd_n_2232), .Y
       (u_rd_n_2228));
  INVX1 u_rd_g3780(.A (u_rd_n_2238), .Y (u_rd_n_2232));
  AOI21XL u_rd_g3781(.A0 (u_rd_n_2364), .A1 (u_rd_n_2240), .B0
       (u_rd_n_2324), .Y (u_rd_n_2234));
  OAI211X1 u_rd_g3782(.A0 (u_rd_n_2358), .A1 (u_rd_n_2355), .B0
       (u_rd_n_2350), .C0 (u_rd_n_2236), .Y (u_rd_n_2235));
  OAI2BB1X1 u_rd_g3783(.A0N (u_rd_n_2349), .A1N (u_rd_n_2355), .B0
       (u_rd_n_2239), .Y (u_rd_n_2236));
  NAND4XL u_rd_g3787(.A (u_rd_n_2277), .B (u_rd_n_2258), .C
       (u_rd_n_2253), .D (u_rd_n_2254), .Y (u_rd_n_2239));
  OAI211X1 u_rd_g3788(.A0 (u_rd_timer[4]), .A1 (u_rd_n_2266), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2259), .Y (u_rd_n_2240));
  NAND2X1 u_rd_g3789(.A (u_rd_timer[5]), .B (u_rd_n_2243), .Y
       (u_rd_n_2238));
  INVX1 u_rd_g3790(.A (u_rd_n_2259), .Y (u_rd_n_2243));
  NOR2X1 u_rd_g3791(.A (epoch_clr), .B (u_rd_n_2253), .Y (u_rd_n_2245));
  NOR2X1 u_rd_g3793(.A (epoch_clr), .B (u_rd_n_2254), .Y (u_rd_n_2247));
  AOI21XL u_rd_g3794(.A0 (u_rd_n_2378), .A1 (u_rd_n_2262), .B0
       (u_rd_n_2324), .Y (u_rd_n_2250));
  NOR2X1 u_rd_g3795(.A (epoch_clr), .B (u_rd_n_2258), .Y (u_rd_n_2251));
  AOI221X1 u_rd_g3797(.A0 (u_rd_n_2375), .A1 (u_rd_n_2320), .B0
       (u_rd_outst_cnt[1]), .B1 (u_rd_n_2271), .C0 (u_rd_n_2435), .Y
       (u_rd_n_2253));
  XNOR2X1 u_rd_g3798(.A (u_rd_outst_cnt[3]), .B (u_rd_n_2272), .Y
       (u_rd_n_2254));
  MXI2XL u_rd_g3802(.A (n_232), .B (u_rd_n_2278), .S0
       (u_rd_drain_cnt[3]), .Y (u_rd_n_2260));
  OAI211X1 u_rd_g3803(.A0 (u_rd_timer[3]), .A1 (u_rd_n_2297), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2285), .Y (u_rd_n_2262));
  XNOR2X1 u_rd_g3804(.A (u_rd_outst_cnt[2]), .B (u_rd_n_2275), .Y
       (u_rd_n_2258));
  NAND2X1 u_rd_g3805(.A (u_rd_timer[4]), .B (u_rd_n_2266), .Y
       (u_rd_n_2259));
  INVX1 u_rd_g3806(.A (u_rd_n_2285), .Y (u_rd_n_2266));
  NOR2X1 u_rd_g3807(.A (u_rd_n_2277), .B (epoch_clr), .Y (u_rd_n_2268));
  AOI21XL u_rd_g3809(.A0 (u_rd_n_2370), .A1 (u_rd_n_2293), .B0
       (u_rd_n_2324), .Y (u_rd_n_2270));
  NAND2X1 u_rd_g3810(.A (u_rd_n_2314), .B (u_rd_n_2280), .Y
       (u_rd_n_2271));
  MX2XL u_rd_g3811(.A (u_rd_n_2435), .B (u_rd_n_2284), .S0
       (u_rd_outst_cnt[2]), .Y (u_rd_n_2272));
  OAI211X1 u_rd_g3812(.A0 (u_rd_n_2315), .A1 (u_rd_n_2394), .B0
       (u_rd_n_2316), .C0 (u_rd_n_2303), .Y (u_rd_n_2274));
  OR2XL u_rd_g3813(.A (u_rd_n_2435), .B (u_rd_n_2284), .Y
       (u_rd_n_2275));
  AOI221X1 u_rd_g3815(.A0 (u_rd_n_2323), .A1 (u_rd_n_2428), .B0
       (u_rd_n_2336), .B1 (u_rd_drain_cnt[2]), .C0 (u_rd_n_2287), .Y
       (u_rd_n_2278));
  AOI22X1 u_rd_g3816(.A0 (u_rd_n_2430), .A1 (u_rd_n_2320), .B0
       (u_rd_outst_cnt[0]), .B1 (u_rd_n_2362), .Y (u_rd_n_2280));
  XNOR2X1 u_rd_g3817(.A (u_rd_outst_cnt[0]), .B (u_rd_n_2314), .Y
       (u_rd_n_2277));
  AND3XL u_rd_g3818(.A (u_rd_outst_cnt[1]), .B (u_rd_outst_cnt[0]), .C
       (u_rd_n_2320), .Y (u_rd_n_2284));
  NAND2X1 u_rd_g3819(.A (u_rd_timer[3]), .B (u_rd_n_2297), .Y
       (u_rd_n_2285));
  MXI2XL u_rd_g3821(.A (u_rd_n_2309), .B (u_rd_n_2315), .S0
       (u_rd_drain_cnt[0]), .Y (u_rd_n_2288));
  OAI211X1 u_rd_g3823(.A0 (u_rd_timer[2]), .A1 (u_rd_n_2342), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2321), .Y (u_rd_n_2293));
  OAI221X1 u_rd_g3824(.A0 (u_rd_n_2322), .A1 (u_rd_n_2360), .B0
       (u_rd_n_2335), .B1 (u_rd_n_2359), .C0 (u_rd_n_2315), .Y
       (u_rd_n_2287));
  INVX1 u_rd_g3825(.A (u_rd_n_2321), .Y (u_rd_n_2297));
  OR2XL u_rd_g3828(.A (u_rd_n_2307), .B (u_rd_n_2306), .Y
       (u_rd_n_2299));
  AOI21XL u_rd_g3829(.A0 (u_rd_n_2383), .A1 (u_rd_n_2337), .B0
       (u_rd_n_2324), .Y (u_rd_n_2302));
  AOI21X1 u_rd_g3830(.A0 (u_rd_n_2336), .A1 (u_rd_n_2360), .B0
       (u_rd_n_2307), .Y (u_rd_n_2303));
  NOR2XL u_rd_g3831(.A (u_rd_n_2340), .B (epoch_clr), .Y (u_rd_n_2308));
  NOR2XL u_rd_g3832(.A (u_rd_n_2336), .B (u_rd_n_2323), .Y
       (u_rd_n_2309));
  NOR2BX1 u_rd_g3833(.AN (u_rd_n_2360), .B (u_rd_n_2322), .Y
       (u_rd_n_2306));
  NOR2BX1 u_rd_g3834(.AN (u_rd_n_2359), .B (u_rd_n_2335), .Y
       (u_rd_n_2307));
  OR3XL u_rd_g3835(.A (u_rd_n_2322), .B (u_rd_n_2359), .C
       (u_rd_n_2360), .Y (u_rd_n_2316));
  NOR2XL u_rd_g3836(.A (u_rd_n_2356), .B (u_rd_n_2324), .Y
       (u_rd_n_2317));
  XNOR2X1 u_rd_g3837(.A (u_rd_n_2362), .B (u_rd_n_2345), .Y
       (u_rd_n_2314));
  OA22X1 u_rd_g3838(.A0 (u_rd_n_2361), .A1 (u_rd_n_2349), .B0
       (u_rd_n_2346), .B1 (epoch_clr), .Y (u_rd_n_2315));
  INVX1 u_rd_g3839(.A (u_rd_n_2322), .Y (u_rd_n_2323));
  NOR2X1 u_rd_g3840(.A (u_rd_n_2362), .B (u_rd_n_2345), .Y
       (u_rd_n_2320));
  NAND2X1 u_rd_g3841(.A (u_rd_timer[2]), .B (u_rd_n_2342), .Y
       (u_rd_n_2321));
  NAND2BX1 u_rd_g3842(.AN (u_rd_n_2349), .B (u_rd_n_2361), .Y
       (u_rd_n_2322));
  OR3X1 u_rd_g3843(.A (rd_timeout_pulse), .B (u_rd_n_2345), .C
       (epoch_clr), .Y (u_rd_n_2324));
  INVX1 u_rd_g3844(.A (u_rd_n_2335), .Y (u_rd_n_2336));
  OAI211X1 u_rd_g3845(.A0 (u_rd_timer[0]), .A1 (u_rd_timer[1]), .B0
       (u_rd_timer_run), .C0 (u_rd_n_2374), .Y (u_rd_n_2337));
  AOI221X1 u_rd_g3846(.A0 (u_rd_n_2411), .A1 (u_rd_n_2373), .B0
       (flush), .B1 (u_rd_n_285), .C0 (rd_timeout_pulse), .Y
       (u_rd_n_2340));
  NAND3BXL u_rd_g3848(.AN (u_rd_n_2361), .B (u_rd_n_2353), .C
       (u_wr_n_2054), .Y (u_rd_n_2335));
  INVX1 u_rd_g3849(.A (u_rd_n_2374), .Y (u_rd_n_2342));
  NAND2XL u_rd_g3851(.A (u_rd_n_2353), .B (u_rd_n_2361), .Y
       (u_rd_n_2346));
  NAND2BX1 u_rd_g3852(.AN (u_rd_n_2358), .B (u_rd_n_2353), .Y
       (u_rd_n_2345));
  OR4X1 u_rd_g3853(.A (u_rd_n_2362), .B (u_rd_rd_state[1]), .C
       (u_rd_rd_state[0]), .D (logic_0_1_net), .Y (u_rd_n_2350));
  OR2XL u_rd_g3854(.A (u_rd_n_2353), .B (epoch_clr), .Y (u_rd_n_2349));
  NAND2X1 u_rd_g3855(.A (s_rready), .B (u_rd_n_2373), .Y (u_rd_n_2353));
  XNOR2X1 u_rd_g3856(.A (u_rd_timer_run), .B (u_rd_timer[0]), .Y
       (u_rd_n_2356));
  NAND3BXL u_rd_g3857(.AN (rd_timeout_pulse), .B (u_rd_n_285), .C
       (u_rd_n_280), .Y (u_rd_n_2355));
  NAND2X1 u_rd_g3859(.A (u_rd_n_2434), .B (u_rd_timer[4]), .Y
       (u_rd_n_2364));
  NAND2X1 u_rd_g3860(.A (u_rd_n_2434), .B (u_rd_timer[13]), .Y
       (u_rd_n_2366));
  NAND2X1 u_rd_g3861(.A (u_rd_n_2434), .B (u_rd_timer[5]), .Y
       (u_rd_n_2367));
  NAND2X1 u_rd_g3862(.A (u_rd_n_2434), .B (u_rd_timer[14]), .Y
       (u_rd_n_2368));
  NAND2X1 u_rd_g3863(.A (u_rd_n_2434), .B (u_rd_timer[12]), .Y
       (u_rd_n_2369));
  NAND2X1 u_rd_g3864(.A (u_rd_n_2434), .B (u_rd_timer[2]), .Y
       (u_rd_n_2370));
  AND2XL u_rd_g3865(.A (u_rd_n_288), .B (s_rvalid), .Y (u_rd_n_2358));
  NOR2X1 u_rd_g3866(.A (u_rd_drain_cnt[1]), .B (u_rd_drain_cnt[0]), .Y
       (u_rd_n_2359));
  NOR2BX1 u_rd_g3867(.AN (u_rd_drain_cnt[0]), .B (u_rd_n_2394), .Y
       (u_rd_n_2360));
  NAND2X1 u_rd_g3868(.A (m_rvalid), .B (u_rd_n_287), .Y (u_rd_n_2361));
  NAND2X1 u_rd_g3869(.A (s_arvalid), .B (s_arready), .Y (u_rd_n_2362));
  NOR2X1 u_rd_g3870(.A (u_rd_outst_cnt[1]), .B (u_rd_n_2430), .Y
       (u_rd_n_2375));
  NAND2X1 u_rd_g3871(.A (u_rd_n_2434), .B (u_rd_timer[8]), .Y
       (u_rd_n_2377));
  NAND2X1 u_rd_g3872(.A (u_rd_n_2434), .B (u_rd_timer[3]), .Y
       (u_rd_n_2378));
  NAND2X1 u_rd_g3873(.A (u_rd_n_2434), .B (u_rd_timer[10]), .Y
       (u_rd_n_2379));
  NAND2X1 u_rd_g3874(.A (u_rd_n_2434), .B (u_rd_timer[6]), .Y
       (u_rd_n_2380));
  NAND2X1 u_rd_g3875(.A (u_rd_n_2434), .B (u_rd_timer[7]), .Y
       (u_rd_n_2381));
  NAND2X1 u_rd_g3876(.A (u_rd_n_2434), .B (u_rd_timer[9]), .Y
       (u_rd_n_2382));
  NAND2X1 u_rd_g3877(.A (u_rd_n_2434), .B (u_rd_timer[1]), .Y
       (u_rd_n_2383));
  NAND2X1 u_rd_g3878(.A (u_rd_n_2434), .B (u_rd_timer[11]), .Y
       (u_rd_n_2384));
  NOR2BX1 u_rd_g3879(.AN (u_rd_rd_state[1]), .B (u_rd_rd_state[0]), .Y
       (u_rd_n_2373));
  NAND2X1 u_rd_g3880(.A (u_rd_timer[1]), .B (u_rd_timer[0]), .Y
       (u_rd_n_2374));
  INVX1 u_rd_g3882(.A (s_rready), .Y (u_rd_n_2411));
  INVX1 u_rd_g3883(.A (u_rd_drain_cnt[2]), .Y (u_rd_n_2428));
  INVX1 u_rd_g3886(.A (u_rd_timer_run), .Y (u_rd_n_2434));
  NOR4BBX1 u_rd_g2011(.AN (u_rd_n_2362), .BN (u_rd_n_2345), .C
       (u_rd_outst_cnt[0]), .D (u_rd_outst_cnt[1]), .Y (u_rd_n_2435));
  INVXL g5897(.A (flush), .Y (u_rd_n_280));
  CLKBUFX2 g5898(.A (u_wr_n_2540), .Y (s_awready));
  INVX1 g5899(.A (u_rd_n_1705), .Y (s_arready));
  INVXL g5900(.A (u_wr_n_3934), .Y (u_wr_n_3933));
  NOR3BX1 g2(.AN (s_wvalid), .B (u_wr_n_435), .C (u_wr_wpair_state[1]),
       .Y (n_224));
  OAI21X1 g5902(.A0 (u_wr_n_3932), .A1 (u_wr_n_4110), .B0
       (u_wr_n_3721), .Y (n_225));
  OAI211X1 g5903(.A0 (u_wr_n_3815), .A1 (u_wr_n_3966), .B0
       (u_wr_n_3749), .C0 (u_wr_n_3801), .Y (n_226));
  NAND2X1 g5904(.A (u_wr_outst_cnt[3]), .B (u_wr_n_3752), .Y (n_227));
  NAND4BBXL g5905(.AN (u_wr_n_3954), .BN (u_wr_outst_cnt[3]), .C
       (u_wr_n_3967), .D (u_wr_outst_cnt[0]), .Y (n_228));
  NOR2BX1 g5907(.AN (n_231), .B (u_wr_wpair_state[1]), .Y (n_230));
  OAI31X1 g5908(.A0 (u_wr_n_435), .A1 (flush), .A2 (u_wr_n_3983), .B0
       (u_wr_n_3994), .Y (n_231));
  NAND2X1 g5909(.A (u_rd_drain_cnt[2]), .B (u_rd_n_2306), .Y (n_232));
  DFFRX1 \mode_reg[1] (.RN (rst_n), .CK (clk), .D (n_8), .Q (mode[1]),
       .QN (n_15));
  DFFRX1 \mode_reg[0] (.RN (rst_n), .CK (clk), .D (n_10), .Q (mode[0]),
       .QN (n_16));
  DFFRX1 u_wr_downstream_w_done_reg(.RN (rst_n), .CK (clk), .D (n_233),
       .Q (u_wr_downstream_w_done), .QN (u_wr_n_398));
  DFFRX1 u_wr_downstream_aw_done_reg(.RN (rst_n), .CK (clk), .D
       (n_234), .Q (u_wr_downstream_aw_done), .QN (u_wr_n_396));
  DFFRX1 \u_wr_drain_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3773), .Q (u_wr_drain_cnt[0]), .QN (u_wr_n_318));
  DFFRX1 \u_wr_wr_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_225), .Q
       (u_wr_wr_state[0]), .QN (u_wr_n_158));
  DFFRX1 \u_rd_outst_cnt_reg[3] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2247), .Q (u_rd_outst_cnt[3]), .QN (u_rd_n_1760));
  DFFRX1 \u_rd_rd_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2308), .Q (u_rd_rd_state[1]), .QN (u_rd_n_1764));
  DFFRX1 \u_rd_drain_cnt_reg[1] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2274), .Q (u_rd_drain_cnt[1]), .QN (u_rd_n_2394));
  DFFRX1 \u_rd_outst_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_rd_n_2268), .Q (u_rd_outst_cnt[0]), .QN (u_rd_n_2430));
  DFFRX1 \u_wr_outst_cnt_reg[0] (.RN (rst_n), .CK (clk), .D
       (u_wr_n_3740), .Q (u_wr_outst_cnt[0]), .QN (n_229));
  AND2XL g5932(.A (u_wr_n_3930), .B (u_wr_n_2550), .Y (n_233));
  AND2XL g5933(.A (u_wr_n_3930), .B (u_wr_n_2552), .Y (n_234));
  NOR3X1 g5935(.A (u_wr_wpair_state[0]), .B (u_wr_n_430), .C
       (u_rd_n_300), .Y (n_236));
  TIELO tie_0_cell(.Y (logic_0_1_net));
  TIEHI tie_1_cell(.Y (logic_1_1_net));
endmodule

